### PR TITLE
[BugFix]: Layout Element "Text" fails to load in object class configuration (settingsconfiguration) #11188

### LINKED ISSUE #11188: [Bug]: Layout Element "Text" fails to load in object class configuration (settingsconfiguration)
### Expected behavior

Load configuration/input fields for layout element of type  "Text" in multiple opened classes.

### Actual behavior

Whenever more than one class that contains a layout element of type  "Text" is opened, the configuration gets not loaded and the JS Console shows the following error as seen in the screenshot below:

**Ext.ComponentManager.register(): Duplicate component id "settingsconfiguration**

Bug_Text

1. 

### Steps to reproduce

In Data Objects > Classes:

* Open a class and add a layout element of type  "Text", save it.
* Leave the class configuration open!
* Open another class and add/save a layout element of type  "Text".
--> Text configuration gets no longer loaded in none of the classes.

### PR DESCRIPTION
**Pull request by karlozrilic**
## Changes in this pull request  
Resolves #11188

### CODE REVIEW

**Comment by weisswurstkanone** [comment]
@dvesh3 what is the id needed for ?

**Comment by dvesh3** [comment]
> @dvesh3 what is the id needed for ?

Nothing. We can get rid of it. 

@karlozrilic could you please remove the id property completely? thanks!

**Comment by karlozrilic** [comment]
Of course

**Review by dvesh3 — APPROVED** [review]

**Comment by weisswurstkanone** [comment]
Merci!

**Pull request merged**
