### PR TITLE
chore: Remove useless proxy methods

### PR DESCRIPTION
**Pull request by jdreesen**
Removes some methods that only proxy the parent ones and provide no further value.

### CODE REVIEW

**Comment by jdreesen** [comment]
I fixed the conflicts.

**Comment by lukmzig** [comment]
Hi @jdreesen, I am sorry for that but merging your previous PR caused a tiny merge conflict. Could you please resolve that? Thanks a lot.

**Comment by jdreesen** [comment]
No problem, I resolved it.

**Comment by jdreesen** [comment]
What's wrong with this SonarCube? How can I _introduce_ duplications when I only _remove_ code?

**Comment by lukmzig** [comment]
> What's wrong with this SonarCube? How can I _introduce_ duplications when I only _remove_ code?

@jdreesen the sonar cloud is scanning the whole core, we are still working on the setup. Please ignore it for now :)

**Pull request merged**
