### PR TITLE
allow custom configuration for ckEditor when adding a wysiwyg element…

### PR DESCRIPTION
**Pull request by solverat**
allow custom configuration for ckEditor when adding a wysiwyg element to class. so user can add a path to a custom config js file to manipulate the editor config like stylesSet.

### CODE REVIEW

**Comment by solverat** [comment]
secondly: 

the _toolbarGroups_ config is hard or impossible do set, because you're only able to define the toolbar groups without removing elements.

to generate some custom toolbarGroups you can use the [toolbarconfigurator](http://ckeditor.com/latest/samples/toolbarconfigurator/index.html#basic). 
as you can see, you need to add `config.removeButtons = 'Source,Save,[...]';`  to remove some buttons, which is not possible in the pimcore class / wysiwyg editor (toolbar settings) editor. so maybe we should add an additional textfield called toolbar? 

eg. `eConfig.toolbar= []` with that you're able to apply all fields within the config string: http://ckeditor.com/latest/samples/toolbarconfigurator/index.html#advanced

**Comment by brusch** [comment]
Isn't `toolbarConfig` obsolete when we add `customConfig`? 
If so, we should remove `toolbarConfig` and make a note in the upgrade notes.

**Comment by solverat** [comment]
ok, i just tested this a little bit further: Set customConfig to each wysiwyg is a bad idea. If a second editor does have a customConfig too and it's using the same eg. styleSet, CKEDITOR will throw some errors.

The best thing to do - i think - is to allow to change the complete config object. so instead of

```javascript
var eConfig = {
    width: this.fieldConfig.width,
    height: this.fieldConfig.height,
    resize_enabled: false,
    language: pimcore.settings["language"]
};

eConfig.toolbarGroups = [
    { name: 'clipboard', groups: [ "sourcedialog", 'clipboard', 'undo', "find" ] },
    { name: 'basicstyles', groups: [ 'basicstyles', 'list'] },
    '/',
    { name: 'paragraph', groups: [ 'align', 'indent'] },
    { name: 'blocks' },
    { name: 'links' },
    { name: 'insert' },
    "/",
    { name: 'styles' },
    { name: 'tools', groups: ['colors', "tools", 'cleanup', 'mode', "others"] }
];

if(this.fieldConfig.toolbarConfig) {
    eConfig.toolbarGroups = Ext.decode("[" + this.fieldConfig.toolbarConfig + "]")
}

eConfig.allowedContent = true; // disables CKEditor ACF (will remove pimcore_* attributes from links, etc.)
eConfig.removePlugins = "tableresize";
```
we should do

```javascript
var eConfig = {
    width: this.fieldConfig.width,
    height: this.fieldConfig.height,
    language: pimcore.settings["language"]
};

eConfig.toolbarGroups = [
    { name: 'clipboard', groups: [ "sourcedialog", 'clipboard', 'undo', "find" ] },
    { name: 'basicstyles', groups: [ 'basicstyles', 'list'] },
    '/',
    { name: 'paragraph', groups: [ 'align', 'indent'] },
    { name: 'blocks' },
    { name: 'links' },
    { name: 'insert' },
    "/",
    { name: 'styles' },
    { name: 'tools', groups: ['colors', "tools", 'cleanup', 'mode', "others"] }
];

if(this.fieldConfig.toolbarConfig) {

    var elementCustomConfig = Ext.decode(this.fieldConfig.toolbarConfig);
    eConfig = mergeObject(eConfig, elementCustomConfig);

}

//prevent override important settings!
eConfig.allowedContent = true; // disables CKEditor ACF (will remove pimcore_* attributes from links, etc.)
eConfig.removePlugins = "tableresize";
eConfig.resize_enabled = false;
```

In the class editor we can add our custom data:

bildschirmfoto 2016-07-05 um 18 04 14

### Advanced Example
if a user want some custom styleSet or a custom toolbarGroup, he could simple include a custom javascript in backend (as a plugin for example):

```
CKEDITOR.stylesSet.add('awesomeStuff', [{
    "name": "Button Default",
    "element": "a",
    "attributes": {
        "class": "btn btn-default"
    }
}]);
```

then he just added this to the wysiwyg element in the class:

```
{
  toolbarGroups : [ { name: 'links' }],
  stylesSet : 'awesomeStuff'
}
```

what do you think?

**Comment by brusch** [comment]
Sounds a lot better to me. 
Are you changing your PR or should we put this into a FR?

**Comment by solverat** [comment]
i'll update the pr.

**Comment by solverat** [comment]
ok, i just updated the pr. the field in wysiwyg class expects now a object, which can contain the complete ck editor configuration. see:
 bildschirmfoto 2016-07-05 um 18 04 14

**Comment by brusch** [comment]
I guess we should use also a different label for the textfield in the field configuration? 
Thanks!

**Comment by solverat** [comment]
true story. i changed the label to "editor configuration".

**Comment by brusch** [comment]
Thanks!

**Comment by brusch** [comment]
Updated docs: https://www.pimcore.org/wiki/display/PIMCORE4/Text+Input+Fields+-+Input%2C+Password%2CTextarea%2C+WYSIWYG

**Pull request merged**
