### PR TITLE
use ElementDescriptor for Session saving

### PR DESCRIPTION
**Pull request by dpfaffenbauer**
That solves issues with DataObjects Linked to Doctrine Entities, also it optimizes the save-size of relations, not the full element is serialized, only its type and id.

### CODE REVIEW

**Comment by dpfaffenbauer** [comment]
BTW: I think we should find some sort of Service for all DeepCopy things that happen in Pimcore, they get more and more and the always cause us issues with Doctrine. Maybe it helps bundling them into services and make them extendable that way too, so we can fix stuff on our side and not on Pimcore side, wdyt?

**Comment by fashxp** [comment]
still, what can be fixed in a generic way should be fixed on Pimcore side - so that also other can benefit from it.

**Comment by dpfaffenbauer** [comment]
Yep, but hotfixing is not possible with Pimcore when certain part is not extendable. With a service, hotfixing is possible ;)

**Comment by fashxp** [comment]
I'm completely with you - as long as the fixes find their way back ;-)

**Comment by dpfaffenbauer** [comment]
sure

**Comment by brusch** [comment]
Thanks!

**Pull request merged**
