### PR TITLE
[Data Object] Improved lazy loading

### LINKED ISSUE #5791: [Data Object] Check if lazy loading could be improved
Currently the `load()` method of a data-type is called no matter if it is lazy loaded or not, maybe we can just skip this call in case lazy loading is active? 
https://github.com/pimcore/pimcore/blob/739957f849b8804683f71eef9be5c21493d932f5/models/DataObject/Concrete/Dao.php#L157

Something like that: 
```
if ($value instanceof CustomResourcePersistingInterface) {
    if(!$value instanceof LazyLoadingSupportInterface || !$value->getLazyLoading()) {
        // datafield has it's own loader
        $params = [
            'context' => [
                'object' => $this->model
            ]
        ];
        $value = $value->load($this->model, $params);
        if ($value === 0 || !empty($value)) {
            $this->model->setValue($key, $value);
        }
    }
}
```

This would also make the `force = true` param obsolete: 
https://github.com/pimcore/pimcore/blob/bf5070deb00e7d428f3c061878cbdc191751bc30/models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php#L159
https://github.com/pimcore/pimcore/blob/bf5070deb00e7d428f3c061878cbdc191751bc30/models/DataObject/ClassDefinition/Data/AdvancedManyToManyRelation.php#L812

### PR DESCRIPTION
**Pull request by weisswurstkanone**
Resolves #5791

### CODE REVIEW

**Comment by brusch** [comment]
@NiklasBr @dpfaffenbauer do you see any possible issues with that? Thanks for you feedback! 😊

**Comment by dpfaffenbauer** [comment]
I don't think so. Only thing that got me thinking was the 'force' part, but that is something each type handles for itself, right?

**Comment by brusch** [comment]
Yep, that's why I think this would be fine to be merged.

**Comment by NiklasBr** [comment]
I have no comments :)

**Comment by dpfaffenbauer** [comment]
Not 100% sure if it is this PR, but it breaks loads of my tests:

https://travis-ci.com/coreshop/CoreShop/jobs/290537830

I think that cause some of the things have todo with loading relations or field-collections.

**Comment by dpfaffenbauer** [comment]
OK, after locally fixing https://github.com/pimcore/pimcore/pull/5852, this PR seems to be fine afterall

**Pull request merged**
