### PR TITLE
Fix cleanup bricks and fieldcollections tables task

### LINKED ISSUE #17101: [Bug]: CleanupBrickTask does not handle initial lower case letter in bricks and fieldcollections
### Pimcore version

2024.1

### Steps to reproduce

Create a brick with initial lower case letter, e.g: unitScannerPartner.
Create a field-collection with initial lower case letter, e.g: phone or email.

Run bin/console messenger:consume pimcore_maintenance

### Actual Behavior

No errors

### Expected Behavior

Errors:

11:02:57 ERROR     [app] Brick 'UnitScannerPartner' not found. Please check table object_brick_store_unitscannerpartner_organisationunit
11:02:57 ERROR     [app] Brick 'UnitScannerPartner' not found. Please check table object_brick_query_unitscannerpartner_organisationunit
11:02:57 ERROR     [app] Fieldcollection 'Email' not found. Please check table object_collection_email_organisation
11:02:57 ERROR     [app] Fieldcollection 'PersonalIdentifier' not found. Please check table object_collection_personalidentifier_person
11:02:57 ERROR     [app] Fieldcollection 'Phone' not found. Please check table object_collection_phone_organisation

### PR DESCRIPTION
**Pull request by matthiashamacher**
## Changes in this pull request  
Resolves #17101 

## Additional info
There is also the possibility to drop the `strtolower` from the [DataObjectTaskHelper](https://github.com/pimcore/pimcore/blob/11.x/lib/Maintenance/Tasks/DataObject/DataObjectTaskHelper.php#L44) instead of adding a `strtolower` to both other helpers. I was not sure what the background of that function is, so I just went with this change to comply with the variable name in that function `mapLowerToCamelCase`. 
The real change for the issue is only the `lcfirst` function call.

### CODE REVIEW

**Comment by mcop1** [comment]
Hello,
can you please help me to reproduce the problem? 
Because right now I can´t, I created an object brick with initial lower case letter. But the tables and the php file itself have the correct name, with the lower case letter:
image

Therefore, parsing the name from the table should be fine here https://github.com/pimcore/pimcore/blob/0cee68048c70ac9696c2a8ba195fb26b596a9467/lib/Maintenance/Tasks/DataObject/CleanupBrickTablesTaskHelper.php#L58

Did I miss something?

**Comment by mcop1** [comment]
@matthiashamacher Any chance you had some time to look at my comment?

**Comment by samdegroot1** [comment]
@mcop1 If you are on MacOS it could be due to the fact MacOS is not a case-sensitive filesystem (by default), Linux is. (I don't know about Windows).

We are experiencing this same issue on production environments where we host the applications on Linux servers. Locally on MacOS not able to reproduce it as well.

**Comment by mcop1** [comment]
Hello @matthiashamacher @samdegroot1 ,
I am on Ubuntu, as most of our devs are. The thing is, I can´t reproduce the problem without the pr, but as soon as I apply the pr, I get errors. The check here works https://github.com/pimcore/pimcore/pull/17342/files#diff-fc0eb9291975280b5381207c7b128938563110e8b2719a20d8e4ac6fdbdc356eR61, but it can´t find the definition file anymore, since it is looking for e.g. `dimensions.php`, instead of `Dimensions.php` (https://github.com/pimcore/pimcore/pull/17342/files#diff-fc0eb9291975280b5381207c7b128938563110e8b2719a20d8e4ac6fdbdc356eR63).

**Comment by klickparkdominik** [comment]
@mcop1 

> Hello, can you please help me to reproduce the problem? Because right now I can´t, I created an object brick with initial lower case letter. But the tables and the php file itself have the correct name, with the lower case letter: image
> 
> Therefore, parsing the name from the table should be fine here
> 
> https://github.com/pimcore/pimcore/blob/0cee68048c70ac9696c2a8ba195fb26b596a9467/lib/Maintenance/Tasks/DataObject/CleanupBrickTablesTaskHelper.php#L58
> 
> Did I miss something?

Hi! I stumbled upon the same problem. I cannot provide steps to reproduce. But we also have uppercase fieldcollection names in our PHP files. Maybe this is caused by our very old Pimcore? We updated Pimcore multiple times from Version 6 to 11. All fieldcollections exist since version 6. Maybe earlier Pimcore versions created fieldcollection filesnames with uppercase letter?

You might want to check my issue where I provide valuabe information:
https://github.com/pimcore/pimcore/issues/17854

**Comment by matthiashamacher** [comment]
@mcop1 
I have some updates regarding this problem:

- First thing is we started to see failures with the patch applied. So we had another closer look. In generell I think the PR is still valid except the part in the [DataObjectTaskHelper](https://github.com/pimcore/pimcore/pull/17342/files#diff-ca3b1fad83cc79ed79ed2d5853a98c03174f6feb756b3d86e474b67c6e97cfc4R44) That is causing errors currently.
- When I removed that change I got another error. And that one is probably also why you could not reproduce any issues. I have no complete explanation why the initial error was caused, but after fixing it I had no more problems, even with initial lower case bricks. When you test something you probably use the pimcore/skeleton repository and docker, right? Then the problem is the following: In that setup the database is not setup to use lower_case_table_names as it is written in the documentation: https://pimcore.com/docs/platform/Pimcore/Installation_and_Upgrade/System_Setup_and_Hosting/DB_Setup#database-server-configuration-optional Even though it is optional that would be the difference between the setups and why you cannot reproduce it. We have that setting enabled and then I have issues, so I disabled it and there are no more issues. The initial idea, why it could be that, came because we started using PaaS and there it is not enabled.

@klickparkdominik Please check if you have it enabled on your system or not. That could be the problem, and also solution, to enable it. In that case even though if the query is something like `SELECT fieldname FROM object_brick_store_AttributeFormat_attribute GROUP BY fieldname` Doctrine will update the query and send out `SELECT fieldname FROM pimcore.object_brick_store_attributeformat_attribute GROUP BY fieldname` so those tables should be found again.

**Comment by klickparkdominik** [comment]
This PR looks like it would fix the problem in my scenario.
Especially the change in:

https://github.com/pimcore/pimcore/blob/5919a4fc2dacd399f2951dc643bef529b659073e/lib/Maintenance/Tasks/DataObject/CleanupFieldcollectionTablesTaskHelper.php#L64

@matthiashamacher:
Thank you for providing the link and your suggestion. I prefer not changing database settings, if possible.

`SHOW VARIABLES LIKE 'lower_case_table_names'` returns `0` for our production database.

**Comment by matthiashamacher** [comment]
@klickparkdominik I can understand that. Have you tried if this really fixes the issue? Because I'm currently not that sure if the change in the DataObjectTaskHelper really fixes stuff or makes it worse. The other two changes are definitely usefull. Maybe you can check if that really fixes it by applying this PR as a patch in your project?

**Comment by klickparkdominik** [comment]
@matthiashamacher:
In our project, we only have this problem with fieldcollections, as we don't use bricks.

Therefore, I have only applied this fix from line 64:
https://github.com/pimcore/pimcore/pull/17342/files#diff-73ded5ca5e08effa30fd1d54e2ba721859f865f3712033e40adbf633e2f1c01dR64

Unfortunately, this increases the error messages during the execution of the maintenance task instead of removing them:

Execute: `bin/console pimcore:maintenance && bin/console messenger:consume pimcore_maintenance --time-limit=10`

Result before one-line-fix applied:
```
14:30:12 ERROR     [app] Fieldcollection 'Benefits' not found. Please check table object_collection_benefits_article
14:30:12 ERROR     [app] Fieldcollection 'Benefits' not found. Please check table object_collection_benefits_localized_article
14:30:12 ERROR     [app] Fieldcollection 'Keyfacts' not found. Please check table object_collection_keyfacts_article
14:30:12 ERROR     [app] Fieldcollection 'Keyfacts' not found. Please check table object_collection_keyfacts_localized_article
```

Result after one-line-fix applied:
```
14:29:50 ERROR     [app] Fieldcollection 'Benefits' not found. Please check table object_collection_benefits_article
14:29:50 ERROR     [app] Fieldcollection 'Benefits' not found. Please check table object_collection_benefits_localized_article
14:29:50 ERROR     [app] Fieldcollection 'Keyfacts' not found. Please check table object_collection_keyfacts_article
14:29:50 ERROR     [app] Fieldcollection 'Keyfacts' not found. Please check table object_collection_keyfacts_localized_article
14:29:50 ERROR     [app] Fieldcollection 'OperatingManual' not found. Please check table object_collection_operatingManual_2
14:29:50 ERROR     [app] Fieldcollection 'TechnicalAttributes' not found. Please check table object_collection_technicalAttributes_article
14:29:50 ERROR     [app] Fieldcollection 'TechnicalAttributes' not found. Please check table object_collection_technicalAttributes_localized_article
14:29:50 ERROR     [app] Fieldcollection 'TechnicalAttributes' not found. Please check table object_collection_technicalAttributes_localized_product
14:29:50 ERROR     [app] Fieldcollection 'TechnicalAttributes' not found. Please check table object_collection_technicalAttributes_product
14:29:50 ERROR     [app] Fieldcollection 'TrustIcons' not found. Please check table object_collection_trustIcons_article
14:29:50 ERROR     [app] Fieldcollection 'TrustIcons' not found. Please check table object_collection_trustIcons_product
```

All errors are gone though, when I apply the second change in file `DataObjectTaskHelper` aswell:
https://github.com/pimcore/pimcore/pull/17342/files#diff-ca3b1fad83cc79ed79ed2d5853a98c03174f6feb756b3d86e474b67c6e97cfc4R44

So in my case I require both changes to get rid of the error.

**Comment by matthiashamacher** [comment]
@klickparkdominik Interesting 🤔 Just to have some more informations on your case:

- Which Pimcore Version are you using? You said something about updating from 6 to 11 but on which specific version are you?
- The Fieldcollection has the key Benefits in the backend, how is the file named under var/classes/fieldcollections?

**Comment by klickparkdominik** [comment]
@matthiashamacher:
- The version I just ran the test on is `v11.4.1`.
- The filename is `benefits.php`

Screenshot 2024-11-28 at 3 35 58 PM

You may want to check my issue for additional information and screenshots:
https://github.com/pimcore/pimcore/issues/17854

**Comment by mcop1** [comment]
Hello,

first of all, thanks again for the efforts you put into fixing this problem. 

@matthiashamacher Almost, we use docker and the demo projects. Still, you are right, the database settings are the same as in skeleton, lower_case_table_names is set to 0. 

Just to summarize a bit:

- With  `lower_case_table_names` set to 0 and the changes from the patch (except the line in `DataObjectTaskHelper`) applied, you have a working solution?
- When you set `lower_case_table_names` to 1 you still run into problems, even with the fixes included in this pr?

@klickparkdominik as far as I understood, your case would be fixed with the fixes in `DataObjectTaskHelper` and `CleanupFieldcollectionTablesTaskHelper` applied? 

Thanks for mentioning the detailed issue, we will discuss everything internally. Would be good to find a solution that works with both options.

**Comment by klickparkdominik** [comment]
@mcop1:
Yes, let me explain my four scenarios. I did some more testing right now:
1. Applying **only** the change from `CleanupFieldcollectionTablesTaskHelper` increases the error message count, as shown above. https://github.com/pimcore/pimcore/pull/17342#issuecomment-2506157818
2. Applying **only** the change form `DataObjectTaskHelper` makes the maintenance task run without any errors.
3. Applying **both** changes (1. and 2.) makes the maintenance task run without any errors.
4. Applying **no** change throws error messages as explained in my issue. https://github.com/pimcore/pimcore/issues/17854

I cannot tell whether option 2 and 3 have any sideeffects or not. I am just applying the file-changes and run the maintenance task afterwards. When the task does not throw any errors anymore, I am happy. Which is the case for option 2 and option 3.

It's logical that it is like that because let's just look at this line:
`14:29:50 ERROR     [app] Fieldcollection 'TechnicalAttributes' not found. Please check table object_collection_technicalAttributes_article`. It is thrown because `TechnicalAttributes != technicalAttributes`.

And this line fixes it with `lcfirst`:
https://github.com/pimcore/pimcore/blob/5919a4fc2dacd399f2951dc643bef529b659073e/lib/Maintenance/Tasks/DataObject/DataObjectTaskHelper.php#L44

`TechnicalAttributes` is uppercase because this is how the file is named on our system:
Screenshot 2024-11-29 at 10 05 32 AM

**Comment by matthiashamacher** [comment]
Ok, I did some more digging, because we had another case wich now failed, and I think I just now found the real issue.

First of all, the change in `DataObjectTaskHelper` only resolves the issue if the object brick has a lower case initial letter or is lower case all together. But if the object brick has an upper case initial letter, the issue still persist. (Object brick and field collection have the same functionality, so when it applies to the object brick it also applies to the field collection.)

We can have three different possibilities:
1. PascalCase
2. camelCase
3. lowercase

The problem now is, that the database tables are created based on those three possibilities according to the **key** of the object brick. For example PascaleCase would be `object_brick_PascaleCase_object` or lowercase would be `object_brick_lowercase_object`

The thing I just now noticed, is that the cleanup tasks use the **PHP Class** to generate the table name from that, but the table generation it selfs uses the **key**. This is the problem, as PHP Classes need to be PascalCase. The lcfirst Addition fixes it for 2 and 3 but for 1 it creates an issue, that wasn't there before. By using the PHP classes we have no knowlege about what the key of the object brick was. Therefore it fixes the problem for you, @klickparkdominik but creates new problems for me as I have PascalCase object bricks.

Therefore I think the easiest option would be to change the logic from the PHP Class to the definition php class. That is named by the key, so we would have the key to look for the table. Basically we only need to change [this part](https://github.com/pimcore/pimcore/blob/11.x/lib/Maintenance/Tasks/DataObject/CleanupBrickTablesTaskHelper.php#L28) so that that points to the definition location not the actual class. And the change in the `DataObjectTaskHelper` can be removed as well. @mcop1 Do you agree with that change? Then I will update this pr accordingly

**Comment by matthiashamacher** [comment]
Synced the wrong branch into this and therefor created a new PR with only the required changes: #17891

**Comment by brusch** [comment]
@matthiashamacher I agree, your proposed solution should work 👍

**Pull request closed without merging**
