### PR TITLE
[Objects] Rename relational data-types to a more meaningful name

### LINKED ISSUE #3575: [Objects] Rename relational data-types to a more meaningful name
- `Href` -> `ManyToOneRelation`
- `Multihref` -> `ManyToManyRelation`
- `Multihref Advanced` -> `AdvancedManyToManyRelation`

- `Objects` -> `ManyToManyObjectRelation`
- `Objects with Metadata` -> `AdvancedManyToManyObjectRelation`

### PR DESCRIPTION
**Pull request by brusch**
Resolves #3575

### CODE REVIEW

**Comment by dpfaffenbauer** [comment]
will there be a bc layer as well?

**Comment by brusch** [comment]
@dpfaffenbauer for PHP class names yes: https://github.com/pimcore/pimcore/pull/3653/files#diff-9927b4f9e0ba22a3373a57d5e406ca99

**Comment by brusch** [comment]
So existing JSON exports and PHP definition files will continue to work. 
If you're extending a JS class of one of the affected data-types for a custom data-type, you'd have to change the class name there.

**Comment by brusch** [comment]
> shouldn't you also introduce a bc layer for the JS files?

Done.

**Comment by ultramegatom** [comment]
shouldn't the renaming also apply to document editables? Otherwise it would be really confusing

**Comment by dpfaffenbauer** [comment]
BC Layer: perfect 👍  Pimcore should be able to run code from 5.5 on 5.6 without changing anything.

**Comment by ultramegatom** [comment]
Whats actually the reason for the 'object-relations'? Is there anything this datatype can do what the normal relation can't? Shares about the same codebase - couldn't it just extend the 'normal relations' and set the restrictions to objects?

**Comment by brusch** [comment]
> shouldn't the renaming also apply to document editables? Otherwise it would be really confusing

@ultramegatom That's actually the plan ;) But this PR will only contain the relevant changes for data objects

**Comment by brusch** [comment]
> Whats actually the reason for the 'object-relations'? Is there anything this datatype can do what the normal relation can't? Shares about the same codebase - couldn't it just extend the 'normal relations' and set the restrictions to objects?

@ultramegatom That has mainly historical reasons. But #3614 requests some additions that gives back this data-type a reason to exist :)

**Comment by ultramegatom** [comment]
👍

**Pull request merged**
