### PR TITLE
[Data objects] Minimizable modals for copying and deleting elements

### PR DESCRIPTION
**Pull request by BlackbitNeueMedien**
When copying or deleting elements in Pimcore backend GUI there is a progress bar modal with a backdrop which prevents any other interaction with the GUI. This PR makes this modal minimizable so the user is able to continue working in the GUI.

### CODE REVIEW

**Comment by brusch** [comment]
Originally we made the progress windows modal intentionally. The idea was to prevent the user from doing anything that could cause any unexpected behavior in the UI while the system is processing jobs. In my opinion this still makes sense for some operations like deleting elements, but for the majority of tasks (like pasting, zipping, exporting, ...) this could be changed in general to a normal window. I'd prefer a smaller window in general for non-modal progress windows, so that there's no need to make it minimizable ... may implemented by just a draggable progressbar? 🤔

What do you think?

**Comment by dpfaffenbauer** [comment]
Bildschirmfoto 2020-02-05 um 10 33 18

Maybe stick it to the bottom like the save confirm dialog?

**Comment by BlackbitNeueMedien** [comment]
```The idea was to prevent the user from doing anything that could cause any unexpected behavior in the UI```
My current workaround when I do not want to wait for deletions to complete is to just open a new browser tab. Have you never deleted loads of objects and were disappointed about not being able to continue work in other areas?

**Comment by brusch** [comment]
@dpfaffenbauer sounds good to me! 
@BlackbitNeueMedien actually not really, but I got your point 😊
To be honest, since deleting is a very critical operation I'm a bit worried about the possible side-effects. But starting with all the other operations would be a good start, wouldn't it? We can then decide about the deleting operation later on, after we have checked the possible side-effects in detail.

**Comment by brusch** [comment]
@BlackbitNeueMedien 
Looks good in my opinion: 
image

**Comment by brusch** [comment]
Closed, see #5914 😊

**Pull request closed without merging**
