### PR TITLE
Remove redundant scheduledTasks properties

### PR DESCRIPTION
**Pull request by blankse**
Followup to https://github.com/pimcore/pimcore/pull/10320

### CODE REVIEW

**Comment by brusch** [comment]
Totally missed them as well 😊 Thanks a lot!

**Comment by dasraab** [comment]
i think you can also delete [here](https://github.com/pimcore/pimcore/blob/5f9c86682639403f22475bf5dc11758d962ba9fd/models/Asset.php#L1896) and [here](https://github.com/pimcore/pimcore/blob/5f9c86682639403f22475bf5dc11758d962ba9fd/models/DataObject/Concrete.php#L825)

**Comment by blankse** [comment]
@dasraab The property exist in the ScheduledTasksTrait and I think it should be set to null by clone. WDYT @brusch ?

**Comment by brusch** [comment]
Yep, that should stay as it is, as this isn't covered by the trait.

**Pull request merged**
