### PR TITLE
[Documents] Change namespace from Document\Tag to Document\Editable

### LINKED ISSUE #6888: [Document] Change PHP/JS namespace from Document\Tag to Document\Editable
- Makes the naming consistent and easier to understand. 
- incl. BC layer
- deprecate old namespace

Also some class names and methods need to be renamed: 
```
\Pimcore\Event\Model\Document\TagNameEvent
\Pimcore\Templating\Renderer\TagRenderer
\Pimcore\Templating\Renderer\TagRenderer::tagExists() // ... and some more methods in this class
\Pimcore\Document\Tag\TagUsageResolver // ... including some methods in this class

Classes and methods in this folder: 
lib/Document/Tag
```

### PR DESCRIPTION
**Pull request by dvesh3**
## Changes in this pull request  
Resolves partially #6888

### CODE REVIEW

**Comment by brusch** [comment]
@dvesh3 can you please resolve the conflicts? Thanks a lot! 😊

**Comment by dvesh3** [comment]
@brusch 
> can you please resolve the conflicts? Thanks a lot! 😊

fixed ☺️

**Comment by palazzetti** [comment]
Have you forgot something? 
image

**Comment by dvesh3** [comment]
hmm... works for me
image

**Comment by palazzetti** [comment]
> hmm... works for me
> image

Yeah it works in the 6.7.x-dev branch but not in the 6.8.x-dev.
Tried this morning, now it may be fixed (
image)

**Comment by brusch** [comment]
I'm running on latest master, no problems here.

**Comment by jdreesen** [comment]
Maybe you have to manually delete your `var/cache` folder? ⇒ `rm -rf var/cache/*`
It sometimes helps for me.

**Pull request merged**
