### PR TITLE
[Task] CS Fixer for Micro Optimiziation

### PR DESCRIPTION
**Pull request by blankse**
See https://github.com/pimcore/studio-backend-bundle/pull/201

### CODE REVIEW

**Comment by mcop1** [comment]
First of all, thanks for the pr. Short update: There will be some tests with a centralized cs fixer configuration in the next weeks, depending on the outcome, we will merge this pr or go with the centralized approach.

**Comment by blankse** [comment]
@mcop1 Does it hurt if you merge this here and then create the centralized approach later?

**Comment by mcop1** [comment]
Thank you :+1:

**Comment by fashxp** [comment]
@blankse https://github.com/pimcore/pimcore/blob/a7f3fef2f8368122cb69c75bd1d4bb6726e638cc/models/Asset/Image/Thumbnail/Processor.php#L33 

with that statement, it seems the method call becomes strict concerning types ... which results in following error when generating thumbnails in backend ui:

image

do you know anything about that?

**Pull request merged**
