### PR TITLE
Show unreferenced assets (Follow-up of #4211)

### PR DESCRIPTION
**Pull request by BlackbitNeueMedien**
Follow-up of #4211

### CODE REVIEW

**Comment by brusch** [comment]
Thanks a lot!

**Comment by BlackbitNeueMedien** [comment]
@brusch, I did not dare to call it "unused" because this could lead to the wrong assumption that these are assets which have never been called via URL / thumbnail.

**Comment by brusch** [comment]
@BlackbitNeueMedien that's true ... let's see if this causes some misunderstandings, we can rename it again any time :)

**Comment by NiklasBr** [comment]
I think this is a nice feature and thank you both for working on it!

Though, *please* consider not using end users as a platform for "wait and see" experiments. Decisions like these are cheap and easy to get right now. But expensive to fix when it is in production and a customer has misunderstood that "unused" actually meant "unreferenced". It might cause unnecessary work, costs, and pain.

**Comment by brusch** [comment]
Whatever ... cf5f48722726ff1693977ebaff38b13cae63a1f8

**Comment by BlackbitNeueMedien** [comment]
@brusch, non-english translations are missing. How is the process to add those?

**Comment by brusch** [comment]
@BlackbitNeueMedien https://poeditor.com/projects/view?id=38068

**Comment by BlackbitNeueMedien** [comment]
Hmm, I created an account there but then your link gets me to a "404 Whoa! Nothing this way my friend!"

**Comment by brusch** [comment]
Login and then join the project, just tested, works as expected.

**Comment by BlackbitNeueMedien** [comment]
Hmm, do I need an invitation to the project? All I see is: Bildschirmfoto 2019-04-16 um 09 35 21
There I could create a new project but not join any.

**Comment by brusch** [comment]
1. Login
2. Open https://poeditor.com/join/project/VWmZyvFVMH
3. Click button **Join**

**Pull request merged**
