### PR TITLE
[Fixed] Error: "Getting Array to string conversion" on installation

### PR DESCRIPTION
**Pull request by pdchaudhary**
**Steps to reproduce:**
1. Run "COMPOSER_MEMORY_LIMIT=-1 composer create-project pimcore/skeleton my-project" cmd

**Error:**
Script Pimcore\Composer::clearCache handling the pimcore-scripts event terminated with an exception
[ErrorException]
Array to string conversion

### CODE REVIEW

**Comment by brusch** [comment]
@pdchaudhary Are you sure?  In Symfony 5 `new Process()` only accepts arrays as the first argument, see: 
https://github.com/symfony/symfony/blob/5.3/src/Symfony/Component/Process/Process.php#L141

**Comment by pdchaudhary** [comment]
@brusch Yes, you are right about accepts arrays but I have tried again it is still giving me the attached error. 

image

but it is giving me error on below code:

```
  $process->run(function ($type, $buffer) use ($event, $writeBuffer) {
            if ($writeBuffer) {
                $event->getIO()->write($buffer, false);
            }
        });
```

Platform: **Windows**

**Comment by brusch** [comment]
Maybe it's a Windows issue, but the code in question is definitely correct. 😊

**Comment by pdchaudhary** [comment]
Okay thx, I will try on Linux subsystem.

**Pull request closed without merging**
