### PR TITLE
Add webservices for tags

### PR DESCRIPTION
**Pull request by Yivan**
This is a pull request for: https://github.com/pimcore/pimcore/issues/1086

I added three services:
- tags: list of tags
- tags for element: list of tags for an element
- elements for tag: list of elements for a tag

### CODE REVIEW

**Comment by weisswurstkanone** [comment]
Can we keep the current naming convention, e.g. assetListAction, objectListAction, ... ?

**Comment by Yivan** [comment]
I made naming like for classes (classesAction) which list classes (so i do tagsAction naming). I thought "list" naming was only for element: document/asset/object.
If we name it listTagAction, maybe classes list action should be rename (but will break backward compatibility).

What do you prefer : you merge and you rename it like you prefer or i do the renaming ?
If i do the renaming i change tagsAction to tagsListAction and what about the 2 others actions naming, is is ok (or shoud i go for elementsTagList and tagsElementList) ?

Thanks.

**Comment by weisswurstkanone** [comment]
Can you do the renaming. After that it should be fine I guess :-)

**Comment by Yivan** [comment]
Sure, I will be pleased to do it.

Just to be certain:
- tagsAction -> tagListAction
- elementsTagAction -> elementsTagListAction
- tagElementsAction -> tagElementsListAction
- I keep classesAction like this

Is it ok ?

**Comment by weisswurstkanone** [comment]
Should be ok

**Comment by Yivan** [comment]
@weisswurstkanone Ok this is done!

**Comment by weisswurstkanone** [comment]
thx!

**Pull request merged**
