### PR TITLE
[Task] Improved validation of url slug

### LINKED ISSUE #14813: Revisit URL slug check validity
### Improvement description

please see https://github.com/pimcore/pimcore/pull/14301#issuecomment-1491893317

### PR DESCRIPTION
**Pull request by Corepex**
## Changes in this pull request  
Resolves #14813

### <samp>🤖 Generated by Copilot at 0297bff</samp>

Improved the validation and error handling of the `urlSlug` data type for objects, both on the client and server side. Fixed the inconsistency between the JavaScript and PHP logic for checking the slug format.

### <samp>🤖 Generated by Copilot at 0297bff</samp>

> _`urlSlug` tag changed_
> _Validation logic synced_
> _Autumn leaves fall fast_

### <samp>🤖 Generated by Copilot at 0297bff</samp>

*  Update the validation logic for URL slug parts on both the client and server side to use a regular expression match instead of a replace, and to show the invalid characters found in the slug ([link](https://github.com/pimcore/pimcore/pull/15145/files?diff=unified&w=0#diff-eb671fd7a3437c0090b544ce988f835fa8b907295ed3f103d4c72cc36a782d76L148-R148), [link](https://github.com/pimcore/pimcore/pull/15145/files?diff=unified&w=0#diff-eb671fd7a3437c0090b544ce988f835fa8b907295ed3f103d4c72cc36a782d76L154-R158), [link](https://github.com/pimcore/pimcore/pull/15145/files?diff=unified&w=0#diff-a520e5406f0131e41cd1471566927447636662db5e1b8f1fff131d81f52e7a83L184-R185))
*  Use `const` instead of `var` to declare the `parts` variable in `urlSlug.js`, following the ES6 syntax and best practices for immutable variables ([link](https://github.com/pimcore/pimcore/pull/15145/files?diff=unified&w=0#diff-eb671fd7a3437c0090b544ce988f835fa8b907295ed3f103d4c72cc36a782d76L148-R148))

### CODE REVIEW

**Comment by Corepex** [comment]
For easier testing comment out this line: https://github.com/pimcore/demo/blob/7add4ddd30be82687ba5c4bbef8048e794e58923/src/Controller/ProductController.php#LL95C1-L95C1

**Comment by Corepex** [comment]
TODO: 

- sanitize slugs in the frontend (to prevent HTML injection)
- remove the `filter_var` since it invalidates some URLs (e.g. slugs with Chinese chars) https://github.com/pimcore/pimcore/blob/10.5/models/DataObject/ClassDefinition/Data/UrlSlug.php#L198-L200

**Comment by brusch** [comment]
We also need to update the docs, here it says: 
> Slugs are validated against [FILTER_VALIDATE_URL](https://www.php.net/manual/en/filter.filters.validate.php) and you could use the [Symfony String component's slugger](https://symfony.com/doc/current/components/string.html#slugger) to generate them  

which is not true anymore 😊 

https://pimcore.com/docs/platform/Pimcore/Objects/Object_Classes/Data_Types/Others#url-slug

**Comment by brusch** [comment]
Regarding slugs in frontend: 
Twig is converting special chars using htmlentities anyway, seems to work quite well, imho ... but not sure if this is compliant with RFC. 

If not we'd need to offer a Twig filter, because we can't use `<a href="{{ object.url|url_encode }}">Foo</a>` because this also converts `/`. So we'd need `urlencode_ignore_slash()` as a Twig filter.

**Comment by Corepex** [comment]
According to d16da7af107baf25946751732f7525f438c01762: 

> rawurldecode() does not decode plus symbols ('+') into spaces. [urldecode()](https://www.php.net/manual/en/function.urldecode.php) does.

see: https://www.php.net/manual/en/function.rawurldecode.php

**Comment by Corepex** [comment]
> Regarding slugs in frontend: Twig is converting special chars using htmlentities anyway, seems to work quite well, imho ... but not sure if this is compliant with RFC.

I checked it with `/wiki/UTC&02:00/allchars/ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~:/[]@!$&'()*+,;=` and everything seems to work as it should. Only `?` and `#` make problems - it seems that the parameters get cut off ...

**Comment by brusch** [comment]
I think it would be still fine if we'd disallow (certain) reserved characters according to RFC 3986 section 2.2 Reserved Characters (January 2005): 

`! * ' ( ) ; : @ & = + $ , / ? % # [ ]` 

Nothing would speak against this, right?

**Comment by Corepex** [comment]
> Nothing would speak against this, right?

I implemented the changes as suggested. (bc7b028b4da7585940463e115bc8d1dfcebc718e)
BUT if we throw an exception when including such a reserved char, we can't comply with what was mentioned here: https://github.com/pimcore/pimcore/issues/14813#issuecomment-1540007691

**Comment by brusch** [comment]
I think we could just disallow the 2 chars that we can't support, not all of them.

**Comment by Corepex** [comment]
OK then I will just throw an exception on `?` and `#`

**Comment by brusch** [comment]
Yep. I think that's acceptable 4 now - we can further improve this anyway in future.

**Comment by Corepex** [comment]
OK done with 2adfe3bf341d3ebad4c7d202627eb549635f4593 - thanks

**Pull request merged**
