### PR TITLE
[Glossary] Deprecate Acronyms and move them to Abbr (Sucessor)

### LINKED ISSUE #5705: [Glossary] Change "acronym" (obsolete) to "abbr"
# Feature Request

## Feature description

the glossary produces HTML elements with "acronym" (obsolete) instead of "abbr"

Link: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/acronym

### Expected behavior
`<abbr class=pimcore_glossary title="Some Text">Text</abbr>`
### Actual behavior
`<acronym class=pimcore_glossary title="Some Text">Text</acronym>`
### Code example
```php
// My simple Code Sample
 $this->glossary()->start();

?>
<div class="content">
        Text - and all the Nice Features in my World
</div>
<?php
$this->glossary()->stop();
```
Thx ... Niki

### PR DESCRIPTION
**Pull request by brusch**
Resolves #5705

### CODE REVIEW

**Comment by NiklasBr** [comment]
This is a BC break, right? I mean, this should be done, but there was no documentation and still no clear guidelines which BC breaks are acceptable and which are not.

**Comment by brusch** [comment]
Shouldn't break under normal conditions, only if: 
- you're accessing directly the database
- your're accessing the public property `$acronym`

**Comment by brusch** [comment]
The change is documented in the upgrade notes.

**Comment by NiklasBr** [comment]
This directly affects frontend HTML `{% pimcoreglossary %} ...`.

There is still no documentation on acceptable BC breaks, which is *very* frustrating. The fact that all these BC breaks are allowed to creep into the code makes it a huge hassle to upgrade Pimcore.

**Comment by brusch** [comment]
Well yes, it uses a different HTML tag, is this really that big problem that we can't change it with a minor release?

**Comment by NiklasBr** [comment]
The problem is the very fact that you allow BC breaks to begin with, then the problem escalates when the rules you implement for *some* PR:s seem very arbitrary.

Example: About a month ago you denied a PR specifically because of minor HTML frontend changes. Now you allow it. Please publish those promised rules soon. Which are breaks acceptable?

**Comment by brusch** [comment]
No further development wanted by @NiklasBr - thanks - closed. 🤷‍♂️

**Comment by dpfaffenbauer** [comment]
what is always the hurry with BC breaks in minor released? why not wait for 7.0?

**Comment by NiklasBr** [comment]
@dpfaffenbauer be careful, you might be labelled png. ;)

**Comment by dpfaffenbauer** [comment]
@NiklasBr png?

**Comment by NiklasBr** [comment]
That's an abbrev... or maybe an acronym for \<abbr title="persona non grata">unwelcome person\</abbr>. 😅

**Comment by dpfaffenbauer** [comment]
Well, pretty sure some already see me that way. 

The thing just is, this are the things I stumble upon in a couple of weeks, then I have to research that just to see that it is an unnecessary/avoidable BC break. And it hasn't to be like that. If you just follow semver properly, everything is fine. 

But however...  I might just need to stop caring too much 🤷‍♂️

**Comment by jdreesen** [comment]
Well, it's very annoying to even be afraid of patch updates, because you never know what will break due to unexpected/undocumented BC breaks (we had this several times in v5.x and it's sometimes hard to spot). So it would be great if Pimcore would care a bit more about these things, because not updating is also not really an option.

**Pull request closed without merging**
