### PR TITLE
Fixes stretched assets in grid

### PR DESCRIPTION
**Pull request by NiklasBr**
Before and after:

image
image

### CODE REVIEW

**Comment by blankse** [comment]
@NiklasBr Wouldn't it be nicer to center the thumbnails?
```
.asset_folder_preview .thumb-wrap {
  display: flex;
  align-items: center;
  justify-content: center;
}
```

**Comment by NiklasBr** [comment]
Good idea!

**Comment by brusch** [comment]
@NiklasBr Thanks a lot for your PR, however I'd classify this as a bug, so could you please rebase onto `10.1` branch? Thanks in advance! 

Regression of #10271

**Comment by NiklasBr** [comment]
@brusch There are too many conflicts to fix when rebasing on 10.1, I thought this would be a quick PR. Will try again for 10.1.6 instead if you don't want it in 10.2?

**Comment by brusch** [comment]
Pushed the changes right to `10.1` since it's just a small change anyway - hope that is ok for you 😊

**Pull request closed without merging**
