### PR TITLE
fix deadlock while saving assets concurrently

### PR DESCRIPTION
**Pull request by hirakch**
## Changes in this pull request  
The PR resolves issues while concurrently saving assets, due to the gap lock created while storing assets metadata

### CODE REVIEW

**Comment by mattamon** [comment]
Hey @hirakch,

thank you for your PR. We highly appreciate any contribution!

Is there a way how we can reproduce and test this behaviour?

**Comment by hirakch** [comment]
> Hey @hirakch,
> 
> thank you for your PR. We highly appreciate any contribution!
> 
> Is there a way how we can reproduce and test this behaviour?

**Comment by hirakch** [comment]
Yes, if you can run the following code parallel through endpoint or a script, you should get the error.

```
$newAsset = new \Pimcore\Model\Asset();
$newAsset->setFilename('asset_'.rand());
$newAsset->setData(file_get_contents('https://cdn.pixabay.com/photo/2022/11/27/08/39/mountain-7619151_1280.jpg'));
$newAsset->addMetadata('isNewFormat', 'input', true);
$folderName = 'NewAssets';
$parent = \Pimcore\Model\Asset\Service::createFolderByPath($folderName);
$newAsset->setParent($parent);
$newAsset->save();
```

**Comment by mattamon** [comment]
@hirakch 
Thank you for your input.
I tested it and got the following error:
```bash
08:28:12 WARNING   [pimcore] Unable to finish transaction (1. run) because of the following reason 'An exception occurred while executing 'INSERT INTO assets_metadata (`name`, `type`, `data`, `language`, `cid`) VALUES (?, ?, ?, ?, ?)' with params ["isNewFormat", "input", true, "", 1187]:

SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction'. --> Retrying in 400000 microseconds ... (2 of 5)
```
This is the error you are talking about right?

**Comment by hirakch** [comment]
yes, exactly

**Review by mattamon — APPROVED** [review]

**Comment by bcorvino** [comment]
Has this fix been applied to objects as well?  We are on version 10.3 but regularly encounter deadlocks.

**Comment by mattamon** [comment]
@bcorvino this specific fix was only applied to the assets. If you are having troubles please update to the latest Pimcore Version first, If the problems still continue, please open up another issue or a discussion for this.

**Pull request merged**
