### PR TITLE
[Improvement] Core: Support key and index in backend search

### LINKED ISSUE #6782: Sorting data objects on key in search grid gives an error (column doesn't exist)
# Bug Report

### Expected behaviour
Sorting on key in search grid

### Actual behaviour
Error because the "key" column doesn't exist on the "search_backend_data" table

### Steps to reproduce
1. Enable "Key (Search)" in the "General Settings" of a data object class.
2. Open that class in a search grid and try to sort on "Key". For example by placing a "Many to one" field on a data object class and clicking the magnifier icon to add an object.

(See attached GIF for reproduction on the demo environment)

key-in-search-grid

### PR DESCRIPTION
**Pull request by kjkooistra-youwe**
This allows sorting by key and index.
Index shouldn't be sorted by default, but may be manipulated via the LIST_BEFORE_LIST_LOAD admin event.

## Changes in this pull request  
Resolves #6782

### CODE REVIEW

**Comment by mcop1** [comment]
@kjkooistra-youwe thank you for your contribution, the pr looks good. 
But I think it would be cool to add 2 more things:

* Add upgrade notes: Mention that it is necessary to execute the search-backend-reindex command for this to work
* Add support for sorting the "filename" column for objects, documents and asset. Could be mapped to "key" column.

What do you think?

**Comment by mcop1** [comment]
@kjkooistra-youwe thank you for your contribution, the pr looks good. 
But I think it would be cool to add 2 more things:

* Add upgrade notes: Mention that it is necessary to execute the search-backend-reindex command for this to work
* Add support for sorting the "filename" column for objects, documents and asset. Could be mapped to "key" column.

What do you think?

**Comment by kjkooistra-youwe** [comment]
@mcop1 Changes were added.

**Comment by mcop1** [comment]
> @mcop1 Changes were added.

That was fast. PR looks good, thank you!

**Comment by kjkooistra-youwe** [comment]
> > @mcop1 Changes were added.
> 
> That was fast. PR looks good, thank you!

You're welcome.

**Comment by Apoorva-cred** [comment]
Is [Backend search] key and index columns have been added to the search index?
Is it necessary to Run ./bin/console pimcore:search-backend-reindex to reindex?

**Pull request merged**
