### PR TITLE
[Image / Video thumbnails] Make thumbnail deletion compatible with stream wrappers

### PR DESCRIPTION
**Pull request by BlackbitNeueMedien**
Currently when a thumbnail definition gets saved or when thumbnails get deleted with the "Clear thumbnails" button at an asset, PHP's glob() function gets used to find the thumbnail files to be deleted.
But glob() does not work with stream wrappers (when thumbnails get stored on AWS S3 or Google Cloud Storage like described in https://pimcore.com/docs/6.x/Development_Documentation/Installation_and_Upgrade/System_Setup_and_Hosting/Amazon_AWS_Setup/Amazon_AWS_S3_Setup.html). For this reason thumbnail deletion does not work at all when thumbnails are not stored locally: once a thumbnail for an image has been created there is no way to update it.

### CODE REVIEW

**Comment by brusch** [comment]
@BlackbitNeueMedien Thanks for your PR! Unfortunately the tests are failing, can you please check? 
Thanks a lot! 
https://travis-ci.com/github/pimcore/pimcore/jobs/333936445#L4699

**Comment by BlackbitNeueMedien** [comment]
Now the tests are green

**Comment by brusch** [comment]
Thanks a lot! 🙏

**Comment by dpfaffenbauer** [comment]
This fails now my tests:

```
    BeforeSuite # CoreShop\Behat\Context\Hook\CoreShopSetupContext::setupPimcore()
      UnexpectedValueException: RecursiveDirectoryIterator::__construct(web/var/tmp/image-thumbnails): failed to open dir: No such file or directory in vendor/pimcore/pimcore/models/Asset/Thumbnail/ClearTempFilesTrait.php:29
      Stack trace:
      #0 vendor/pimcore/pimcore/models/Asset/Thumbnail/ClearTempFilesTrait.php(29): RecursiveDirectoryIterator->__construct('/home/runner/wo...', 4096)
      #1 vendor/pimcore/pimcore/models/Asset/Thumbnail/ClearTempFilesTrait.php(24): Pimcore\Model\Asset\Image\Thumbnail\Config->recursiveDelete('/home/runner/wo...', 'coreshop_catego...')
      #2 vendor/pimcore/pimcore/models/Asset/Image/Thumbnail/Config.php(903): Pimcore\Model\Asset\Image\Thumbnail\Config->doClearTempFiles('/home/runner/wo...', 'coreshop_catego...')
      #3 vendor/pimcore/pimcore/models/Asset/Image/Thumbnail/Config/Dao.php(104): Pimcore\Model\Asset\Image\Thumbnail\Config->clearTempFiles()
      #4 vendor/pimcore/pimcore/models/Asset/Image/Thumbnail/Config/Dao.php(88): Pimcore\Model\Asset\Image\Thumbnail\Config\Dao->autoClearTempFiles()
      #5 [internal function]: Pimcore\Model\Asset\Image\Thumbnail\Config\Dao->save()
```

https://github.com/dpfaffenbauer/CoreShop/runs/709817562

**Comment by brusch** [comment]
> This fails now my tests:
> 
> ```
>     BeforeSuite # CoreShop\Behat\Context\Hook\CoreShopSetupContext::setupPimcore()
>       UnexpectedValueException: RecursiveDirectoryIterator::__construct(web/var/tmp/image-thumbnails): failed to open dir: No such file or directory in vendor/pimcore/pimcore/models/Asset/Thumbnail/ClearTempFilesTrait.php:29
>       Stack trace:
>       #0 vendor/pimcore/pimcore/models/Asset/Thumbnail/ClearTempFilesTrait.php(29): RecursiveDirectoryIterator->__construct('/home/runner/wo...', 4096)
>       #1 vendor/pimcore/pimcore/models/Asset/Thumbnail/ClearTempFilesTrait.php(24): Pimcore\Model\Asset\Image\Thumbnail\Config->recursiveDelete('/home/runner/wo...', 'coreshop_catego...')
>       #2 vendor/pimcore/pimcore/models/Asset/Image/Thumbnail/Config.php(903): Pimcore\Model\Asset\Image\Thumbnail\Config->doClearTempFiles('/home/runner/wo...', 'coreshop_catego...')
>       #3 vendor/pimcore/pimcore/models/Asset/Image/Thumbnail/Config/Dao.php(104): Pimcore\Model\Asset\Image\Thumbnail\Config->clearTempFiles()
>       #4 vendor/pimcore/pimcore/models/Asset/Image/Thumbnail/Config/Dao.php(88): Pimcore\Model\Asset\Image\Thumbnail\Config\Dao->autoClearTempFiles()
>       #5 [internal function]: Pimcore\Model\Asset\Image\Thumbnail\Config\Dao->save()
> ```
> 
> https://github.com/dpfaffenbauer/CoreShop/runs/709817562

Just for the sake of completeness: #6463 fixes the issue 😊

**Pull request merged**
