### PR TITLE
Fix russian translate

### PR DESCRIPTION
**Pull request by NikitchenkoSergey**
## Changes in this pull request  
Item is not товар. Товар is product. This key used in many modals like adding user or data object.

### CODE REVIEW

**Comment by blankse** [comment]
@NikitchenkoSergey Translations other than "en" are managed via POEditor.
See: https://github.com/pimcore/pimcore/pull/9369

**Comment by NikitchenkoSergey** [comment]
@blankse  thanks, i [update](https://poeditor.com/projects/po_edit?order=&filter=&per_page=20&id=38068&id_language=134&search=%D0%92%D0%B2%D0%B5%D0%B4%D0%B8%D1%82%D0%B5+%D0%BD%D0%B0%D0%B7%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5+%D0%BD%D0%BE%D0%B2%D0%BE%D0%B3%D0%BE+%D1%8D%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82%D0%B0) translate. When it will be updated in main branch?

**Comment by blankse** [comment]
@NikitchenkoSergey I think with the 10.3.0 release, right @brusch ?

**Comment by brusch** [comment]
yep

**Pull request closed without merging**
