### PR TITLE
[DataObjects] Add new range data types

### LINKED ISSUE #4535: "Range" data type
# Feature Request

- [x] There is no existing issue regarding the same topic

### `Range`

Adding a new data type `Range` would allow to model attributes meant to hold two values. 

Examples include:
- weight for child diapers (6kg - 10kg)
- age for toys (2yr - 5yr)
- operational temperature (-30°C - 40°C)

etc.

Note: this is **not** the same as existing min/max values because they're used to **constrain** a single value, this is meant to **specify** min/max as a single property. We should still have min/max to constrain (lower end must be >= min, <= higher end, higher end must be <= max).

### `QuantityRange`

Same as above, with a (single) unit attached. Since all my examples actually include units, this makes more sense to have, but for completeness sake, I've included the plain `Range` type too.

### PR DESCRIPTION
**Pull request by aarongerig**
The goal of this PR is to add a couple of new "range" data types as discussed in https://github.com/pimcore/pimcore/issues/4535. It is still work in progress and includes only the first `NumericRange` range data type as of now. The rest will follow...

The `NumericRange` data type saves two fields (`minimum` and `maximum`) into the database, similar of how the generic `Numeric` data type does it (configuration for integer, decimal precision/size, unsigned as well as min/max values). In the Pimcore Back-End the two fields get displayed in a Hbox. Displaying and editing the values in the Grid as well as CSV export should work as well already.

I wanted to see what you guys think so far and continue with the work, once I got some feedback and everything is clear.

**TODO:**
- [x] Add data type `NumericRange`
- [x] Add data type `QuantityValueRange`
- [x] Add data type `DateRange`
- [x] Add translations for EN
- [x] Add documentation

### CODE REVIEW

**Comment by aarongerig** [comment]
Is this going into the right direction and shall I continue like that? Any feedback would be appreciated. 🙂 @brusch @dkarlovi

**Comment by brusch** [comment]
@aarongerig the approach looks already good to me 👍

**Comment by brusch** [comment]
As this doesn't seem active anymore, I'm closing this PR for now. 
In case it's getting active again, we'll of course re-open it. 😊

**Comment by aarongerig** [comment]
@brusch It's still active and under development. As I don't have too much sparse time on hand, I work on it from time to time. Maybe that's why it doesn't "feel" very active. But it's coming along nicely – slowly, but surely. 😉

**Comment by brusch** [comment]
@aarongerig ok, cool 👍 Let us know when it's ready for review, we'll then re-open it 😊

**Comment by aarongerig** [comment]
@brusch The feature should be ready now. If you'd like you can reopen this PR again. Thanks!

**Comment by brusch** [comment]
@aarongerig reopened, but I can't see any additional commits, u pushed already? 😊

**Comment by brusch** [comment]
aaah, here it is ... I was just too impatient 😉

**Comment by aarongerig** [comment]
Yeah, at first I was confused as well, but it seems that Github does not update the commits/code anymore once the PR gets closed.

**Comment by mcop1** [comment]
@aarongerig Thanks, great work! But I found some minor problems:

Quantity Value Range:
- Add quantity value range, but don´t fill in precision and/or default unit. An error message pops up.
Same message pops up when you add a quantity value range to the classification store
- Default unit doesn´t get pre selected, when creating a new data object
- There is a check in place for numeric and date range types. It checks if the start value exceeds the end value. But there isn´t such a check for quantity value range. Would this make sense for quantity value range too- What do you think? 
image

Could you please have a look?

**Comment by aarongerig** [comment]
@mcop1 Thank you for testing!

**Quantity Value Range:**

> - Add quantity value range, but don't fill in precision and/or default unit. An error message pops up.
Same message pops up when you add a quantity value range to the classification store

This one I could not reproduce. Are you sure you used the latest commit? I had some issues with saving the `QuantityValueRange` as well, which I had to fix locally. Now it works flawlessly for me.

> - Default unit doesn't get pre selected, when creating a new data object

Fixed that one.

> - There is a check in place for numeric and date range types. It checks if the start value exceeds the end value. But there isn´t such a check for quantity value range. Would this make sense for quantity value range too- What do you think?

Yes, good catch! That check got left behind. I optimized the validation check of the `QuantityValueRange` a bit, this should work now.

Just as a heads up, today is my last day before leaving for summer vacation. I won't be able to do any fixes during the next weeks. Sorry for the inconvenience!

**Comment by mcop1** [comment]
@aarongerig 
Thanks, default value, the check and leaving precision/unit empty are working now. But I still have problems with the classification store. I can add the data range types to the classification store, but as soon as I try to save a data object that has the store added, I get an error message: 

image

=> 

```
Message: An exception occurred while executing 'INSERT INTO `object_classificationstore_data_6` (`o_id`, `collectionId`, `groupId`, `keyId`, `fieldname`, `language`, `type`, `value`, `value2`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?) ON DUPLICATE KEY UPDATE `o_id` = ?, `collectionId` = ?, `groupId` = ?, `keyId` = ?, `fieldname` = ?, `language` = ?, `type` = ?, `value` = ?, `value2` = ?;' with params [1198, 2, 1, 1, "RangeStore", "default", "dateRange", ["2022-07-12T22:00:00.000000Z","2022-07-13T22:00:00.000000Z","2022-07-14T22:00:00.000000Z","2022-07-15T22:00:00.000000Z","2022-07-16T22:00:00.000000Z","2022-07-17T22:00:00.000000Z","2022-07-18T22:00:00.000000Z","2022-07-19T22:00:00.000000Z","2022-07-20T22:00:00.000000Z","2022-07-21T22:00:00.000000Z","2022-07-22T22:00:00.000000Z","2022-07-23T22:00:00.000000Z","2022-07-24T22:00:00.000000Z","2022-07-25T22:00:00.000000Z","2022-07-26T22:00:00.000000Z","2022-07-27T22:00:00.000000Z","2022-07-28T22:00:00.000000Z"], null, 1198, 2, 1, 1, "RangeStore", "default", "dateRange", ["2022-07-12T22:00:00.000000Z","2022-07-13T22:00:00.000000Z","2022-07-14T22:00:00.000000Z","2022-07-15T22:00:00.000000Z","2022-07-16T22:00:00.000000Z","2022-07-17T22:00:00.000000Z","2022-07-18T22:00:00.000000Z","2022-07-19T22:00:00.000000Z","2022-07-20T22:00:00.000000Z","2022-07-21T22:00:00.000000Z","2022-07-22T22:00:00.000000Z","2022-07-23T22:00:00.000000Z","2022-07-24T22:00:00.000000Z","2022-07-25T22:00:00.000000Z","2022-07-26T22:00:00.000000Z","2022-07-27T22:00:00.000000Z","2022-07-28T22:00:00.000000Z"], null]:
```

I moved the pr to Pimcore 11, have a nice vacation :)

**Comment by aarongerig** [comment]
@mcop1
I disallowed the use of the new range types as classification store keys, since saving complex (array) values doesn't seem to be supported. Hope this should be fine now too, otherwise let me know. Thanks!

**Comment by mcop1** [comment]
@aarongerig Thanks again, but there is one more thing: Could you please have a look at the merge conflict? I will have a final look right after that

**Comment by aarongerig** [comment]
@mcop1 Oops, didn't see that. Done!

**Comment by aarongerig** [comment]
@mcop1 Oops didn't see that. Should be good now!

**Pull request merged**
