### PR TITLE
Fix link in CustomLayouts docs

### PR DESCRIPTION
**Pull request by NiklasBr**
## Changes in this pull request  
Resolves #

### CODE REVIEW

**Comment by brusch** [comment]
@NiklasBr Thanks for you PR! Can you please rebase it onto `10.0` branch?  Thanks 😊

**Comment by NiklasBr** [comment]
Looks like you already did @brusch 👍

**Comment by brusch** [comment]
@NiklasBr actually I tried it, but your branch needs rebasing, so I've changed it back 😊

**Comment by NiklasBr** [comment]
This does not look right, I edited the file in the 10.x branch as should be according to the instructions: https://github.com/pimcore/pimcore/blob/10.x/CONTRIBUTING.md#contributing-pull-requests but I have changed to `10.0` now anyway.

**Comment by brusch** [comment]
@NiklasBr I'd classify this as a bug, even if it's in the docs, so the right branch would be `10.0`. 
Actually you now need to rebase your branch on `10.0`, just changing the target branch on the PR isn't enough. Thanks again 😊

**Comment by NiklasBr** [comment]
> you now need to rebase your branch on 10.0

> NiklasBr changed the base branch from 10.x to 10.0 3 days ago

Feel free to open it again if you want, I thought I did what you asked me to do.

**Pull request closed without merging**
