### PR TITLE
[Improvement]: Move CollectGarbageMiddleware to pimcore repository

### LINKED ISSUE #17181: [Improvement]: Move CollectGarbageMiddleware to pimcore repository
### Improvement description

Move https://github.com/pimcore/generic-data-index-bundle/blob/1.x/src/Service/Messenger/Middleware/CollectGarbageMiddleware.php into a generic namespace, then:

- [x] Configure and use it for generic execution engine
- [x] Update @markus-moser after the pr was merged. He will substitute the version from `generic-data-index` with the version from the core

### PR DESCRIPTION
**Pull request by mcop1**
## Changes in this pull request  
Resolves #17181

### CODE REVIEW

**Review by markus-moser — CHANGES_REQUESTED** [review]
We need to find another solution for the logger as the `Pimcore\Bundle\GenericDataIndexBundle\Traits\LoggerAwareTrait` is not part of the core. ;)

Maybe we should make the class final?

**Comment by mcop1** [comment]
> We need to find another solution for the logger as the `Pimcore\Bundle\GenericDataIndexBundle\Traits\LoggerAwareTrait` is not part of the core. ;)
> 
> Maybe we should make the class final?

I removed the trait and the log, since it looked more like a debug information anyway. WDYT? 
I added the final keyword too.

**Comment by markus-moser** [comment]
> I removed the trait and the log, since it looked more like a debug information anyway. WDYT? I added the final keyword too.

Thanks - yes I agree that the logging is quite superfluous.

**Review by markus-moser — APPROVED** [review]
LGTM

**Pull request merged**
