### PR TITLE
Add install/update log file information

### PR DESCRIPTION
**Pull request by Yivan**
@maff @fashxp This is the PR for https://github.com/pimcore/pimcore/issues/2236

It adds the installer logs file directory in error message for install/update.

Thanks

### CODE REVIEW

**Comment by dpfaffenbauer** [comment]
IMO, thats not 100% correct. When updating and something fails, I'll get the message to check installer-logs, which is not true, since I am not installing anything, I am updating Pimcore.

**Comment by Yivan** [comment]
But if you see my original issue https://github.com/pimcore/pimcore/issues/2236, which is an update process,  i didn't get the touch warning in neither dev or prod log, nor in any log files of /var/log. So i think update rely on the same installer too and log are in /var/installer ?
@maff do you confirm this ?

**Comment by maff** [comment]
Sorry, seems I misunderstood #2236 - `var/installer/logs` is **only** used when installing Pimcore, not for updates.

**Comment by Yivan** [comment]
Ha ok! So yes this PR is no more good. Thanks.

**Pull request closed without merging**
