### PR TITLE
[PHPStan] Baseline feature

### LINKED ISSUE #5725: [PHPStan] Investigate Baseline feature
see https://medium.com/@ondrejmirtes/phpstans-baseline-feature-lets-you-hold-new-code-to-a-higher-standard-e77d815a5dff

and

#5717

### PR DESCRIPTION
**Pull request by blankse**
## Changes in this pull request  
Resolves #5725

## Additional info  
Create a new baseline file with:
```
# Deactivate baseline (comment out)
sed -e "s?- phpstan-baseline.neon?#- phpstan-baseline.neon?g" -i phpstan.neon

# Generate new baseline file
vendor/bin/phpstan analyse -c .travis/phpstan.s4.travis.neon bundles/ lib/ models/ -l 2 --memory-limit=-1 --error-format baselineNeon > phpstan-baseline.neon

# Activate baseline
sed -e "s?#- phpstan-baseline.neon?- phpstan-baseline.neon?g" -i phpstan.neon
```

### CODE REVIEW

**Comment by weisswurstkanone** [comment]
please let me know when this is ready to be reviewed. thx!

**Comment by blankse** [comment]
@weisswurstkanone You can review it.

**Comment by weisswurstkanone** [comment]
Could you please add a short essay describing this to the testing docs ?

**Comment by blankse** [comment]
@weisswurstkanone I added an entry to the docs

**Comment by weisswurstkanone** [comment]
What is the procedure for keeping phpstan-baseline.neon up to date ?

**Comment by blankse** [comment]
@weisswurstkanone If you fix phpstan errors you should generate a new baseline file. If you forget it, I don't think it's bad either. 

We can also think about automation, Similar to the "Code Standard Bot".

**Comment by weisswurstkanone** [comment]
I would prefer the second option as there are probably just a few guys out there running this manually.

**Comment by weisswurstkanone** [comment]
Thanks a lot!

**Comment by weisswurstkanone** [comment]
Can we add it to the upload artifacts for now ?

travis.yml

addons ->  artifacts -> paths

**Comment by blankse** [comment]
@weisswurstkanone What do you mean? I am not very familiar with travis.

Is following possible:

1. The master branch generate a new phpstan-baseline.neon file via after_test in this artifacts?
2. The PR branches use this phpstan-basline.neon file.

**Comment by weisswurstkanone** [comment]
Travis uploads certain files (can configured in travis.yml) to AWS. Approach would be to pick that file from time to time an check it in.

Second approach:
@brusch is it possible  to check this file in  automatically but only if generated on master branch ?

**Comment by weisswurstkanone** [comment]
@blankse seems to work :-)
see https://travis-ci.com/pimcore/pimcore/jobs/286870737?utm_medium=notification&utm_source=email

**Comment by blankse** [comment]
@weisswurstkanone Hooray 🎉

**Comment by brusch** [comment]
Whoop Whoop! 🚀🎉

**Pull request merged**
