### PR TITLE
Update 75_Reverse_Object_Relation_Type.md

### LINKED ISSUE #14001: [Docs]: Reverse Object Relation Type | Wrong / unclear documentation
### Expected behavior

Documentation should define why the descriped way is the "best way".

### Actual behavior

At least for me it's unclear why this is the best way.

### Steps to reproduce

https://pimcore.com/docs/pimcore/current/Development_Documentation/Objects/Object_Classes/Data_Types/Reverse_Object_Relation_Type.html#page_Working-with-PHP-API

Why do we have to use:
```
$def = $object->getClass()->getFieldDefinition("myNonOwnerObjectField");
$refKey = $def->getOwnerFieldName();
$refId = $def->getOwnerClassId();
$nonOwnerRelations = $object->getRelationData($refKey, false, $refId);
```
which returns an array with the object id's instead of
```
$object->getMyNonOwnerObjectField()
```
which returns an array with the objects?

### PR DESCRIPTION
**Pull request by hethehe**
## Changes in this pull request  
Resolves #14001

## Additional info  
Just a quick edit, didn't checked if there are any other new features (had no time)

### CODE REVIEW

**Comment by blankse** [comment]
👍🏼 
Can you rebase it to branch 10.5, because it's a bugfix?

**Comment by jdreesen** [comment]
The edit links in the `10.5` docs still need to be changed to point to the right branch... it is a big effort to rebase this kind of changes (compared to creating them in the first place) and is very frustrating.

**Comment by Corepex** [comment]
@hethehe friendly reminder to rebase the PR 🍭 🔔

**Comment by hethehe** [comment]
@Corepex is there an easy solution to rebase it? sorry didn't found a usable solution so far... Wouldn't it be easier for me to create a new PR in the 10.5 branch?

**Comment by Corepex** [comment]
@hethehe rebasing a PR is always a bit difficult. I also struggle with that topic so don't feel bad about that 😄.
I will do the release on Wednesday so I will cherry-pick your changes. That is probably the easiest solution 💯 🍭

**Comment by hethehe** [comment]
@Corepex thank you 😃

**Comment by blankse** [comment]
For rebasing a branch to a new base branch you need to use the rebase with the onto option:
`git rebase --onto <newparent> <oldparent>`
Than you need a force push:
`git push --force`

**Comment by Corepex** [comment]
@hethehe I created a new PR with your changes (#14094). I added you as a co-author 👍 
This will be the easiest way to merge the changes 💯

**Pull request closed without merging**
