### PR TITLE
Bug fix: Fixed faulty classification store active groups filtering 

### LINKED ISSUE #10661: [Bug]: Cannot view/restore versions of Objects with Classification Stores
### Expected behavior

When clicking on the *Versions* tab on DataObjects it should be possible to view and restore from versions created prior to Pimcore X which contains Classification Stores.

### Actual behavior

```log
[2021-10-20T09:56:31.636336+02:00] php.CRITICAL: Uncaught Error: 
Cannot assign __PHP_Incomplete_Class to property Pimcore\Model\DataObject\Classificationstore::$object of type ?Pimcore\Model\DataObject\Concrete {"exception":"[object] (TypeError(code: 0): 
Cannot assign __PHP_Incomplete_Class to property Pimcore\\Model\\DataObject\\Classificationstore::$object of type ?Pimcore\\Model\\DataObject\\Concrete at /var/www/pimcore/vendor/pimcore/pimcore/lib/Tool/Serialize.php:43)"} []
[2021-10-20T09:56:31.636655+02:00] request.CRITICAL: Uncaught PHP Exception TypeError: 
"Cannot assign __PHP_Incomplete_Class to property Pimcore\Model\DataObject\Classificationstore::$object of type ?Pimcore\Model\DataObject\Concrete" at /var/www/pimcore/vendor/pimcore/pimcore/lib/Tool/Serialize.php line 43 {"exception":"[object] (TypeError(code: 0): 
Cannot assign __PHP_Incomplete_Class to property Pimcore\\Model\\DataObject\\Classificationstore::$object of type ?Pimcore\\Model\\DataObject\\Concrete at /var/www/pimcore/vendor/pimcore/pimcore/lib/Tool/Serialize.php:43)"} []

```

image

### Steps to reproduce

Save a version in Pimcore 6.9.6
Upgrade to Pimcore 10.1+
Try to restore the object

*edit* example version file (renamed with `.txt` to allow upload here on Github)
[255796.txt](https://github.com/pimcore/pimcore/files/7379969/255796.txt)

### PR DESCRIPTION
**Pull request by michaelclaesson**
## Changes in this pull request
Resolves #10661

## Additional info
Since active groups are stored with group ID in key and whether it's enabled or not as the value, we need to filter on the key and not the value.

### CODE REVIEW

**Review by dvesh3 — CHANGES_REQUESTED** [review]
Could you please also fix it for QuickSearch https://github.com/pimcore/pimcore/blob/10.2/bundles/AdminBundle/Resources/views/SearchAdmin/Search/Quicksearch/object.html.twig#L43? thanks!

**Comment by dvesh3** [comment]
🏓 @michaelclaesson

**Comment by michaelclaesson** [comment]
> 🏓 @michaelclaesson

Haha, nice one! :-)

I will try to have it fixed today 👌🏻

**Comment by michaelclaesson** [comment]
@dvesh3 Fixed!

Another thing to look at here is what break does in the following code? As it is right now, it will never get to my classification store as it finds localized fields before that and breaks right after. 

```twig
{% set break = false %}
    {% for fieldName, definition in fields|slice(0,30) %}
        {% if not break %} {# <---------- HERE #}
            {% if definition is instanceof('\\Pimcore\\Model\\DataObject\\ClassDefinition\\Data\\Localizedfields') %}
                {% for language in validLanguages %}
                    {% for lfd in definition.getFieldDefinitions() %}
                        {% set trClass = (c % 2) ? 'odd' : '' %}
                        <tr class="{{ trClass }}">
                            <th>{{ lfd.getTitle() ? lfd.getTitle()|trans([],'admin') : lfd.getName() }} ({{ language }})</th>
                            <td>
                                <div class="limit-height">
                                    {% if element.getValueForFieldName(fieldName) %}
                                        {{ lfd.getVersionPreview(element.getValueForFieldName(fieldName).getLocalizedValue(lfd.getName(), language)) | raw }}
                                    {% endif %}
                                </div>
                            </td>
                        </tr>
                        {% set c = c + 1 %}
                    {% endfor %}
                    {% set break = true %} {# <---------- HERE #}
                {% endfor %}
            {% elseif definition is instanceof('\\Pimcore\\Model\\DataObject\\ClassDefinition\\Data\\Classificationstore') %}
                {% set storedata = element.getValueForFieldName(fieldName) %}

                {% set activeGroups = [] %}
```

**Comment by dvesh3** [comment]
> Another thing to look at here is what break does in the following code? As it is right now, it will never get to my classification store as it finds localized fields before that and breaks right after.

@michaelclaesson good catch! I would consider this a bug, as `break` is used for `validLanguages` loop and it should just display single language in the search result. could you please fix this (also at line 84) too? thanks!

**Comment by dvesh3** [comment]
Fixed break issue directly on 10.2 branch https://github.com/pimcore/pimcore/commit/6c1a586b88868ae25150b1282bc4b83b0150264?w=1

**Review by dvesh3 — APPROVED** [review]

**Comment by dvesh3** [comment]
@michaelclaesson thanks a lot!

**Comment by michaelclaesson** [comment]
> @michaelclaesson thanks a lot!

No worries!

> Fixed break issue directly on 10.2 branch [6c1a586?w=1](https://github.com/pimcore/pimcore/commit/6c1a586b88868ae25150b1282bc4b83b0150264?w=1)

Great! Sorry I wasn't able to fix it, been on sick leave.

**Pull request merged**
