### PR TITLE
Update 01_System_Requirements.md

### PR DESCRIPTION
**Pull request by jonathan00**
## Changes in this pull request  
grants for functions (routines) were missing

### CODE REVIEW

**Comment by brusch** [comment]
@jonathan00 Thanks for your PR! 
Can you please explain where routines are used by Pimcore? I can't think of any usage of function/stored procedures in the core. 
Thanks! :)

**Comment by jonathan00** [comment]
hi, 
it is needed for this sql:

CREATE FUNCTION PLUGIN_CMF_COLLECT_ASSET_SEGMENT_ASSIGNMENTS(elementIdent INT) [....]

when my mysql user didn't have the grants, installer will fail because it can't create this function

**Comment by jonathan00** [comment]
if you look at https://pimcore.com/docs/6.x/Development_Documentation/Installation_and_Upgrade/System_Setup_and_Hosting/DB_Setup.html

"grant ALL" doesn't work with AWS RDS, so i had to grant deticated rights. Currently i'm using

`GRANT SELECT, INSERT, UPDATE, DELETE, DROP, CREATE, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, CREATE VIEW, ALTER ROUTINE,CREATE ROUTINE, SHOW VIEW, EXECUTE, INDEX, EXECUTE ON .....`

**Comment by jonathan00** [comment]
FYI i still have some issues with installer, no error messages anymore but function wasn't created

**Comment by yariksheptykin** [comment]
Looks like `CREATE FUNCTION` statements come from [pimcore/customer-data-framework](https://github.com/pimcore/customer-data-framework/search?q=%22CREATE+FUNCTION%22&unscoped_q=%22CREATE+FUNCTION%22). Maybe updating the docs of this extension would be more appropriate here? Maybe under [Installation](https://github.com/pimcore/customer-data-framework/blob/master/doc/02_Installation.md#installation)?

**Comment by jonathan00** [comment]
functions are  defined in 
`storedFunctionAsset.sql     storedFunctionDocument.sql  storedFunctionObject.sql`

**Comment by jonathan00** [comment]
FYI, issues with functions #4526 but workaround didn't work

**Comment by brusch** [comment]
The CMF (https://github.com/pimcore/customer-data-framework) is not part of the core product (it's an additional optional bundle provided by the core-team), therefore the right place for this kind of information would be here: https://github.com/pimcore/customer-data-framework/blob/master/doc/02_Installation.md

**Comment by brusch** [comment]
Thanks anyway 👍😊

**Comment by jonathan00** [comment]
hi,

but i used Option 4 (Advanced Demo Package)
from https://pimcore.com/docs/6.x/Development_Documentation/Getting_Started/Installation.html

**Comment by jonathan00** [comment]
so in my point of view it is relevant

**Pull request closed without merging**
