### PR TITLE
wysiwyg: pre-fill image alt and title from asset metadata

### PR DESCRIPTION
**Pull request by chix**
Hi, as discussed via e-mail yesterday, here is the pull request. Martin

### CODE REVIEW

**Comment by fashxp** [comment]
hi martin, 
thank you very much for your pull request. We reviewed and discussed it internally and there is one aspect we need to consider: 

We don't think that the the tree items are the correct place for this information. 
Basically this information has nothing to do with the tree itself and is only needed in a quite special use case. Therefore we should not fill up the tree items with such kind of information (also in terms of performance). Also the necessary tree reload on asset save is quite a big trade off to archive this.

What is about loading the metadata information via ajax directly when an asset it assigned to wysiwyg fields? So we would leave the tree out of this.

The feature itself is a very good idea and we would like take this a step further. 
What do you think about this aspect? 


P.S.: it is only a minor thing, but please also use {} for one-line-if-statements too (http://www.php-fig.org/psr/psr-2/#5-1-if-elseif-else). thanks.

**Comment by chix** [comment]
Hi, sound good, I did not consider that. I can update the pull request if you want. Just wondering if a synchronous ajax call would be good enough or should I try to load the metadata asynchronously and inject them into the wysiwyg html after the image is shown?

**Comment by fashxp** [comment]
hmm, i guess we have to try what is best. and also what is possible. if you like, please have a look at it :)
thanks...

**Comment by chix** [comment]
Hi, I made some changes, hope it's better now :).

**Comment by cmaerz** [comment]
Any Updates here?

**Comment by brusch** [comment]
No. Actually there's more to consider then it seems to be, therefore we put this on hold. 
To summarize it: 
- Design decision: should it be a pre-fill or should it keep itself up to date
- Context issues: eg. localized fields in field collections, ...

**Comment by brusch** [comment]
Actually the development of the upcoming major version is already quite well-advanced, so we've decided to do not accept any further features for the v4 branch. 
If you'd like to see this feature in version 5, please create an issue for us.  
We'll take it into consideration as soon as possible.

**Pull request closed without merging**
