### PR TITLE
Update Dao.php

### PR DESCRIPTION
**Pull request by j-jonas**
getRelationData is called in vendor\pimcore\pimcore\models\DataObject\ClassDefinition\Data\Objectbricks.php line 201 with null as third parameter

### CODE REVIEW

**Comment by mattamon** [comment]
@j-jonas this should also be a bugfix?

**Comment by j-jonas** [comment]
Yes, it is a bugfix

**Comment by mcop1** [comment]
@j-jonas same here, please rebase to 11.0. 
Thank you for your efforts.

**Comment by j-jonas** [comment]
see https://github.com/pimcore/pimcore/pull/15312
please delete this

**Comment by mattamon** [comment]
Closed in favor of #15312

**Pull request closed without merging**
