### PR TITLE
Fix: Exception thrown in "Search Assets" window

### LINKED ISSUE #11281: [Bug]: Exception thrown in "Search Assets" window
### Expected behavior

If no search is provided initially and the table is sorted, all assets should be displayed in correct order.

grafik

### Actual behavior

If no search is provided initially and the table is sorted, an exception is thrown.

grafik

Exception:
```
Pimcore\Bundle\AdminBundle\Controller\Searchadmin\SearchController::filterQueryParam(): Argument #1 ($query) must be of type string, null given, called in /var/www/html/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Searchadmin/SearchController.php on line 74

Server threw exception - could not perform action. Please reload the admin interface and try again.
```

### Steps to reproduce

1. Head over to [https://demo.pimcore.fun/admin/?perspective=CMS](https://demo.pimcore.fun/admin/?perspective=CMS)
2. Create a blank page
3. Add an image element
grafik
4. Right click the element > Search
grafik
5. Click directly on a table header, e.g. "Path", to sort the content. Do not type anything in the search field beforehand.
grafik

### PR DESCRIPTION
**Pull request by blankse**
Fix https://github.com/pimcore/pimcore/issues/11281

### CODE REVIEW

**Comment by BabovicT** [comment]
@blankse it does fix the part where exception is thrown but now there is another bug. Go to dociment search for example and press the path. Now because type param is not send, after you press it, you see resoults for everything nit just documents.

**Comment by blankse** [comment]
@BabovicT Fix this bug also.

**Comment by brusch** [comment]
@blankse thanks a lot for your PR, however, since it's a bug fix, it should be based on `10.2` branch, right? Could you please rebase? Thanks in advance!

**Comment by blankse** [comment]
@brusch Was created for 10.2 :) Only the branch in PR was wrong. Now it should be correct.

**Comment by mcop1** [comment]
Looks great, thanks!

**Pull request merged**
