### PR TITLE
add LibreOffice as Web2Print Option

### PR DESCRIPTION
**Pull request by anyMOTION-GRAPHICS**
## Please make sure your PR complies with all of the following points: 
- [ X ] Read and accept our [contributing guidelines](/CONTRIBUTING.md) before you submit a PR.
- [ X ] Features need to be proper documented in `doc/`

**Don't submit a PR if it doesn't comply, it'll be closed without a comment!**
  
## Changes in this pull request  
Added a Web2Print Option for LibreOffice to use LibreOffice for rendering PDFs.

## Additional info
Pimcore 5 only

### CODE REVIEW

**Comment by fashxp** [comment]
Thank you very much for this contribution. 
Could you please remove all the translations except the English one from the pull request? The other languages will be imported from [POEditor](https://poeditor.com/join/project/VWmZyvFVMH) automatically.

**Comment by fashxp** [comment]
and please sign the CLA :)

**Comment by anyMOTION-GRAPHICS** [comment]
@fashxp The CLA is signed :)

**Comment by fashxp** [comment]
:+1: perfect, could you also please remove all the translations except the English one from the pull request? (see comment above). 
thank you!

**Comment by brusch** [comment]
@anyMOTION-GRAPHICS quick reminder ;) Thank you 😸

**Comment by brusch** [comment]
@anyMOTION-GRAPHICS anything?

**Comment by anyMOTION-GRAPHICS** [comment]
@brusch and @fashxp we apologize for the long distance between your feedback/request and out answer. The languages are deleted from PR.

**Comment by brusch** [comment]
@anyMOTION-GRAPHICS unfortunately there are still changes in the languages files, you'd need to revert the changes, instead of deleting the actual files 😉
Please also resolve the conflicts. 

Thanks again!

**Comment by dvesh3** [comment]
@anyMOTION-GRAPHICS please fix the conflicts so that we can review & merge this PR. Thank you! 😃

**Comment by brusch** [comment]
Closed due to inactivity.

**Pull request closed without merging**
