### PR TITLE
Fix sending image data embedded in CSV

### PR DESCRIPTION
**Pull request by NiklasBr**
## Changes in this pull request  
Sending image data in CSV didn't really make a lot of sense, fixing it to instead send the expected image path.

See #13079

### CODE REVIEW

**Comment by mcop1** [comment]
@NiklasBr since this is a change of behaviour, could you please rebase to 11.x? 
Thank you.

**Comment by NiklasBr** [comment]
image

Huh?

Was the behaviour correct to begin with?

**Comment by NiklasBr** [comment]
@mcop1 why change target?

**Comment by mcop1** [comment]
@NiklasBr I tried to change the target to 11.x, because I wanted to see if it works without rebasing, but it didn´t, so I changed it back to 10.5. 
image

But this pr changes the behaviour and I think it would be better to avoid this in a bugfix release. That´s why I have asked you to please rebase it to 11.x.

**Comment by NiklasBr** [comment]
Isn't the entire point of bug fixes to resolve unintended behaviours?

**Comment by mcop1** [comment]
The path makes more sense to me too, I agree with you on that. But the code is as it is since years. I can´t say if no one is using this feature, but if someone is, then we would break the behaviour for him.

**Comment by NiklasBr** [comment]
See #13154

**Pull request closed without merging**
