### PR TITLE
ElementInterface classes should be trigger a deprecation warning if an integer id param is passed to the getById() method

### PR DESCRIPTION
**Pull request by blankse**
See:
https://github.com/pimcore/pimcore/blob/a3ce0f91a8847993372f7eea22e608b6b555bbbd/models/Element/ElementInterface.php#L64

### CODE REVIEW

**Comment by dvesh3** [comment]
We intentionally kept the string type hint for `$id` in the `getById()` is for BC reasons as before you could use string numeric id for the elements.

Agree, the implementation looks wrong but this change could break existing implementations (keeping serialized data in mind) so we need to come up with a proper strategy to migrate this property. I'll create an issue to correct the implementations later on.

At the moment, we cannot accept this change. Sorry!

**Comment by blankse** [comment]
@dvesh3 Should we than not remove the "declare(strict_types=1);" for BC reasion? Than the numeric strings should be automatic cast to int.

**Comment by dvesh3** [comment]
Nope. we still want to remain strict for other methods in the implementation.

**Comment by blankse** [comment]
I think we should at least generate a deprecation warning when a string is passed. Then we can remove it later. Should I adapt the PR to this?

**Comment by dvesh3** [comment]
@blankse yes, you can re-open the PR afterwards. thankyou!

**Comment by blankse** [comment]
@dvesh3 I added a commit to the branch. Can you reopen the PR?

**Comment by dvesh3** [comment]
@blankse done. could you please resolve the conflicts? thanks!

**Comment by blankse** [comment]
@dvesh3 Done :)

**Comment by dvesh3** [comment]
@blankse thanks a ton!

**Pull request merged**
