### PR TITLE
[WebsiteSettings] getData() should lazy load relations

### LINKED ISSUE #4095: [Website Settings] Creating new items is not possible anymore

### PR DESCRIPTION
**Pull request by blankse**
Resolves #4095
Follow up of #3973

### CODE REVIEW

**Comment by brusch** [comment]
@blankse thanks for your PR! 
One thing ... can you please put the changes regarding `Properties` into a separate PR as it is something completely different? 
Thanks a lot!

**Comment by blankse** [comment]
@brusch I put the changes of Properties to a separate PR: https://github.com/pimcore/pimcore/pull/4166

**Comment by brusch** [comment]
Internal note: add BC warning to upgrade notes before merging.

**Comment by blankse** [comment]
@brusch Is already in the BC Notes:
https://pimcore.com/docs/5.x/Development_Documentation/Installation_and_Upgrade/Upgrade_Notes/Within_V5/index.html

Was not reverted

**Comment by blankse** [comment]
@dvesh3 I fixed the usage via \Pimcore\Config\Config

**Pull request merged**
