### PR TITLE
fix apache configuration documentation

### PR DESCRIPTION
**Pull request by dbu**
## Please make sure your PR complies with all of the following points: 
- [x] Read and accept our [contributing guidelines](/CONTRIBUTING.md) before you submit a PR.
- [x] Features need to be proper documented in `doc/` 
- [x] Bugfixes need a short guide how to reproduce them -> target branch is the oldest supported maintenance branch, e.g. `11.1` (see Readme.md for the list of supported versions)
- [x] Meet all coding standards (see PhpStan actions) 

## Changes in this pull request  

I tried the setup instructions but did not get static files to be served. Not sure if the original configuration would be the correct one for some versions of Apache (its been quite a while since i had to use it), but with my 2.4.57, the REQUEST_FILENAME is only the path and we need to prepend the DOCUMENT_ROOT

### CODE REVIEW

**Comment by robertSt7** [comment]
@dbu Since this is a bugfix, could you please rebase the PR to 11.1? Thanks

**Comment by brusch** [comment]
@dbu were you using the config in the context of a `.htaccess` or directly in the vhost?

**Comment by dbu** [comment]
uh, that might explain it :see_no_evil: 

i use it in the vhost configuration. i have not done much apache in the last decade, but back in the days `.htaccess` was considered the hacky solution. might well be that in `.htaccess` it would work without the change. if it still works with the change too, it could make sense to keep it for others who also configure the vhost directly.

**Comment by brusch** [comment]
@dbu Yeah, I guess that's the reason then 😊 
I'm not (entirely) sure whether your change also works in the context of `.htaccess` and I currently don't have the possibility to test it. Maybe someone else could help here? 😊

**Comment by fashxp** [comment]
anyone in?

**Comment by brusch** [comment]
Keeping it as it as for now for 2 reasons: 
- the documentation is explicitly talking about `.htaccess` context and not about others (server config, vhost, directory) 
- Symfony is using the config as it is - we'd like to stay here close to how Symfony does and recommends things 

Using the config in a different context probably needs some more adaptions anyway 🤔 

Thanks anyway for your PR.

**Pull request closed without merging**
