### PR TITLE
Do not silently ignore invalid setOrder/setOrderKey parameters

### PR DESCRIPTION
**Pull request by blankse**
## Changes in this pull request  

Pimcore should give a feedback if a developer use the setOrder/setOrderKey methods wrong.

### CODE REVIEW

**Comment by lukmzig** [comment]
@blankse thank you for the improvement

**Comment by dpfaffenbauer** [comment]
@blankse @lukmzig this actually is a bc break see here https://github.com/instride-ch/pimcore-data-definitions/issues/436

**Comment by blankse** [comment]
@dpfaffenbauer I don't think so. Your usage was incorrect, and this exception has now revealed it.

**Comment by dpfaffenbauer** [comment]
@blankse thanks for the PR, we will merge it. But I still consider it a BC, it worked before without a exception ;) Wrong usage is true, but it didn't break anything.

**Comment by jdreesen** [comment]
But there is no BC promise for wrong usage, right? If there were, it probably wouldn't be possible to fix any bug without it being a BC break, and every release would have to be a major release.

See also: https://xkcd.com/1172/ :wink:

**Comment by dpfaffenbauer** [comment]
@jdreesen right. okay. I agree. 

No worries then guys :)

**Pull request merged**
