### PR TITLE
fix getEnv #475

### PR DESCRIPTION
**Pull request by solverat**
fix getEnv #475

### CODE REVIEW

**Comment by brusch** [comment]
Sorry, but where is the difference, ...? ;-) 
getenv() returns false if the variable doesn't exists and that's fine - so what does your patch actually fixes?

**Comment by brusch** [comment]
Assuming PIMCORE_ENVIRONMENT is not set, getenv() returns false, according to your code you return FALSE again because of the ternary - and then the same procedure again, ... for me this makes no sense ;-) 

$env = getenv("PIMCORE_ENVIRONMENT") ?: (getenv("PIMCORE_ENVIRONMENT") ?: FALSE);

**Comment by solverat** [comment]
i'm sorry! you'r right of course, i pushed to corrected version.

and that's why: when working with rewrite rules in `.htaccess` to set the environment and in some cases its bindet with the .htaccess per-dir context.

for an example:

````
RewriteCond %{HTTP_HOST} ^localhost
RewriteRule .? - [E=PIMCORE_ENVIRONMENT:Development]
RewriteCond %{HTTP_HOST} ^staging\.site\.com$
RewriteRule .? - [E=PIMCORE_ENVIRONMENT:Staging]
RewriteCond %{HTTP_HOST} ^www\.site\.com
RewriteRule .? - [E=PIMCORE_ENVIRONMENT:Production]
```
more about that: http://stackoverflow.com/a/10128290

**Comment by brusch** [comment]
ok, thanks for your feedback - so there's nothing wrong in pimcore, right?

**Comment by solverat** [comment]
actually there is. without the REDIRECT_ -prefix it's not possible to define the PIMCORE_ENVIRONMENT environment variable in the htaccess like the example above.

**Comment by brusch** [comment]
Ah, sorry - browser - cache, haven't seen the updated code :-) 
Sorry :)

**Comment by brusch** [comment]
Merged - Thanks :+1:

**Pull request merged**
