### PR TITLE
[Data Object] Unique and Index option should be only available on data-types th…

### LINKED ISSUE #5861: [Data Object] Unique option should be only available on data-types that support it
Currently this option is available across nearly all data-types even though they don't support it. 
See also #5850 

This option should be limited to data-types that support it, currently: input, numeric, user

### PR DESCRIPTION
**Pull request by weisswurstkanone**
resolves #5861

### CODE REVIEW

**Comment by weisswurstkanone** [comment]
resolves #5861

**Comment by brusch** [comment]
Looks good, should we implement the same for the index? Would make sense in my opinion. I think we can add this to this PR.

**Comment by weisswurstkanone** [comment]
Good question. This would affect everything that implements ResourcePersistenceAwareInterface and is not relational.

**Comment by brusch** [comment]
@weisswurstkanone well, many to one would work in theory 😊
But I think it would make sense, just to avoid misunderstandings, ... you don't think this is worth the effort?

**Comment by weisswurstkanone** [comment]
Currently this is "enabled" by default. Changing this in the same manner would maybe break custom data types.

**Comment by brusch** [comment]
@weisswurstkanone ok, then let's leave it as it is for now.

**Pull request merged**
