### PR TITLE
Editing the Classification values in grid view throws an error

### PR DESCRIPTION
**Pull request by ayoob-lfc**
## Changes in this pull request  
Resolves the following issue:
https://github.com/pimcore/pimcore/issues/15758

### CODE REVIEW

**Comment by blankse** [comment]
@ayoob-lfc I think we shouldn't cast the values to string. We should change the return type of the getStoreValueForObject method to `mixed`

**Comment by blankse** [comment]
@ayoob-lfc I created a alternative PR https://github.com/pimcore/pimcore/pull/15773

**Comment by blankse** [comment]
@ayoob-lfc With your change I get a warning instead:
image

**Comment by ayoob-lfc** [comment]
@blankse You are correct. I tested your changes with my setup and it works 👍

**Pull request closed without merging**
