### PR TITLE
Extract method for processing result in AbstractElasticSearch

### PR DESCRIPTION
**Pull request by mysliwietzflorian**
## Changes in this pull request  

In order to use or modify results from Elasticsearch queries other than [Bucket Aggregations](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket.html#search-aggregations-bucket) (cf. metrics or pipeline aggregations) in the `doLoadGroupByValues()` method this functionality was extracted into its own method.

### CODE REVIEW

**Comment by brusch** [comment]
@mysliwietzflorian Thanks a lot for your PR. Since this isn't a bug fix, can you please rebase this PR onto the `6.9` or `master` branch and change the merge target accordingly? Thanks!

**Comment by mysliwietzflorian** [comment]
@brusch I hope you meant it like this. :)
I cannot change the base branch on GitHub therefore the branchnames do not match.

**Comment by brusch** [comment]
@mysliwietzflorian unfortunately not, there's still 59792e875e8ae27ea05d58f3fc01a212c68c5575 which doesn't belong to this PR. 
I'll just push it directly, thanks anyway.

**Comment by brusch** [comment]
Fixed by 392ec4cf43bf2ecb440ef353746f26c65ecf3df0

**Comment by jdreesen** [comment]
You should have kept @mysliwietzflorian as the author, though...

**Pull request closed without merging**
