### PR TITLE
PhpDoc - loadIdList does not return an integer array.

### PR DESCRIPTION
**Pull request by ultramegatom**
loadIdList does not return an integer array.

### CODE REVIEW

**Comment by brusch** [comment]
Thanks!

**Comment by dpfaffenbauer** [comment]
what else does it return? string array with ids? Cause it should be int[]

**Comment by blankse** [comment]
The Ids are strings. Is it possible to cast these to integer?
```
array (size=4)
  0 => string '447' (length=3)
  1 => string '441' (length=3)
  2 => string '445' (length=3)
  3 => string '443' (length=3)
```

**Comment by dpfaffenbauer** [comment]
thats the point I tried to make with my comment ;)

**Comment by blankse** [comment]
I created a PR for this https://github.com/pimcore/pimcore/pull/4003

**Pull request merged**
