### PR TITLE
Added locale interface

### PR DESCRIPTION
**Pull request by ascheider**
## Changes in this pull request  
Added possibility to decorate locale service.

At the moment it is not possible to decorate locale service because of usage concrete Locale class and not the interface.
So added possibility to decorate the service like:
 AppBundle\DecoratingLocale:
      decorates: Pimcore\Localization\Locale
      # pass the old service as an argument
      arguments: ['@AppBundle\DecoratingLocale.inner']

### CODE REVIEW

**Comment by brusch** [comment]
Thanks for your PR! 
So far it looks good, but the `LocaleInterface` should have defined all methods required by Pimcore.

**Comment by ascheider** [comment]
@brusch ok, you mean all methods which are implemented in locale?
I will update PR

**Comment by brusch** [comment]
@ascheider yep, otherwise when decorating it, it's not guaranteed that everything still works when they are missing in the interface :)

**Comment by ascheider** [comment]
@brusch ok right. One more question. Should i add declare(strict_types=1); to my interface? Locale.php does not have declare(strict_types=1);

**Comment by brusch** [comment]
@ascheider no, not necessary if `Locale.php` doesn't have it

**Comment by ascheider** [comment]
@brusch ok, thanks.
PR is updated. 
Ping me when there are further issues.

**Pull request closed without merging**
