### PR TITLE
Installer improvements

### LINKED ISSUE #1420: [Installer] add way to integrate additional repositories - like demo-ecommerce
important aspects
- download additional installation profiles from github repositories into /install-profiles/xxx
- list additional install-profiles in install.php
- add possibility to run composer update in order to add additional dependencies if necessary.

### PR DESCRIPTION
**Pull request by maff**
Resolves #1420 

* reusable installer can be used from `install.php` and a CLI command `bin/install`
* install profiles can be resolved from `vendor/` and from `install-profiles/` and define what is installed through a `manifest.yml`
* CLI command adds a switch to symlink profile files instead of copying them (useful for dev environments)
* install data (credendials, ...) for CLI installer can be set via env variables

Example CLI usage:

    $ PIMCORE_ENVIRONMENT=dev bin/install --symlink --profile demo-ecommerce --admin-username admin --admin-password admin --mysql-username homestead --mysql-password secret --mysql-database pimcore5 --ignore-existing-config --no-interaction

### CODE REVIEW

**Comment by dpfaffenbauer** [comment]
This is amazing! Thanks very much, makes it very easy for automated installs with custom "bootstrap" design.

One question: What do think about installing pimcore-bundles with install-profiles as well? I mean, installing the demo-ecommerce profile is not enough, Somebody (or something) still needs to enable/install the corresponding Pimcore-Bundle as well.

**Comment by brusch** [comment]
Well, it would be more *enabling* bundles than installing - because installing should be done using composer?

**Comment by dpfaffenbauer** [comment]
With installing I mean calling the Pimcore\Extension\Bundle\Installer\InstallerInterface::install method of the PimcoreBundle.

**Comment by brusch** [comment]
I guess we could add another config option `bundles` to the manifest, yes.

**Comment by dpfaffenbauer** [comment]
related to that, I created a issue for dependent symfony-bundles, which will be a case for bigger plugins (like CoreShop). And I am sure, CoreShop will not be the only plugin which will depend on certain symfony-bundles. (https://github.com/pimcore/pimcore/issues/1780)

**Comment by maff** [comment]
@dpfaffenbauer Good idea! We'll merge this change to have the basic installer infrastructure in place and will have a look at the dependency resolving logic (also inside extension manager) in a later step. I'll still need to test all the implications of calling a/multiple bundle installers simultaneously, especially when coming from "outside" (a Pimcore kernel being booted later) as in this situation. 

Before bringing this to the installer level I think we should sort out #1750 and #1780 for already installed instances to see how this can be integrated here.

For the installer, this would add:

* Installer checks if a bundle is available (installed via composer) before installing a profile (easy)
* Installer applies the same logic as the extension manager when auto-enabling and installing a bundle + handling of dependent bundles

**Pull request merged**
