### PR TITLE
[Document] Fix: Tags getElement method returns only saved data

### PR DESCRIPTION
**Pull request by blankse**
I have an areablock with items. These items have editables like an input.
In the moment it is impossible to get the current data from this input in the controller.
Because the getElement method loads the saved version of the document.

I add a setDocument and getDocument method. So we can use the modified document.

### CODE REVIEW

**Comment by brusch** [comment]
@blankse Thanks a lot for your PR! 
I'm afraid that this was for a reason, namely because of caching and versioning where the documents get serialized. If we go in this direction we should correctly implement `__sleep()`.

**Comment by blankse** [comment]
@brusch I add the new document property to the __sleep method

**Comment by brusch** [comment]
@blankse Thanks a lot! 
Maybe one more thing ... what do you think about adding the following to `setDocumentId()`: 

```php
    public function setDocumentId($id)
    {
        $this->documentId = (int) $id;
        
        if($this->document instanceof PageSnippet && $this->document->getId() != $this->documentId) {
            $this->document = null; 
        }
        
        return $this;
    }
```

Just to ensure `$this->document` can't be a different document as stored in `$this->documentId`.

**Comment by blankse** [comment]
@brusch I extended the `setDocumentId()` method 👍

**Comment by brusch** [comment]
Thanks! :)

**Pull request merged**
