### PR TITLE
Checkbox fix.

### LINKED ISSUE #13804: [Bug]: Checkbox in grid moves down by selection. If a class has a checkbox field, editing will slide that field down the grid instead of checking it in. To check, you have to click on the slipped checkbox again.
### Expected behavior

When clicking checkbox field in grid, checkbox should be direct checked/unchecked.

### Actual behavior

Checkbox is slid down and only then can it be edited.

### Steps to reproduce

This can easily be reproduced on demo system:
- Add checkbox-Field to class definition
Bildschirmfoto 2022-12-14 um 18 17 38

- add this field to grid view 
Bildschirmfoto 2022-12-14 um 18 17 07

- click on checkbox field. checkbox is slid down 
Bildschirmfoto 2022-12-14 um 18 17 19

### PR DESCRIPTION
**Pull request by torqdev**
## Changes in this pull request  
Resolves #13804

### CODE REVIEW

**Comment by dvesh3** [comment]
@torqdev Hi, thanks for your PR. Could you please rebase it on 10.5 branch? since this is a fix.

**Comment by Corepex** [comment]
@torqdev friendly reminder 👀

**Comment by torqdev** [comment]
Hi @dvesh3 and @Corepex - we were going with `10.6` because of this line https://github.com/pimcore/pimcore/blob/bf8d956c5e7ab85ee85ea79a59348c58625d53d6/CONTRIBUTING.md?plain=1#L11 in  `CONTRIBUTING.md`. Please advise.

**Comment by jdreesen** [comment]
@torqdev you have to rebase the branch on `10.5`.

**Comment by torqdev** [comment]
New PR: https://github.com/pimcore/pimcore/pull/14017

**Pull request closed without merging**
