### PR TITLE
fix custom-view classes save as array

### PR DESCRIPTION
**Pull request by solverat**

### CODE REVIEW

**Comment by weisswurstkanone** [comment]
What is the actual issue here? Also, does this affect the ExtJS6 mode in any way?

**Comment by solverat** [comment]
hey - yes, the issue comes with extjs6. if you try to save more than one class in a custom view, its not possible because of the missing array element in the request.

**Comment by weisswurstkanone** [comment]
so you are saying that this actually fixes a issue that comes with ExtJS6 but wasn't there in 3.4?

**Comment by solverat** [comment]
just tested it with demo.pimcore.org, can't confirm it for ext4. will test it the next hour.

**Comment by solverat** [comment]
i'm sorry, i edited the wrong setings.js. the problem only appears in ext6 (see video above). in ext4 everything works fine.

**Comment by weisswurstkanone** [comment]
fixed in build 3620

**Pull request closed without merging**
