### PR TITLE
[DataObject] Classdefinition - Fix available sites selection in url slug field

### LINKED ISSUE #10604: [Bug]: Domain input for URL Slug is hidden since Pimcore X
### Expected behavior

All fields should be visible in the Ext JS interface.

### Actual behavior

The domain-specific URL Slug field (and its button is hidden:
image
image

By manually adjusting the height of the elements in the DOM it is possible to show that both fields are available, just hidden behind some inline `height` attributes:
image

### Steps to reproduce

Putting a URL Slug in a fieldset which in turn is in a Localized fields 

image

### PR DESCRIPTION
**Pull request by dvesh3**
## Changes in this pull request  
Related to https://github.com/pimcore/pimcore/issues/10604#issuecomment-1044176324

### CODE REVIEW

**Comment by NiklasBr** [comment]
I don't think this seems to fix the issue linked, it is only ~hiding the~ fixing another problem.

**Comment by dvesh3** [comment]
> I don't think this seems to fix the issue linked, it is only ~hiding the~ fixing another problem.

yes, the description was wrongly typed. Now fixed it by stating "Related to".

**Comment by NiklasBr** [comment]
Please revert this. it made #10604 worse

**Comment by dvesh3** [comment]
@NiklasBr how?

**Comment by NiklasBr** [comment]
The entire field disappeared. Removing this PR manually in 10.3.3 at least restores some of the fields.

**Comment by dvesh3** [comment]
This change is for classdefinition, so it shows selected values on reload. I don't understand how it affects the fields visibility 😕

**Comment by NiklasBr** [comment]
In 10.2.10 the fields were visible and the URL Slugs could be edited in the admin interface, but after updating to 10.3.2 and 10.3.3 respectively this no longer works. I don't understand it either, which is why I need your documentation to fix it the way you want it fixed, but at least reverting this change locally improves situation so that at least some parts works.

**Comment by dvesh3** [comment]
Sorry, this change does not affect the fields visibility on edit view. Infact fixes the multiselect selection view in classdefinition so we don't need to revert this.

**Pull request merged**
