### PR TITLE
Deprecate `Pimcore\Tool\Authentication::authenticateHttpBasic()`

### PR DESCRIPTION
**Pull request by jdreesen**
It seems like this method is not used in Pimcore itself (anymore?) so I propose to deprecate it in Pimcore `10.6` and [remove it in Pimcore `11.0`](https://github.com/pimcore/pimcore/pull/14299).

### CODE REVIEW

**Comment by jdreesen** [comment]
Test failures are not related and should be fixed upstream by allowing or disallowing the new composer plugin of `php-http/discovery`.

**Comment by brusch** [comment]
LGTM, afaik this was used for WebDav, but should be covered by https://github.com/pimcore/skeleton/blob/11.x/config/packages/security.yaml#L14 now.

**Comment by jdreesen** [comment]
Probably, as the used `\Sabre\HTTP\...` API comes with the `sabre/dav` package.

**Review by dvesh3 — APPROVED** [review]

**Comment by dvesh3** [comment]
@jdreesen thanks!

**Pull request merged**
