### PR TITLE
Added CLI utility to reset password

### PR DESCRIPTION
**Pull request by gabrielsomoza**
In case you're interested. This might be useful to other users and to e.g. automate installation under certain use-cases. 

Usage:
```bash
php pimcore/cli/reset-password.php id/username
```

The utility will prompt for the new password and update the record in the database automatically.

### CODE REVIEW

**Comment by brusch** [comment]
Nice tool. 
But before we can merge it, we have to ensure it's platform independent. 
Can you remove the dependency on "bash"?

**Comment by brusch** [comment]
See http://stackoverflow.com/a/15322457 
That should do the trick without utilizing bash. 

Thanks!

**Comment by gabrielsomoza** [comment]
Done, ended up using a tool from http://www.sitepoint.com/interactive-cli-password-prompt-in-php/ because the other one wouldn't hide the password as its being typed.

NB: I can't test windows compatibility myself though..

**Comment by brusch** [comment]
Thanks

**Comment by gabrielsomoza** [comment]
A pleasure, hope it helps someone :)

**Comment by brusch** [comment]
There was a problem with your pull request. 
See this patch: https://github.com/pimcore/pimcore/commit/2514d3e3f9c22694fce1d858079c9ba672010e56

**Comment by gabrielsomoza** [comment]
Sorry about that, I had actually fixed that but it looks like I forgot to move the latest changes to the PR after I tested it in my local project.

**Pull request merged**
