### PR TITLE
Setup Content Security Policy header based on new handler.

### PR DESCRIPTION
**Pull request by aryaantony92**
## Changes in this pull request  
Follow up to pimcore/pimcore#11447

## Additional info  

Added the whitelisting for the urls. But the page is not loaded since there is some issue with the inline scripts in external opcache page.

### CODE REVIEW

**Comment by NiklasBr** [comment]
Shouldn't these be added to the [default configuration](https://symfony.com/doc/current/components/config/definition.html#default-and-required-values) rather than in the code?

**Comment by aryaantony92** [comment]
No, we don't want to override the default configuration

**Comment by NiklasBr** [comment]
Why?

**Comment by dvesh3** [comment]
@NiklasBr because these URLs should be merged with the ones provided from bundle configs. These are whitelisted here for Opcache view in admin interface.

**Pull request merged**
