### PR TITLE
Fix exception on pimcore:build:classes when db not available

### LINKED ISSUE #16157: [Bug]: Exception on execute ClassesDefinitionsBuildCommand
### Pimcore version

11.1

### Steps to reproduce

- update from v11.0.12 to v11.1 

- call the command

`pimcore/bin/console pimcore:build:classes`

### Actual Behavior

exception

### Expected Behavior

update to v11.1 and call of the command possible without error

### PR DESCRIPTION
**Pull request by dvesh3**
## Changes in this pull request  
Resolves #16157

### WHAT
copilot:summary

copilot:poem

### HOW
copilot:walkthrough

### CODE REVIEW

**Comment by dvesh3** [comment]
Do not silently catch exceptions when db not available on running class rebuild command. We still need to fix this issue https://github.com/pimcore/pimcore/issues/16157#issuecomment-1822404236 along with notices about using `settings-store`configs on deployment.

**Comment by brusch** [comment]
Alternative fix: https://github.com/pimcore/ee-pimcore/pull/19

**Comment by jdreesen** [comment]
grafik

**Comment by brusch** [comment]
@jdreesen yeah, sorry about that - this is intentional, we'll share the reasons behind this soon 😊

**Pull request closed without merging**
