### PR TITLE
[FIX]: Filter for object brick attributes does not work

### LINKED ISSUE #12293: [Bug]: Filter for object brick attributes does not work
### Expected behavior

Sort or filter on an attribute of an object brick in the grid view.

### Actual behavior

An error message pops up:
image

### Steps to reproduce

1. Open a gridview for a class that contains objectbricks
2. Add a random attribute (from an objectbrick) to the grid view. (in my case this was a WYSIWYG-field)
3. Try to sort or filter on it.

Pimcore-version: 10.3.3

### PR DESCRIPTION
**Pull request by dturopoli**
Resolves #12293

Issue was caused by localized fields inside object brick

### CODE REVIEW

**Comment by kingjia90** [comment]
Thank you for the PR! 

I've review it, filtering works again, but Sorting is not fixed. It seems expecting a key with a question mark for localized Fields. 

I've also noticed with the classTree changes, the following case (highlighted in yellow) cannot be dragged in Grid Options anymore. Could you also double check this?
image

**Comment by kingjia90** [comment]
Notes: might also need to take in consideration this https://github.com/pimcore/pimcore/pull/12349

**Comment by kingjia90** [comment]
@dturopoli Just a gentle reminder 🏓

**Comment by dturopoli** [comment]
@kingjia90 I think d&d is working now. I'm not sure about Sorting, I can't reproduce bug, it is working for me. Maybe I'm missing some test case

**Comment by dvesh3** [comment]
@dturopoli thanks!

**Pull request merged**
