### PR TITLE
PIMCORE-2466 Change order of the system language

### PR DESCRIPTION
**Pull request by nspacex**
Reordering is still not possible but each language-container has a "mark as default" option

### CODE REVIEW

**Comment by brusch** [comment]
Hi, 

Thanks for your pull request, but I can't see anything in the code that allows changing the order of the languages (as the title of the pull request says)? All is just about defining a default language, is this right so far - so only the title of the pull request is wrong?

Thanks for clarifying!

**Comment by nspacex** [comment]
Hi,

yes you are right, the title is actually wrong / unclear. I have only added radio buttons to language containers. I think this is a easier way to define the default language (?)

pimcore-lang

regards,
Erik

**Comment by brusch** [comment]
Thank you very much!

**Comment by nspacex** [comment]
Your welcome, btw. sorry for the wrong jira-issue-id, it is PIMCORE-2446 instead of PIMCORE-2466.

**Pull request merged**
