### PR TITLE
Make symfony/dotenv package optional 

### LINKED ISSUE #11411: [Bug]: \Pimcore\Bootstrap::prepareEnvVariables forces using DotEnv
### Expected behavior

When running in modern environments like Lambda or containers (local dev and prod), the env vars are not distributed via files but are **real environment variables**. In which case the DotEnv component creates some issues and noise, so it's generally a best practice to not use it there at all. This is known even to Symfony so [they support checking for it being installed or disabling it in their Runtime component](https://symfony.com/doc/current/components/runtime.html#using-options).

Pimcore currently hard requires the `DotEnv` component (which is IMO a mistake, as discussed in #11105), but the component itself can be removed in a hackish way by adding this to your own `composer.json`:

```json
    "provide": {
        "symfony/dotenv": "v5.4.0"
    },
```

The `DotEnv` component should be removed as the hard dependency and the loading using it of it should be made optional (either via config or at least checking with `class_exists` that it's there).

### Actual behavior

`DotEnv` component hardcoded into Pimcore 10.x

### Steps to reproduce

1. add to your `composer.json`:
```json
    "provide": {
        "symfony/dotenv": "v5.4.0"
    },
```
2. run `composer update`, `symfony/dotenv` gets removed
3. `\Pimcore\Bootstrap::prepareEnvVariables` complains about the class not being available

### PR DESCRIPTION
**Pull request by dvesh3**
## Changes in this pull request  
Resolves #11411

### CODE REVIEW

**Comment by kingjia90** [comment]
LGTM , but found a behaviour change:
When removing `dotenv`, it turns the `APP_DEBUG` to `false`, while it is usually defaulting to `true` when `APP_ENV` alone is set to `dev` in .env file

image



potentially is this line
https://github.com/symfony/dotenv/blob/1a24cb3ab1dbb8834a75c9d46e427e84baae29bc/Dotenv.php#L154-L155
https://github.com/symfony/symfony/issues/43793 may also help to understand the "automatisms" behind there

**Comment by kingjia90** [comment]
Suggesting to change 
https://github.com/pimcore/pimcore/blob/e0be45b840484dcb2e3e4e82958061ef390573fe/lib/Bootstrap.php#L227
to something like 
```
$debug = (bool) ($_SERVER['APP_DEBUG'] ?? $environment !== 'prod');
```
so that by default when is in prod, debug is `false`, while for test and dev, it is `true`

**Comment by brusch** [comment]
I think we shouldn't have hardcoded envs in the code. 
I'd just leave it as it is (Symfony default) and you just need to set the env variable accordingly when required. WDYT?

**Comment by dvesh3** [comment]
@brusch yes, these vars needs to be set somehow to define the active environment. Should we then get rid off the fallbacks? e.g. 

https://github.com/pimcore/pimcore/blob/579a9b7a435e96027886aa717f77f25fb5ee9e8d/lib/Config.php#L497

https://github.com/pimcore/pimcore/blob/c48250bbbbb354a90d80e63542609bc5233adba8/lib/Bootstrap.php#L227

**Comment by brusch** [comment]
@dvesh3  I'd leave the defaults, but I'd make checks on actual values, like `environment !== 'prod'`.

**Comment by fashxp** [comment]
Update docs for .env ... see https://pimcore.com/docs/pimcore/current/Development_Documentation/Deployment/Configuration_Environments.html#page_Environment-Specific-Configurations

**Pull request merged**
