### PR TITLE
Correct the call to get the correct img thumbnail in image tags in backend/ edit mode

### PR DESCRIPTION
**Pull request by roland4432**
Fixed parameters passed to this.getThumbnailConfig

  
  

## Changes in this pull request  

The function merging parameters to create the img.src is being called with wrong parameters, hence I corrected it

## Additional info  
none - easy fix

### CODE REVIEW

**Comment by weisswurstkanone** [comment]
Could you please rebase it to 6.7 ? Thx!

**Review by jdreesen — APPROVED** [review]
This broke in #6778

**Comment by roland4432** [comment]
Rebased to 6.7

**Comment by jdreesen** [comment]
You need to change the target branch of the PR as well.

**Comment by jdreesen** [comment]
And only keep the original commit (e0f75e9) when rebasing, skipping everything else.

**Comment by roland4432** [comment]
Close this one and opened #7022 since rebasing again would duplicate commits

**Comment by jdreesen** [comment]
No, it wouldn't (if done right). You have to do an interactive rebase, skipping everything not related to the actual fix ;)

**Comment by roland4432** [comment]
> No, it wouldn't (if done right). You have to do an interactive rebase, skipping everything not related to the actual fix ;)

Agreed, but not if the branched is already rebased (which it was). I would need to create a new branch then anways... which I could already base on pimcore/6.7 when checking out...

**Comment by jdreesen** [comment]
> I would need to create a new branch then anways...

No, it's still possible with rebasing the branch (almost anything is possible in git :D). 

Anyways, creating a new branch based on the desired target branch and cherry-picking the commit may be faster/easier in this case. Except that you have to create a new PR on GitHub then...

**Pull request closed without merging**
