### PR TITLE
Bump PhpStan Level to 6: Add missing param/return types

### PR DESCRIPTION
**Pull request by blankse**
Execute PhpStan with level 6 `vendor/bin/phpstan analyse -l 6`

Before:
`[ERROR] Found 7012 errors`
After:
`[ERROR] Found 4820 errors`

Fixed all PhpStan errors:
- Method * has no return type specified
- Method * has parameter * with no type specified

Still open errors of PhpStan level 6:
- Property * type has no value type specified in iterable type array.
- Method * return type has no value type specified in iterable type array.
- Method * has parameter * with no value type specified in iterable type array.

### CODE REVIEW

**Comment by blankse** [comment]
PhpStan error is fixed with https://github.com/pimcore/pimcore/pull/13870

**Comment by blankse** [comment]
I bumped the PhpStan level to 6 with checkGenericClassInNonGenericObjectType/checkMissingIterableValueType = false
So there are no errors left.

**Review by fashxp — CHANGES_REQUESTED** [review]
looks good to me. could you please merge 11.x once more to get rid of the phpstan errors

**Comment by blankse** [comment]
@fashxp Done

**Comment by fashxp** [comment]
@blankse could you please once more merge 11.x and resolve the conflicts, then we can merge

**Comment by blankse** [comment]
@fashxp Done :)

**Comment by fashxp** [comment]
thx very much!

**Review by fashxp — APPROVED** [review]

**Pull request merged**
