### PR TITLE
Require Composer ^2.0

### LINKED ISSUE #7419: Make Composer 2.0 requirement

### PR DESCRIPTION
**Pull request by brusch**
Resolves #7419
See also: 
https://github.com/pimcore/demo/commit/dafcb86a512fad19d8dfd60a510397f31601b5b1
https://github.com/pimcore/skeleton/commit/bf80dd8e96f814ef6b629c265dc518d1fb378339

### CODE REVIEW

**Comment by dpfaffenbauer** [comment]
I don't get the point of this?

**Comment by brusch** [comment]
@dpfaffenbauer same as with PHP 8, it's just to be prepared for the future 😉

**Comment by fashxp** [comment]
and make sure that shipped composer.lock files work properly (because depending on composer versions different dependencies might be loaded) ... but that would be maybe more a topic of the skeletons...

**Comment by NiklasBr** [comment]
That shoudn't be a problem from my understanding:
> - `composer.lock` files are interoperable between versions, so you can upgrade to 2.0 and roll back easily if needed.

**Comment by fashxp** [comment]
not if some dependencies, that are locked in the lock file, require composer 2 ... then you can't install pimcore with composer 1 anymore. 
at least we had that issue already in some constellations.

**Comment by dpfaffenbauer** [comment]
Requirements are the problem here, "ocramius/package-version" in Pimcore's case. You should rather require the root-package causing it, instead of composer v2

**Comment by brusch** [comment]
Well, not much difference, isn't it?

**Pull request closed without merging**
