### PR TITLE
Check the character count on WYSIWYG fields based on the initial content in the field

### LINKED ISSUE #17440: [Bug]: wysiwyg doesn't check character count based on initial content
### Pimcore version

11.3.1

### Steps to reproduce

1. Set max characters on wysiwyg field
2. Exceed that length.
3. Observe fields goes red
4. Save 
5. Reload
6. Observe field does not appear in red
7. Add / delete character in field.
8. Observe fields goes red

### Actual Behavior

Field is not marked red on initial load. required user input

### Expected Behavior

Field should be marked in red on initial load

### PR DESCRIPTION
**Pull request by cancan101**
## Changes in this pull request  
Resolves #17440

### CODE REVIEW

**Comment by mattamon** [comment]
@cancan101 can you please resolve the conflict. Thank you!

**Comment by cancan101** [comment]
Should this PR go against 11.3 vs 11.x? I would say the current behavior might be considered a "bug" .

**Comment by mattamon** [comment]
I would say so yes that it is a bug currently

**Comment by cancan101** [comment]
I updated the base branch and rebased.

**Comment by mattamon** [comment]
> I updated the base branch and rebased.

Perfect! Thank you! I will test it accordingly! Thanks for the quick response!

**Comment by mattamon** [comment]
@cancan101 I tested it and it works like a charm! 
Thank you for your contribution. 

One thing that still bugs me, which has nothing to do with your changes btw, is that you still can save e.g. the object, even though you exceeded the limit. So what is the point of adding a limit, if you can hit save anyways. 
Maybe we should do a follow up, to prevent saving in the first place if you exceed the limit.

WDYT?

**Review by mattamon — APPROVED** [review]
Works like a charm!

**Comment by cancan101** [comment]
>One thing that still bugs me, which has nothing to do with your changes btw, is that you still can save e.g. the object, even though you exceeded the limit. So what is the point of adding a limit, if you can hit save anyways.

We actually consider this a feature rather than a bug. We are using the character count as a warning (soft limit) to our users rather than a hard limit. A few reasons:
1) These fields may be localized in which case the count may be < limit in primary language but exceed count when translated
2) This is rich text field anyway so the concept of characters might not be a strict concept for display reasons
3) There is no hard DB limit here so less of a strict issue

**Comment by mattamon** [comment]
@cancan101 thanks for your explanation! Sounds reasonable to me! Then let's merge this PR :)

**Pull request merged**
