### PR TITLE
Revert native type changes in navigation container

### PR DESCRIPTION
**Pull request by GALPR**
The change was initially part of the commit: https://github.com/pimcore/pimcore/commit/83142b53cfd5a791e3c6167470a66336fd03da22#diff-6d072dd8e428eeff1dff129ad1056e39b8a7fdbf8273fa3aee2436a34d482ad4
See this issue for details: https://github.com/pimcore/pimcore/issues/15970

### CODE REVIEW

**Comment by GALPR** [comment]
[This](https://github.com/pimcore/pimcore/pull/16989) might already be enough to fix the issue.

**Comment by brusch** [comment]
Fixed by #16989

**Comment by brusch** [comment]
@GALPR unfortunately we've a merge conflict here, can you maybe have a look at it? Thanks!

**Comment by fashxp** [comment]
@GALPR can you please sign the CLA?

**Comment by GALPR** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by GALPR** [comment]
recheck

**Comment by brusch** [comment]
Thank you very much 👍

**Pull request merged**
