### PR TITLE
Change mail log / redirect handling to retain the original message data

### PR DESCRIPTION
**Pull request by das-peter**
Currently the mail redirecting in the mail debug mode leads to "information loss" in the email log.
The receivers are not retained and hence the log can't be searched for mails to a certain receiver. 

## Changes in this pull request  
1. `Pimcore\Mail\Plugins\RedirectingPlugin` has been adjusted to put the receiver & sender information in the `originalData` property and restore the information once the mail is sent. It also takes care to inject properties to the message which provide information about the redirection that happened.
2. `Pimcore\Mail::sendWithoutRendering()` has been adjusted to not overwrite receiver information when the mail debug mode is enabled (this should be task of whoever handles the receiver manipulation anyways, right?).

### CODE REVIEW

**Comment by brusch** [comment]
But the email was actually sent to the debug addresses and should be therefore logged as such.

**Comment by das-peter** [comment]
@brusch  fair point. How about switching the approach then and logging the original data as message parameters? That still keeps the log searchable for the original data which is my ultimate goal here.

Background: I've extended the REST service to be able to fetch a sent mail by receiver - allowing me to create automated testing of our password-reset process.

**Comment by brusch** [comment]
@das-peter message parameters sound ok for me, can you create a new PR for that? 
Thanks!

**Comment by das-peter** [comment]
Erm, the branch was already updated to reflect the changes :/ But sure, I can re-branch and create another pull-request

**Comment by brusch** [comment]
Oh, sorry haven't seen that and was not mentioned in the comments 😐 Anyway, thanks for the new PR 😉

**Pull request closed without merging**
