### PR TITLE
[Feature] Application Logger for class definition save actions

### PR DESCRIPTION
**Pull request by NiklasBr**
## Changes in this pull request  
Resolves comment in #6211, at least potentially, by restoring the intention of logging these changes according to [comment](https://github.com/pimcore/pimcore/issues/6211#issuecomment-613462338)

## Additional info  

So, this PR is not complete, it only handles the save() action, nothing else. But I'm throwing it out here to ask if this seem to be a sensible way to move forward?

This stores the new version of the Classs as a file object in the Application Logger, allowing administrators to search through the logger by filtering on the class name and finding the class history there.

An alternative would be to save the JSON version in the file object, which would allow for a quicker path to restore the class definition by re-importing it.

### CODE REVIEW

**Comment by weisswurstkanone** [comment]
Hi @NiklasBr , looks fine for me. Question is if we want to add this to brick and fieldcollection save as well ?

**Comment by NiklasBr** [comment]
@weisswurstkanone I just thought of a second alternative I think might be better. Why not add a new [EventListener](https://github.com/pimcore/pimcore/tree/master/bundles/AdminBundle/EventListener) called something along the lines of `ObjectDefinitionListener` and have it log events on [Classes](https://github.com/pimcore/pimcore/blob/master/lib/Event/DataObjectClassDefinitionEvents.php)?

**Comment by weisswurstkanone** [comment]
yes, it is on the list for milestone 7 :-)
https://github.com/pimcore/pimcore/issues/5965

**Comment by weisswurstkanone** [comment]
@NiklasBr , so what's the outcome regarding bricks and fieldcollections ? Add it in the same fashion?

**Comment by NiklasBr** [comment]
@weisswurstkanone I'll get back to this soon, might not be ready in time for project 83 however.

**Comment by weisswurstkanone** [comment]
Take as much time as needed, this one is not super urgent. Thx @NiklasBr

**Comment by NiklasBr** [comment]
Closing this because I accidentally deleted the branch and the easiest way was to create a new one from scratch

**Pull request closed without merging**
