### PR TITLE
Navigation Container with OPCache creates infinite loop

### LINKED ISSUE #15970: [Bug]: Autoloading issue for navigation container in conjunction with OPCache
### Pimcore version

11.0.8

### Steps to reproduce

- Activate PHP OPCache extension
- Add a call to `new \Pimcore\Navigation\Container()` anywhere
- Reload the page where this call is executed multiple times (so that it is definitely cached by OPCache)
- This issue seems to occur since the following type-hint change: https://github.com/pimcore/pimcore/commit/83142b53cfd5a791e3c6167470a66336fd03da22#diff-6d072dd8e428eeff1dff129ad1056e39b8a7fdbf8273fa3aee2436a34d482ad4
- Removing the type-hints for the `Page` class again resolves this issue

### Actual Behavior

The page does not load anymore. I get the following exception logged in the php.log (formatted for readability):

```
Uncaught PHP Exception Symfony\Component\ErrorHandler\Error\FatalError: 
"Error: During inheritance of Pimcore\Navigation\Container, while autoloading Pimcore\Navigation\Page: Uncaught Error: Class "Pimcore\Navigation\Container" not found in /var/www/html/vendor/pimcore/pimcore/lib/Navigation/Page.php:44 
Stack trace: 
#0 /var/www/html/vendor/symfony/error-handler/DebugClassLoader.php(293): include() 
#1 /var/www/html/vendor/pimcore/pimcore/lib/Navigation/Container.php(42): Symfony\Component\ErrorHandler\DebugClassLoader->loadClass('Pimcore\\Navigat...') 
#2 /var/www/html/vendor/symfony/error-handler/DebugClassLoader.php(293): include('/var/www/html/v...') 
#3 /var/www/html/src/Controller/DefaultController.php(19): Symfony\Component\ErrorHandler\DebugClassLoader->loadClass('Pimcore\\Navigat...') 
#4 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(166): App\Controller\DefaultController->defaultAction(Object(Symfony\Component\HttpFoundation\Request)) 
#5 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) 
#6 /var/www/html/vendor/symfony/http-kernel/Kernel.php(197): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) 
#7 /var/www/html/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php(35): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) 
#8 /var/www/html/vendor/autoload_runtime.php(29): Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner->run() 
#9 /var/www/html/public/index.php(22): require_once('/var/www/html/v...') 
#10 {main}" at /var/www/html/vendor/pimcore/pimcore/lib/Navigation/Container.php line 42 {"exception":"..."} []
```

### Expected Behavior

The page should load as normal

### PR DESCRIPTION
**Pull request by jheimbach**
## Changes in this pull request  
Resolves #15970 

## Additional info

As far as i could debug the issue, the problem lays in the inheritance structure and class loading. 

The DebugClassLoader tries to load `Pimcore\Navigation\Container`, because of: [this](https://github.com/symfony/error-handler/blob/7.0/DebugClassLoader.php#L493-L506) functionaility it loads all returnTypes, which in turn has to load `Pimcore\Navigation\Page` ... which tries to load its parent `\Pimcore\Navigation\Container` ... which is not finished loading yet,  and the cycle continues.

I am not 100% certain that this is what happens... because the Debugger cannot help here either :-D

Nevertheless, when I switch the return type of `getChildren` to `?static` (or `?self`), the issue is no longer present and the class can load every time.

As far as i checked, the change of return type should not effect calls to the method, because we already getting the same Objects back as before.

### CODE REVIEW

**Comment by brusch** [comment]
@jheimbach does it also fix the issue if we just remove the return type? Because it seems PhpStan doesn't like the change. Thanks for a quick feedback.

**Comment by jheimbach** [comment]
@brusch works also without the return type. I could also fix the issue with returntype `?\RecursiveIterator`

**Comment by brusch** [comment]
@jheimbach perferct, that would be nice. Thanks in advance

**Comment by brusch** [comment]
@jheimbach can you please check PhpStan here: 
https://github.com/pimcore/pimcore/actions/runs/9855809642/job/27211475469?pr=16989#step:8:46

Thanks a lot!

**Comment by brusch** [comment]
@jheimbach 🏓 - can you maybe have another look - then we could merge the PR. 
Thanks in advance 🙏

**Comment by brusch** [comment]
See also #17048 
I'd prefer this PR, as it focuses only on the problematic parts. 😊

**Comment by jheimbach** [comment]
@brusch missed the doctype `@param` - should be fine now.

**Comment by brusch** [comment]
Yesss, nice -thanks a lot 👍

**Pull request merged**
