### PR TITLE
DotEnv support BC layer - regression fix for #16652

### LINKED ISSUE #16794: [Bug]: Pimcore 11.2 needs a runtime without requiring one
### Pimcore version

11.2

### Steps to reproduce

Install Pimcore without a runtime, you will get an error on vendor/bin/pimcore-install that no runtime is installed and composer install should be called

### Expected Behavior

Pimcore should either require a runtime, or don't require one at all.

### PR DESCRIPTION
**Pull request by brusch**
Fixes #16794

### CODE REVIEW

**Review by jdreesen — APPROVED** [review]

**Review by blankse — APPROVED** [review]

**Comment by jdreesen** [comment]
I know it has nothing to do with this PR, but if you are planning another short term release regarding the BC break, I would be very happy if this PR could be considered as well (even if it's not strictly a BC break): #16797

**Comment by kingjia90** [comment]
LGTM so far, just found one potential problem that this ` $_SERVER['TRUSTED_PROXIES']` could be changed by `.env` file before but now, if i am not wrong, it's always `NULL` at this point, since the DotEnv parsing stuff is done at `kernel()` after `bootstrap()`
https://github.com/pimcore/pimcore/blob/3b9af529ec41cc6a9723dde96714df67b65d6078/lib/Bootstrap.php#L119-L126

**Comment by brusch** [comment]
Yeah, I've seen this as well. If I'm not wrong, I'd say we could copy the code to the BC function, should still work imho.

**Comment by brusch** [comment]
Just pushed the changes, now everything should be covered 😊

**Comment by kingjia90** [comment]
Merged as it looked just fine after the fix about `TRUSTED_PROXIES` , but later on just had a doubt that suddendly occured, it might affect this part of the constant value assignment as well 🙈 https://github.com/pimcore/pimcore/blob/ffc43e73a7fd0991234d1a780798e37bd152fca5/lib/Bootstrap.php#L169

Update: Opened a PR https://github.com/pimcore/pimcore/pull/16803 that may fix this

**Pull request merged**
