### PR TITLE
Pass and consume correct error messages when declining a workflow transition

### PR DESCRIPTION
**Pull request by roland4432**
## Changes in this pull request  

The controller passes non-translated default error messages to the user trying to commit a transition while using workflows for objects.
These changes get the correct error messages being passed from the event, collects them, passes them to the transitionPanel and translates each item via backend translations

### CODE REVIEW

**Comment by roland4432** [comment]
PHPStan failed, though the given exception is not right. How can I rerun the checks?

**Comment by brusch** [comment]
@roland4432 restarted the job 😊

**Comment by roland4432** [comment]
TY sir..
Do you think that failing check is correct or a false positive?

**Comment by brusch** [comment]
@roland4432 there's definitely an issue with Symfony 3.4
The method `buildTransitionBlockerList()` doesn't exists in 3.4 it seems. 
See: https://travis-ci.com/github/pimcore/pimcore/jobs/371294641#L1086

**Comment by roland4432** [comment]
I've checked the logs and was irritated for a short time, that 5 other jobs running symfony 3.4 passed, but those jobs are doing other things.
I took a look at https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/Workflow/Workflow.php and the assumption was correct, that the method doesn't exist in symfony 3.4.

I still think the feature to pass the correct translated messages is important. Will pimcore 7.0 drop symfony 3.x support so maybe this might come in handy at a later time?

**Comment by brusch** [comment]
@roland4432 yep, let's schedule it for 7 which drops Sf 3.4 support

**Comment by roland4432** [comment]
Shall I take a note or do you have any internal workflow to postpone this PR?

**Comment by brusch** [comment]
I put this PR on the 7  milestone already (see right sidebar 😉)

**Comment by roland4432** [comment]
Wheeeeee... perfect.. thank you

**Comment by brusch** [comment]
@roland4432 can you please rebase/merge your branch onto the current master? 
Thanks a lot!

**Comment by roland4432** [comment]
Merged the current master into my branch @brusch

**Comment by brusch** [comment]
Thanks a lot!

**Pull request merged**
