### PR TITLE
QuantityValue webservice bugfix

### PR DESCRIPTION
**Pull request by markus-moser**
A check is needed whether the unit actually exists otherwise a problem will result if units get deleted as the unit ID might be still in the database.

### CODE REVIEW

**Comment by weisswurstkanone** [comment]
Many thanks, maybe we should also think about a proactive cleanup task as part of the maintenance?

**Comment by markus-moser** [comment]
yes, the cleanup task might be a good idea

**Comment by dpfaffenbauer** [comment]
or just use foreign key constraints?

**Comment by weisswurstkanone** [comment]
technically possible, was considering this but wasn't sure if this really performs ...

**Comment by dpfaffenbauer** [comment]
`SET NULL` definitely will work

https://dev.mysql.com/doc/refman/5.6/en/create-table-foreign-keys.html

**Comment by weisswurstkanone** [comment]
maybe open a seperate "improvement" ticket ?

**Comment by dpfaffenbauer** [comment]
of course, either for the foreign key or the cleanup task. Can you?

**Comment by weisswurstkanone** [comment]
done, see #3376

**Pull request merged**
