### PR TITLE
Support displaying field collections in the grid view

### PR DESCRIPTION
**Pull request by BlackbitDevs**
With this PR content of field collections can be displayed in the grid view.

Before:
Bildschirmfoto 2024-01-10 um 17 18 02

After:
Bildschirmfoto 2024-01-10 um 17 14 57

It also supports displaying localized fields.

Corresponding classic-theme PR: https://github.com/pimcore/admin-ui-classic-bundle/pull/388

### CODE REVIEW

**Comment by BlackbitDevs** [comment]
Added some fine-tuning to not display the field collection class name each time but to group the items by class name (usually in real world it is only one class anyway):
Bildschirmfoto 2024-01-19 um 09 03 12

**Comment by fashxp** [comment]
I like the idea. 

but hmm ... preview of wysiwyg fields and blocks is not ideal: 
image

I'm also wondering why not use `getVersionPreview` directly?

**Comment by fashxp** [comment]
@BlackbitDevs any chance you get time to continue the discussion here?

**Comment by fashxp** [comment]
@BlackbitDevs :ping_pong:

**Comment by BlackbitDevs** [comment]
Sorry @fashxp - I was out of order for some weeks. But have just told today about this PR with the client and have to polish it a bit. Will continue soon.

**Comment by mcop1** [comment]
@BlackbitDevs Any chance you had some time to look at this? Please make sure to tag me once you had the chance to add something to the pr. Thank you!

**Comment by BlackbitDevs** [comment]
@fashxp, @mcop1 

> I'm also wondering why not use getVersionPreview directly?

The reason is that localized fields do not support `getVersionPreview()` currently as this is handled in Twig directly, see https://github.com/pimcore/pimcore/blob/177a8604c06831da6bb5889931342512659fef53/models/DataObject/ClassDefinition/Data/Localizedfields.php#L302-L307

> preview of wysiwyg fields and blocks is not ideal:

Escaping of wysiwyg fields comes from https://github.com/pimcore/pimcore/blob/177a8604c06831da6bb5889931342512659fef53/models/DataObject/ClassDefinition/Data/Extension/Text.php#L47-L50 - so shall I call `htmlspecialchars_decode()` on the result of `getVersionPreview()` to get the renderable HTML?

**Comment by brusch** [comment]
@BlackbitDevs regarding WYSIWYG, plz see https://github.com/pimcore/pimcore/pull/17365

**Comment by BlackbitDevs** [comment]
So I guess the Wysiwyg problem got then solved by #17365 - HTML will get displayed in a clean way.

**Comment by fashxp** [comment]
@BlackbitDevs created an alternative approach here https://github.com/pimcore/pimcore/pull/17510
wasn't happy with the fact that html is generated in `getDataForGrid()` function and also added some minor improvements to make it more robust. 

maybe you can double check the alternative approach.

**Pull request closed without merging**
