### PR TITLE
issue 16039: update versionCount also if versions are disabled

### PR DESCRIPTION
**Pull request by chm0815**
## Changes in this pull request  
Resolves #issue [16039](https://github.com/pimcore/pimcore/issues/16039) 

### HOW
The versionCount will now also be set when version creation is disabled for the the current process.

### CODE REVIEW

**Comment by dvesh3** [comment]
Hi @chm0815 Pimcore 10.6 reached EOL so we don't accept contributions for this version anymore. Please rebase it on branch 11.1 **only** if it is reproducible on latest version v11.1.0 otherwise please close this PR. thanks for your understanding :blush:

**Comment by chm0815** [comment]
Rebased the PR to pimcore 11.1

**Comment by dvesh3** [comment]
the failing test is not related to the changes here.

**Comment by dvesh3** [comment]
@chm0815 thanks!

**Pull request merged**
