### PR TITLE
use .env Kernel if found

### PR DESCRIPTION
**Pull request by dpfaffenbauer**
## Changes in this pull request  
Resolves #

### CODE REVIEW

**Comment by dpfaffenbauer** [comment]
tests fail for some other reason

**Comment by brusch** [comment]
@dpfaffenbauer yep, seems that PhpStan changed something, the reported issues look quite weird.

**Comment by weisswurstkanone** [comment]
@dpfaffenbauer , could you please merge the master again. see https://github.com/pimcore/pimcore/pull/8985

**Comment by brusch** [comment]
Merged it already 😉

**Pull request merged**
