### PR TITLE
Change Objectbrick ClassId to ClassName

### PR DESCRIPTION
**Pull request by dpfaffenbauer**
This PR changes how ObjectBricks save their definition. Currently it looks like this:

```php
<?php 

return Pimcore\Model\Object\Objectbrick\Definition::__set_state(array(
    'classDefinitions' =>
        array(
            0 =>
                array(
                    'classname' => 3, //Here we have the ClassId instead of the ClassName
                    'fieldname' => 'objectBrickField',
                ),
        ),
    'key' => 'ObjectBrickTest',
    'parentClass' => '',
    'layoutDefinitions' => '' //LAYOUT SHOULD BE HERE, BUT HAS BEEN REMOVED FOR READABILITY
));
```

ClassIds are saved within the Database, so they depend to an environment, if we now deploy to a different environment where we have different Ids (which happens a lot), this object brick cant be saved, cause the ID belongs to a different or even non existing class.

The definition should look like this:

```php
<?php 

return Pimcore\Model\Object\Objectbrick\Definition::__set_state(array(
    'classDefinitions' =>
        array(
            0 =>
                array(
                    'classname' => 'AnyClassName', //Now we have the actual name
                    'fieldname' => 'objectBrickField',
                ),
        ),
    'key' => 'ObjectBrickTest',
    'parentClass' => '',
    'layoutDefinitions' => '' //LAYOUT SHOULD BE HERE, BUT HAS BEEN REMOVED FOR READABILITY
));
```

With the actual ClassName, Objectbricks are more easy deployable and detached to an environment.

## Extjs 3
This PR is also backward compatible to Extjs 3.

### CODE REVIEW

**Comment by dpfaffenbauer** [comment]
Whats the state of this PR?

**Comment by brusch** [comment]
We're quite busy with Pimcore 5 at the moment - we'll review & test your PR asap.

**Comment by brusch** [comment]
Thanks for your PR. 
Actually the development of the upcoming major version is already quite well-advanced, so we've decided to do not accept any further features for the v4 branch at the moment (to keep the merging effort as low as possible). We'll publish the first alpha version within the next weeks and of course we'd love to see this PR again based on the new version. 

Thank you very much for your understanding :)

**Comment by dpfaffenbauer** [comment]
:(

fine with me, it's a very small PR anyway ;)

**Pull request closed without merging**
