### PR TITLE
Fix uncaught error "Argument #1 ($id) must be of type int, null given" when userOwner of userModification is null

### PR DESCRIPTION
**Pull request by atul-emico**
When userOwner and userModification are not set that time search by id is throwing error.

php.CRITICAL: Uncaught Error: Pimcore\Model\User\AbstractUser::getById(): Argument #1 ($id) must be of type int, null given, called in {project_root}/var/cache/acceptance/twig/ac/ac4a382cb38374880f7892b33abdbe63.php on line 174 {"exception":"[object] (TypeError(code: 0): Pimcore\\Model\\User\\AbstractUser::getById(): Argument #1 ($id) must be of type int, null given, called in {project_root}/var/cache/acceptance/twig/ac/ac4a382cb38374880f7892b33abdbe63.php on line 174 at {project_root}/vendor/pimcore/pimcore/models/User/AbstractUser.php:41)"} []

File - templates/searchadmin/search/quicksearch/info_table.html.twig
Line number - 52 - 66

 {% set owner = pimcore_user(element.getUserOwner()) %}
      {% if owner is instanceof('\\Pimcore\\Model\\User') %}
          <tr>
              <th>{{ 'owner'|trans([],'admin') }}</th>
              <td>{{ owner.name }}</td>
          </tr>
      {% endif %}

      {% set editor = pimcore_user(element.getUserModification()) %}
      {% if editor is instanceof('\\Pimcore\\Model\\User') %}
          <tr>
              <th>{{ 'usermodification'|trans([],'admin') }}</th>
              <td>{{ editor.name }}</td>
          </tr>
      {% endif %}
        
        
There is no condition set.

### CODE REVIEW

**Comment by blankse** [comment]
I think, we should change the template:
```
{% set userModificationId = element.getUserModification() %}
{% set editor = userModificationId ? pimcore_user(userModificationId) : null %}
```

**Comment by blankse** [comment]
@atul-emico I created a alternative PR https://github.com/pimcore/admin-ui-classic-bundle/pull/262

**Comment by kingjia90** [comment]
Closing in favor of https://github.com/pimcore/admin-ui-classic-bundle/pull/262

Thank you again for reporting and the PRs!

**Comment by atul-emico** [comment]
@blankse 

Thanks for the quick fix. That will be good approach.

**Pull request closed without merging**
