### PR TITLE
[Data objects] For input fields checkValidity should check column length

### PR DESCRIPTION
**Pull request by BlackbitDevs**
Script to reproduce problem:
```php
$input = new \Pimcore\Model\DataObject\ClassDefinition\Data\Input(); // has default column length of 190 characters
$input->checkValidity(str_repeat('a', 500)); // should throw a ValidationException but is treated as valid
```

### CODE REVIEW

**Comment by mcop1** [comment]
Hello @BlackbitDevs,
looks good to me, thank you. But could you please have a look at the failing test? I think it would be enough to reduce the amount of characters for the generated string. 
And maybe it would be possible to add a test for the input validation check?

**Comment by BlackbitDevs** [comment]
@mcop1 Test fixed. And I added a new test for input length check.

**Comment by mcop1** [comment]
> @mcop1 Test fixed. And I added a new test for input length check.

Awesome, thank you 👍

**Comment by hbauer** [comment]
@mcop1 There is one side effect of this new validation, if "input" or "select" attributes are used in a classification store: 
The default columnLength of 190 is now restricting each of these attributes, without the possibility to change it in the backend like it is possible in a class. The validation of the columnLength in "input" or "select" attributes within a classification store makes no sense at all, because the type of the value(s) in the table "object_classificationstore_data_..." is "longtext" and not "varchar".

Until someone provided a solution to fix that, this commit should be reverted.

**Comment by fashxp** [comment]
@hbauer please create a new issue for that and reference that one. thx.

**Pull request merged**
