### PR TITLE
PHP 8.3 Support

### LINKED ISSUE #16350: PHP 8.3 Support
### Improvement description

https://www.php.net/releases/8.3/en.php

### PR DESCRIPTION
**Pull request by brusch**
Resolves #16350

### CODE REVIEW

**Comment by jdreesen** [comment]
Duplicate of #16564?

**Comment by brusch** [comment]
@jdreesen in a way yes, but with less jobs defined by the matrix - so a bit optimized 😉

**Comment by limenet** [comment]
@brusch now that this MR has been merged and Pimcore supports PHP 8.3, can you please create releases for the bundles containing the MRs for PHP 8.3 as well?

Right now using e.g. the `pimcore/personalization-bundle` with PHP 8.3 is not possible since https://github.com/pimcore/personalization-bundle/pull/66 is merged yet not part of a tagged version. However, most bundles are affected by this; either the MR is still open (see also https://github.com/pimcore/customer-data-framework/pull/529#issuecomment-2063542233) or no new tag has been created so far.

Thank you!

**Comment by blankse** [comment]
@limenet There are problems with the imagick php module in PHP 8.3.
See: https://github.com/pimcore/docker/pull/148

So I think you should stay on PHP 8.2 and Pimcore have no hurray to support it everywhere.

**Comment by fashxp** [comment]
> @limenet There are problems with the imagick php module in PHP 8.3. See: [pimcore/docker#148](https://github.com/pimcore/docker/pull/148)
> 
> So I think you should stay on PHP 8.2 and Pimcore have no hurray to support it everywhere.

that's also the reason why that topic hasn't top prio for us right now.

**Pull request merged**
