### PR TITLE
[DataObjects] Relation fields inside Fieldcollections are not saved o…

### LINKED ISSUE #6733: [DataObjects] Relation fields inside Fieldcollections are not saved on update
### Expected behavior
Relation fields inside Fieldcollections should be saved on update
### Actual behavior
Relation fields inside Fieldcollections are not saved on update , **when fieldcollection setter is not called** 
### Steps to reproduce
```php
    $man = Manufacturer::getById(80);
    $fc = $man->getTestfc();

    $item0 = $fc->get(0);
    $item0->setInputtest("test 000"); // working and saved
    $item0->setManytoonetest(News::getById(766)); // updated in dump but not saved
    $item0->setManytomanytest([News::getById(766)]);  // updated in dump but not saved
    dump($item0);

    $item1 = $fc->get(1);
    $item1->setInputtest("test 111"); // working and saved
    $item1->setManytoonetest(News::getById(766));  // updated in dump but not saved
    $item1->setManytomanytest([News::getById(766)]);  // updated in dump but not saved
    dump($item1);

    $man->save();
```
https://talk.pimcore.org/t/saving-field-collections/3680/3

### PR DESCRIPTION
**Pull request by weisswurstkanone**
resolves #6733

### CODE REVIEW

**Comment by dvesh3** [comment]
@weisswurstkanone test fails when trying to flush existing relations on object save https://travis-ci.com/github/pimcore/pimcore/jobs/357307110#L4829

**Comment by macmastermike** [comment]
awesome! THANKS!

**Comment by vaishaliPimcore** [comment]
@dvesh3  @weisswurstkanone 
I am working on Pimcore 6.2.3. I am facing the same issue.
I have applied Patch of mention 6 files but 2 files are not available due to version difference.
models/DataObject/ClassDefinition/Data/Relations/ManyToManyRelationTrait.php
bundles/CoreBundle/Migrations/Version20200703093410.php 

Any suggestions to make it work.
Thanks in advance.

**Comment by dvesh3** [comment]
@vaishaliPimcore Please use official forum https://talk.pimcore.org thanks!

**Pull request merged**
