### PR TITLE
CSV Export: no carriage return every 20 lines

### LINKED ISSUE #6725: CSV Export: no carriage return every 20 lines
# Bug Report
In the generated csv file, a carriage return is missing every 20 lines.

### Expected behavior
A carriage return on each line of the export file.

### Actual behavior
Every 20 lines, the next line is on the same line as the previous one: a carriage return is missing

### Steps to reproduce
From https://demo.pimcore.fun/admin.
1) Click on "alfa romeo" folder
2) Click on CSV Export
3) Click  "OK"
4) Download and open file

### PR DESCRIPTION
**Pull request by weisswurstkanone**
resolves #6725

### CODE REVIEW

**Comment by dvesh3** [comment]
It breaks import
image

**Comment by weisswurstkanone** [comment]
Good point. please re-review

**Comment by ayoob-lfc** [comment]
Hey @weisswurstkanone just wondering was this fix suppose to work for v6.6.10.
I'm still getting the same issue (every 20 lines) for v6.6.10.

**Comment by jdreesen** [comment]
It was merged in `master` so it's getting released with `v6.7`. The associated milestone is wrong and should be fixed.

**Comment by brusch** [comment]
Thanks - fixed it!

**Pull request merged**
