### PR TITLE
Add right autoload path in application testing documentation

### LINKED ISSUE #17004: [Improvement]: Insert right autoload path in Application Testing Documentation
### Description

In the Application Testing section of the Pimcore documentation there is a discrepancy between the _bootstrap.php and the functional.suite.yml code examples.
The autoloader for the first has the following path 
``` 
PIMCORE_PROJECT_ROOT . '/vendor/pimcore/pimcore/tests/Support'
``` 
mapped to:
``` 
'Pimcore\Tests'
``` 

But then in the functional.suite.yml example the Helper is called like this:
``` 
\Pimcore\Tests\Support\Helper\Pimcore:
``` 
Instead of this:
``` 
\Pimcore\Tests\Helper\Pimcore:
``` 

which is a small detail but can save a lot of time and research for copy pasters like myself.

Generally I would prefer to have 'Pimcore\Tests' mapped to PIMCORE_PROJECT_ROOT . '/vendor/pimcore/pimcore/tests instead of PIMCORE_PROJECT_ROOT . '/vendor/pimcore/pimcore/tests/Support'

### Suggestions

I would also like to suggest removing 
``` 
- \Tests\Support\Helper\Functional:
``` 
From the functional.suite.yml code example since it does not exist and is not being generated. 

And I think functional.suite.yml should be renamed to **Functional.suite.yml** as it being generated and mentioned in the Codeception documentation.

### Sources
- Pimcore Application Testing Documentation:
``` 
https://pimcore.com/docs/platform/Pimcore/Development_Tools_and_Details/Testing/Application_Testing
``` 
- Codeception Functional Suite Documentation:
``` 
https://codeception.com/docs/FunctionalTests
``` 

### Screenshots
Bildschirmfoto 2024-04-30 um 11 52 19

Bildschirmfoto 2024-04-30 um 11 51 21

### PR DESCRIPTION
**Pull request by sl0wlydeadly**
Continuation of https://github.com/pimcore/pimcore/pull/17130#issuecomment-2344109378
Resolves https://github.com/pimcore/pimcore/issues/17004

### CODE REVIEW

**Comment by mattamon** [comment]
Hey @sl0wlydeadly my colleague changed it from 11.x to 11.3. You you please rebase your changes to 11.3

Thanks in advance!

**Comment by sl0wlydeadly** [comment]
Somethings not right i think

**Comment by mattamon** [comment]
> Somethings not right i think

Yeah you probably branched of 11.x and @kingjia90 change the branch to 11.3. 
Which is a problem because all the 11.x commits are now in your PR.

Maybe you could close this one and reopen a PR where you branch off 11.3.?

**Comment by sl0wlydeadly** [comment]
alright closing this to open a new one based on 11.3

**Pull request closed without merging**
