### PR TITLE
[Routing] Element Router must implement RouterInterface

### PR DESCRIPTION
**Pull request by dvesh3**
Follow up to #6281
Resolves issues with the data-hub

Screenshot

### CODE REVIEW

**Comment by blankse** [comment]
Maybe the interface should be checked in the GraphQLController? Symfony also allows routers without this interface. Please refer:
https://github.com/symfony-cmf/Routing/blob/master/src/ChainRouter.php#L82-L98

**Comment by brusch** [comment]
@blankse yep, would make sense.
@dvesh3 can you add this check? thanks a lot!

**Comment by brusch** [comment]
Probably this change can then be discarded ...

**Comment by brusch** [comment]
Doesn't make sense to implement interfaces which are actually not needed 😐

**Comment by blankse** [comment]
I looked deeper. The ChainRouter always want the `getRouteCollection` function from its router without checking the Interface. Seems like a bug in Symfony than... Can't be changed in the GraphQLController.

**Comment by dvesh3** [comment]
@blankse @brusch  the check was added to support ChainRouter https://github.com/symfony-cmf/Routing/blob/bee5389c27aa57ba0c0ca9bb09590ba77578ddd5/CHANGELOG.md#changelog

also something to note here: https://github.com/symfony/routing/blob/aa0ed350e84a464f53d429992ecaebd6e0c87c08/RouterInterface.php#L18

**Comment by romainbessugesmeusy** [comment]
The clientname bug in Datahub is still there. Tried 6.6.2 and 6.6.4

**Comment by brusch** [comment]
@romainbessugesmeusy doesn't seem to be reproducible on our public demo ... any more details? 😐

**Comment by romainbessugesmeusy** [comment]
The problem resides in the data-hub repository. It has been fixed on dev-master but hasn't made it to a tag yet. Sorry for bothering here

**Comment by brusch** [comment]
@weisswurstkanone maybe time for a release tag then? 😊

**Comment by weisswurstkanone** [comment]
https://github.com/pimcore/data-hub/releases/tag/v0.6.2

**Pull request merged**
