### PR TITLE
fix for scheduled tasks staying active after execution

### LINKED ISSUE #10318: [Bug]: Scheduled Tasks
### Expected behavior

Can save a schedule task

### Actual behavior

Can not save a schedule task

### Steps to reproduce

1. Open https://demo.pimcore.fun/admin/login/deeplink?object_765_object
2. Save a new draft
3. Go to the Schedule tab and create a new item
4. Save only schedule tasks
5. Reload

### PR DESCRIPTION
**Pull request by dasraab**
this pull request is a combination of commits [1](https://github.com/pimcore/pimcore/commit/962e71bf1a64d9162f610ee4d0fcc94b8df0955a) and [2](https://github.com/pimcore/pimcore/commit/5f9c86682639403f22475bf5dc11758d962ba9fd)

and fixes #10318 for pimcore 4.9.6

### CODE REVIEW

**Comment by brusch** [comment]
Thanks a lot for your PR, however, support for `6.9` has already ended. 😉

**Comment by dasraab** [comment]
> Thanks a lot for your PR, however, support for `6.9` has already ended. 😉

thats too bad. in this case i'll just use my own fork. thank you!

**Comment by betterapp** [comment]
@dasraab did you try this commit as path for pimcore 6.9.6 ?

**Comment by dasraab** [comment]
@betterapp nope not yet. i'm only working with v10 now.

**Comment by betterapp** [comment]
@dasraab but is it working on 6.9 ? Did you test it ?

**Comment by dasraab** [comment]
I can't remember to be honest...

**Pull request closed without merging**
