### PR TITLE
[Docs] Update 00_Docker_Based_Installation.md

### PR DESCRIPTION
**Pull request by hethehe**
Fix docker compose command (should be docker-compose) and add database settings to pimcore-install command

  
  

## Changes in this pull request  
Resolves #

### <samp>🤖 Generated by Copilot at ed1a5cd</samp>

Fix and update the command for installing pimcore with docker-compose in the documentation. Use the correct service name and arguments for the MySQL connection and ensure consistency with the docker-compose syntax.

### <samp>🤖 Generated by Copilot at ed1a5cd</samp>

> _`docker-compose` fix_
> _MySQL args and service_
> _Winter of errors_

### <samp>🤖 Generated by Copilot at ed1a5cd</samp>

* Fix the command for installing pimcore with docker-compose by adding the necessary arguments for the MySQL connection and using the correct service name (`db`) ([link](https://github.com/pimcore/pimcore/pull/15250/files?diff=unified&w=0#diff-46b5bdf332a66cc8a785f041eb629f5e4e39e539fa8e4f0c84586ffcc2c72734L33-R36))

### CODE REVIEW

**Comment by brusch** [comment]
Actually `docker compose`  is right, it's v2 😉

**Comment by hethehe** [comment]
my bad...  😞 
but the database settings to pimcore-install should be added, am I right? 😉

**Comment by brusch** [comment]
@hethehe yep, can you Update your PR accordingly? Thanks!

**Review by fashxp — APPROVED** [review]

**Comment by fashxp** [comment]
thx very much

**Pull request merged**
