### PR TITLE
Solution for dealing with a LazyCommand - Bug #16160

### LINKED ISSUE #16160: [Bug]: Console command "bin/console doctrine:migrations:migrate" fails with the error "The prefix option does not exist."
### Pimcore version

11.1.0

### Steps to reproduce

Actually I can't say who and why this happend. It's deep in the dependency injection somewhere. I'm glad for every hint where I can modify this befaviour.

The problem is that the command is not loaded as a real DoctrineCommand than as a LazyCommand, which will replaced later to the real DoctrineCommand. For this reason in \Pimcore\Console\Application::add the command is not recognized as DoctrineCommand and therefore the prefix option won't add. That causes the error.

### Actual Behavior

If you execute the console command "doctrine:migration:migrate" the command ends with an error:

>  The "prefix" option does not exist.

### Expected Behavior

The command works as expected.

### PR DESCRIPTION
**Pull request by MarkTro**
Resolves the problem that the comand can be a LazyCommand instead of the real DoctrineCommand.

### CODE REVIEW

**Comment by MarkTro** [comment]
It's a little bit confusing in the description of creating a merge request the base branch for bug fixes is "10.5", which is an older version, and in your checklist above is "11.0".

**Comment by kingjia90** [comment]
> It's a little bit confusing in the description of creating a merge request the base branch for bug fixes is "10.5", which is an older version, and in your checklist above is "11.0".

The checklist is outdated, it should be [11.1](https://github.com/pimcore/pimcore/pull/16153), while 10.5 and 10.6 are not supported anymore, they are EOL.

**Comment by MarkTro** [comment]
Ok. So your announcements are more relevant than the mentioning in the system messages. :-)

**Comment by DuckThom** [comment]
Symfony appears to be doing this in the Application

```php
        if ($command instanceof LazyCommand) {
            $command = $command->getCommand();
        }
```

Wouldn't is be a cleaner solution to use something like this as well? For example:

```php
    public function add(Command $command): ?Command
    {
        if ($command instanceof LazyCommand) {
            $command = $command->getCommand();
        }

        if ($command instanceof DoctrineCommand) {
            $definition = $command->getDefinition();

```

I just ran into this error aswell (both on Pimcore 11.0 and 11.1) and adding the instanceof LazyCommand check appears to have solved it for me.

**Comment by MarkTro** [comment]
@DuckThom : That is also a nice solution. The difference is that every LazyCommand which passes will be loaded. I don't know if this have a big impact or not. I guess not, because the Command might be load during the request anyway.

**Comment by kingjia90** [comment]
Tests are likely failing due the branch not being up-to-date
image
Could you please pull and merge `11.1` into it?

**Comment by MarkTro** [comment]
@kingjia90 

> Could you please pull and merge 11.1 into it?

Done.

**Comment by jdreesen** [comment]
@MarkTro you merged `11.x` instead of `11.1`, so it now contains many unrelated commits.

**Comment by kingjia90** [comment]
BTW I've already opened a PR https://github.com/pimcore/pimcore/pull/16257 in replace of this branch

**Comment by dvesh3** [comment]
Closed in favor of #16257. thank you!

**Pull request closed without merging**
