### PR TITLE
Remove duplicate error log

### PR DESCRIPTION
**Pull request by blankse**
## Changes in this pull request  
Resolves https://github.com/orgs/pimcore/discussions/17201

### CODE REVIEW

**Comment by fashxp** [comment]
Thx very much. 
Not sure, if we should that in a minor though, as someone could rely on the php.log? At least we should add an upgrade note, wdyt? 
We plan to release 11.3 tomorrow, so maybe we update this PR after that.

**Comment by blankse** [comment]
@fashxp I added upgrade notes https://github.com/pimcore/pimcore/pull/17209/commits/0a9f1006726b77eb53f8c7a8af09f0fa43043cd5

**Comment by fashxp** [comment]
thx very much! ... but we will need to adapt that after tomorrow once again and move it ti 11.4, I don't want to merge it before release anymore :)

**Comment by blankse** [comment]
@fashxp Ok, I moved the upgrade notes to 11.4.0

**Pull request merged**
