### PR TITLE
Introduce schema-generator

### PR DESCRIPTION
**Pull request by dpfaffenbauer**
Basically https://github.com/pimcore/pimcore/pull/7786 for Pimcore 11.

I just want to discuss this thing again before finishing it. This would allow to decouple class-building and schema-changes completely. Making it far more save executing class changes against the database.

https://github.com/pimcore/pimcore/issues/8256

Partly https://github.com/pimcore/pimcore/issues/8255

This is also far from being done, I just merged the one PR I did years ago again just to showcase how it would work.

### CODE REVIEW

**Comment by dpfaffenbauer** [comment]
@dvesh3 11.1 will not work for this, this is considered a BC break and should be either considered for 11.0 or 12.0

**Comment by dvesh3** [comment]
@brusch we need to discuss if this feasible for v11.

**Comment by dpfaffenbauer** [comment]
@dvesh3 @brusch heavily depends on the timeline. I am not sure if it can be finished within a reasonable timespan

**Comment by fashxp** [comment]
Tbh, I don't have a good feeling for such a last minute change for 11

**Comment by brusch** [comment]
Don't think we can manage this for v11, so needs to be considered for v12 then.

**Comment by brusch** [comment]
Closing this then for now - thanks anyway @dpfaffenbauer for your efforts 👍

**Pull request closed without merging**
