### PR TITLE
[Improvement]:  don't read package info from `composer.lock`

### LINKED ISSUE #12491: [Improvement]: don't read from lock file when loading package info
### Improvement description

Based on https://github.com/pimcore/pimcore/discussions/12441, the consensus seems to be that only these lines should be kept for loading the composer packages information: https://github.com/pimcore/pimcore/blob/a020f961b19ead3899215f8c9188e763e9741536/lib/Composer/PackageInfo.php#L68-L71

Here's the patch I'm currently using:

```diff
Index: vendor/pimcore/pimcore/lib/Composer/PackageInfo.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/vendor/pimcore/pimcore/lib/Composer/PackageInfo.php b/vendor/pimcore/pimcore/lib/Composer/PackageInfo.php
--- a/vendor/pimcore/pimcore/lib/Composer/PackageInfo.php	
+++ b/vendor/pimcore/pimcore/lib/Composer/PackageInfo.php	(date 1655962969883)
@@ -59,24 +59,14 @@
         if (null !== $this->installedPackages) {
             return $this->installedPackages;
         }
-
-        // try to read composer.lock first
-        $json = $this->readComposerFile(PIMCORE_PROJECT_ROOT . '/composer.lock');
-        if ($json && isset($json['packages']) && is_array($json['packages'])) {
-            $this->installedPackages = $json['packages'];
-        }
-
-        if (null === $this->installedPackages) {
-            // try to read vendor/composer/installed.json as fallback
-            $json = $this->readComposerFile(PIMCORE_COMPOSER_PATH . '/composer/installed.json');
-            if ($json && is_array($json)) {
-                $this->installedPackages = $json['packages'] ?? $json;
-            }
+        
+        // try to read vendor/composer/installed.json as fallback
+        $json = $this->readComposerFile(PIMCORE_COMPOSER_PATH . '/composer/installed.json');
+        if ($json && is_array($json)) {
+            $this->installedPackages = $json['packages'] ?? $json;
         }
 
-        if (null === $this->installedPackages) {
-            $this->installedPackages = [];
-        }
+        $this->installedPackages = $this->installedPackages ?? [];
 
         return $this->installedPackages;
     }

```

> I created a new issue, because the discussion started as an issue and was then moved.

### PR DESCRIPTION
**Pull request by jdreesen**
## Changes in this pull request  
Resolves #12491

## Additional info

It should be sufficient to load the package info from `vendor/composer/installed.json` as that file contains information of all *installed* packages.

### CODE REVIEW

**Comment by passioneight** [comment]
@jdreesen thank you! Just tested your PR and can confirm that it's working.

**Comment by dkarlovi** [comment]
@jdreesen this class seems like it can be fully deprecated since Composer provides the same feature now with `\Composer\InstalledVersions`.

**Comment by jdreesen** [comment]
No, `\Composer\InstalledVersions` doesn't provide the same data. It only provides *version* data (from the `vendor/composer/installed.php` file) while this one is able to provide package metadata like the *description*, etc. (from the `vendor/composer/installed.json` file).

**Comment by brusch** [comment]
Thank you very much guys!

**Pull request merged**
