### PR TITLE
Do not run Codeception and static analysis on Markdown files

### PR DESCRIPTION
**Pull request by NiklasBr**
## Changes in this pull request  
Resolves #

## Additional info  

IMO it should not be necessarily to waste computing resources when e.g. docs and other .md files are updated.

### CODE REVIEW

**Comment by brusch** [comment]
Good idea - but probably also relevant for other file types, right? What about CSS, JS, ...?

**Comment by NiklasBr** [comment]
@brusch what if someone moves/renames those files, could have side effects? E.g. [PimcoreEcommerceFrameworkBundle.php](https://github.com/pimcore/pimcore/blob/10.x/bundles/EcommerceFrameworkBundle/PimcoreEcommerceFrameworkBundle.php) and that would be useful to know, right?

**Comment by brusch** [comment]
@NiklasBr Don't think this is getting checked by Codeception at the moment ... so it should be safe to ignore. I'm also wondering whether it would be better to just exclude pathes, like `/docs`, `bundles/AdminBundle/Resources/public`, ... WDYT?

**Comment by NiklasBr** [comment]
Let's try that @brusch

**Comment by dvesh3** [comment]
@NiklasBr what happens with this change when a PR changes both code & docs? tests should run in that case.

**Comment by NiklasBr** [comment]
The docs says it should work:

> When all the path names match patterns in paths-ignore, the workflow will not run. If any path names do not match patterns in paths-ignore, even if some path names match the patterns, the workflow will run.

**Comment by dvesh3** [comment]
> The docs says it should work:
> 
> > When all the path names match patterns in paths-ignore, the workflow will not run. If any path names do not match patterns in paths-ignore, even if some path names match the patterns, the workflow will run.

@NiklasBr 👍 I would also change Documentation Action to run only if there's a change in `docs/` path.

**Comment by NiklasBr** [comment]
@dvesh3 did you see my change?

**Comment by dvesh3** [comment]
> @dvesh3 did you see my change?

LGTM. thanks!

**Review by dvesh3 — APPROVED** [review]

**Comment by dvesh3** [comment]
@NiklasBr thanks!

**Pull request merged**
