### PR TITLE
Convert special chars in username to URL encoded values.

### LINKED ISSUE #5185: Login as user fails if there is special characters in the username.
https://github.com/pimcore/pimcore/blob/27633d378bbbeb10ec84e238575f3a814b72991b/pimcore/modules/admin/controllers/UserController.php#L673

### PR DESCRIPTION
**Pull request by tanaydin**
## Changes in this pull request  
Resolves #5185

## Additional info  
Create a user with & in name of it. Then try login as this user. It will fail.
(I didn't try with pimcore v5 or v6 yet)

### CODE REVIEW

**Comment by kubaplas** [comment]
@tanaydin Maybe it would be better to use user id instead of username?

**Comment by tanaydin** [comment]
> @tanaydin Maybe it would be better to use user id instead of username?

so instead of fixing username, I should get user id and change internal "login as" process of old pimcore?

**Comment by brusch** [comment]
Obsolete due to #5182

**Comment by brusch** [comment]
Oh I haven't seen that this PR was for Pimcore 4, but anyway, Pimcore 4 is end of life. 
Thanks anyway :)

**Comment by tanaydin** [comment]
you welcome, I'll try contribute more :)

**Pull request closed without merging**
