### PR TITLE
[BUGFIX] fixes marshalling of DataObject Link

### LINKED ISSUE #8381: Increased Memory Usage when Saving DataObject with Block in LocalizedFields
# Bug Report

Increased Memory Usage when saving DataObjects which contains Blocks in LocalizedFields

### Expected behavior
The used memory should not differ.

### Actual behavior
After reloading a DataObject (from Cache), changing it and saving it again, then the used memory is increased.

### Steps to reproduce
**(1) Use class export json to create a new Class StorageBug**
[class_StorageBug_export.zip](https://github.com/pimcore/pimcore/files/6109688/class_StorageBug_export.zip)

**(2) Create a new DataObject with one link in Main Block and one link in Additional Block**

image

**(3) Check the memory usage in the table _object_localized_data_storagebug_**

use the following query to check the length of the fields

SELECT LENGTH(mainBlock), LENGTH(additionalBlock) FROM object_localized_data_storagebug;

I got a length of **537** characters for both fields.

image

**(4) Reload the DataObject, change the Link of the Main Block and save it again**

image

**(5) Check the memory usage in the table _object_localized_data_storagebug_ again**

Now I got **538** characters for the first changed field and **17287** characters for the second field (cache).

image

### Assumption

My assumption is that it relates to the PR https://github.com/pimcore/pimcore/pull/6328.

The problem is that the owner will be serialized too, when it comes from cache.

A workaround for me was to comment the following lines of the class 

_pimcore/pimcore/models/DataObject/Data/BlockElement.php_

image

### PR DESCRIPTION
**Pull request by storbahn**
## Changes in this pull request  
Resolves #8381

### CODE REVIEW

**Comment by weisswurstkanone** [comment]
how is this related to #8381 ?

**Comment by weisswurstkanone** [comment]
could you please add a reference to the right issue including steps to reproduce. thx a lot!

**Comment by storbahn** [comment]
In the example I mentioned in the issue I used a Link in a Block in a LocalizedField and when saving it, I could recognize an increased memory usage in the db table. After implementing this Bugfix I could not reproduce it anymore.

It seems that the original problem was the Marshalling of the Link DataObject.

**Comment by weisswurstkanone** [comment]
please be careful here. is it backwards compatible ? I guess in unmarshal we have to take precautions

**Comment by storbahn** [comment]
In my opinion it should be backwards compatible. (therefore I check if $data is an array)

**Comment by weisswurstkanone** [comment]
thanks a lot!

**Pull request merged**
