### PR TITLE
[Data objects] Support nl2br in version note

### PR DESCRIPTION
**Pull request by BlackbitDevs**
Currently when setting a version note via `$object->save['versionNote' => 'my version note'])` it is not possible to have the version note displayed with line breaks or any formatting. In the concrete case, I would like to add some context information about the data source or the changed fields. Without HTML formatting it looks confusing:
Bildschirmfoto 2023-01-24 um 22 02 17

With this PR it is better readable:
Bildschirmfoto 2023-01-24 um 22 04 04

If you say, this is too dangerous when HTML does not get escaped, then perhaps we could at least support [nl2br](https://twig.symfony.com/doc/3.x/filters/nl2br.html)?

### CODE REVIEW

**Comment by fashxp** [comment]
Since version notes can be added by users in the user interface, we need to make sure they are properly escaped. 
So I guess we need to go for the [nl2br](https://twig.symfony.com/doc/3.x/filters/nl2br.html)... 😒

**Comment by fashxp** [comment]
and since it is a feature, please switch to 11.x ... we are not accepting any features for 10.x anymore.

**Comment by BlackbitDevs** [comment]
Adjusted to `nl2br`.

**Comment by lukmzig** [comment]
Thank you @BlackbitDevs for this improvement, looks good.

**Pull request merged**
