### PR TITLE
fix [Pimcore 5] Area Brick names are not shown in toolbar and buttons…

### PR DESCRIPTION
**Pull request by js-aw**
#1837 #1845

### CODE REVIEW

**Comment by brusch** [comment]
Thanks, but the fallback shouldn't be used for admin translations, since they can have completely different locales.

**Comment by fashxp** [comment]
I'll have a look at it today

**Comment by fashxp** [comment]
fixed it in a bit different way ... please have a look and verify

**Comment by js-aw** [comment]
thx!

**Pull request closed without merging**
