### PR TITLE
Make AbstractUser and UserRole class abstract

### LINKED ISSUE #14365: UserRole class should be abstract
### Expected behavior

When calling UserRole::getBynName with a valid role name, it should return the given role

### Actual behavior

When calling UserRole::getBynName with a valid role name, it's always return null.
But if you try to get UserRole by it's ID with UserRole::getById, no problem UserRole is returned.

### Steps to reproduce

* Create a new role in pimcore backend (for example "appAdmin")
* Call UserRole::getByName("appAdmin") and try to dump the return value (for example inside a command)
* Return value is null

### PR DESCRIPTION
**Pull request by blankse**
Resolve https://github.com/pimcore/pimcore/issues/14365

### CODE REVIEW

**Review by mattamon — APPROVED** [review]
LGTM, should we consider a deprecation of some sort for 10.6? 
Maybe an upgrade note will be enough?

Wdyt?

**Comment by blankse** [comment]
@mattamon Maybe we can add the `@abstract` php doc in 10.6 and add there also a upgrade note?

**Comment by blankse** [comment]
@mattamon I created a PR: https://github.com/pimcore/pimcore/pull/14519

**Comment by mattamon** [comment]
Thanks alot @blankse, I will check it asap!

**Review by mattamon — CHANGES_REQUESTED** [review]
@blankse I merged 10.6 into 11.x, can you please resolve the conflicts then this PR is also ready for merge and thank you very much for your help!

**Comment by blankse** [comment]
@mattamon Done :)

**Review by mattamon — APPROVED** [review]
Thank you! I love your motivation, even on Fridays! 
Happy weekend!

**Pull request merged**
