### PR TITLE
Block data-type needs no query column

### LINKED ISSUE #3746: Cannot create object with Block-Datatype
See screenshot. Just tested on the latest demo

image

### PR DESCRIPTION
**Pull request by blankse**
## Changes in this pull request  
Resolves #3746

### CODE REVIEW

**Comment by weisswurstkanone** [comment]
thx!

**Comment by brusch** [comment]
This fix is unfortunately not entirely right, tried to fix it the proper way with 51f47bda2107262a27f158716e00e3f419caa4d9

**Comment by blankse** [comment]
Isn't it a bc break?

**Comment by brusch** [comment]
Well, kind of ... but to be realistic, who does override/call useless functions on data-types?

**Comment by dpfaffenbauer** [comment]
@brusch true, lets wait how my tests react 😜

**Comment by blankse** [comment]
I mean: Every non core data type must implement these traits now. Because the data abstract class don't have these function anymore. Is this not a bc break?

**Comment by brusch** [comment]
@blankse that's true ... maybe not such a good idea.
At least we shouldn't use them in the BC layer to determine whether to call `getDataForQueryResource()` or not :) 

see: https://github.com/pimcore/pimcore/commit/51f47bda2107262a27f158716e00e3f419caa4d9#diff-16f9a3cbf890a5bd4d3ba500c90e2478R255

**Comment by brusch** [comment]
Done in 71729e5a6475c2f229316f8349e16579a3230368

**Comment by blankse** [comment]
@brusch We should set the function direct in the abstract class and trigger a deprecation warning. So the custom data type owner can migrate to the new traits.

**Comment by brusch** [comment]
@blankse done in 0c0fd117d82cddc7585fc2ef755fa94ad0a190d9

**Pull request merged**
