### PR TITLE
[docs] .php template to .twig template

### PR DESCRIPTION
**Pull request by Cruiser13**
## Changes in this pull request  
minor docs update only

### CODE REVIEW

**Comment by kingjia90** [comment]
Thank you for the PR!

Could you please rebase to 10.5?

**Comment by aashan10** [comment]
@Cruiser13 please rebase this to 10.5

**Comment by Cruiser13** [comment]
Base should be 10.5 @aashan10 ?

**Comment by aashan10** [comment]
@Cruiser13 yes, since this is going to the 10.5.x release, you need to have your starting point for pr based on 10.5 branch. 

In this pr, you just changed the target branch to 10.5 when in fact it also should have been your starting point. 

You can rebase your pr from 10.5 and force push the changes.

**Comment by kingjia90** [comment]
> Base should be 10.5 @aashan10 ?

there are extra commits in the PR, the branch needs to be rebased (beside the base on GitHub)

**Pull request closed without merging**
