### PR TITLE
Delete old application_logs_archive tables, even if there are gaps in table names

### PR DESCRIPTION
**Pull request by BlackbitDevs**
Follow-up of #14934 for version 11.

### CODE REVIEW

**Comment by BlackbitDevs** [comment]
@brusch Can you disable the sonarcloud comment - at least if there are no errors? If there is an error, it will appear in the tests list anyway and cause an email to be sent to the PR creator.

**Comment by brusch** [comment]
@herbertroth please see @BlackbitDevs comment above. Thanks for taking over 😊

**Comment by mcop1** [comment]
@BlackbitDevs sorry to bother you again, could you please resolve the conflict? I will merge the pr immediately after that. 

Thank you!

**Comment by BlackbitDevs** [comment]
@mcop1 Conflicts resolved.

**Comment by mcop1** [comment]
Thanks!

**Pull request merged**
