### PR TITLE
[Improvement] Only show area EditableDialogBox dialog when it actually has items to edit

### PR DESCRIPTION
**Pull request by rberneder**
**Situation**
An area is used multiple times throughout different templates.

**Problem**
The area shall offer an EditableDialogBox in the one template, but must not have such in the other one.

**Solution**
The area checks if there are items to be edited. If so, the dialog is output.

### CODE REVIEW

**Comment by blankse** [comment]
@rberneder Should already be fixed. See https://github.com/pimcore/pimcore/pull/10962

Edit: I see it is fixed for areablock and not for area. Maybe we should use the same fix?

**Comment by rberneder** [comment]
You are right @blankse. I have adopted the implementation to the solution in #10962.

**Comment by dvesh3** [comment]
@rberneder please rebase on 10.2 branch. thanks!

**Comment by dvesh3** [comment]
@rberneder Now  we have unrelated commits in the PR. Could you please create a new PR with relevant changes? thanks!

**Comment by dvesh3** [comment]
Fixed directly on 10.2 branch https://github.com/pimcore/pimcore/commit/82dae6902d9a78c48e8de9e4fdbd2ecf0cec7816 thanks!

**Pull request closed without merging**
