### PR TITLE
Fix lowercase table/filename problems

### LINKED ISSUE #10427: [Bug]: CleanupBrickTables maintenance task does not recognize bricks with capitalization in name
### Expected behavior

CleanupBrickTables runs smoothly, without any errors.

### Actual behavior

I've managed to reproduce the problem from #5824.  
Our devops used [this manual](https://github.com/pimcore/pimcore/edit/10.x/doc/Development_Documentation/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/05_DB_Setup.md) and added lower_case_table_names=1 in accordance with it.  
Unfortunately, he did it on the production DB, on Linux and on AWS, so I didn't even have access to mysql system settings and I wasn't aware of the changes.  
My next morning started with shouts of angry users, who were completely unable to work with the website. After some research, I changed the actual table names to lower case (luckily, I had access to mysqldump/mysql on production).  
So I appreciate the decision taken in Mysql 8 to disallow changing this setting if DB directory has already been initialized.  
But now we're getting the error with CleanupBrickTables mentioned in #5824, and I was able to reproduce it on a fresh installation, see the steps to reproduce.

### Steps to reproduce

Use Linux, set lower_case_table_names=1 in Mysql config. Create a new DataObject class, named with a capital letter. This creates tables with lower_case, but actual class files are still created case-sensitive. So CleanupBrickTables gets lower_cased Mysql table name and tries to look up a class with a lower_cased filename on a case-sensitive linux filesystem.
But even if we lower_case the filename of the class, datatype definitions (which are string literals in Pimcore) cannot be lower_cased - and Pimcore on Linux still tries to look them up in case-sensitive mode. It should not be a problem on Windows, though - datatype definitions and filenames can be CamelCased there, but CleanupBrickTables should still be able to get them, because the filesystem is case-insensitive there.

I've made a test using fresh & clean Pimcore installation, the result is shown [here](https://raw.githubusercontent.com/CountZero1981/pimcore/image/Untitled.png)

### PR DESCRIPTION
**Pull request by florian25686**
MySQL 8 stores all tables names in lower case by default. ObjectBricks and fieldcollections are created case-sensitiv on the filesystem. The cleanup task uses names from the database, which are lower cased, and tries to find filenames, which are casesensitive.

  
  

## Changes in this pull request  
Resolves #10427

## Explanation
The cleanup cronjobs for objectbricks and fieldcollections are using the tablenames from the sql-server (mariadb in my case, but works with mysql) to find the matching definition_{files}  on the filesystem.
On most OS the filename is case-sensitive, and with the default settings for mysql8/mariadb the table names are **case-insensitive**.

## Severity
:warning: currently we are not sure if this maybe considered as breaking change

### Requirements
- Use a linux based case-sensitive system
- Use mysql 8 or verify that the setting for `lower_case_table_names` is `1` -> This can be used to show the settings `select @@lower_case_file_system, @@lower_case_table_names;`  
- More information about `lower_case_table_names` in the [Documentation](https://dev.mysql.com/doc/refman/8.0/en/identifier-case-sensitivity.html)

### Steps
- Create a new objectbrick `TestObjectBrick` and add this to dataobject class
- Now a file in `var/classes/objectbricks`-Folder will be created in lowercase
- Run the maintenance cronjob `./bin/console pimcore:maintenance`

### CODE REVIEW

**Comment by florian25686** [comment]
@paulhaem fyi

**Comment by brusch** [comment]
That's quite a dangerous one ... maybe it's just better to require `lower_case_table_names = 0` ... 
and we add this to the requirements check and the documentation 🤔

**Comment by florian25686** [comment]
@brusch I see your point. The problem, in my point of view, is the different requirements/settings that are possible and causing problems.
Quote from the mysql 8 documentation

    You should not set [lower_case_table_names](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_lower_case_table_names) to 0 if you are running MySQL on a system where the data directory resides on a case-insensitive file system (such as on Windows or macOS)
 
The suggested setting `lower_case_table_names = 0` is than required for pimcore but should not be set due to the mysql documentation and I end up with a dilema. And sometimes the developer does not have control over the database-settings nor is able to change this (shared hosting as an example)

There are similar issues/fixes https://github.com/pimcore/pimcore/issues/12101 and https://github.com/pimcore/pimcore/discussions/10973 -> which this does fix.

**Comment by robertSt7** [comment]
@florian25686 We are very sorry, but we won't merge this, because it breaks so much. Anyway thanks for pointing out the problem we will follow it up with this [Issue](https://github.com/pimcore/pimcore/issues/14790)

**Pull request closed without merging**
