### PR TITLE
[DOCS] Update 13_Building_Custom_Rest_APIs.md

### PR DESCRIPTION
**Pull request by pdchaudhary**
doc link: https://pimcore.com/docs/6.x/Development_Documentation/Best_Practice/Building_Custom_Rest_APIs.html
There is two error coming on 1) undefined method name checkPermission 2) undefined method name adminJson
so I changed this way to element these errors by extends 'Pimcore\Bundle\AdminBundle\Controller\Rest\AbstractRestController' and changing routes.

Thank you

  
  

## Changes in this pull request  
Resolves #

### CODE REVIEW

**Comment by weisswurstkanone** [comment]
thx!

**Comment by thgross** [comment]
But why is `Pimcore\Bundle\AdminBundle\Controller\Rest\AbstractRestController` deprecated?

**Comment by brusch** [comment]
@thgross because the entire REST API is deprecated, see #5517

**Comment by thgross** [comment]
I understand. But then the documentation shouldn't encourage using a deprecated API.

**Comment by brusch** [comment]
The note is just missing on this documentation page, on the main page about REST services it's already mentioned. 
See also: https://github.com/pimcore/pimcore/blob/8ec544cafa2956bf8227c732babc657be9ab4fae/doc/Development_Documentation/24_Web_Services/README.md#L3

**Comment by dvesh3** [comment]
@brusch I would say, it should not be suggested to use deprecated API in best practices. How about we change the doc to extend `AdminController` instead of `AbstractRestController`? this will also solve the checkPermission  & adminJson issue.

**Comment by brusch** [comment]
@dvesh3 see 230217855e14b7865f8e7a8a0de269bbb977df16 😉

**Comment by dvesh3** [comment]
@brusch nice! we should also do something about `adminJson` in example.

**Comment by pdchaudhary** [comment]
routes endpoint also needs to change if REST API is deprecated. because using these routes "/webservice/rest/*" , it will use the deprecated api key method for authentication.

**Pull request merged**
