### PR TITLE
Tinymce: Add advlist, charmap, searchreplace, visualblocks plugins

### PR DESCRIPTION
**Pull request by blankse**
Alternative to https://github.com/pimcore/pimcore/pull/16635

Loads the plugins via the npm package, also add the icons in the toolbar.

Additional changes
- Update Tinymce from 6.8.3 to 6.8.4
- Add hr button
- Allow class attribute for img element (classes can be added via image_class_list config)
- Allow hr element
- Cleanup build directory
- Store language files outside of build directory (otherwise they will be removed via cleanup) (Downloaded from here: https://www.tiny.cloud/get-tiny/language-packages/, "TinyMCE 6 All Languages")

Before:
image

After:
image

### CODE REVIEW

**Comment by robertSt7** [comment]
@blankse This looks like an improvement for me. Could you please re-base it to 11.x? Thanks

**Comment by blankse** [comment]
@robertSt7 Done :)

**Comment by robertSt7** [comment]
@blankse  I got the error `Unknown "endblock" tag.` when I try to open a document (News, Events). Could you please take a look at this? Thx

**Comment by blankse** [comment]
@robertSt7 I don't change a twig template. Are you sure this error is related?

**Comment by blankse** [comment]
@robertSt7 I tested it again in the pimcore demo. I have no errors. Please check your setup.

**Comment by robertSt7** [comment]
@blankse Sorry that bug has nothing to do with your PR. I just became aware of it when I have switched to your PR. Thanks a lot for your contribution

**Pull request merged**
