### PR TITLE
[Doc] Nginx does not allow to deliver .webp files

### PR DESCRIPTION
**Pull request by blankse**
Fix https://github.com/pimcore/pimcore/issues/15416

### CODE REVIEW

**Comment by dvesh3** [comment]
@blankse Is it something for 10.6?

**Comment by jdreesen** [comment]
I would say so, yes.

**Comment by blankse** [comment]
@dvesh3 @jdreesen You are right, I have rebased it to `10.6`.

**Comment by dvesh3** [comment]
@blankse thanks!

**Pull request merged**
