### PR TITLE
Fix for Object disabled fields to show tool tip

### LINKED ISSUE #738: Objects: Tooltip on a non-editable field isn't displayed on hover
### Expected behavior

Tooltip should be displayed on a mouseover event
### Actual behavior

For non editable fields the tooltip doesn't appear. 
### Steps to reproduce

Enter a Tooltip-> activate the not editable checkbox ->  do a mouse over in the object on that field
### Version/ Build

Bug seen in:
Version: 4.1.1
Build: 3821

### PR DESCRIPTION
**Pull request by dvesh3**
## Changes in this pull request  
Resolves #738

### CODE REVIEW

**Comment by brusch** [comment]
Thanks!

**Comment by AroraVaishali** [comment]
This solution is not working in Chrome.

**Comment by brusch** [comment]
@dvesh3 can you please check that? Thanks!

**Comment by AroraVaishali** [comment]
It was my bad, It is working fine after clearing browser cache. Thanks.

**Pull request merged**
