### PR TITLE
Bump and fix Phpstan

### PR DESCRIPTION
**Pull request by dvesh3**
## Changes in this pull request  
Resolves #

### CODE REVIEW

**Comment by blankse** [comment]
@dvesh3 We can disable the has() check, see https://github.com/phpstan/phpstan-symfony#constant-hassers
We should change this also for branch 10.5, because there will also be errors when phpstan release the new version. Only the 11.x branch has the dev version test.

**Comment by dvesh3** [comment]
> @dvesh3 We can disable the has() check, see https://github.com/phpstan/phpstan-symfony#constant-hassers We should change this also for branch 10.5, because there will also be errors when phpstan release the new version. Only the 11.x branch has the dev version test.

@blankse thanks for the suggestion. I'm more skeptical about this change due to this line "_Be aware that it may hide genuine errors in your application_." I would really try to fix the errors.

**Comment by blankse** [comment]
Another possibility would be to freeze the version of PhpStan (Version in composer.json without ^). Then it would be the same for the DEV test and can be ignored again.

**Comment by dvesh3** [comment]
@blankse we should get rid off this [line](https://github.com/pimcore/pimcore/pull/14081/commits/cc765c894da42210b4597ccdbed095e9e4c497fc#diff-4c869badd54cd922fd4ff5d901f7fa5b1ea0f2e18526c0e7b025be7b536a8347L5) since we just want to test again Symfony dev version not other dependencies.

**Pull request merged**
