### PR TITLE
Fix: Change the published state, regardless of the previous settings.

### PR DESCRIPTION
**Pull request by patrick-schmid**
## Changes in this pull request  
If you open a document, switch to the "settings" tab and then try to publish or unpublish the document, the new status is not applied.

### Reason:
If you switch to the tab "settings", all settings - including the current published/unpublished status - are transferred to the controller, which overwrites the new desired status.

### Solution:
Set the new status after all other settings are set.

### CODE REVIEW

**Comment by weisswurstkanone** [comment]
@patrick-schmid could you please sign the CLA. Thanks a lot!

**Comment by brusch** [comment]
@patrick-schmid one more thing :) Can you please rebase your PR onto the `6.8` branch, since it's a bug fix? Thanks a lot!

**Comment by brusch** [comment]
@patrick-schmid one more thing :) Can you please rebase your PR onto the `6.8` branch, since it's a bug fix? Thanks a lot!

**Comment by patrick-schmid** [comment]
I think I have now crashed this pull request. I close this and open a new one from the right branch.

**Pull request closed without merging**
