### PR TITLE
Default init function parameter lifetime to 0 and always set it

### LINKED ISSUE #16487: [Bug]: pimcore_cache extension without a lifetime causes exception in template rendering
### Pimcore version

11.1.4

### Steps to reproduce

- Use `pimcore_cache` Twig extension without passing the second argument `$lifetime`
- Render template in browser by navigating to it
- Exception is seen instead of proper rendering `("Cannot assign null to property Pimcore\Twig\Extension\CacheExtension::$lifetime of type int").`

I guess the fix would be to default the second parameter to `0` instead of `null` and not setting it back to `null` inside the `init` function

### Actual Behavior

- The `\Pimcore\Twig\Extension\CacheExtension::init` function defaults `$lifetime` parameter to `null`, then tries setting the property `$lifetime` which causes the exception
- Page cannot be rendered:

> An exception has been thrown during the rendering of a template ("Cannot assign null to property Pimcore\Twig\Extension\CacheExtension::$lifetime of type int").

### Expected Behavior

A cache with the same lifetime as the output cache is written to into cache
- According to the documentation the cache should behave like the output cache:

>  If you define no lifetime the behavior is like the output cache

### PR DESCRIPTION
**Pull request by muratbinerbay**
## Changes in this pull request  
Resolves #16487

### CODE REVIEW

**Comment by blankse** [comment]
@muratbinerbay Target branch should be `11.1` because it is a bug fix.

**Comment by muratbinerbay** [comment]
@blankse thanks fixed it :)

**Comment by blankse** [comment]
@muratbinerbay You need to rebase your branch. There are commits from 11.x in your current branch.

**Comment by muratbinerbay** [comment]
@blankse sorry about that, should be okay now :)

**Comment by blankse** [comment]
@muratbinerbay I think we should allow null for lifetime. I guess a 0 value will deactivate the cache because the lifetime is set to the expiresAfter method of the Symfony CacheItem, which have following comment:
`The period of time from the present after which the item MUST be considered expired. An integer parameter is understood to be the time in seconds until expiration. If null is passed explicitly, a default value MAY be used. If none is set, the value should be stored permanently or for as long as the implementation allows.`

I think we should change the line 38 to:
`protected ?int $lifetime = null;`
And revert this changes

**Comment by muratbinerbay** [comment]
@blankse You're right, I was getting a hit on the cache when I tested the change in our project, but debugged into `AbstractTagAwareAdapter` and it only uses the default lifetime when null is sent as the lifetime value. 

Thanks! I made the change as you suggested

**Comment by fashxp** [comment]
thx very much

**Pull request merged**
