### PR TITLE
Removed migration script from composer.json on post update

### LINKED ISSUE #12514: Composer: do not run migrations automatically on post update
### Improvement description

see: https://github.com/pimcore/skeleton/blob/469496120e95dd7755d7368c3ac168363ede20b0/composer.json#L34

### PR DESCRIPTION
**Pull request by aashan10**
## Changes in this pull request  
Resolves #12514

### CODE REVIEW

**Comment by brusch** [comment]
We should also change the docs accordingly, e.g. here https://pimcore.com/docs/pimcore/current/Development_Documentation/Installation_and_Upgrade/Updating_Pimcore/index.html

**Comment by brusch** [comment]
@aashan10 I think we can also remove `Pimcore\Composer::executeMigrationsUp()` as we don't need it anywhere else ...

**Comment by brusch** [comment]
@aashan10 note: we also need to remove that from skeleton and demos. 
E.g.: https://github.com/pimcore/skeleton/blob/11.x/composer.json#L34

**Comment by aashan10** [comment]
@brusch I'll create the issues in skeleton and demo and remove the `executeMigrationsUp` method as well. Thanks

**Comment by brusch** [comment]
@aashan10 you can straight create a PR as well, shouldn't be too much effort - think it's just a one-liner 😉

**Comment by dvesh3** [comment]
for demo https://github.com/pimcore/demo/pull/341

**Pull request merged**
