### PR TITLE
[ClassificationStorre] Error validating mandatory fields

### PR DESCRIPTION
**Pull request by kjkooistra-youwe**
Error message: Call to a member function getMessage() on array

Caused by a series of events:

- In ClassificationStore::checkValidity() the ValitionException sub items are set with an array of error data instead of nested ValidationExceptions.
- In Concrete::update() the ValidationException is rethrown when inheritance isallowed.
- In AdminExceptionListener::onKernelException() the method recursiveAddValidationExceptionSubItems() is called.
- This in turn causes the error because it expects the sub items to be ValidationException objects and tries to call getMessage() in the foreach loop.

Fixed by changing sub items to ValidationException objects in ClassificationStore::checkValidity()

Pimcore master
To reproduce:
- Data object allows inheritance
- Add a classification store to a data object
- Set a key to mandatory
- Save the data object while the field is still empty

Also see https://github.com/pimcore/pimcore/pull/5120
@weisswurstkanone

### CODE REVIEW

**Comment by weisswurstkanone** [comment]
Mhm, looks a bit weird for localized fields.

image

**Comment by kjkooistra-youwe** [comment]
Ok, so then that's probably what the condition is for. So how can we fix this error?

**Comment by weisswurstkanone** [comment]
well, it seems that the subitems get lost

**Comment by kjkooistra-youwe** [comment]
It does. But if they don't get lost it causes the fatal error with classification store. I guess the classification store validation logic should still be fixed then to use ValidationException objects as sub items.

**Comment by kjkooistra-youwe** [comment]
Changed the code so the fix is applied within the ClassificationStore.

**Comment by weisswurstkanone** [comment]
thx!

**Pull request merged**
