### PR TITLE
[Assets] Add option to download image assets thumbnails as zip

### PR DESCRIPTION
**Pull request by BlackbitDevs**
Currently there is the option in the assets grid view to download selected assets as zip. This PR changes the "download as zip" button to a split button offering to download selected image assets with a certain (downloadable) thumbnail definition.
This PR implements this feature for asset grid view and for asset search.

### CODE REVIEW

**Comment by brusch** [comment]
@BlackbitNeueMedien can you please resolve the conflicts? Thanks a lot!

**Review by dvesh3 — CHANGES_REQUESTED** [review]
@BlackbitNeueMedien thanks for your PR!
This PR changes looks good to me except error on downloadaction, see below:
image


Important: please resolve conflicts by merging master, when  https://github.com/pimcore/pimcore/pull/8562 is done. 😉

**Comment by dvesh3** [comment]
@BlackbitNeueMedien ready for merge https://github.com/pimcore/pimcore/pull/7466#pullrequestreview-619570464 😉

**Comment by brusch** [comment]
@BlackbitNeueMedien can you please resolve the conflicts and also consider the changes made by #8562 ? 
Thanks a lot!

**Comment by dvesh3** [comment]
🏓 @BlackbitNeueMedien

**Comment by brusch** [comment]
@BlackbitNeueMedien 🏓 would be good to have this finished now if it should make it into `10.0`. If you're currently busy, just let us know, then I'll move it to `10.1` milestone. Thanks!

**Comment by BlackbitNeueMedien** [comment]
@brusch Yes, we are too busy currently - and eben worse - not for the customer who we implemented this feature for. So as the switch to Flysystem will need some bigger adjustements here, please plan this for 10.1.

**Comment by brusch** [comment]
@BlackbitNeueMedien alright, thanks a lot for your feedback! I'll change the status to _Draft_ then. 👍

**Comment by brusch** [comment]
Closed - stale PR - please feel free to continue the discussion or create a follow-up PR once this topic get's active again. Thanks!

**Pull request closed without merging**
