### PR TITLE
 Add filter for path column in the dependencies view

### LINKED ISSUE #14690: [Improvement]: Filter the data in dependencies view.
### Improvement description

Hi,

Currently, if you have a lot of dependencies it's very hard to go through all of them and find what you are looking for, so one solution for this is to have a search or filter as it exists in the Notes & Events view for example.
This could be a very important feature for all the users who use the dependencies view often.

Now there is a solution for this and you can filter the data based on their Path.
Follow up [#14671](https://github.com/pimcore/pimcore/pull/14671)

### PR DESCRIPTION
**Pull request by Geni2**
## Changes in this pull request  

I have added the remote filter on the path column in the dependencies view. 
The changes are tested and work as expected, it also makes the filtering when you have multiple pages.

The plugins that is used in Ext JS for the filter make it easy if you want later to add "numeric or date" filter in other columns 
Changes are made as close as possible to the developing style that is used for Pimcore.

## Additional info 
This is an important change for users who use the dependencies view on a daily basis and have multiple pages with Requires and RequiredBy, this filter makes it easier to find the Requires and RequiredBy in the dependencies view. 

filter1 (4)

### CODE REVIEW

**Comment by aryaantony92** [comment]
@Geni2 Could you please resolve the conflicts? Thanks!

**Comment by Geni2** [comment]
@aryaantony92 The conflicts are resolved. Thanks

**Comment by jdreesen** [comment]
@Geni2 I think you need to take another look, it doesn't seem up-to-date with the latest Pimcore yet.

**Comment by Geni2** [comment]
> @Geni2 I think you need to take another look, it doesn't seem up-to-date with the latest Pimcore yet.

@jdreesen thanks for mentioning, actually I'm working to address this issue asap.

**Comment by Geni2** [comment]
Hi everyone, because the AdminBundle was deprecated from here and according to the Pimcore documentation to introduce changes in the UI now you have to push the changes into the `admin-ui-classic-bundle` project. For this reason, I have made the changes of `dependencies.js` and `ElementController.php` files there and I have created a Pull Request: https://github.com/pimcore/admin-ui-classic-bundle/pull/225

**Comment by robertSt7** [comment]
@Geni2 Could you please use type declarations for parameters and return types instead of php docs? Thanks

**Comment by robertSt7** [comment]
@Geni2 Any news on this?

**Comment by robertSt7** [comment]
@Geni2 Thanks for the PR. I will create a follow up for the types

**Pull request merged**
