### PR TITLE
PIMCORE-2770 Add confirmation dialog when adding or removing class fields

### PR DESCRIPTION
**Pull request by jbq**
Also prevent multiple clicks on the Save button while save operation is in progress.

Work done by Alexandre Delattre (BrainsBucket), and sponsored by Jean-Baptiste Quenot (CML-ID)

### CODE REVIEW

**Comment by brusch** [comment]
Nice addition! 
But unfortunately there are some parts missing: 
- translations in en.csv (->translate() should use keys instead of the actual text) 
- localized fields are unsupported (fields within LF are not recognized) 

Thanks!

**Comment by brusch** [comment]
Any updates?

**Comment by jbq** [comment]
Hi, I'll keep you informed when we can provide an update.

>

-- 
Jean-Baptiste Quenot
Tel: +33 (0)972 394 293

**Comment by brusch** [comment]
not compatible with version 4 - closed

**Pull request closed without merging**
