### PR TITLE
PIMCORE4 MultihrefMetdata columnbool

### PR DESCRIPTION
**Pull request by cleggypdc**
This is a slightly different implementation of the boolean field on the multihrefmetadata component.

It forces a whole column of hrefs to be limited to one selection only. Similar to Magento 1's image selection component (that's why i had to implement it)

columnbool

Currently only frontend, it probably needs some backend validation, I'm happy to PR too just let me know.

This is reletively easy to port to Pimcore 5, if you think its a good feature let me know and I will port.

### CODE REVIEW

**Comment by weisswurstkanone** [comment]
Hi, what about the translation for "objectsMetadata_type_columnbool" ?

**Comment by cleggypdc** [comment]
whats the best way to provide the translation, just in the lang file?

**Comment by weisswurstkanone** [comment]
Translations have to be added to the \pimcore\config\texts\en.json file

**Comment by weisswurstkanone** [comment]
Also a PR for pimcore 5 would be nice

**Comment by weisswurstkanone** [comment]
Hi, looks good. Do you have a PR for Pimcore 5 as well ?

**Comment by cleggypdc** [comment]
@weisswurstkanone sorry for the delay! still in my backlog to do ;)

**Comment by weisswurstkanone** [comment]
many thanks!

**Pull request merged**
