### PR TITLE
Remove leftover QR-Code parts

### PR DESCRIPTION
**Pull request by jdreesen**
QR-Codes were removed in #7262 but there was still some code left.

The Document preview panel has a "QR-Codes" button that's now broken because the route doesn't exist anymore, as its controller has been removed.

Note: there's a translation with the key `qr_codes` left, that doesn't seem to be used anywhere. Not sure if it should be deleted, too (and if so, in which translation files - only English or all?)

### CODE REVIEW

**Comment by brusch** [comment]
Thanks a lot for your PR! 
I'd keep this functionalitity, so this was removed by mistake. Maybe we move the action just to the document controller, I guess this would make sense, wdyt? 😊

**Comment by jdreesen** [comment]
I'll update this PR accordingly.

**Comment by jdreesen** [comment]
I restored the deleted controller action into the `Pimcore/Bundle/AdminBundle/Controller/Admin/Document/DocumentController` and removed the unnecessary parts.

As the preview button is currently only in `bundles/AdminBundle/Resources/public/js/pimcore/document/pages/preview.js`, should I move it into the `Bundle/AdminBundle/Controller/Admin/PageController` instead?

**Comment by brusch** [comment]
Yes, then PageController would be nice 😊 Thanks!

**Comment by jdreesen** [comment]
I moved it to the `PageController`.

**Comment by brusch** [comment]
Thanks a lot!

**Pull request merged**
