### PR TITLE
Fix deprecations with jsonSerialize() methods

### PR DESCRIPTION
**Pull request by blankse**
See https://github.com/pimcore/pimcore/pull/11356
Fix all usages of jsonSerialize() method

Additional:
- "return $this" should be return typehint "static"
(Maybe in PHP 8.2 it is possible to use return type $this: https://wiki.php.net/rfc/this_return_type)
- EncryptedField: Add missing LayoutDefinitionEnrichmentInterface

### CODE REVIEW

**Review by xlttj — CHANGES_REQUESTED** [review]
See See https://www.php.net/manual/en/class.jsonserializable.php

Return type shoult be `mixed` to match the interface, not `array` or `self`

**Comment by blankse** [comment]
@xlttj See https://www.php.net/manual/en/language.oop5.variance.php

> In PHP 7.2.0, partial contravariance was introduced by removing type restrictions on parameters in a child method. As of PHP 7.4.0, full covariance and contravariance support was added.
> 
> Covariance allows a child's method to return a more specific type than the return type of its parent's method. Whereas, contravariance allows a parameter type to be less specific in a child method, than that of its parent.

**Comment by xlttj** [comment]
@blankse ack.

**Review by dvesh3 — APPROVED** [review]

**Comment by dvesh3** [comment]
@blankse thanks a lot!

**Pull request merged**
