### PR TITLE
Notes: Missing delete option

### PR DESCRIPTION
**Pull request by blankse**
In the admin interface the notes can't be deleted but in the PHP API is a delete method. I think it should be possible.

### CODE REVIEW

**Comment by brusch** [comment]
Thanks @blankse !
See discussion here: 
https://github.com/pimcore/pimcore/issues/3396

Actually it would be something for `11.x` (not a bug) - but we should discuss the details how it should work first 😊

**Comment by blankse** [comment]
@brusch Thanks for the reply. I'll take a look and report back.

**Comment by aashan10** [comment]
@blankse any updates on this one?

**Comment by blankse** [comment]
@brusch @aashan10 I'm back from vacation. I added the locked attribute. Think this would be a good solution. WDYT?

**Comment by brusch** [comment]
@blankse Thanks, LGTM! 😊

**Comment by aashan10** [comment]
@blankse The changes in this pr work fine, however I have a question. If a note is locked by default, shouldn't there be some option to "unlock" a note?  Or else, there will be no delete option and I don't think this feature will be known to anyone at all.. 

https://github.com/pimcore/pimcore/issues/3396#issuecomment-461086161
The third point in this list is missing.

**Comment by blankse** [comment]
@aashan10 No the third point is not missing. See here:
https://github.com/pimcore/pimcore/blob/1d736e3acdf8c3c9f9c1356bc8485589c891e638/bundles/AdminBundle/src/Controller/Admin/ElementController.php#L324

I think it sould in the first step no possibility in the admin interface exist to unlock it, right @brusch?

**Comment by aashan10** [comment]
In that case, everything else looks good to me! 
Thanks @blankse

**Review by aashan10 — APPROVED** [review]

**Review by dvesh3 — APPROVED** [review]

**Comment by dvesh3** [comment]
@blankse thanks a lot!

**Pull request merged**
