### PR TITLE
Fix division by zero in progress,  increment iPos

### PR DESCRIPTION
**Pull request by andreas-gruenwald**
Improvement for PR #4639

### CODE REVIEW

**Comment by fashxp** [comment]
@andreas-gruenwald is every thing fixed now?

**Comment by NiklasBr** [comment]
@fashxp I think you can also change `$count = count($products->getObjects());` to `$count = $products->getCount();` while you are at it? :)

**Comment by fashxp** [comment]
@andreas-gruenwald finished?

**Comment by fashxp** [comment]
there were some other problems too ... should be fixed now.

**Pull request closed without merging**
