### PR TITLE
Enable Editable Icons for Region Panels in DataObjects

### PR DESCRIPTION
**Pull request by daves-weblab**
## Changes in this pull request  
Icons were already editable for basic panel in data object's edit mode. This PR just enables the same feature for region panels as well.

### CODE REVIEW

**Comment by weisswurstkanone** [comment]
can we add the link to the icon library as well ?

**Comment by weisswurstkanone** [comment]
also see https://github.com/pimcore/pimcore/pull/5273

**Comment by jremmurd** [comment]
I gues this PR is independent of #5273 as it relates to the panel/region icons not on the class definition itself. If we want to add a select to the elements inside the class layout, shouldn't we add it for all layout types which support the icon config and per default add options for the whole icon library?

**Comment by brusch** [comment]
@jremmurd agree! 
@daves-weblab can you please update your PR? Thanks a lot!

**Comment by brusch** [comment]
@daves-weblab ping 😊

**Comment by brusch** [comment]
Closed in favor of #5735

**Pull request closed without merging**
