### PR TITLE
[Test] Fix wrong if expression

### PR DESCRIPTION
**Pull request by blankse**

### CODE REVIEW

**Comment by dvesh3** [comment]
please fix here as well https://github.com/pimcore/pimcore/blame/14a1fd11bc8adfe950136044ce434c7adfc8a86e/.travis/phpstan-bootstrap.php#L22 thanks!

**Comment by blankse** [comment]
@dvesh3 I have fixed it also in `phpstan-bootstrap.php` now

**Comment by dvesh3** [comment]
@blankse thanks! It should go into 6.6 branch since it is a fix 😉

**Comment by blankse** [comment]
@dvesh3 I rebased to 6.6 branch

**Comment by dvesh3** [comment]
thanks a lot! 🙏

**Pull request merged**
