### PR TITLE
Reverts changes from #15200 (FlysystemVisibilityPass not needed anymore)

### LINKED ISSUE #17216: [Bug]: FlysystemVisibilityPass causing problems with other Flysystem adapters
### Pimcore version

11.2.6

### Steps to reproduce

Try using flysystem with a provider with non-S3 storage system adapter (eg. [PlatformCommunity/flysystem-bunnycdn](https://github.com/PlatformCommunity/flysystem-bunnycdn)).
Pimcore will error out with this exception as the FlysystemVisibilityPass class is only checking for fully S3 compatible storages that support arguments at specified places for visibility. Adapters that do not support visibility or have different argument placing will not work when specified.

The problem lies within this code piece here
https://github.com/pimcore/pimcore/blob/76a0f020262381a91f87c742debf1d69e1c84930/bundles/CoreBundle/src/DependencyInjection/Compiler/FlysystemVisibilityPass.php#L37-L42
inside the FlysystemVisibilityPass which checks for arguments at position 1. This will only work for S3 but not for other storage types.

Exception:
```
PHP Fatal error:  Uncaught Error: Call to a member function setArgument() on string in /home/webserver/pimcore-test.local/vendor/pimcore/pimcore/bundles/CoreBundle/src/DependencyInjection/Compiler/FlysystemVisibilityPass.php:41
Stack trace:
#0 /home/webserver/pimcore-test.local/vendor/symfony/dependency-injection/Compiler/Compiler.php(80): Pimcore\Bundle\CoreBundle\DependencyInjection\Compiler\FlysystemVisibilityPass->process()
#1 /home/webserver/pimcore-test.local/vendor/symfony/dependency-injection/ContainerBuilder.php(767): Symfony\Component\DependencyInjection\Compiler\Compiler->compile()
#2 /home/webserver/pimcore-test.local/vendor/symfony/http-kernel/Kernel.php(506): Symfony\Component\DependencyInjection\ContainerBuilder->compile()
#3 /home/webserver/pimcore-test.local/vendor/pimcore/pimcore/lib/Kernel.php(155): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#4 /home/webserver/pimcore-test.local/vendor/symfony/http-kernel/Kernel.php(763): Pimcore\Kernel->initializeContainer()
#5 /home/webserver/pimcore-test.local/vendor/symfony/http-kernel/Kernel.php(126): Symfony\Component\HttpKernel\Kernel->preBoot()
#6 /home/webserver/pimcore-test.local/vendor/pimcore/pimcore/lib/Kernel.php(140): Symfony\Component\HttpKernel\Kernel->boot()
#7 /home/webserver/pimcore-test.local/vendor/pimcore/pimcore/lib/Bootstrap.php(255): Pimcore\Kernel->boot()
#8 /home/webserver/pimcore-test.local/vendor/pimcore/pimcore/lib/Bootstrap.php(64): Pimcore\Bootstrap::kernel()
#9 /home/webserver/pimcore-test.local/bin/console(36): Pimcore\Bootstrap::startupCli()
#10 /home/webserver/pimcore-test.local/vendor/autoload_runtime.php(24): {closure}()
#11 /home/webserver/pimcore-test.local/bin/console(20): require_once('...')
#12 {main}
  thrown in /home/webserver/pimcore-test.local/vendor/pimcore/pimcore/bundles/CoreBundle/src/DependencyInjection/Compiler/FlysystemVisibilityPass.php on line 41
```

### Actual Behavior

Throws an exception when not using fully S3 compatible adapters.

Exception:
```
PHP Fatal error:  Uncaught Error: Call to a member function setArgument() on string in /home/webserver/pimcore-test.local/vendor/pimcore/pimcore/bundles/CoreBundle/src/DependencyInjection/Compiler/FlysystemVisibilityPass.php:41
Stack trace:
#0 /home/webserver/pimcore-test.local/vendor/symfony/dependency-injection/Compiler/Compiler.php(80): Pimcore\Bundle\CoreBundle\DependencyInjection\Compiler\FlysystemVisibilityPass->process()
#1 /home/webserver/pimcore-test.local/vendor/symfony/dependency-injection/ContainerBuilder.php(767): Symfony\Component\DependencyInjection\Compiler\Compiler->compile()
#2 /home/webserver/pimcore-test.local/vendor/symfony/http-kernel/Kernel.php(506): Symfony\Component\DependencyInjection\ContainerBuilder->compile()
#3 /home/webserver/pimcore-test.local/vendor/pimcore/pimcore/lib/Kernel.php(155): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#4 /home/webserver/pimcore-test.local/vendor/symfony/http-kernel/Kernel.php(763): Pimcore\Kernel->initializeContainer()
#5 /home/webserver/pimcore-test.local/vendor/symfony/http-kernel/Kernel.php(126): Symfony\Component\HttpKernel\Kernel->preBoot()
#6 /home/webserver/pimcore-test.local/vendor/pimcore/pimcore/lib/Kernel.php(140): Symfony\Component\HttpKernel\Kernel->boot()
#7 /home/webserver/pimcore-test.local/vendor/pimcore/pimcore/lib/Bootstrap.php(255): Pimcore\Kernel->boot()
#8 /home/webserver/pimcore-test.local/vendor/pimcore/pimcore/lib/Bootstrap.php(64): Pimcore\Bootstrap::kernel()
#9 /home/webserver/pimcore-test.local/bin/console(36): Pimcore\Bootstrap::startupCli()
#10 /home/webserver/pimcore-test.local/vendor/autoload_runtime.php(24): {closure}()
#11 /home/webserver/pimcore-test.local/bin/console(20): require_once('...')
#12 {main}
  thrown in /home/webserver/pimcore-test.local/vendor/pimcore/pimcore/bundles/CoreBundle/src/DependencyInjection/Compiler/FlysystemVisibilityPass.php on line 41
```

### Expected Behavior

Skip FlysystemVisibilityPass completely if provider does not have expected arguments at the position we expect them to be or provider is not an S3 compatible provider.

### PR DESCRIPTION
**Pull request by tomhatzer**
## Changes in this pull request  
Resolves #17216 by reverting #15200 as commented here https://github.com/pimcore/pimcore/pull/15200#issuecomment-1549314112

## Additional info
Please have a look at this comment for further information: https://github.com/pimcore/pimcore/issues/17216#issuecomment-2197143893

### CODE REVIEW

**Comment by tomhatzer** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by brusch** [comment]
@tomhatzer thanks a lot for your PR. 
To avoid issues, we also need to adapt the minimum version of `league/flysystem-bundle` to `^3.3.0` in `composer.json`: 
https://github.com/pimcore/pimcore/blob/3da303cb3adf3be7e9d4948c681c814f95233569/composer.json#L65 

Regarding the failing tests: this seems to be unrelated, but maybe you can rebase to the latest `11.x` as well, I'd assume that fixes that. 

Thanks a lot!

**Comment by tomhatzer** [comment]
Thank you very much @brusch !

I've updated the PR as recommended. Workflows look good again now.

Have a lovely weekend!

**Comment by brusch** [comment]
@tomhatzer nice - thanks a lot! 🙏👍 😊

**Pull request merged**
