### PR TITLE
added CalculatedFieldInterface interface for calculated value field d…

### PR DESCRIPTION
**Pull request by FredoVelcro**
…efinition

  
  

## Changes in this pull request  
Resolves #

### CODE REVIEW

**Comment by dpfaffenbauer** [comment]
IMO: that is not enough. You should also check if the given class implements the interface and raise an deprecation warning if it doesn't implement it. Also: I am not sure, but do calculators support being loaded from the container?

**Comment by brusch** [comment]
@FredoVelcro any updates? thanks :)

**Comment by brusch** [comment]
@FredoVelcro ping

**Comment by FredoVelcro** [comment]
Hello,
Sorry didn't have enought time to do it...

**Comment by brusch** [comment]
Closed due to inactivity.

**Pull request closed without merging**
