### PR TITLE
Fix wrong QuantityValue PHPDocs

### PR DESCRIPTION
**Pull request by blankse**
- getUnitId(), getUnit(), getValue() can return null
- Cunstructor should use string instead of int as unit

### CODE REVIEW

**Comment by brusch** [comment]
@blankse We did some major changes to `OwnerAwareFieldInterface` for v10 recently  (see #7580), which also affects this PR. So I'd  base this PR directly on `master` and consider the changes of #7580. Ok for you? Thanks a lot!

**Comment by blankse** [comment]
@brusch Okay, I rebased to master

**Comment by brusch** [comment]
@blankse thanks a lot!

**Comment by weisswurstkanone** [comment]
thx!

**Pull request merged**
