### PR TITLE
[Static Routes] load controller from service

### LINKED ISSUE #1405: [Static Routes] load controller from service
_From @dpfaffenbauer on April 4, 2017 16:7_

Is it possible to load controllers as service with Static Routes? If no, is there a plan to do it?

_Copied from original issue: pimcore/pimcore-5-issues#94_

### PR DESCRIPTION
**Pull request by dpfaffenbauer**
## Please make sure your PR complies with all of the following points: 
- [x] Read and accept our [contributing guidelines](/CONTRIBUTING.md) before you submit a PR.
- [x] Features need to be proper documented in `doc/`
- [x] Bugfixes need a short guide how to reproduce them. 
- [x] We're not accepting any feature PR's only for **version 4** anymore, you have to provide a feature PR for both versions. 
- [x] Submit bugfixes for version 4 to the target branch `pimcore4`, version 5 is `master` branch.

**Don't submit a PR if it doesn't comply, it'll be closed without a comment!**
  
  
## Fixes Issue #
fixes #1405 

## Changes in this pull request  
Adds possibility to use a controller as a service in Static Routes.

### CODE REVIEW

**Comment by dpfaffenbauer** [comment]
Good Point. Changed the PR according to your idea. If the controller starts with '@', we process the route as service-controller.

**Comment by dpfaffenbauer** [comment]
I also added your idea of adding all available service-controllers to the container as parameter and display them in the dropdown.

**Comment by maff** [comment]
Thanks for the update! As this affects both static and document routes, I enhanced your PR i #1566 to also handle document routes and to look up service controllers by the following criteria to match the possibilities introduced in Symfony 3.3:

* services tagged with `controller.service_arguments`
* services extending `Controller` or `AbstractController`

BTW the demo install profiles now define all controllers as services (updated from the Symfony 3.3 standard edition).

**Comment by dpfaffenbauer** [comment]
Cheers maff :) 🍻

**Pull request merged**
