### PR TITLE
SEO Document Editor - prevent of calling undefined methods

### PR DESCRIPTION
**Pull request by zerlpaMMT**
Prevent Exception of undefined method call -> /admin/document/seopanel-tree -> Call to undefined method .... in class Pimcore\Model\Document\Folder

### CODE REVIEW

**Comment by blankse** [comment]
@zerlpaMMT Can you change the param phpdoc to only Document and can you use "instanceof Page" instead of method_exists?

**Comment by blankse** [comment]
@zerlpaMMT You fixed a ignored phpstan error. You can remove it from the baseline file now:
https://github.com/pimcore/pimcore/blob/b35761e749f42000170b778ef8c127ae2735d266/phpstan-baseline.neon#L8-L12

I think we don't need to set the array keys to an empty string if it isn't a Page. You can simply set the instanceof if around the existing code.

**Review by blankse — APPROVED** [review]
@zerlpaMMT Thanks for the changes :)

**Comment by robertSt7** [comment]
Thank you very much for the PR :)

**Pull request merged**
