### PR TITLE
[Symfony 4] Replace SensioGeneratorBundle #3275

### LINKED ISSUE #3275: [Symfony 4] Replace SensioGeneratorBundle
we are not using **symfony/maker-bundle** at the moment as it does not provide bundle skeleton generate command and also there are no changes in directory structure for backward compatibility.

### PR DESCRIPTION
**Pull request by dvesh3**
## Changes in this pull request  
Resolves #3275

### CODE REVIEW

**Comment by dpfaffenbauer** [comment]
what about https://github.com/symfony/maker-bundle?

**Comment by brusch** [comment]
@dpfaffenbauer doesn't support generating bundles 😉

**Comment by dpfaffenbauer** [comment]
@brusch but you could extend it to support it ;)

**Comment by brusch** [comment]
@dpfaffenbauer this was also our first idea, but the maker-bundle uses the new folder structure, so this approach is less effort. As soon as we switch to the new folder structure it definitely makes sense to use the maker-bundle.

**Comment by dpfaffenbauer** [comment]
ok

**Pull request merged**
