### PR TITLE
add twig extension for pimcore translate helper and update documentation

### PR DESCRIPTION
**Pull request by jms-gsulcer**
## Changes in this pull request  
Resolves #

Add twig extension for the pimcore translate helper and update the documentation for Shared Translations

### CODE REVIEW

**Comment by brusch** [comment]
`{% trans %}Hello %name%{% endtrans %}` is not working?

**Comment by jms-gsulcer** [comment]
No, we have not been able to make that work. Twig expects %name% to be a twig variable, which it isn't, so we get the twig error on the page "Variable %name% does not exist."  We can make it a variable and assign it from controller information, but that seemed extra work.

Also, it seemed simpler for training our template designers to use pimcore_translate since they were already familiar with pimcore 4 helpers and we told them they could generally just add "pimcore_" and it would work, which is mostly true, but wasn't for translate.  This seemed simpler and less verbose to us.

**Comment by brusch** [comment]
How other Twig users are dealing with that, any suggestions? Thanks!

**Comment by dpfaffenbauer** [comment]
```{{ 'blub'|trans }}```

**Comment by dpfaffenbauer** [comment]
that easy ;)

**Comment by jms-gsulcer** [comment]
Wow, thanks, that's simple!  We didn't see it in the documentation anywhere.

**Comment by dpfaffenbauer** [comment]
check twig documentation for useful things as well ;)

**Comment by aarongerig** [comment]
FYI: If you need to add something to admin translation with twig, here's the syntax for it:

```twig
{{ 'blub'|trans({}, 'admin') }}
```

**Pull request closed without merging**
