### PR TITLE
Fix compatibility issue with doctrine/dbal ^2.13.0

### LINKED ISSUE #8610: Pimcore 6.8 is incompatible with doctrine/dbal 2.13.0
# Bug Report
doctrine/dbal published Version 2.13.0 an hour ago. But I get errors.

For example:
`php bin/console pimcore:deployment:classes-rebuild -n -c -d -v`

```
In Doctrine.php line 216:
                                                                                                               
  [Symfony\Component\Debug\Exception\UndefinedMethodException]                                                 
  Attempted to call an undefined method named "execute" of class "Doctrine\DBAL\ForwardCompatibility\Result".  
                                                                                                               

Exception trace:
  at /var/www/html/vendor/pimcore/pimcore/lib/Cache/Pool/Doctrine.php:216
```

### PR DESCRIPTION
**Pull request by brusch**
Alternative approach for #8611
fixes #8610

### CODE REVIEW

**Comment by blankse** [comment]
@brusch The command works. Can you make sure that it is the only execute method? Why are no tests running in the 6.8 branch?

**Comment by brusch** [comment]
@blankse sometimes GitHub is ignoring new PRs, then you have to close/reopen the PR 😊

**Comment by blankse** [comment]
@brusch Good to know. I also closed/reopend my PR :)

**Comment by brusch** [comment]
I think just using `insertOrUpdate()` is the most elegant fix 😊

**Pull request closed without merging**
