### PR TITLE
JavaScript: Remove unused variables

### PR DESCRIPTION
**Pull request by jdreesen**
## Changes in this pull request  
There are various unused variables throughout the JavaScript. This PR tries to get rid of most of them.

### CODE REVIEW

**Comment by dvesh3** [comment]
@jdreesen 🏓 in case you missed review comments 😉

**Comment by jdreesen** [comment]
Thx, I'm busy at the moment. I'll try to address them next week.

**Comment by dvesh3** [comment]
Hey @jdreesen! any progress on this?

**Comment by jdreesen** [comment]
Sorry for the delay, I don't have much spare time at the moment.

I just rebased the branch and addressed your review comments.

**Comment by brusch** [comment]
@jdreesen unfortunately there's a conflict, can you please resolve it? 
Thanks a lot in advance!

**Comment by jdreesen** [comment]
Rebased and resolved.

**Comment by brusch** [comment]
@jdreesen Thanks a lot!

**Comment by jdreesen** [comment]
@dvesh3 
I'm not sure what you did exactly (I think you squashed manually) but by doing this you took the ownership of my commits, which is not very nice :/

**Comment by dvesh3** [comment]
Hey @jdreesen really sorry that happened and it was not my intention. I used Github's UI "squash and merge" option to keep the history clean and this is our default approach for these kind of PRs. 
Also, I tried to find the root cause and it seems, there were some changes at Github's end https://github.com/isaacs/github/issues/1303 and now they have reverted it. In case, if we face the issue again then we'll change our approach.

I totally understand your concern and apologize for the same 🙏. We love our community and really appreciate the contributions ❤️

**Comment by jdreesen** [comment]
Oh well, thx for the investigation! Let's hope GitHub doesn't break this again.

**Pull request merged**
