### PR TITLE
null-safe nullable value of path as third argument of preg_replace

### PR DESCRIPTION
**Pull request by ivannit**
As the return type `?string` of `getPath()` states , `$this->path` can be NULL.

This PR solves the error:
> preg_replace(): Argument #3 ($subject) must be of type array|string, null given

### CODE REVIEW

**Comment by ivannit** [comment]
> I have read the CLA Document and I hereby sign the CLA

I have read the CLA Document and I hereby sign the CLA

recheck

**Comment by ivannit** [comment]
recheck

**Comment by kingjia90** [comment]
Thank you for the PR! 
It should be based on `11.3` instead  of `11.x` as it looks like a potential bug fix.

For the CLA, i believe the comment should only contain the phrase
`I have read the CLA Document and I hereby sign the CLA`
and nothing else (no quoting). Could you please retry? TIA

**Comment by ivannit** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ivannit** [comment]
- replaced by #17487

**Pull request closed without merging**
