### PR TITLE
[CACHE][REDIS] Fix redis cache with LUA not clearing invalidated tags from zc:tags set

### LINKED ISSUE #2009: Redis cache doInvalidateTags() fails to remove tags from zc:tags using LUA
Tag names in the Redis set SET_TAGS (zc:tags) are non-prefixed. But the LUA implementation of doInvalidateTags() gets tag names prefixed ($pTags which is $tags after calling the preprocessTagIds() method). Therefore KEYS in the LUA script are prefixed, and the following command must fail:

https://github.com/pimcore/pimcore/blob/53fe103062833ba3da1cdca9607a5534997651f3/pimcore/lib/Pimcore/Cache/Pool/Redis.php#L494

The non-LUA implementation does it right:
https://github.com/pimcore/pimcore/blob/53fe103062833ba3da1cdca9607a5534997651f3/pimcore/lib/Pimcore/Cache/Pool/Redis.php#L522

### PR DESCRIPTION
**Pull request by maff**
Fixes #2009

### CODE REVIEW

**Comment by maff** [comment]
@gadget60 could you check this change against your setup and verify that it fixes your issue?

**Comment by gadget60** [comment]
@maff  I think you must not reuse the variable name "i" for the inner loop - it is already used by the main loop...

**Comment by gadget60** [comment]
@maff don't know why travis build now fails, looks good to me now!

**Comment by maff** [comment]
Travis build is another issue already fixed on master. Thanks for testing!

**Comment by maff** [comment]
@gadget60 merged and added a test for this scenario.

**Pull request merged**
