### PR TITLE
Grouping role permissions for better overview

### PR DESCRIPTION
**Pull request by PGBrandi**
Added groups for permissions in roles
collapsed elements at initialization

### CODE REVIEW

**Comment by andreas-gruenwald** [comment]
This is how the feature looks like:
image

- same feature for user permissions still pending.

**Comment by brusch** [comment]
Thank you very much for your PR! 
In general I like the idea of grouping the available permissions, but in my opinion we should choose a more generic approach. I'm thinking of an additional column `group` in the `users_permission_definitions` table, which is then used for grouping the permissions. 
What do you think?

**Comment by PGBrandi** [comment]
I already thought about this option, but didn't want to alter anything in the database. So yes, this would be the nicer option. I'll look at it.

**Comment by andreas-gruenwald** [comment]
Has this PR been closed on purpose?
Should we create another PR to continue with this topic, or just adapt the current solution?

**Comment by fashxp** [comment]
lets create a new one as it is a complete different approach. thank you very much!

**Pull request closed without merging**
