### PR TITLE
Target group events

### LINKED ISSUE #5044: Target group events
## Changes in this pull request
I've noticed, that there are no events firing upon creating/modifying/deleting Target groups. 
In my own deveIopment, I'd like to build upon such events, so I'm going to implement the followings: 
- an Event model called TargetGroupEvent, which extends Symfony\Component\EventDispatcher\Event
- an Event class called TargetGroupEvents, which contains POST_ADD, POST_UPDATE and POST_DELETE event constants
- event dispatches in bundles/AdminBundle/Contreoller/Admin/TargetingController with the newly created events above upon Target group creation, modification and deletion
## Additional info

### PR DESCRIPTION
**Pull request by simon-dcode**
## Changes in this pull request  
Resolves #5044

### CODE REVIEW

**Comment by simon-dcode** [comment]
All Travis job fails with 

```
$ mysql --version
0.01s$ mysql -e "SET GLOBAL innodb_file_format=Barracuda;"
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
The command "mysql -e "SET GLOBAL innodb_file_format=Barracuda;"" failed and exited with 1 during .
Your build has been stopped.

```

My code changes have no relation to mysql whatsoever. How am I supposed to fix this?

**Comment by weisswurstkanone** [comment]
Not related to your PR. Just restarted the travis job, let's see :-)

**Comment by simon-dcode** [comment]
Thank you!
Should I close this PR and start a new one then?

**Comment by weisswurstkanone** [comment]
can you amend it to your PR ?

**Comment by simon-dcode** [comment]
I fixed the constructor comment on this branch as well, so it started over.
But something seems off again. Now I see the Travis build failed, but there are no logs there.

**Comment by weisswurstkanone** [comment]
closed in favour of #5053

**Comment by simon-dcode** [comment]
Maybe I misunderstood something, but I'd like to have these changes in 5.8.x as well as in 6.x
Isn't the way for this is to finish both of these PRs?

**Comment by weisswurstkanone** [comment]
sorry, closed by accident.

**Comment by simon-dcode** [comment]
Travis is failing again with the same mysql error as [mentioned above.](https://github.com/pimcore/pimcore/pull/5052#issuecomment-538304416)

**Comment by weisswurstkanone** [comment]
will look at the travis issue later.

**Comment by simon-dcode** [comment]
Thank you!

**Pull request merged**
