### PR TITLE
Deprecate Data::$fieldtype

### PR DESCRIPTION
**Pull request by blankse**
## Changes in this pull request  
This attribute shouldn't be used, because it make problems with extending. See https://github.com/pimcore/ecommerce-framework-bundle/pull/119

### <samp>🤖 Generated by Copilot at 3dfb478</samp>

Replace the deprecated `fieldtype` property of the `Data` class and its subclasses with the `getFieldType()` method. This affects the `getDiffDataForEditMode` method of several classes that extend `Data`, such as `BooleanSelect`, `Date`, `Datetime`, `Password`, and `Select`. This refactoring improves the code quality and consistency.

### <samp>🤖 Generated by Copilot at 3dfb478</samp>

> _Oh we're the coders of the `Data` class_
> _And we're refactoring all our code_
> _We're replacing the `fieldtype` property_
> _With the `getFieldType()` method, yo ho!_

### <samp>🤖 Generated by Copilot at 3dfb478</samp>

*  Deprecate the `fieldtype` property of the `Data` class and recommend using the `getFieldType()` method instead ([link](https://github.com/pimcore/pimcore/pull/15770/files?diff=unified&w=0#diff-b5f1d85f837f86e84cd4a1a905d034c9c71bf3124bf03e6fcbf6de61919b47e7R48-R50))
*  Replace the direct access to the `fieldtype` property with the `getFieldType()` method in the `getDiffDataForEditMode` methods of the `Data` class and its subclasses `BooleanSelect`, `Date`, `Datetime`, `Password`, and `Select` ([link](https://github.com/pimcore/pimcore/pull/15770/files?diff=unified&w=0#diff-b5f1d85f837f86e84cd4a1a905d034c9c71bf3124bf03e6fcbf6de61919b47e7L1103-R1106), [link](https://github.com/pimcore/pimcore/pull/15770/files?diff=unified&w=0#diff-488d3d97be8bace849bb91f5c99a0cb970a187670af9f33aab308be11d26c132L217-R217), [link](https://github.com/pimcore/pimcore/pull/15770/files?diff=unified&w=0#diff-f9e8614c6fe54e4873af1506ee66172b2c8aad0ee906e85e93b07c8905382c53L304-R304), [link](https://github.com/pimcore/pimcore/pull/15770/files?diff=unified&w=0#diff-576184ea3bf05f2cb1af45b7536d8d3ca10bf05775ef3ad1686bb7dab560abe3L304-R304), [link](https://github.com/pimcore/pimcore/pull/15770/files?diff=unified&w=0#diff-dd280011afe4eae89c01d5b7dcb849fb9b5b26509fc1f3569e236179f749a805L337-R337), [link](https://github.com/pimcore/pimcore/pull/15770/files?diff=unified&w=0#diff-c622407049f7baa79f2520f1745ee112b447b41efff4f19ff50b8a7df44bd521L253-R253))

### CODE REVIEW

**Comment by kingjia90** [comment]
Thank you very much!

LGTM, not only fixes that issue with ecommerce framework,but it is also a bug, eg. under 🔧 > `Compare object` and likely was affecting Object Merger bundle too

Before PR:
Untitled

After PR:
image

**Review by kingjia90 — APPROVED** [review]
LGTM and approving. 

I would like to have some second confirmation before merging, since it introduces a deprecation in a bug fix release, but looks more a *leftover* from https://github.com/pimcore/pimcore/pull/13888 that needs a followup of something that is supposed to be already *bc-broken* and therefore no need further deprecation

**Comment by kingjia90** [comment]
UPDATE: https://github.com/pimcore/demo/pull/533#discussion_r1315022222

----- Notes for "historical recostruction" -----
Leaving some note and asking for feedback from @brusch when he is back.

There are some inconsistency for ecommerce framework related files on  https://github.com/pimcore/pimcore/pull/13888/files?w=1#diff-ad7ff8c32f16d4866a157ef0cf6a5025b6ab6b37a595e406cffdd63f596753c4L32-L37.
Either this change is bc-breaking because it's wasn't deprecated nor marked as internal(unlike the others definitions that got the similar changes), 
OR, 
these properties in these class definition of ecommerce framework bundle should have been marked as `internal` like all the others (in model folder), but somehow they were missing it from the beginning.

In the first case, the mentioned lines should be reverted and deprecated first like https://github.com/pimcore/ecommerce-framework-bundle/pull/119, and probably this PR should introduce a BC layer which checks if the property exists.
In the second case, it should have marked internal all the time (but now with `10.6` EOL it could be tricky) and change it all to follow the latest implementations, without the property deprecation in https://github.com/pimcore/ecommerce-framework-bundle/pull/119

The upgrade note in the current PR might need to be `11.0.0` \ `removed` instead of `11.0.8` \ `deprecated`, depending on the outcome.

**Comment by brusch** [comment]
@kingjia90 Due to the fact that `getFieldType()` needs to be implemented by a data-type anyway, because it's defined as  `abstract public function getFieldType(): string;` it should be safe to change, right?

**Pull request merged**
