### PR TITLE
[Bug]: Workflow notification are sent to inactive users

### PR DESCRIPTION
**Pull request by rahul-pim-dev**
Added a new option in workflow notificationSettings to ensure that notifications are also sent to inactive users.

see : https://github.com/pimcore/pimcore/issues/16867

### CODE REVIEW

**Comment by markus-moser** [comment]
@rahul-pim-dev Thanks a lot, could you please sign the CLA?

I would call the current behaviour more like a bug. The workflow engine should not send notifications to inactive users. I would say let's not make this configurable. I would call this more like a "security leak". When someone deactivates a user this user should not get any notifications anymore (and therefore receive potentially internal information). If someone wants to send notifications to users without real access to the Pimcore backend it would be possible to add a user without rights but activate it.

**Comment by markus-moser** [comment]
@rahul-pim-dev  Sorry for the late feedback - missed your commit. It LGTM but could you please sign the CLA?

**Comment by rahul-pim-dev** [comment]
@markus-moser I've signed the CLA. Thanks for letting me know!

**Comment by markus-moser** [comment]
@rahul-pim-dev 

I tested it and found a few problems:

* The email field could be either null or (potentially) an empty string. The empty email check did not work for an empty string.
* Pimcore notifications should be sent to (active) users without email.

Therefore I improved your PR a bit -> now it's fine and I'll merge it. Thanks a lot!

**Pull request merged**
