### PR TITLE
Fix, cleanup & refactor some inherited values setter related code (followup of #14428)

### PR DESCRIPTION
**Pull request by jdreesen**
This is a followup of #14428 which fixes some bugs and cleans up/refactors some code a bit.

Please read the commit messages to find out what was done in particular.

### CODE REVIEW

**Comment by jdreesen** [comment]
Note that this is not only an improvement, but also a bugfix!

**Comment by mcop1** [comment]
Thanks for the follow up 👍

**Comment by jdreesen** [comment]
Just a note:
I wasn't really able to understand what [`DefaultValueTrait::handleDefaultValue()`](https://github.com/pimcore/pimcore/pull/14534/commits/71d2701687193cc5dc552050b854e5824ed4cd09) did, so I refactored it while trying to understand it. I think it's clearer now. If you think this is too much of a change, I can revert the refactoring and just fix the bug.

**Comment by mcop1** [comment]
> Just a note: I wasn't really able to understand what [`DefaultValueTrait::handleDefaultValue()`](https://github.com/pimcore/pimcore/pull/14534/commits/71d2701687193cc5dc552050b854e5824ed4cd09) did, so I refactored it while trying to understand it. I think it's clearer now. If you think this is too much of a change, I can revert the refactoring and just fix the bug.

Thanks for the hint, it was a bit confusing and is more readable now, so I would like to keep it. Tested some combinations with parents and default values, they worked as expected. And the pr is based on the 11.x branch anyway, so we should be fine.

**Comment by mcop1** [comment]
@jdreesen Could you please have a look at the merge conflicts? I would merge the pr right after the conflicts are resolved.

**Comment by jdreesen** [comment]
Fixed.

**Comment by mcop1** [comment]
> Fixed.

Thank you 👍

**Pull request merged**
