### PR TITLE
[Travis] Generate PHPStan baseline job

### PR DESCRIPTION
**Pull request by blankse**

### CODE REVIEW

**Comment by weisswurstkanone** [comment]
related:
#5810 
#5790

**Comment by blankse** [comment]
@weisswurstkanone The output redirection operator (>) don't want to work on travis. Do you know why?

**Comment by blankse** [comment]
The job should create a new baseline file now. But in this job there are no artifact links. Do we still need to activate this?

**Comment by weisswurstkanone** [comment]
No, everything is fine. See

image

Only supported for branches!

So next step would be to try this on a (master) branch.

Does it make sense to add a comment to the baseline file to see if it gets generated properly ?

**Comment by blankse** [comment]
@weisswurstkanone Ah okay, the artifacts are only for master branch 👍 
I would be happy with it. We will see it after some fixes :)

**Comment by weisswurstkanone** [comment]
e.g. https://github.com/pimcore/pimcore/pull/5821 ?

**Comment by blankse** [comment]
Yes #5821 should remove some errors from the baseline file

**Comment by weisswurstkanone** [comment]
Nice :-)

https://s3-eu-west-1.amazonaws.com/pimcoretravisci/pimcore/pimcore/17214/17214.13/phpstan-baseline.neon

**Comment by blankse** [comment]
@weisswurstkanone :clap:

**Pull request merged**
