### PR TITLE
Video getfromcsvimport

### PR DESCRIPTION
**Pull request by ckogler-elements**
Method did not return correct value

### CODE REVIEW

**Comment by dvesh3** [comment]
@ckogler-elements please rebase it to 6.6 branch since it is a fix. thanks!

**Comment by ckogler-elements** [comment]
> @ckogler-elements please rebase it to 6.6 branch since it is a fix. thanks!

Hi, I can't rebase it because it would include all the changes from the master :-(. 
Can you just close this Pull request and add it directly to pimcore?

**Comment by jdreesen** [comment]
You have to do an interactive rebase and skip all but the last commit (7c9680d3e2b463edb265e0c8cacf33018f8eea29).

**Comment by ckogler-elements** [comment]
dont know how to do this - closing the PR

**Comment by brusch** [comment]
Fixed in #6851

**Pull request closed without merging**
