### PR TITLE
[DOC] Cleanup permissions

### PR DESCRIPTION
**Pull request by blankse**
- **Backup**, **Bounce Mail Inbox** doesn't exist anymore
- **Plugins** renamed in **Extensions**
- **Website Translations** renamed in **Translations**

### CODE REVIEW

**Comment by brusch** [comment]
Thanks a lot!

**Comment by brusch** [comment]
Can you please rebase this PR onto master? Thanks again!

**Comment by blankse** [comment]
@brusch I rebased to master

**Comment by brusch** [comment]
Thanks!

**Pull request merged**
