### PR TITLE
[Ecommerce] Only consider rules as applied on items if product actions exist

### PR DESCRIPTION
**Pull request by jremmurd**
Partially fixes https://github.com/pimcore/pimcore/issues/8636

### CODE REVIEW

**Comment by fashxp** [comment]
fine for now, for Pimcore X we should find a more generic solution. see #8647

**Comment by fashxp** [comment]
on second thoughts ... this might break custom rules, that do changes on product prices

**Comment by jremmurd** [comment]
I see your point, it can be problematic, if there are custom actions on products which are not considered in the `hasProductActions()` method of the `Rule` class. 

To me it is still a bug, which even can be easily overlooked, if you do not test your pricing rules containing voucher conditions separatly for product and cart actions well enough.

**Comment by fashxp** [comment]
agree, this is a bug ... but right now I don't see a possibility to fix this bug without introducing other possible problems. 
solution would be #8647 what we will introduce in Pimcore X

**Pull request closed without merging**
