### PR TITLE
Update ObjectBrickContainerClassBuilder.php

### PR DESCRIPTION
**Pull request by j-jonas**
null value is needed for deleting objectbricks

### CODE REVIEW

**Comment by j-jonas** [comment]
Sry, but i can not follow you.

**Comment by mcop1** [comment]
@brusch Can you elaborate a bit, please? 

Additionally we would need a migration that recreates the object bricks, otherwise changes won´t take effect. Maybe something like we did here https://github.com/pimcore/pimcore/blob/a36d11e8b8f9611181ce8ed0d4ec9b7f6826e41d/bundles/CoreBundle/src/Migrations/Version20230508121105.php#L44C1-L48 ?

**Comment by brusch** [comment]
@j-jonas @mcop1 Sorry, I posted the comment on the wrong PR 😉 All fine with this PR - thanks!

**Comment by j-jonas** [comment]
Maybe we have to add an extra migration for saving all object bricks after the update?
Or is there already a task which is running during the update, that saves the bricks?

**Comment by mcop1** [comment]
> Maybe we have to add an extra migration for saving all object bricks after the update? Or is there already a task which is running during the update, that saves the bricks?

@j-jonas No, unfortunately there is no such task. You would have to add a migration to your pr, please. See: https://github.com/pimcore/pimcore/pull/15314#issuecomment-1572033932 .

**Comment by j-jonas** [comment]
I added migration Version20230606112233 for rebuilding the object bricks.

**Pull request merged**
