### PR TITLE
Set PIMCORE_ENVIRONMENT in Console.php

### PR DESCRIPTION
**Pull request by solverat**
when PIMCORE_ENVIRONMENT is defined in the `.htaccess` file, the pimcore exec() commands (started in `pimcore/lib/Pimcore/Tool/Console.php`) will lose the context. pimcore then tries to load the default system.php instead of the system.ENVIRONMENT.php

we checked this PR in a live environment and it's working.

### CODE REVIEW

**Comment by solverat** [comment]
i think this is not just a .htaccess problem. because the PIMCORE_ENVIRONMENT could be defined in the virtual host, the data will then be lost too, as soon pimcore starts in cl mode.

**Comment by solverat** [comment]
@brusch do you use environment settings in the demo page? if so, i'll try to test it there.

**Comment by brusch** [comment]
@solverat no, there we don't use this environment settings.

**Comment by solverat** [comment]
mhm, ok. may u can check that locally? (see steps to reproduce)

**Comment by brusch** [comment]
Hmmm, in my opinion the executing user itself should have the env. variable permanently set, otherwise you would have the same issues when manually running cli tasks (maintenance, ...)-
So this PR would just coat the main problem I think.

**Comment by solverat** [comment]
so what's the idea than? i think, i'm not getting the "executing user itself should have the env. variable permanently set" phrase. :) it's not possible to transport a .htaccess or a virtual host env into the cli mode, but we should/need to keep up the consistency of different environment files. maybe i can extend the PR with the missing stuff? 

btw, the crontab also needs to set the environment manually, like so:

```
*/5 * * * * PIMCORE_ENVIRONMENT=Staging /usr/bin/php /pimcore/cli/console.php maintenance
```
after we found a solution, we should also add this to the documentation.

**Comment by solverat** [comment]
@brusch: ok, i checked that (additional to the crontab command, see above). To run console tasks you simple need to define the PIMCORE_ENVIRONMENT in the command too. 

for example:
```
PIMCORE_ENVIRONMENT=Development php console.php lucenesearch:frontend:crawl crawl
```

i think there is no other way.

i also think this is very urgent because without the right detection of the current environment the integration is useless at the moment: all the background processes won't work!

**Comment by brusch** [comment]
In my opinion adding the env variable to /etc/profile (for system wide change) or to ~/.bash_profile( user) makes much more sense. 

Then you don't have to add the var to each cron job, ... manually and additionally you don't have to care about the environment when running scripts manually on the command line.

**Comment by solverat** [comment]
@brusch mhm, that could be a solution for some hosting scenarios, but i think that's not a recommended way. as an example on our servers we do have a user for each client, but each client does have multiple projects / environments. if we would define the _env vars_ there, it's only possible for **one** project with **one** environment. so the only way would be to create a user for each project and each environment... not the best idea i think?

**Comment by brusch** [comment]
Well, yes, ... if the different environments are on the same server using the same user, this isn't a solution, but shouldn't the different env. more separted? At least running as a different user?

**Comment by solverat** [comment]
@brusch  well... that depends mostly on your company's strategy. but i think it's not the part of pimcore to decide which server configuration should be set. some of them will use different users for each env, some won't, some can't. the point is: pimcore should allow both ways. if users can set their env variables globally they don't need to add the env to the command - all good. but without the integration of my PR, the others won't be able to run pimcore to 100% on a server because the background processes are lost without the env data.

if you don't like the idea of defining the env in the exec command as a fixed integration, we also could dispatch the `$cmd` within a event?

**Comment by solverat** [comment]
@brusch. ok, last try. we just changed the cmd with an event hook and it's working. 

```php
$cmd = "COMMAND_STRING";

$cmdEv = \Pimcore::getEventManager()->trigger("system.exec.cmd", $cmd);
if ($cmdEv->stopped() ) {
   $cmd = $cmdEv->last();
}
```

if you add the attached event in `startup.php`, the cmd can be extended. for example:

```php
\Pimcore::getEventManager()->attach('system.exec.cmd', function(\Zend_EventManager_Event $e) {

    $cmd = $e->getTarget();
    $e->stopPropagation(true);

    return 'PIMCORE_ENVIRONMENT=Development ' . $cmd;

});
```

if you agree i'll update this PR. I found the shell_exec() in 3 files (`Mail.php`, `ResetPasswordCommand.php` and `Console.php`) which would be updated. Of course i'll update the docs too.

**Comment by brusch** [comment]
@solverat sorry for the late answer, we're currently discussing this internally - I'll come back on this as soon as possible. 

Thank you so far for your suggestions & examples!

**Comment by brusch** [comment]
Ok, I we think the first approach is the better one (pass through the env variable) - can you adapt the PR and additionally add also windows support? 

Thanks in advance!

**Comment by solverat** [comment]
hey @brusch. glad to hear, i just pushed the updated commit.

**Comment by brusch** [comment]
Thanks! But Windows support ist still missing - can you add this as well?

**Comment by solverat** [comment]
@brusch, i just added the var to the windows command. i can't test it but i think passing the var as a single parameter is all we have to provide, right?

**Comment by brusch** [comment]
I'm also not able to test it, maybe anyone else?

**Comment by brusch** [comment]
Decided to implement a different approach - see 13205a4583cb46140086b8925a1feb4fe5faf73f 
Feedback appreciated :)

**Comment by solverat** [comment]
hell yea, that looks great! Thanks!

**Pull request closed without merging**
