### PR TITLE
[Objects] Lazy Loading Bugfixes and Improvements

### PR DESCRIPTION
**Pull request by brusch**
- Lazy loaded items shouldn't be serialized (go to cache) ->  regression of #3938 
- Change the way how Pimcore stores the information which lazy loaded fields were already loaded and which not

### CODE REVIEW

**Comment by dpfaffenbauer** [comment]
Any ETA for that? Since this is a huge issue, many have to wait for that in order for Pimcore 5.7.* to work

**Comment by brusch** [comment]
No, but it's the top prio we work on.

**Comment by dpfaffenbauer** [comment]
👍  So sometime next week I guess?

**Comment by brusch** [comment]
Yep, that's definitely our plan (the sooner the better).

**Comment by dpfaffenbauer** [comment]
cool 👍

**Comment by solverat** [comment]
hey @brusch, i could initiate a quick branch test on a current project if you want.

**Comment by brusch** [comment]
@solverat that would be really nice! 👍
We're just doing a lot of testing at the moment, plan would be to release 5.7.2 today in the afternoon.

**Comment by solverat** [comment]
@brusch everything works just fine now! (we explicitly tested lazy many-to-one relations, lazy relations in bricks and object storage in session) 👍

**Pull request merged**
