### PR TITLE
[Improvement]: Being able to filter on "null" values in the dataobject folder grids

### LINKED ISSUE #12809: [Improvement]: Being able to filter on "null" values in the dataobject folder grids
### Improvement description

It is currently not possible to filter on null values in the data object folder grids using the column header. 

For exemple, here (on the demo), I want to filter the cars on the "empty description" condition
image

What would I need to type to return the "null" descriptions only ? space, null, escape characters... None of these work.

One way to achieve this would be to sort ascending on the description field, but it wouldn't give me the number of impacted cars, and I couldn't get an extract of just the cars that don't have description.

As mentioned in this [discussion](https://github.com/pimcore/pimcore/discussions/7882), the only way to do this is to go though the SQL filter option, but it is not available for non-admin users and it is too technical anyway. I feel like there should be a better way to do this.

### PR DESCRIPTION
**Pull request by lukmzig**
## Changes in this pull request  
Resolves #12809

## Additional info  
When no value is passed but filter is checked then try to query null values or empty strings

### CODE REVIEW

**Comment by Corepex** [comment]
@lukmzig, I tested the PR, and everything works as expected. I found one thing we could change. 

If you set a filter, a button "Filter Active!" will be displayed - if you click on that button, it will print out the current grid filter conditions. I think it would be a good idea to add an extra `elseif` case to the condition to catch this new filter ability ...

https://github.com/pimcore/pimcore/blob/64ad7c9c54486d74cb715024b91652301e2206cc/bundles/AdminBundle/public/js/pimcore/element/helpers/gridColumnConfig.js#L242-L247

Currently, the message box (when you click on that button) prints out: `{field} like undefined`

WDYT?

**Comment by lukmzig** [comment]
@Corepex thanks I think that is a good point. I think we should still show the button since the filter is active, however I added different value which will be shown also as a tooltip.

**Comment by SamyMP** [comment]
Hello @lukmzig, thank you for the feature 🙂

I've tried it and it seems it only works for text inputs. So, do you think there is a way to add it to the other filter types as well (Select, Number, Date...) ? It already works for relation type

**Comment by lukmzig** [comment]
Hi @SamyMP, thank you for the comment. I created a follow up issue here: https://github.com/pimcore/pimcore/issues/14666

**Comment by SamyMP** [comment]
Thank you !

**Pull request merged**
