### PR TITLE
Fix issue #11327

### LINKED ISSUE #11327: [Bug]: Display error in admin backend at URLslug attribute with multiple sites
### Expected behavior

Display the URLslug in the right way when using multiple sites:
Bildschirmfoto 2022-02-01 um 14 43 18

### Actual behavior

If the slug of a page is in alphabetical order before the standard site the GUI display works not as expected:
Bildschirmfoto 2022-02-01 um 14 47 59

### Steps to reproduce

- Create at least 2 sites
- Set the slug of one site in alphabetical order before the default slug
- Reload edit tab in admin backend after saving

The reason of this behavior seems to be the order from the controller, more precisely the order from the function return of UrlSlug::getDataForEditmode(...):
Bildschirmfoto 2022-02-01 um 14 53 36
See lines 118 + 122
https://github.com/pimcore/pimcore/blob/e464b003b51a92ebd7abc989883a1d3da34bebeb/models/DataObject/ClassDefinition/Data/UrlSlug.php#L100-L125

### PR DESCRIPTION
**Pull request by woellundwoell**
## Changes in this pull request  
Resolves #11327

I have read the CLA Document and I hereby sign the CLA

### CODE REVIEW

**Comment by woellundwoell** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by brusch** [comment]
@woellundwoell Thanks a lot for your PR, however since this is a bug fix, could you rebase this PR onto the `10.2`? Thanks in advance.

**Comment by woellundwoell** [comment]
@brusch Here you are ;)

**Comment by brusch** [comment]
@woellundwoell you'd need to rebase your branch onto `10.2` as well and then force-push it again (see all the unrelated commits now 😉) If it's easier for you, you can of course also create a new PR based on `10.2`.

**Comment by woellundwoell** [comment]
The latter option was the easier one, so we'll close this PR and focus on https://github.com/pimcore/pimcore/pull/11336 instead.

**Pull request closed without merging**
