### PR TITLE
[Bug] GCS: Asset Upload broken - stream is not a valid resource

### LINKED ISSUE #17227: [Bug]: GCS: Asset Upload broken - stream is not a valid resource
### Pimcore version

11.2.6

### Steps to reproduce

Configure Google Cloud Storage and try to upload assets - it fails. Reason is that after using storage->write, the stream is closed and therefore not a valid resource anymore. 11.2.6 is the first release were this happens cause here https://github.com/pimcore/pimcore/blob/11.x/models/Asset.php#L737 it tries to get a local file to guess the mime-type. $src is not valid anymore here.

### PR DESCRIPTION
**Pull request by mcop1**
## Changes in this pull request  
Resolves #17227 
Follow up to https://github.com/pimcore/pimcore/pull/17148

## Additional info
Reverted the mime type detection from https://github.com/pimcore/pimcore/pull/17148

### CODE REVIEW

**Comment by mcop1** [comment]
@BlackbitDevs was there a specific reason to change the mime type detection? 
@albertmueller & @dpfaffenbauer Sorry, for the inconvience that may has caused, I reverted the part with the mime type, but kept the changes to the return types. Can you have a look, please?

**Comment by albertmueller** [comment]
@mcop1 thx for the revert, it solves the issue. before you merge, please have a look at the sonarcube issue

**Comment by mcop1** [comment]
> @mcop1 thx for the revert, it solves the issue. before you merge, please have a look at the sonarcube issue

It is a code style issue, I fixed it. Should be fixed by cs fixer anyways, but apparently it doesnt run for prs in the core.

**Comment by blankse** [comment]
@mcop1 When https://github.com/pimcore/pimcore/pull/17000 is merged it does :)

**Comment by dpfaffenbauer** [comment]
@mcop1 fix works, thanks

**Comment by BlackbitDevs** [comment]
Reason for changing MIME type detection to `symfony/mime` was #17005 
Simply reverting #17005 does not make sense. Instead we should check if file is remote.

**Comment by BlackbitDevs** [comment]
@dpfaffenbauer Can you please check what happens if you update an asset ("upload new version")? Because this also uses `symfony/mime` in https://github.com/pimcore/admin-ui-classic-bundle/blob/5536216395824be91fda28884c911555de6bf28a/src/Controller/Admin/Asset/AssetController.php#L573-L574
Ah but there it checks on the just uploaded (local) temporary file, so this should work...

But I do not understand why remote files are a problem because https://github.com/pimcore/pimcore/pull/17005/files#diff-867a334e4cc9a097b215afcb2b1f4949910cb2f2103a2cd997d8699d4d414fc9R730 uses
> $mimeType = MimeTypes::getDefault()->guessMimeType($this->getLocalFileFromStream($src));

`$this->getLocalFileFromStream($src)` should return a local file which `symfony/mime` should be able to handle, right?

**Comment by BlackbitDevs** [comment]
I just see that in #17148 I have accidentically included also the changes from #17005. Actually after @brusch's comment in https://github.com/pimcore/pimcore/pull/17005#issuecomment-2109603779 those changes should only be added to `11.x`

So what is to be done now? In 11.2 @mcop1 has already reverted the changes. But in 11.x they are still available: 
https://github.com/pimcore/pimcore/blob/8838b8c37b6c0f0eb88c773978c4aa5e2c333916/models/Asset.php#L737-L743

I cannot see why this does not work with Google cloud storage because `$this->getLocalFileFromStream($src)` should return a local file path.

**Comment by brusch** [comment]
Just merged this fix into `11.x` - so we're no consistent again. 
Now we can check how we can fix the original issue #17005 without breaking anything 😊

**Pull request merged**
