### PR TITLE
feature: custom color_admin_interface_background

### PR DESCRIPTION
**Pull request by daniele-sarnari**
## Changes in this pull request  
In system settings, Appearance & Branding, adds the possibility to put a custom admin background color on image. 
image
image

### CODE REVIEW

**Comment by brusch** [comment]
@DrewLiberty Thanks a lot for your PR! However there's one thing, could you please remove all translations except the `en` one? All the other texts are managed by POEditor here: https://poeditor.com/join/project/XliCYYgILb so no need to include it in the PR 😉

Thanks in advance!

**Comment by daniele-sarnari** [comment]
> @DrewLiberty Thanks a lot for your PR! However there's one thing, could you please remove all translations except the `en` one? All the other texts are managed by POEditor here: https://poeditor.com/join/project/XliCYYgILb so no need to include it in the PR 😉
> 
> Thanks in advance!

Done, thanks to you :)

**Comment by brusch** [comment]
LGTM, thanks! Just one more thing, please sign the CLA, so that we can merge the PR.

**Comment by daniele-sarnari** [comment]
> LGTM, thanks! Just one more thing, please sign the CLA, so that we can merge the PR.

I think the process is broken, already signed it around 4/5 times today :rofl:
image
image

**Comment by brusch** [comment]
Please check if your commit `email` address matches one of your email addresses in your profile: 
https://docs.github.com/en/pull-requests/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

You can check the email address used for the commits in the patch file: 
https://patch-diff.githubusercontent.com/raw/pimcore/pimcore/pull/10752.patch
It's in line 2. 

Please add this address to your profile an check again 😉 Thanks!

**Comment by brusch** [comment]
@DrewLiberty perfect, lgtm now - thanks a lot! 👍

**Pull request merged**
