### PR TITLE
Delete old application_logs_archive tables, even if there are gaps in table names

### PR DESCRIPTION
**Pull request by BlackbitDevs**
With current implementation in https://github.com/pimcore/pimcore/blob/7821f65a897349e64223cc02b9c3e04d740ad9f7/lib/Maintenance/Tasks/LogArchiveTask.php#L118-L148
the `application_logs_archive_*` tables get deleted one after another - but only if there are no gaps in the table names.

For example if (for whatever reason) the following tables exist:
- `application_logs_archive_01_21`
- `application_logs_archive_06_22`
- `application_logs_archive_07_22`
- `application_logs_archive_09_22`
- `application_logs_archive_10_22`

Then the cleanup will calculate `$deleteArchiveLogDate = NOW() - 6 months = 10/22`. It will delete this table and then go 1 month back to 09_22. This does the same. But then for 08_22, there is no table and thus the tables older than `09_22` will stay forever. This is especially a problem because those archive tables only get created if there are application logs for a given month. If there are non, such gaps will get produced.

With this PR all `application_logs_archive_*` tables get fetched and then get checked if their date is older than 6 months. If yes, the table gets deleted. This way gaps are no problem.

### CODE REVIEW

**Comment by NiklasBr** [comment]
Might need a follow-up PR to 11.x with support for the change in #13104?

**Comment by BlackbitDevs** [comment]
@NiklasBr Ah yes, you are right. Will provide follow-up for 11.x as soon as this one has been reviewed.

**Comment by mcop1** [comment]
Hello @BlackbitDevs ,
thank your for the pr, looks good. Just one small question, to be 100% sure, instead of `application_logs_archive_01/21` you meant something like `application_logs_archive_01_2021`, right? 
And could you please create the follow up pr you mentioned?

**Comment by BlackbitDevs** [comment]
@mcop1 You are right, I meant application_logs_archive_01_2021 (with underscore as date year separator). Code was correct only PR description was wrong. Have fixed it. Will create follow-up PR for 11.0 now...

**Pull request merged**
