### PR TITLE
Deprecation fix for Data

### PR DESCRIPTION
**Pull request by dpfaffenbauer**

### CODE REVIEW

**Comment by dpfaffenbauer** [comment]
@brusch @aryaantony92 any ETA on this?

**Comment by blankse** [comment]
Maybe we should return always a string in the getTitle() method? Whats the advantage to have it nullable?

**Comment by brusch** [comment]
@dpfaffenbauer I agree with @blankse : I also don't see a reason for having the title nullable.

**Comment by brusch** [comment]
Btw. we should base this on `10.3` ☺️

**Comment by dpfaffenbauer** [comment]
@brusch done

**Comment by brusch** [comment]
Thanks a lot! 👍

**Pull request merged**
