### PR TITLE
Gridconfig restructuring

### PR DESCRIPTION
**Pull request by weisswurstkanone**

### CODE REVIEW

**Comment by dpfaffenbauer** [comment]
maybe you could also consider this right away? https://github.com/pimcore/pimcore/issues/3200

😄

**Comment by weisswurstkanone** [comment]
:scream:

**Comment by dpfaffenbauer** [comment]
I'll just assume you mean yes with that? :stuck_out_tongue:

**Comment by weisswurstkanone** [comment]
BC breaking in a sense that it affects configs with custom renderers

**Pull request merged**
