### PR TITLE
SecurityHelper: there could be numeric values as well, which shouldn't be casted to string

### PR DESCRIPTION
**Pull request by brusch**
Follow up to #14986

### CODE REVIEW

**Comment by blankse** [comment]
@brusch This would have been noticed earlier if the class was in strict mode.

**Comment by brusch** [comment]
@blankse you're right, new classes should be definitely in strict mode 😊

**Comment by fashxp** [comment]
@blankse is there a php-stan option to check for newly added files to be in strict mode?

**Comment by blankse** [comment]
@fashxp There is a extension that can this:
https://github.com/ergebnis/phpstan-rules#filesdeclarestricttypesrule
See https://github.com/phpstan/phpstan-strict-rules/issues/59

We can add this and enable it. Than we need to add the errors to baseline file or we merge https://github.com/pimcore/pimcore/pull/15065 :)

**Comment by fashxp** [comment]
@blankse would you like to give it a try? We definitely will need to add a baseline then, but we would ensure that all new files have strict mode.

**Comment by blankse** [comment]
@fashxp It works. See https://github.com/pimcore/pimcore/pull/15115

**Comment by Corepex** [comment]
> @blankse you're right, new classes should be definitely in strict mode 😊

@brusch should we then add `declare(strict_types=1)` to the class?

**Comment by brusch** [comment]
@Corepex yep, please 😊

**Comment by brusch** [comment]
@Corepex yep, please 😊

**Comment by brusch** [comment]
@Corepex yep, please 😊

**Comment by brusch** [comment]
@Corepex yep, please 😊

**Comment by brusch** [comment]
@Corepex yep, please 😊

**Comment by brusch** [comment]
@Corepex yep, please 😊

**Comment by brusch** [comment]
@Corepex yep, please 😊

**Comment by brusch** [comment]
@Corepex yep, please 😊

**Comment by brusch** [comment]
@Corepex yep, please 😊

**Comment by brusch** [comment]
@Corepex yep, please 😊

**Comment by brusch** [comment]
@Corepex yep, please 😊

**Comment by brusch** [comment]
@Corepex yep, please 😊

**Comment by brusch** [comment]
@Corepex yep, please 😊

**Comment by brusch** [comment]
@Corepex yep, please 😊

**Comment by brusch** [comment]
@Corepex yep, please 😊

**Comment by brusch** [comment]
@Corepex yep, please 😊

**Comment by brusch** [comment]
@Corepex yep, please 😊

**Comment by brusch** [comment]
@Corepex yep, please 😊

**Comment by brusch** [comment]
@Corepex yep, please 😊

**Comment by brusch** [comment]
@Corepex yep, please 😊

**Comment by brusch** [comment]
@Corepex yep, please 😊

**Comment by brusch** [comment]
@Corepex yep, please 😊

**Comment by brusch** [comment]
@Corepex yep, please 😊

**Comment by brusch** [comment]
@Corepex yep, please 😊

**Comment by passioneight** [comment]
@brusch makes sure the message gets through 😄 

image

**Comment by brusch** [comment]
@passioneight GitHub has obviously some issues at the moment 😂

**Pull request merged**
