### PR TITLE
Define Commands with #[AsCommand] attribute

### LINKED ISSUE #15491: Define commands with #[AsCommand] attribute
### Improvement description

https://symfony.com/doc/current/console/commands_as_services.html

### PR DESCRIPTION
**Pull request by aryaantony92**
## Changes in this pull request  
Resolves https://github.com/pimcore/pimcore/issues/15491

### <samp>🤖 Generated by Copilot at 62d9afe</samp>

This pull request refactors several command classes in the CoreBundle to use the `AsCommand` attribute from Symfony Console. This simplifies the code, improves readability, and makes use of the component features. It also fixes some missing or inconsistent command descriptions and hides some internal commands from the console help.

### <samp>🤖 Generated by Copilot at 62d9afe</samp>

> _Sing, O Muse, of the skillful pull request_
> _That simplified the code of many commands_
> _By using the `AsCommand` attribute_
> _From the Console component of Symfony._

### <samp>🤖 Generated by Copilot at 62d9afe</samp>

*  Replace `setName` and `setDescription` methods with `AsCommand` attribute for various command classes ([link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-0faa136f242a6d9e778699912295b6fa559708cea4d7e5b4acb561f282118dc4R30-R33),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-0faa136f242a6d9e778699912295b6fa559708cea4d7e5b4acb561f282118dc4L34-L35),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-b6fc82b4ddc51d1230b4d273b48df5132bf3c57096cd64ebce3236063c7e1b05R30-R33),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-b6fc82b4ddc51d1230b4d273b48df5132bf3c57096cd64ebce3236063c7e1b05L34-L35),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-444d8f77bcdacf16f4452b8af516bac7152421a170c3f008e8e7641e6285eb2cL33-R36),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-444d8f77bcdacf16f4452b8af516bac7152421a170c3f008e8e7641e6285eb2cL44),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-1b7c6ac7908a0746d3330c389d1ac04bc1d304b7e9c7958dcbbf8ac2f5dff232R29-R32),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-1b7c6ac7908a0746d3330c389d1ac04bc1d304b7e9c7958dcbbf8ac2f5dff232L63-L64),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-59089f49e808f7416c52fdbd9772f5bc09e8247b625d8d9c40fd2f81f78861bdR32-R35),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-59089f49e808f7416c52fdbd9772f5bc09e8247b625d8d9c40fd2f81f78861bdL42-L50),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-fc8171ef5fd8e6d8c97465456ce43bfef114ecf84f7fef386251f9505fff763cR32-R36),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-fc8171ef5fd8e6d8c97465456ce43bfef114ecf84f7fef386251f9505fff763cL38-R44),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-5d778a46cc042f8adc27731c4179dbfcca22ba22223766126fa35e814e05e805R30-R34),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-5d778a46cc042f8adc27731c4179dbfcca22ba22223766126fa35e814e05e805L34-L36),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-17c9cf4a8d43a07e48244b12a69af091d84d6288414d7c73556606b6fd30d98bR31-R34),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-17c9cf4a8d43a07e48244b12a69af091d84d6288414d7c73556606b6fd30d98bL37-L38),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-0dbe61020a03098dcebc6737014cc2e2924ad5a7abfb5fa68fd3e4a60145ebebR28-R31),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-0dbe61020a03098dcebc6737014cc2e2924ad5a7abfb5fa68fd3e4a60145ebebL43-L44),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-fe583ac4863e935e88fb30aab5dab54e36c8531ac0fe1f183f874c3ef3e3a06bR32-R35),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-fe583ac4863e935e88fb30aab5dab54e36c8531ac0fe1f183f874c3ef3e3a06bL36-L37),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-ce10241c14ec50a7eb95f76a2496379319e89707f3b545fadbf3d9ed73438f73L28-R36),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-e28f632b35bf04d37f190ab6b9bcd5233f05b0f2bd6f4ad47ec2423daf8a4c13R29-R33),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-e28f632b35bf04d37f190ab6b9bcd5233f05b0f2bd6f4ad47ec2423daf8a4c13L33-L35),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-5085ecd9222ef9e846261086c74b4e6893ca25ee130e7f6c86509942234a0263R31-R34),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-5085ecd9222ef9e846261086c74b4e6893ca25ee130e7f6c86509942234a0263L40-L41),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-0d554cd43682bc332927d560da98f6cf45a5582c934fffdb32bba70eb879f182R30-R34),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-0d554cd43682bc332927d560da98f6cf45a5582c934fffdb32bba70eb879f182L39-L41),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-f537e631fd0715de68c6dd133dba1683bb295ebdf7520b460352fe6979f94a36L29-R36),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-0ef9cba6f09c4a7c2e42fcef93c02f091da0d63a65e8a67d724fadfed3167f11R29-R33),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-0ef9cba6f09c4a7c2e42fcef93c02f091da0d63a65e8a67d724fadfed3167f11L35-L42),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-2a625c13eb2b3590b3924d0ae1f4f97f929cade5494303044eda5d17d115b8b2R31-R36),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-2a625c13eb2b3590b3924d0ae1f4f97f929cade5494303044eda5d17d115b8b2L35-L37),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-3d316a2e633a581b1773583169b524dc0804ce5bb86428f7d6a2eddcb5aac0c3R30-R34),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-3d316a2e633a581b1773583169b524dc0804ce5bb86428f7d6a2eddcb5aac0c3L48-L50),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-c5fb037eb884a60868c4951bdce23f1d31ea1fbdb5f1ead7dd663185a1a8f114R30-R33),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-c5fb037eb884a60868c4951bdce23f1d31ea1fbdb5f1ead7dd663185a1a8f114L34-L35),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-281dbb770058fb424694aa5240f6804a105f696facb88c6b30309d5ecf86fc23R31-R34),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-281dbb770058fb424694aa5240f6804a105f696facb88c6b30309d5ecf86fc23L40-L41))
  * Import `AsCommand` attribute from `Symfony\Component\Console\Attribute\AsCommand` in each file ([link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-0faa136f242a6d9e778699912295b6fa559708cea4d7e5b4acb561f282118dc4R22),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-b6fc82b4ddc51d1230b4d273b48df5132bf3c57096cd64ebce3236063c7e1b05R22),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-1b7c6ac7908a0746d3330c389d1ac04bc1d304b7e9c7958dcbbf8ac2f5dff232R21),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-59089f49e808f7416c52fdbd9772f5bc09e8247b625d8d9c40fd2f81f78861bdR25),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-fc8171ef5fd8e6d8c97465456ce43bfef114ecf84f7fef386251f9505fff763cR23),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-5d778a46cc042f8adc27731c4179dbfcca22ba22223766126fa35e814e05e805R22),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-17c9cf4a8d43a07e48244b12a69af091d84d6288414d7c73556606b6fd30d98bR23),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-0dbe61020a03098dcebc6737014cc2e2924ad5a7abfb5fa68fd3e4a60145ebebR22),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-fe583ac4863e935e88fb30aab5dab54e36c8531ac0fe1f183f874c3ef3e3a06bR24),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-ce10241c14ec50a7eb95f76a2496379319e89707f3b545fadbf3d9ed73438f73R23),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-e28f632b35bf04d37f190ab6b9bcd5233f05b0f2bd6f4ad47ec2423daf8a4c13R21),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-5085ecd9222ef9e846261086c74b4e6893ca25ee130e7f6c86509942234a0263R22),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-0d554cd43682bc332927d560da98f6cf45a5582c934fffdb32bba70eb879f182R22),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-f537e631fd0715de68c6dd133dba1683bb295ebdf7520b460352fe6979f94a36R22),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-0ef9cba6f09c4a7c2e42fcef93c02f091da0d63a65e8a67d724fadfed3167f11R22),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-2a625c13eb2b3590b3924d0ae1f4f97f929cade5494303044eda5d17d115b8b2R22),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-3d316a2e633a581b1773583169b524dc0804ce5bb86428f7d6a2eddcb5aac0c3R22),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-c5fb037eb884a60868c4951bdce23f1d31ea1fbdb5f1ead7dd663185a1a8f114R22),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-281dbb770058fb424694aa5240f6804a105f696facb88c6b30309d5ecf86fc23R22))
  * Use the attribute to specify the name, description, and aliases of each command as arguments ([link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-0faa136f242a6d9e778699912295b6fa559708cea4d7e5b4acb561f282118dc4R30-R33),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-b6fc82b4ddc51d1230b4d273b48df5132bf3c57096cd64ebce3236063c7e1b05R30-R33),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-444d8f77bcdacf16f4452b8af516bac7152421a170c3f008e8e7641e6285eb2cL33-R36),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-1b7c6ac7908a0746d3330c389d1ac04bc1d304b7e9c7958dcbbf8ac2f5dff232R29-R32),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-59089f49e808f7416c52fdbd9772f5bc09e8247b625d8d9c40fd2f81f78861bdR32-R35),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-fc8171ef5fd8e6d8c97465456ce43bfef114ecf84f7fef386251f9505fff763cR32-R36),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-5d778a46cc042f8adc27731c4179dbfcca22ba22223766126fa35e814e05e805R30-R34),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-17c9cf4a8d43a07e48244b12a69af091d84d6288414d7c73556606b6fd30d98bR31-R34),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-0dbe61020a03098dcebc6737014cc2e2924ad5a7abfb5fa68fd3e4a60145ebebR28-R31),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-fe583ac4863e935e88fb30aab5dab54e36c8531ac0fe1f183f874c3ef3e3a06bR32-R35),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-ce10241c14ec50a7eb95f76a2496379319e89707f3b545fadbf3d9ed73438f73L28-R36),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-e28f632b35bf04d37f190ab6b9bcd5233f05b0f2bd6f4ad47ec2423daf8a4c13R29-R33),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-5085ecd9222ef9e846261086c74b4e6893ca25ee130e7f6c86509942234a0263R31-R34),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-0d554cd43682bc332927d560da98f6cf45a5582c934fffdb32bba70eb879f182R30-R34),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-f537e631fd0715de68c6dd133dba1683bb295ebdf7520b460352fe6979f94a36L29-R36),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-0ef9cba6f09c4a7c2e42fcef93c02f091da0d63a65e8a67d724fadfed3167f11R29-R33),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-2a625c13eb2b3590b3924d0ae1f4f97f929cade5494303044eda5d17d115b8b2R31-R36),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-3d316a2e633a581b1773583169b524dc0804ce5bb86428f7d6a2eddcb5aac0c3R30-R34),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-c5fb037eb884a60868c4951bdce23f1d31ea1fbdb5f1ead7dd663185a1a8f114R30-R33),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-281dbb770058fb424694aa5240f6804a105f696facb88c6b30309d5ecf86fc23R31-R34))
  * Remove the redundant methods that were previously used to set the name, description, and aliases of each command ([link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-0faa136f242a6d9e778699912295b6fa559708cea4d7e5b4acb561f282118dc4L34-L35),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-b6fc82b4ddc51d1230b4d273b48df5132bf3c57096cd64ebce3236063c7e1b05L34-L35),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-444d8f77bcdacf16f4452b8af516bac7152421a170c3f008e8e7641e6285eb2cL44),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-1b7c6ac7908a0746d3330c389d1ac04bc1d304b7e9c7958dcbbf8ac2f5dff232L63-L64),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-59089f49e808f7416c52fdbd9772f5bc09e8247b625d8d9c40fd2f81f78861bdL42-L50),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-fc8171ef5fd8e6d8c97465456ce43bfef114ecf84f7fef386251f9505fff763cL38-R44),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-5d778a46cc042f8adc27731c4179dbfcca22ba22223766126fa35e814e05e805L34-L36),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-17c9cf4a8d43a07e48244b12a69af091d84d6288414d7c73556606b6fd30d98bL37-L38),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-0dbe61020a03098dcebc6737014cc2e2924ad5a7abfb5fa68fd3e4a60145ebebL43-L44),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-fe583ac4863e935e88fb30aab5dab54e36c8531ac0fe1f183f874c3ef3e3a06bL36-L37),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-e28f632b35bf04d37f190ab6b9bcd5233f05b0f2bd6f4ad47ec2423daf8a4c13L33-L35),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-5085ecd9222ef9e846261086c74b4e6893ca25ee130e7f6c86509942234a0263L40-L41),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-0d554cd43682bc332927d560da98f6cf45a5582c934fffdb32bba70eb879f182L39-L41),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-0ef9cba6f09c4a7c2e42fcef93c02f091da0d63a65e8a67d724fadfed3167f11L35-L42),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-2a625c13eb2b3590b3924d0ae1f4f97f929cade5494303044eda5d17d115b8b2L35-L37),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-3d316a2e633a581b1773583169b524dc0804ce5bb86428f7d6a2eddcb5aac0c3L48-L50),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-c5fb037eb884a60868c4951bdce23f1d31ea1fbdb5f1ead7dd663185a1a8f114L34-L35),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-281dbb770058fb424694aa5240f6804a105f696facb88c6b30309d5ecf86fc23L40-L41))
  * Set the `hidden` argument to true for the commands that should not be listed in the console help (`InternalMigrationHelpersCommand`, `InternalModelDaoMappingGeneratorCommand`, `InternalUnicodeCldrLanguageTerritoryGeneratorCommand`) ([link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-0d554cd43682bc332927d560da98f6cf45a5582c934fffdb32bba70eb879f182R30-R34),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-f537e631fd0715de68c6dd133dba1683bb295ebdf7520b460352fe6979f94a36L29-R36),[link](https://github.com/pimcore/pimcore/pull/15957/files?diff=unified&w=0#diff-0ef9cba6f09c4a7c2e42fcef93c02f091da0d63a65e8a67d724fadfed3167f11R29-R33))

### CODE REVIEW

**Review by kingjia90 — CHANGES_REQUESTED** [review]
- [x] Adapt the documentation to recommend the attribute in the example https://github.com/pimcore/pimcore/blob/add_ascommand_attribute/doc/05_Objects/05_External_System_Interaction.md
- [x] Adapt the documentation to recommend the attribute in the example https://github.com/pimcore/pimcore/blob/82b7f2d53448694aa6d1e42d5c3e92dfa8722117/doc/19_Development_Tools_and_Details/11_Console_CLI.md#L46

- [x] can and should be also done for this?https://github.com/pimcore/pimcore/blob/62d9afeedbabb8ed3eab3b84e6449849a5e21fdd/bundles/CoreBundle/src/Command/Definition/Import/AbstractStructureImportCommand.php#L32
- [x] https://github.com/pimcore/pimcore/blob/68f198d32add713f2e4025b5dcb6414754133145/bundles/SimpleBackendSearchBundle/src/Command/SearchBackendReindexCommand.php#L32
- [x] https://github.com/pimcore/pimcore/blob/68f198d32add713f2e4025b5dcb6414754133145/bundles/InstallBundle/src/Command/InstallCommand.php#L148
- [x] https://github.com/pimcore/pimcore/blob/afb100ae2493ef0b473af0acbe8cc93181f270d7/bundles/CoreBundle/src/Command/Bundle/ListCommand.php#L35

**Comment by aryaantony92** [comment]
@kingjia90 Not sure whether we can adapt the AsCommand for https://github.com/pimcore/pimcore/blob/62d9afeedbabb8ed3eab3b84e6449849a5e21fdd/bundles/CoreBundle/src/Command/Definition/Import/AbstractStructureImportCommand.php#L32 since the name of the command is dynamically generated

**Comment by kingjia90** [comment]
> @kingjia90 Not sure whether we can adapt the AsCommand for
> 
> https://github.com/pimcore/pimcore/blob/62d9afeedbabb8ed3eab3b84e6449849a5e21fdd/bundles/CoreBundle/src/Command/Definition/Import/AbstractStructureImportCommand.php#L32
> 
> since the name of the command is dynamically generated

then let's keep as is for the moment, also don't know either if is supported.
The latest commit is fine, i see only that is missing https://github.com/pimcore/pimcore/blob/13f766b67511d319dfac9e6ca37493ae3fa3ef41/bundles/CoreBundle/src/Command/Bundle/ListCommand.php#L35 then will merge it

**Comment by aryaantony92** [comment]
@kingjia90 Yes, but we cannot add the AsCommand attribute with out the 'name' parameter. Here https://github.com/pimcore/pimcore/blob/13f766b67511d319dfac9e6ca37493ae3fa3ef41/bundles/CoreBundle/src/Command/Bundle/ListCommand.php#L34C1-L34C1, the name is generated from here https://github.com/pimcore/pimcore/blob/13f766b67511d319dfac9e6ca37493ae3fa3ef41/bundles/CoreBundle/src/Command/Bundle/AbstractBundleCommand.php#L68C16-L68C16. So, is it fine to make the command name static like 'pimcore:bundle:list'

**Pull request merged**
