### PR TITLE
TinyMCE Bundle shouldn't be a recommended bundle anymore

### PR DESCRIPTION
**Pull request by brusch**
Quill is the new default WYSIWYG editor

### CODE REVIEW

**Comment by dpfahlbusch** [comment]
@brusch and maybe add Quill as a recommended bundle?

**Comment by brusch** [comment]
Well, I didn't include it, because it's not always there (it's located in a dedicated package), so this could lead to errors.

**Comment by jdreesen** [comment]
What happens if you *don't* enable any WYSIWYG bundle? It seems like the [edtiable](https://github.com/pimcore/pimcore/blob/11.x/models/Document/Editable/Wysiwyg.php) and [data object type](https://github.com/pimcore/pimcore/blob/11.x/models/DataObject/ClassDefinition/Data/Wysiwyg.php) are still provided by the core. Do they work without a bundle? Shouldn't they be moved to those bundels?

**Comment by brusch** [comment]
Yep, they are still in the core, because moving them would break things - so we keep them as they are for now.
If you don't enable a WYSIWYG you won't have the editor on your field, but would still work (not editing) and doesn't break anything.

**Pull request merged**
