### PR TITLE
[Data objects] Catch error when loading data object whose latest version is not accessible

### PR DESCRIPTION
**Pull request by blankse**
Alternative to #14045 which fix it also for saving and for documents

### CODE REVIEW

**Comment by blankse** [comment]
Or should we remove the exception and return null (like also in line 373)? Was a regression from https://github.com/pimcore/pimcore/pull/11458

**Comment by Corepex** [comment]
@blankse I tested the PR, and I don't get the described (https://github.com/pimcore/pimcore/pull/14045#issue-1530199783) error message when I try to open the dataObject (or document).
I only see the error message when I click the versions tab ... 

image

**Comment by blankse** [comment]
Maybe only when the object/document have a not published draft version? Maybe from auto save?

**Comment by Corepex** [comment]
> Maybe only when the object/document have a not published draft version? Maybe from auto save?

verified - so its only a problem if you have draft version ...

**Comment by Corepex** [comment]
> Or should we remove the exception and return null (like also in line 373)?

sounds good to me - would be consistent. Could you provide a commit with the according changes?

**Comment by blankse** [comment]
@Corepex I changed it

**Comment by Corepex** [comment]
image

if we change the return to null we also have to check for this return value - what do you think about checking the return here:
https://github.com/pimcore/pimcore/blob/156a5c9f4f60dd99099c83219ed84372e09c6cd3/bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php#L1618

this would make the if check obsolete: https://github.com/pimcore/pimcore/blob/156a5c9f4f60dd99099c83219ed84372e09c6cd3/bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php#L1626

**Comment by Corepex** [comment]
@blankse thanks for the very fast reply/commit 💯

**Comment by blankse** [comment]
@Corepex Oh you are fast :) I fixed more calls. I will create a follow PR

**Comment by Corepex** [comment]
Ah sorry 😝 just open another PR and link it to that one - i will review it tomorrow 👍

**Comment by blankse** [comment]
@Corepex Here it is: https://github.com/pimcore/pimcore/pull/14086

**Pull request merged**
