### PR TITLE
chore: Use short list syntax everywhere

### PR DESCRIPTION
**Pull request by jdreesen**
This is just some cleanup that uses the more modern short list syntax `[...] = ...` instead of `list(...) = ...`.

### CODE REVIEW

**Comment by Corepex** [comment]
@jdreesen, could you please resolve the conflicts? thanks

**Comment by jdreesen** [comment]
Done. This will probably happen a few more times, unless you merge it soon.

**Comment by jdreesen** [comment]
I fixed the conflicts and configured PHP-CS-Fixer to fix this automatically.

**Comment by lukmzig** [comment]
thank you @jdreesen

**Pull request merged**
