### PR TITLE
[DocType] Fix: Predefined Document Type Select in Settings Tab

### PR DESCRIPTION
**Pull request by blankse**
## Changes in this pull request  
In the moment the select shows only undefined > undefined and doesn't work.

### CODE REVIEW

**Comment by blankse** [comment]
@brusch Why did you remove my translation function?

**Comment by brusch** [comment]
Ah, sorry, that was by mistake :)

**Comment by brusch** [comment]
I've also added it for the group name.

**Comment by blankse** [comment]
Thanks :)

**Comment by blankse** [comment]
Shouln't be the > sign between group and name?

**Comment by brusch** [comment]
Oh dear, yes, of course - thanks again man :)

**Pull request merged**
