### PR TITLE
BUGFIX: Fix unit conversion logic with offset

### LINKED ISSUE #16470: [Bug]: Unit conversion with offset returns incorrect values
### Pimcore version

11.1.4

### Steps to reproduce

- Create two units that depend on each other with a conversion factor, like Celsius and Fahrenheit in the docs (https://pimcore.com/docs/platform/Pimcore/Objects/Object_Classes/Data_Types/Number_Types/#quantity-value-unit-conversion):  
image
- Create an object class with a quantity value field that allows both units
- Check the "automatic conversion" box

### Actual Behavior

When switching between units, conversion works correctly, using the following formula:
°F = °C * 1.8 + 32

### Expected Behavior

The conversion applies the incorrect formula.
Instead of the formula above, the following is applied:
°F = °C * **1/1.8** + 32
This occurs only if an offset is used.

### PR DESCRIPTION
**Pull request by beheist**
Fixes the conversion logic to correctly respect offsets and factors.
Please do some of your own testing, there might be cases which I missed.

  
  

## Changes in this pull request  
Resolves #16470

### CODE REVIEW

**Comment by fashxp** [comment]
@BlackbitDevs could you please have a look at this?

**Comment by fashxp** [comment]
@BlackbitDevs :ping_pong:

**Comment by BlackbitDevs** [comment]
This is the same formula only from two different perspectives. The current factors and offsets are defined as: how to convert this unit to the base unit.

@beheist, you provided this configuration in #16470
296994828-a0868580-de70-4944-9a3d-48052e1fe58a

According to https://www.thoughtco.com/celcius-to-farenheit-formula-609227 the formula for converting °F to the base unit °C is:
> °C = (°F − 32) x 5/9 

So the original and this PR's formula are the same when
- current formula: factor and offset define how to convert the current unit to the base unit
- this PR's formula: factor and offset define how to convert base unit to current unit

So in either case, it should work correctly - but if this PR gets accepted, we need a migration script which changes the factors and offsets for all currently existing units because otherwise ALL conversions will be wrong (including those which do not have offset but only factors).

**Comment by fashxp** [comment]
but then we maybe should just clarify the behavior in the docs?

**Comment by fashxp** [comment]
@beheist wdyt?

**Comment by fashxp** [comment]
@beheist :ping_pong:

**Comment by fashxp** [comment]
created a PR for updating the docs, see https://github.com/pimcore/pimcore/pull/16931

**Pull request closed without merging**
