### PR TITLE
Reimplement #12736

### PR DESCRIPTION
**Pull request by blankse**
Reimplement #12736, got lost in the last merge of 10.6 https://github.com/pimcore/pimcore/commit/f5edb29173a9beeed856b9f8715799599912a962

### CODE REVIEW

**Comment by jdreesen** [comment]
Funny how often conflict resolution goes wrong in this project. I'm glad you're keeping an eye on it, @blankse :heart:

**Comment by blankse** [comment]
There are also empty files under lib/Google, I removed it in https://github.com/pimcore/pimcore/pull/14469

**Comment by Corepex** [comment]
merging in the recently merged changed from https://github.com/pimcore/pimcore/pull/14517 should resolve the phpstan problems

**Comment by blankse** [comment]
@Corepex Done :)

**Pull request merged**
