### PR TITLE
[Bug]: strip_tags needs empty string as default value, cannot handle null

### LINKED ISSUE #13723: [Bug] Null Perspective when logging in as some other user or in deeplinks
### Expected behavior

https://github.com/pimcore/pimcore/blob/906f47135946b1ea598d268bb957926797126b10/bundles/AdminBundle/src/Security/Authenticator/AdminAbstractAuthenticator.php#L124

maybe `$request->get('perspective') ?? ''` or just append `&perspective=` to the generated url to fix the problem

### Actual behavior

image

Deeplink also affected

### Steps to reproduce

Create a new user
set a password

then press this and copy&paste the generated temporary link in a new browser
image

image

#AND

When using a deeplink eg. `http://localhost/admin/login/deeplink?document_136_page`

### PR DESCRIPTION
**Pull request by mattamon**
## Changes in this pull request  
Resolves #13723 

## Additional info  
strip_tags cannot handle null values

### CODE REVIEW

**Comment by blankse** [comment]
I think this should be also changed in `10.5` branch

**Comment by blankse** [comment]
@mattamon I created a PR for `10.5` https://github.com/pimcore/pimcore/pull/13757

**Comment by mattamon** [comment]
@blankse You're totally right. Thank you for your PR!

**Comment by mattamon** [comment]
Closing in favor of #13757

**Pull request closed without merging**
