### PR TITLE
[Sitemap generation] Add option handleCurrentSite

### PR DESCRIPTION
**Pull request by BlackbitDevs**
Assume you have a multi-site project with domains site1.com and site2.com and use `DocumentTreeGenerator` to generate the sitemap based on the documents. When you call the sitemap index URL https://site1.com/sitemap.xml, by default you will get the sitemap files for all the sites: 
```xml
<sitemapindex xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/siteindex.xsd">
  <sitemap>
    <loc>
      https://site1.com/sitemap.site_1.xml
    </loc>
    <loc>
      https://site1.com/sitemap.site_2.xml
    </loc>
    <lastmod>2023-05-31T11:51:16+02:00</lastmod>
  </sitemap>
</sitemapindex>
```
https://site2.com/sitemap.xml will contain https://site2.com/sitemap.site_1.xml and https://site2.com/sitemap.site_2.xml - for Google https://site1.com/sitemap.site_1.xml and https://site2.com/sitemap.site_1.xml are different sitemaps.
From SEO perspective it is also a problem that https://site1.com/sitemap.site_2.xml only contains URLs for site2.com (although it is called with domain site1.com).
Currently there is no setting to only retrieve sitemap URLs for the current site.

With this PR it is possible to set `handleCurrentSite` option in the service defintion:
```yaml
Pimcore\Sitemap\Document\DocumentTreeGenerator:
        arguments:
            $filters:
                - '@Pimcore\Sitemap\Element\Filter\PublishedFilter'
                - '@Pimcore\Sitemap\Element\Filter\PropertiesFilter'
                - '@Pimcore\Sitemap\Document\Filter\DocumentTypeFilter'
                - '@Pimcore\Sitemap\Document\Filter\SiteRootFilter'
            $processors:
                - '@Pimcore\Sitemap\Element\Processor\ModificationDateProcessor'
                - '@Pimcore\Sitemap\Element\Processor\PropertiesProcessor'
            $options:
                handleCurrentSite: true
                handleMainDomain: false
                handleSites: false
```

This way https://site1.com/sitemap.xml will link to https://site1.com/sitemap.site_1.xml and https://site2.com/sitemap.xml will only link to https://site2.com/sitemap.site_2.xml.

### CODE REVIEW

**Comment by BlackbitDevs** [comment]
Sonarcloud comlains about ANY usage of `md5()`. In this case it is for a temporary file, there is no security issue here.

**Comment by mattamon** [comment]
@BlackbitDevs do you think we can add this to a bug fix version like 11.0.1?

**Comment by BlackbitDevs** [comment]
To me it would be fine if this was released as a bugfix. Shall I change to target branch `11.0`?

**Comment by mattamon** [comment]
> To me it would be fine if this was released as a bugfix. Shall I change to target branch `11.0`?

Would it break anything? I guess not right? Because you have to add the option. 
We will discuss this in the team :)

**Comment by BlackbitDevs** [comment]
Hmm currently it may change behaviour because default value is `true`. This means if somebody has option `handleSites=false` you will nevertheless get the sitemap data for the current site (from `handleCurrentSite` being true by default). Of course we could set `handleCurrentSite` to false by default, then it would not change current behaviour.

**Comment by mattamon** [comment]
> Hmm currently it may change behaviour because default value is `true`. This means if somebody has option `handleSites=false` you will nevertheless get the sitemap data for the current site (from `handleCurrentSite` being true by default). Of course we could set `handleCurrentSite` to false by default, then it would not change current behaviour.

Ah yes I see. Yes for a bugfix we need to set it to false, to not change the default behaviour.

**Comment by BlackbitDevs** [comment]
Default value is now false.

**Comment by mattamon** [comment]
@BlackbitDevs we discussed it in the team and we will leave it for 11.x since it adds new functionality.

**Comment by Jan-Walther-Basilicom** [comment]
@mattamon Fine for me. If there is anything for me to do concerning this PR, just notify me...

**Review by dvesh3 — APPROVED** [review]

**Comment by dvesh3** [comment]
@BlackbitDevs thanks!

**Pull request merged**
