### PR TITLE
Fixes missing class reference in built Listing classes

### PR DESCRIPTION
**Pull request by NiklasBr**
## Changes in this pull request  
Resolves "Undefined class 'ElementInterface'" in class definition files at `var/classes/DataObject/ClassName/Listing.php`

image

## After this change

image

### CODE REVIEW

**Comment by mcop1** [comment]
Thanks!

**Comment by dvesh3** [comment]
we need a migration here to fix the existing classes.

**Comment by NiklasBr** [comment]
@dvesh3 I suppose I could re-save them like here?

https://github.com/pimcore/pimcore/blob/11.x/bundles/CoreBundle/Migrations/Version20220201132131.php

**Comment by dvesh3** [comment]
> @dvesh3 I suppose I could re-save them like here?
> 
> https://github.com/pimcore/pimcore/blob/11.x/bundles/CoreBundle/Migrations/Version20220201132131.php

yes, like this..

**Pull request merged**
