### PR TITLE
Object brick -- allowed classes sorting and filtering

### PR DESCRIPTION
**Pull request by dturopoli**
Solution for  #10397

### CODE REVIEW

**Comment by brusch** [comment]
@dturopoli Thanks for your PR, however I'd add this information to the existing store and just filter for it to generate the selection menu. Thanks!

**Comment by brusch** [comment]
@dturopoli 🏓

**Comment by dturopoli** [comment]
@brusch Im kinda busy at the moment, I updated the code as you suggested.

**Comment by brusch** [comment]
Works like a charm - very nice improvement - thanks!

**Pull request merged**
