### PR TITLE
delete dynamic-contants.php

### PR DESCRIPTION
**Pull request by dpfaffenbauer**
First: it has a spelling error in the name
Second: It's not used anywhere?!

### CODE REVIEW

**Comment by brusch** [comment]
It's just there for auto-completion in the IDE, because the constants are set dynamically here  https://github.com/pimcore/pimcore/blob/master/lib/Bootstrap.php... but yes, the typo im the file name needs to be fixed 😊

**Comment by dpfaffenbauer** [comment]
🤦‍♂

**Comment by brusch** [comment]
What's wrong with that?

**Comment by dpfaffenbauer** [comment]
It's just a dirty hack for something that should be refactored anyway...

**Comment by Yivan** [comment]
I think it should be kept.
For my case, stubs is of great help for AST analyser like phpstan.
I included them in autoload_files section so I can analyse project bundle code without phpstan warning.

**Comment by Yivan** [comment]
@brush just the line `require_once '../config/constants.php';` is bad resolved... phpstan reports it does not exists.

**Comment by brusch** [comment]
@Yivan You are referencing the wrong user name ;) 
I have no clue what you mean ...

**Comment by Yivan** [comment]
@brush No it was well for this issue, i was telling:
- yes in Pimcore stub `dynamic-contants.php` should be renammed `dynamic-constants.php` : https://github.com/pimcore/pimcore/tree/master/stubs
- and Pimcore stubs are useful so it should be kept (for IDE like you said or in my case for php linter PHPStan).
That's all !

**Comment by brusch** [comment]
@Yivan again ... wrong username referenced, it's `brusch` not `brush` 😅

**Comment by Yivan** [comment]
Ha I get it !!! I correct it !! Thanks : ) I need some sleep ; )

**Pull request closed without merging**
