### PR TITLE
fix session save for objects with complex linked entities as well

### PR DESCRIPTION
**Pull request by dpfaffenbauer**
Basically the same Problem we have with copy and had with versions now fixed for Session saving as well.

I will provide a proper PR for all DeepCopy related parts for 7.0.

### CODE REVIEW

**Comment by brusch** [comment]
Thanks a lot! 

> I will provide a proper PR for all DeepCopy related parts for 7.0.   
As this shouldn't break anything, this could also go in 6.7, right?

**Comment by jdreesen** [comment]
You mean `v6.6.5`, right (because it was merged in branch `6.6`)?

**Comment by dpfaffenbauer** [comment]
yes, this doesn't break anything

**Comment by brusch** [comment]
No, what I meant was regarding  
> I will provide a proper PR for all DeepCopy related parts for 7.0.  
  
The refactoring of all the DeepCopy stuff doesn't need to wait until 7.0 as it wouldn't break anything, we're just outsourcing the functionality into proper services, right?

**Comment by dpfaffenbauer** [comment]
Gotcha, yep, that wouldn't be a break. Right.

**Pull request merged**
