### PR TITLE
Fix PhpStan errors

### PR DESCRIPTION
**Pull request by blankse**
This fix all PhpStan errors in the baseline file. False positives are ignored inline.

### CODE REVIEW

**Comment by blankse** [comment]
@brusch The PHP-CS-Fixer seems not working with fork branches...

**Comment by blankse** [comment]
@brusch Unfortunately still does not work :(

**Comment by brusch** [comment]
@blankse ok, now it fails at a different step 🤔

**Comment by blankse** [comment]
@brunsch I read something about the pull_request_target workflow event for forks. See https://github.com/stefanzweifel/git-auto-commit-action:
`The following workflow runs php-cs-fixer (a code linter and fixer for PHP) when a pull_request is opened. We've added the pull_request_target-trigger too, to make it work for forks.`

**Comment by brusch** [comment]
@blankse thanks for the hint, I've seen this as well, but at the end they also write: 
> For Workflows which run linters and fixers (like the example above) we recommend running them when a push happens on the main-branch.

So I've excluded PRs for now, which should be also fine.

**Comment by brusch** [comment]
@blankse can you please rebase & push again? Thanks 😊

**Comment by blankse** [comment]
@brusch Okay 👍🏼 Should now work 😄 Have also a nice weekend and I looking forward to the release next week 🎉

**Comment by blankse** [comment]
@weisswurstkanone I see you change the milestone to 10.1

I think this could be too late for some changes because of BC. Should I split this changes in a seperate PR, so you can review this and merge before 10.0 Release?

**Comment by brusch** [comment]
@blankse that would be great, thanks a lot!

**Comment by brusch** [comment]
Closed in favor of #9067

**Pull request closed without merging**
