### PR TITLE
[Feature] Application Logger for class definition save actions

### PR DESCRIPTION
**Pull request by NiklasBr**
Updated PR for #6242

### CODE REVIEW

**Comment by dvesh3** [comment]
@blankse could you please fix the tests. thanks!

**Comment by blankse** [comment]
@dvesh3 I think you mean @NiklasBr :)

**Comment by dvesh3** [comment]
@blankse yes, thanks for correction! missed you both on weekend 😄

**Comment by NiklasBr** [comment]
I'll look at it @dvesh3

**Comment by NiklasBr** [comment]
@dvesh3 Feel free to have a look again.

**Comment by brusch** [comment]
We discussed this internally and for now we came to the conclusion that we're not going to put any core log entries into the application logger, that should stay (for now) exclusive for application related stuff. 
We agree that this would be a handy feature, but we don't think the application logger (as it is designed at the moment) is the right place for that. If we go in this direction, this feature should be also implemented for other topics.

**Comment by brusch** [comment]
Thanks anyway! Maybe we should also create a follow-up issue for that feature. 🤔

**Pull request closed without merging**
