### PR TITLE
Tags filter not works if tags are uppercase

### PR DESCRIPTION
**Pull request by Se7en-IT**
I have uppercase tags, but when i search on tags filter section, i don't find nothing.

### CODE REVIEW

**Comment by brusch** [comment]
@Se7en-IT Thanks a lot for your PR. Since this is a bug fix, can you please rebase this PR onto the `6.8` branch and change the base of the PR as well to `6.8`. Thanks a lot!

**Comment by brusch** [comment]
@Se7en-IT please also sign the CLA. Thanks again!

**Comment by brusch** [comment]
Closed in favor of #7610

**Comment by Se7en-IT** [comment]
@brusch this is PR #7610. ok?

**Comment by brusch** [comment]
Yep. Thanks a lot!

**Pull request closed without merging**
