### PR TITLE
add doctrine filter to RecycleBin creation.

### PR DESCRIPTION
**Pull request by dpfaffenbauer**

### CODE REVIEW

**Comment by dpfaffenbauer** [comment]
BTW: The behaviour is exactly the same as with Versions, why not re-use that? 

Currently it is copy paste stuff and leads to errors, like this already does...

**Comment by albertmueller** [comment]
i can confirm, that with this PR the doctrine issue is fixed

**Comment by brusch** [comment]
@dpfaffenbauer Thanks for your PR! 
Actually it is not exactly the same behavior (e.g. the recycling bin includes children, ...), that's why we're not sharing the code with versions and providing dedicated interfaces 😊

**Comment by brusch** [comment]
Related to #5423

**Comment by dpfaffenbauer** [comment]
can we expect a new patch release? or is this bug-fix coming with a minor release?

**Comment by brusch** [comment]
Is coming with 6.5.0 next week.

**Pull request merged**
