### PR TITLE
Consider role permissions in price rule overview.

### PR DESCRIPTION
**Pull request by andreas-gruenwald**
Ecommerce Framework bugfix:
the price rule controller now also takes role permissions into account, not only user permissions.

### CODE REVIEW

**Comment by dpfaffenbauer** [comment]
is this really necessary? Pimcore does the same internally:

```php
//Pimcore\Bundle\AdminBundle\Controller\AdminController:73

if (!$this->getUser() || !$this->getUser()->isAllowed($permission)) {
    $this->get('monolog.logger.security')->error(
        'User {user} attempted to access {permission}, but has no permission to do so', [
            'user'       => $this->getUser()->getName(),
            'permission' => $permission
        ]
    );

    throw new AccessDeniedHttpException('Attempt to access ' . $permission . ', but has no permission to do so.');
}
```

**Comment by fashxp** [comment]
hmm, this shouldn't be necessary ... see https://github.com/pimcore/pimcore/blob/master/pimcore/models/User.php#L318-L318

or do I miss something?

**Comment by andreas-gruenwald** [comment]
Ok, so we  can just replace the part 
`$this->getUser()->getPermission($key)`
by
`$this->getUser()->isAllowed($permission)) { `,
right?

isAllowed() considers roles, while getPermission doesn't seem to?

**Comment by fashxp** [comment]
thats right...

**Comment by fashxp** [comment]
thanks

**Pull request merged**
