### PR TITLE
[ExtJs] add combo-box selection for bundle/controller/action/template to doc-types

### PR DESCRIPTION
**Pull request by dpfaffenbauer**
This PR adds the combo-box selection for bundle/controller/action/template to document-types.

### CODE REVIEW

**Comment by dpfaffenbauer** [comment]
ping @maff, ping @brusch, ping @weisswurstkanone could anybody give me some feedback on please? 😄

**Comment by brusch** [comment]
Please give us some time ... we are busy with some other things at the moment.

**Comment by maff** [comment]
Nice one, thanks!

**Comment by dpfaffenbauer** [comment]
yeah 🍻  😄

**Pull request merged**
