### PR TITLE
fix sql condition being skipped when exporting objects in grid

### LINKED ISSUE #13662: [Bug]: Sql condition is skipped when exporting to csv in grid
### Expected behavior

When applying sql condition only data objects that match sql conditions are exported when export to csv or xlsx is called.

### Actual behavior

When applying sql condition all data objects are exporting when export to csv or xlsc is called skipping sql condition.

### Steps to reproduce

1. Create some sql condition that will limit data objects, for example "length(color) <= 5"
2. Click "export to csv". All records will be exported including records that not match sql condition.

### PR DESCRIPTION
**Pull request by pfilipkowskilemon**
## Changes in this pull request  
Resolves #
#13662 

## Additional info  
Resolves issue with skipping sql condition when exporting to csv in grid

### CODE REVIEW

**Comment by Corepex** [comment]
@pfilipkowskilemon, thanks for your PR. I tested your solution, and it worked correctly, but I maybe found another way that fixes the `this.sqlFilter`. I think it would be a cleaner solution to add `this.sqlFilter = field.getValue()` to `gridTabAbstract.js#L181`. In this case, `this.sqlFilter` will be set on "submitting" the filter input.

https://github.com/pimcore/pimcore/blob/10.6/bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/gridTabAbstract.js#L181

**Comment by Corepex** [comment]
@pfilipkowskilemon friendly reminder - if you provide the changes, we could add them to today's release

**Comment by pfilipkowskilemon** [comment]
@Corepex thanks for reminder

**Comment by Corepex** [comment]
@pfilipkowskilemon, thanks for helping us to improve pimcore 👍

**Pull request merged**
