### PR TITLE
Bump PhpStan level to 5

### PR DESCRIPTION
**Pull request by blankse**
`[OK] Baseline generated with 134 errors.`

- [ ] Create new baseline, when all 10.4 PhpStan PRs are merged

### CODE REVIEW

**Comment by blankse** [comment]
@dvesh3 Okay its not possible to generate one baseline file for lowest/highest dependency until these PRs are merged:

- https://github.com/pimcore/pimcore/pull/11978
- https://github.com/pimcore/pimcore/pull/11977
- https://github.com/pimcore/pimcore/pull/11976

So these are tagged for 10.5 we must stay to level 4

**Comment by blankse** [comment]
Maybe we can ignore it with the phpstan-ignore comments. I try it, when the 10.4 PRs are merged

**Comment by blankse** [comment]
@dvesh3 With the reportUnmatchedIgnoredErrors config param for lowest dependency analyse it works. Is ready for 10.4 now (if you want)

**Comment by dvesh3** [comment]
@blankse thanks a lot!

**Pull request merged**
