### PR TITLE
[Ecommerce] [IndexService] Fix the Pimcore TagsGetter

### LINKED ISSUE #7306: [Bug] [Ecommerce] [IndexService] The TagsGetter returns wrong values
Config in YAML file:

```yaml
imports:
  - { resource: '@PimcoreEcommerceFrameworkBundle/Resources/config/v7_configurations.yml' }

pimcore_ecommerce_framework:
  ...
  index_service:
    tenants:
      default:
        ...
        attributes:
          ...
          tags:
            type: varchar(255)
            getter_id: Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\Getter\TagsGetter
            getter_options:
              includeParentTags: true
            filter_group: multiselect
```

If you save the DataObject with defined tags, they will be saved in the index table as `Array` (just string).

Bildschirmfoto 2020-10-13 um 12 17 32

### PR DESCRIPTION
**Pull request by MyZik**
Resolves #7306

Bildschirmfoto 2020-10-13 um 12 25 15

### CODE REVIEW

**Comment by brusch** [comment]
@MyZik Thanks a lot for your PR! Could you please change the base of the PR to `6.8` as this is a bug-fix 😉 Thanks a lot!

**Comment by MyZik** [comment]
@brusch Thank you! I've changed the base branch. There are a lot of commits :D

**Comment by blankse** [comment]
@MyZik You can add this repository as second remote
```
git remote add upstream https://github.com/pimcore/pimcore.git
git fetch upstream
```
Then you can rebase it with this repository and push it
```
git rebase --onto upstream/6.8 master
git push --force
```

**Comment by MyZik** [comment]
@blankse thank you! :)

**Comment by brusch** [comment]
@MyZik Looks good now, thanks a lot! 
@blankse thanks for helping out!

**Pull request merged**
