### PR TITLE
Relation performance fix

### PR DESCRIPTION
**Pull request by NiklasBr**
## Changes in this pull request 

Improves performance with large relations tables where fieldnames are important.

### CODE REVIEW

**Comment by devpetrov** [comment]
@mattamon I can see that this migration file is missing in Pimcore 11 and could not find why and where it has been removed. Is that intentional or it should be restored for v11?

**Comment by blankse** [comment]
@devpetrov See https://pimcore.com/docs/platform/Pimcore/Installation_and_Upgrade/Updating_Pimcore/Preparing_for_V11

> Upgrade to version 10.6.x, if you are using a lower version.

So this migration should have already executed in Pimcore 10 und must not be part of Pimcore 11.

**Comment by devpetrov** [comment]
@blankse thanks for the quick response! 

So then I guess the indexes provided by that migration are there out of the box for Pimcore 11? Also, because we are migrating from 10.6 to 11 we already have the migration executed, but the missing file is causing this migration to always appear as pending when executing migrations. I guess I can consider it safe to delete the record for that migration from the `migration_versions` table?

**Comment by blankse** [comment]
@devpetrov When the migration is still pending, maybe it was occoured a error and it was stopped? I would check then all object_relations_* tables manually if the fieldname index is set. When this is the case you can remove the migration from the migration_versions table.

**Pull request merged**
