### PR TITLE
Update README.md - fixed getting started installation link

### PR DESCRIPTION
**Pull request by ibousfiha**
## Changes in this pull request  
Resolves broken link in getting started

### <samp>🤖 Generated by Copilot at f4c8299</samp>

This pull request updates the `README.md` file to fix a broken link to the installation guide. This change improves the user experience and accessibility of the development documentation.

### <samp>🤖 Generated by Copilot at f4c8299</samp>

> _`installation guide`_
> _link was broken, now it works_
> _users are happy_

### <samp>🤖 Generated by Copilot at f4c8299</samp>

* Updated the installation guide link in `README.md` to fix a broken link ([link](https://github.com/pimcore/pimcore/pull/15188/files?diff=unified&w=0#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L94-R94))

### CODE REVIEW

**Comment by dvesh3** [comment]
@ibousfiha thanks for your contribution. could you please sign the CLA? so that we can merge the PR 😊

**Comment by jdreesen** [comment]
This should _not_ be merged. The link is already correct for `v11.x`. @ibousfiha changed it back to the old `v10.5` one.

**Comment by jdreesen** [comment]
Also, it's a duplicate of #14973

**Comment by dvesh3** [comment]
@jdreesen yes, right. thanks the notice! please see https://github.com/pimcore/pimcore/pull/14973#issuecomment-1537910128

**Pull request closed without merging**
