### PR TITLE
[Improvement] Adding functionality to create preview images on InDesign Files

### PR DESCRIPTION
**Pull request by Alanin**
## Changes in this pull request  
Adding functionality to render preview images from InDesign (indd) Files.

### CODE REVIEW

**Comment by brusch** [comment]
@Alanin Thanks a lot for your PR, however, since this is an improvement, can you please rebase your PR onto `11.x`?

**Comment by Alanin** [comment]
@brusch i had to create a new PR https://github.com/pimcore/pimcore/pull/13319

Another Question: even its something "new", would it be possible to merge that code to the 10.5 as well? we need that feature for a customer right now and not in about 6 months...

**Comment by brusch** [comment]
@Alanin unfortunately not, `10.5` is only for bug-fixes - I'm sorry, but that's how versioning works - at some point we need to mark a version as feature complete, otherwise we're getting into a merging madness 😊 
You could use something like https://github.com/cweagans/composer-patches to pull the changes into your instance.

**Comment by mcop1** [comment]
Closed in favor of https://github.com/pimcore/pimcore/pull/13319

**Pull request closed without merging**
