### PR TITLE
[Task]: Disallow php-http/discovery plug in

### PR DESCRIPTION
**Pull request by mcop1**
See failing tests, e.g. https://github.com/pimcore/pimcore/actions/runs/4161678073/jobs/7203127248

Pr for 10.5 -> https://github.com/pimcore/pimcore/pull/14314

### CODE REVIEW

**Comment by jdreesen** [comment]
> Needs to be disabled **until a new version of composer gets released**.

What does it have to do with a new composer version?

**Comment by mcop1** [comment]
> > Needs to be disabled **until a new version of composer gets released**.
> 
> What does it have to do with a new composer version?

I added some links to the description. Basically the new composer version adds the possibility to mark plug-ins as optional. Optional plugins then shouldn´t cause this errors anymore (in non-interactive mode).

**Comment by blankse** [comment]
@mcop1 Shouldn't we also disallow the plugin in the 10.5 branch?

**Comment by mcop1** [comment]
> @mcop1 Shouldn't we also disallow the plugin in the 10.5 branch?

I was thinking about that too, but the branch doesn´t seem to be affected, at least when I take a look at the last pull requests that were created. On the other hand it wouldn´t hurt anyone, I guess.

**Comment by blankse** [comment]
Maybe because the new version of composer is already released? I think also it wouldn't hurt.

**Comment by jdreesen** [comment]
> I added some links to the description.

The linked issues are already released: [2.5.3](https://github.com/composer/composer/releases/tag/2.5.3), [2.2.20](https://github.com/composer/composer/releases/tag/2.2.20)

**Comment by mcop1** [comment]
> > I added some links to the description.
> 
> The linked issues are already released: [2.5.3](https://github.com/composer/composer/releases/tag/2.5.3), [2.2.20](https://github.com/composer/composer/releases/tag/2.2.20)

The first one yes, but second one is missing, as far as I can see.

**Pull request closed without merging**
