### PR TITLE
Remove redundant layout expansions in GRID config

### PR DESCRIPTION
**Pull request by skoch98**
See https://github.com/pimcore/admin-ui-classic-bundle/pull/293#issue-1913221698

FYI: @brusch  @fashxp @skochTC

### CODE REVIEW

**Comment by dev-pim** [comment]
Hello! Great improvement
However, have you tried the method that I indicated in the comment from the related topic?
https://github.com/pimcore/pimcore/issues/12465#issuecomment-1520945714

Set **bufferedRender** to **true** in https://github.com/pimcore/pimcore/blob/f39ea979c2c5bc460c59703e3b61a0d03697ce65/bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/classTree.js#L94

With your changes I get an increase in speed
24.7 seconds => 2.1 seconds
With changing **bufferedRender** to **true** it's a little better
24.7 seconds => 1.1 seconds
At the same time, the nodes remain expanded

Could you, with your expertise, check the option with **bufferedRender: true**, maybe it will be possible to **return this.expand();** and get a greater increase in performance
[https://github.com/pimcore/pimcore/pull/16007/commits/f39ea979c2c5bc460c59703e3b61a0d03697ce65#diff-ac637775f79f55cd116eff06ef361578e91e4f299b7099754cfb153b 3ac88bc8L228](https://github.com/pimcore/pimcore/commit/f39ea979c2c5bc460c59703e3b61a0d03697ce65#diff-ac637775f79f55cd116eff06ef361578e91e4f299b7099754cfb153b3ac88bc8L228)

**Comment by dev-pim** [comment]
According to my tests, the line with [baseNode.expand(true)](https://github.com/pimcore/pimcore/commit/f39ea979c2c5bc460c59703e3b61a0d03697ce65#diff-ac637775f79f55cd116eff06ef361578e91e4f299b7099754cfb153b3ac88bc8R164) does not give any speed increase.
Only deleting rows using [this.expand()](https://github.com/pimcore/pimcore/commit/f39ea979c2c5bc460c59703e3b61a0d03697ce65#diff-ac637775f79f55cd116eff06ef361578e91e4f299b7099754cfb153b3ac88bc8L228) has an effect

**Comment by dev-pim** [comment]
If we use **bufferedRender: true** and **remove this.expand()** we get a little more performance

only **removing this.expand()**
24.7 seconds => 2.1 seconds

only **bufferedRender: true**
24.7 seconds => 1.1 seconds

**bufferedRender: true** + **this.expand()**
24.7 seconds => 0.9 seconds
But in this case, the nodes remain collapse and will have to be expande manually, which, it seems to me, may not be entirely convenient for those who are used to seeing them expanded

**Comment by skoch-twocream** [comment]
> If we use **bufferedRender: true** and **remove this.expand()** we get a little more performance
> 
> only **removing this.expand()** 24.7 seconds => 2.1 seconds
> 
> only **bufferedRender: true** 24.7 seconds => 1.1 seconds
> 
> **bufferedRender: true** + **this.expand()** 24.7 seconds => 0.9 seconds But in this case, the nodes remain collapse and will have to be expande manually, which, it seems to me, may not be entirely convenient for those who are used to seeing them expanded

Hi @dev-pim, thanks for you note. If you see any improvements fell free to extend my changes.

My changes was already merged for Pimcore >=X, see https://github.com/pimcore/admin-ui-classic-bundle/pull/293#issue-1913221698

We did a lot of mersuremtns and for us we was able to reduce the client "overheat" down to this:
> In my test case, I was able to reduce the wait time from an average of 30,619s to 1,434s.

Just by ading a true to the `baseNode.expand();` and remove the redundant call

BR, Sebastian

**Comment by kingjia90** [comment]
Thank you for the PR, but unfortunately i have to close it because it''s for`10.6` and it is already EOL

**Comment by herbertroth** [comment]
Fixed in LTS version.

**Pull request closed without merging**
