### PR TITLE
Fixed: programmatically setting children of type "variant" will not be loaded when calling getChildren([AbstractObject::OBJECT_TYPE_VARIANT])

### PR DESCRIPTION
**Pull request by mcuenez**
## Description
When programmatically creating an object and its variants then setting the variants via `setChildren($variants)` will result in unexpected behaviour when trying to call `getChildren([AbstractObject::OBJECT_TYPE_VARIANT])`, if the object/variants is/are never saved.

## Expected Behaviour
Whenever the method `setChildren` is called, I'd expect it to return the same children when calling `getChildren`.

## Actual Behaviour
When calling `getChildren([AbstractObject::OBJECT_TYPE_VARIANT])`, the returned array is empty.

## Example Code
```php
$product = new Product();
$product->setChildren($variants);
p_r($product->getChildren([AbstractObject::OBJECT_TYPE_VARIANT]));
```

## The Problem
Setting the children works differently than getting the children when it comes to building the cache key.
In the method `getChildren` one automatically defines the cache key with the passed arguments:

```php
$cacheKey = $this->getListingCacheKey(func_get_args());
```
However, in the method `setChildren`, the cache key is always the same:

```php
$cacheKey = $this->getListingCacheKey();
```

## The Solution
Building the cache key the same way as `getChildren` does, will resolve this issue:
```php
public function setChildren($children, array $objectTypes = [self::OBJECT_TYPE_OBJECT, self::OBJECT_TYPE_FOLDER], $includingUnpublished = false)
    {
        if ($children === null) {
            // unset all cached children
            $this->o_children = [];
            $this->o_hasChildren = [];
        } elseif (is_array($children)) {
            //default cache key
            $cacheKey = $this->getListingCacheKey([$objectTypes, $includingUnpublished]);
            $this->o_children[$cacheKey] = $children;
            $this->o_hasChildren[$cacheKey] = (bool) count($children);
        }

        return $this;
    }
```

Now, when setting variants using `setChildren($variants, [AbstractObject::OBJECT_TYPE_VARIANT])` it is possible to retrieve the same variants using `getChildren([AbstractObject::OBJECT_TYPE_VARIANT])`.

### CODE REVIEW

**Comment by brusch** [comment]
We should add a note to the upgrade notes that the method signature changed.

**Comment by brusch** [comment]
Should go into the 6.8 release as there's a very little chance that it breaks existing code (if `AbstractObject` was extended and `setChildren()` overridden, what is very unlikely but still possible).

**Comment by dvesh3** [comment]
@mcuenez please see requested changes ;) thanks!

**Comment by mcuenez** [comment]
see #7125

**Comment by brusch** [comment]
`master` branch was fine as this patch should go into `6.8`, just the docs were missing, but now this PR is fine to be merged, just waiting for Travis to finish the jobs 😊

**Comment by dvesh3** [comment]
thanks a lot!

**Pull request merged**
