### PR TITLE
New feature: Added thumbnail download option

### PR DESCRIPTION
**Pull request by adrozdek**
Thumbnail Download option in asset's view:
thumbnail-download

There will be an error message: "No thumbnail selected" if thumbnail was not selected.

### CODE REVIEW

**Comment by brusch** [comment]
Good idea! But maybe we should introduce a new option on the thumbnail definition, that causes the thumbnail to be listed in this new download selection. Because there are projects with over a hundred thumbnail definitions, and then this functionality gets quite confusing :) 

What do you think? 

image

**Comment by adrozdek** [comment]
I think it's a good idea :) I will add this checkbox tomorrow or in a few days.

**Comment by brusch** [comment]
I'd also move this box between _Download_ and _Custom Download_

**Comment by adrozdek** [comment]
Okay

**Comment by adrozdek** [comment]
@brusch I pushed these changes. Could you check again? :)

**Comment by brusch** [comment]
Thanks!

**Pull request merged**
