### PR TITLE
[DataObject] Fix: Checkbox/Link/Slider/Datetime label width is not respected

### PR DESCRIPTION
**Pull request by blankse**

### CODE REVIEW

**Comment by dvesh3** [comment]
for me it works when i set label width on panel
image

**Comment by blankse** [comment]
@dvesh3 Yes direct in panel it works. The edit helper fill this option than.

It doesn't work in localizedfields.

**Comment by dvesh3** [comment]
@blankse ok, I understand the problem. So then we also need to fix other types using `FieldContainer` like slider, datetime.

**Comment by blankse** [comment]
@dvesh3 I added the fix to slider, datetime. The other fields with FieldContainer should respect the labelWidth option already

**Comment by dvesh3** [comment]
thank you very much 🙏

**Pull request merged**
