### PR TITLE
[Travis] Add tests with lowest dependencies & changed zend-* packages to laminas

### PR DESCRIPTION
**Pull request by blankse**
I think it would be good to test with lowest dependencies. Than we can see when a class is used, which is added in a newer version as defined in composer.json

Also removed old symfony 3 tests, load only symfony as source and use composer 2 to reduce the test duration.

### CODE REVIEW

**Comment by brusch** [comment]
Fixes #6187

**Comment by brusch** [comment]
Very nice, thanks a lot! (Composer 2 is just great, tests are twice as fast now 🎉)

**Comment by blankse** [comment]
@brusch Yes and only symfony as source should also be faster ;)

**Comment by brusch** [comment]
But prefer source was there before as well, or was it ignored for a reason?

**Comment by blankse** [comment]
@brusch I removed it and add only source for symfony (see config section in composer.json [root only]). source is slower than dist.

**Pull request merged**
