### PR TITLE
[Docs] Use map for static page config in nginx

### PR DESCRIPTION
**Pull request by jdreesen**
See: pimcore/skeleton#100
Followup of #9447 and #11211

### CODE REVIEW

**Comment by dvesh3** [comment]
@jdreesen can we also add it to the 10.5 upgrade notes to update the NGINX config?

**Comment by jdreesen** [comment]
Well, the old one should still work, but I can add it to the upgrade notes if you want.

**Comment by dvesh3** [comment]
> Well, the old one should still work, but I can add it to the upgrade notes if you want.

yes, I mean adding a recommendation 😉

**Comment by dvesh3** [comment]
@jdreesen could you please update it? thanks!

**Comment by jdreesen** [comment]
I added something, is that okay?

**Comment by dvesh3** [comment]
> I added something, is that okay?

yes, looks good. thanks! 🙏

**Pull request merged**
