### PR TITLE
Use proper binary KiB, MiB, ... for base 2 numbering in formatBytes()

### PR DESCRIPTION
**Pull request by NiklasBr**
See https://en.wikipedia.org/wiki/Kibibyte

### CODE REVIEW

**Comment by NiklasBr** [comment]
Of course. That's because they use base 10 = MB/GB and not base 2 = MB/GiB. :)

**Comment by brusch** [comment]
@NiklasBr that's actually not right, see
image (Win 10)

**Comment by NiklasBr** [comment]
Apple has done it for 9 years now: https://www.apple.com/shop/question/answers/readonly/what-does-tb-mean-when-compared-to-gb/QXD9XA7YJ74X9XJJ2

**Comment by NiklasBr** [comment]
Dropbox uses base 10: https://www.quora.com/Why-does-Dropbox-use-base-10-instead-of-base-2-for-storage-e-g-I-got-an-email-asking-to-upgrade-to-1-TB-and-they-provided-the-conversion-as-being-equal-to-1000-GB-instead-of-1024-GB

**Comment by NiklasBr** [comment]
HP uses base 10: https://support.hp.com/gb-en/document/c01179504

**Comment by brusch** [comment]
Oh dear ... then let's use base 10 ...

**Comment by NiklasBr** [comment]
Bash uses base ten: From the man page: "If base# is omitted, then base 10 is used"

**Comment by brusch** [comment]
follow up, see  #3889

**Pull request closed without merging**
