### PR TITLE
Fixes Unique constraint violation on UrlSlugs

### PR DESCRIPTION
**Pull request by NiklasBr**
## Changes in this pull request  
Upon saving a *product variant* this would throw an error even if it was actually unique: `Unique constraint violated. Slug already used by object` which resolved the issue

### CODE REVIEW

**Comment by NiklasBr** [comment]
> Test redis DB is not configured 

Not related to these changes, right?

**Comment by dvesh3** [comment]
@NiklasBr Redis tests are skipped. There are 3 failed tests related to slug change https://github.com/pimcore/pimcore/runs/1968991517#step:11:3777

**Comment by NiklasBr** [comment]
We should allow an object to update its own slug, so this need to change then.

**Comment by NiklasBr** [comment]
I don't have time to understand and fix the failing Tests right now. Closing.

**Pull request closed without merging**
