### PR TITLE
add ability to generate public frontend path even in console

### PR DESCRIPTION
**Pull request by dasraab**
This PR gives you the option to get the public image thumbnail path with included frontend_prefixes even when you are in a console command. 

Resolves #12326

### CODE REVIEW

**Comment by kingjia90** [comment]
@dasraab a gentle reminder to sign the CLA

**Comment by brusch** [comment]
This should be already covered by https://github.com/pimcore/pimcore/pull/12657
Thanks anyway 😊

**Comment by dasraab** [comment]
@brusch its not because you won't ever get the frontend path with frontend_prefixes in a console command. 

See [here](https://github.com/aashan10/pimcore/blob/ccb97544263c5d30ecab7daa4dad255cf27f84bf/models/Asset/Thumbnail/ImageThumbnailTrait.php#L319)

**Comment by brusch** [comment]
@dasraab then we should fix `getFrontendPath()` to return the right value, I'd say 😊Can you create another PR for that?

**Comment by dasraab** [comment]
@brusch that's what i planned to do in the first place but sadly this [line](https://github.com/pimcore/pimcore/blob/0984d48c8f629fedfab0f560f8ad37d6ab0de819/models/Asset/Thumbnail/ImageThumbnailTrait.php#L328) in convertToWebPath() is preventing the generation of frontend_paths with frontend_prefixes for console commands (it works fine as long its called via browser request)

i would love to submit a pr but right now i don't see a way of fixing this without also modifying getPath() and convertToWebPath()...

if you give me a hint on how you would like to have this fixed i'll give my very best to submit a PR

**Comment by dasraab** [comment]
@brusch i gave it another try #12895

**Pull request closed without merging**
