### PR TITLE
[Documents] Image editable - fix missing alt & title in frontend

### PR DESCRIPTION
**Pull request by ramundomario**
## Changes in this pull request  
Regression of #7661

## Steps to reproduce 

- Set alt value in editmode for image editable 
- Alt & title attributes are empty when image is displayed in frontend

### CODE REVIEW

**Comment by dvesh3** [comment]
Sorry, not able to reproduce the issue. please pass image attributes as below:
```twig
{{ pimcore_image('pimcore-image',
    {
        thumbnail: 'content',
        imgAttributes: {
            title: 'title text',
            alt: 'alt text'
        }
    }) }}
```

**Comment by ramundomario** [comment]
@dvesh3 
Issue refers to the value entered in editmode which should be printed by default if it is not specified when printing the editable:
`{{ pimcore_image('pimcore-image') }}`

Please see this example reproduced on demo:
Oc5pE5pgzX

**Comment by dvesh3** [comment]
@ramundomario sorry, misunderstood the steps. It makes sense 👍

**Comment by ramundomario** [comment]
@dvesh3 
Don't worry :+1: 
BTW: We should also handle alt and title passed via code as in your example.
Who should take precedence? The value entered in editmode or the one in the code?

**Comment by dvesh3** [comment]
> BTW: We should also handle alt and title passed via code as in your example.
> Who` should take precedence? The value entered in editmode or the one in the code?

yes, true. I would say editmode takes the precedence since it is set by document author and the one defined in the code is used as a fallback.

**Comment by ramundomario** [comment]
> > BTW: We should also handle alt and title passed via code as in your example.
> > Who` should take precedence? The value entered in editmode or the one in the code?
> 
> yes, true. I would say editmode takes the precedence since it is set by document author and the one defined in the code is used as a fallback.

Updated as discussed!
_Note_: used `!empty(...)` instead `??` since alt & text from editmode are empty string instead `null`.

**Comment by dvesh3** [comment]
@ramundomario thanks a lot!

**Pull request merged**
