### PR TITLE
Fix to avoid inverting colour icons

### LINKED ISSUE #6553: Admin CSS icon inversion not compatible with colours
### Expected behavior

Colours should not be inverted when a view is expanded.

### Actual behavior

Colours are inverted, due to the class `.pimcore_icon_material` being applied to icons which are not material design-esque:

https://github.com/pimcore/pimcore/blob/afc26e512d96a504dc477ae9898576e766b14e6f/bundles/AdminBundle/Resources/public/js/pimcore/startup.js#L769

https://github.com/pimcore/pimcore/blob/2cfeca2ee1fdc3a2e9d2ab4b2f7763e2e8570930/bundles/AdminBundle/Resources/public/css/admin.css#L1849-L1852

### Steps to reproduce

Add a colour icon to a custom view. Result:

Screen Shot 2020-06-09 at 12 46 31

### PR DESCRIPTION
**Pull request by NiklasBr**
Should only invert white flat icons.

Resolves #6553

### CODE REVIEW

**Comment by dvesh3** [comment]
@NiklasBr please change the base to 6.6(latest release branch) as it is a fix. thanks! [updated guidelines](https://github.com/pimcore/pimcore/blob/master/CONTRIBUTING.md#contributing-pull-requests) 😉

**Comment by NiklasBr** [comment]
That didn't work @dvesh3 ;)

**Comment by brusch** [comment]
@NiklasBr probably easier to rebase your branch on `6.6` then apply the patch. As it is now, with all the additional commits,  we can't merge the PR.

**Comment by jdreesen** [comment]
Yes, a rebase is needed.

**Pull request merged**
