### PR TITLE
[Email] Consider multiple recipients and email name annotation 'NAME <name@email.com>'

### PR DESCRIPTION
**Pull request by ultramegatom**
send test email consider multiple recipients and email name annotation `NAME <name@email.com>`

### CODE REVIEW

**Comment by brusch** [comment]
We have the same functionality already here: 
https://github.com/pimcore/pimcore/blob/f70577a6366ab57a660750bcd7f599bcc9cbfdd3/lib/Mail.php#L528 

So i guess we should unify that by using the newly introduced function, to avoid duplicate code. 
Can you just quickly fix that? 

Thanks a lot!

**Comment by ultramegatom** [comment]
> We have the same functionality already here:
> [pimcore/lib/Mail.php](https://github.com/pimcore/pimcore/blob/f70577a6366ab57a660750bcd7f599bcc9cbfdd3/lib/Mail.php#L528)
> 
> Line 528 in [f70577a](/pimcore/pimcore/commit/f70577a6366ab57a660750bcd7f599bcc9cbfdd3)
> 
>              if (!empty($fromArray)) { 
> So i guess we should unify that by using the newly introduced function, to avoid duplicate code.
> Can you just quickly fix that?
> 
> Thanks a lot!

yes sure can do.

should we also remove the get(From|To|ReplyTo) methods from the models? e.g. https://github.com/pimcore/pimcore/blob/8b04bd00a02e7f138aaeedf58ba4c5425a4333f1/models/Document/Email.php#L208

And refactor the usages in lib\Email ? As far as i can tell the only usages are there.

**Comment by ultramegatom** [comment]
@brusch updated

I also found something similar in the 'email log': 
https://github.com/pimcore/pimcore/blob/master/models/Tool/Email/Log.php#L661

The Email Addresses are however formated like: ```mail@mail.com (Name)```

Should we refactor this to? I think we would have to change all current 'email logs' in the database within an update script.

**Comment by brusch** [comment]
@ultramegatom yep, that would be definitely nice in my opinion!

**Comment by ultramegatom** [comment]
@brusch i added a migration script. could you test if it works in your setup?

thx

**Comment by brusch** [comment]
@ultramegatom I'm afraid that you last push messed up your PR, it contains also commits from the master branch which were not merged properly, so that they show up as changes of this PR :(

**Comment by ultramegatom** [comment]
@brusch hmm strange. i merged with the master again - should be fine now

**Comment by brusch** [comment]
@ultramegatom that looks better ;)

**Comment by brusch** [comment]
Cherry-picked the log migration into #3743

**Pull request merged**
