### PR TITLE
Process Page count if does not exist or status is failed

### PR DESCRIPTION
**Pull request by mattamon**
## Changes in this pull request  
`document_page_count` will now be processed if it does not exist or is failed.
## Additional info  
Before it was only processed if it was at least processed once

### CODE REVIEW

**Comment by Corepex** [comment]
checkable after https://github.com/pimcore/pimcore/pull/14630 is merged (and merged into 11.x)

**Comment by fashxp** [comment]
We need to bei careful not to create endless loops here.
When it failed for a reason and is recalculated, it probably will fail again and again ... making server very busy.
Is that covered?

**Comment by mattamon** [comment]
> We need to bei careful not to create endless loops here. When it failed for a reason and is recalculated, it probably will fail again and again ... making server very busy. Is that covered?

It will only be calculated in the ReindexCommand right? When would it cause an endless loop?

**Comment by blankse** [comment]
@mattamon Wrong, the method `processPageCount()` is also called in `AssetUpdateTasksHandler` and this is called when you try to generate a thumbnail (and this is also in the backend I guess).

We had a endless loop with 10.5.18, because Libreoffice couldn't generate the PDF from DOC file. We could fix the Libreoffice (missing libreoffice-filters package), but it would be good to handle a dependency error. Maybe we can cache it and can clear this cache when the dependency is fixed.

**Comment by blankse** [comment]
@mattamon @fashxp I think this was a regression from https://github.com/pimcore/pimcore/pull/14349
The endless loop was fixed by https://github.com/pimcore/pimcore/commit/e47bbb965e7048bf705a06684ae4992894b78fcd

**Comment by mattamon** [comment]
@blankse ah! Thank you for the update. 
Then we need to fix this in 10.5.20 and we could actually close this PR then.

**Comment by mattamon** [comment]
Closing because of potential endless loop

**Comment by fashxp** [comment]
@blankse thank you very much for checking 😍
@mattamon is there a followup Task somewhere?

**Comment by mattamon** [comment]
@fashxp not yet, but I will create one asap.

**Comment by fashxp** [comment]
see https://github.com/pimcore/pimcore/issues/14686

**Pull request closed without merging**
