### PR TITLE
Removes references to getBricks() as it does not exist

### PR DESCRIPTION
**Pull request by NiklasBr**
## Additional info  

Not 100% sure this is correct, but it aligns better with what works in my environment at least :) 

`Call to undefined method getBricks in class Model\DataObject\Category`

### CODE REVIEW

**Comment by brusch** [comment]
I think the docs are correct, but maybe the name for the bricks field (`bricks` so that the getter is named `getBricks()`) was not well decided 😊
So basically the class definition has a brick field called `bricks` and this brick field has a brick `tyre` assigned.

**Comment by NiklasBr** [comment]
Aha! I'll see if I can clarify it better :)

**Comment by brusch** [comment]
@NiklasBr 🏓Would be nice to have this out of the way - Thanks a lot! 😉

**Comment by NiklasBr** [comment]
Not a lot of time this week to finish it, sorry

**Comment by brusch** [comment]
Closed due to inactivity. Please feel free to continue the discussion or provide the missing information on this PR, we'll then reopen it if necessary. Thanks a lot!

**Pull request closed without merging**
