### PR TITLE
Update CustomReportController.php

### PR DESCRIPTION
**Pull request by milesimarco**
## Changes in this pull request  
Resolves #

Status: 500 | Internal Server Error
URL: /admin/reports/custom-report/get
Message: Call to a member function getObjectVars() on null

Trace: 
in /pimcore/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Reports/CustomReportController.php:164
#0 /pimcore/vendor/symfony/http-kernel/HttpKernel.php(156): Pimcore\Bundle\AdminBundle\Controller\Reports\CustomReportController->getAction()
#1 /pimcore/vendor/symfony/http-kernel/HttpKernel.php(78): Symfony\Component\HttpKernel\HttpKernel->handleRaw()
#2 /pimcore/vendor/symfony/http-kernel/Kernel.php(199): Symfony\Component\HttpKernel\HttpKernel->handle()
#3 /pimcore/public/index.php(35): Symfony\Component\HttpKernel\Kernel->handle()
#4 {main}

### CODE REVIEW

**Comment by dvesh3** [comment]
@milesimarco thanks for your PR! Since this is considered as a bugfix, could you please rebase it on branch 10.2? thanks!

**Comment by dvesh3** [comment]
🏓 @milesimarco

**Comment by milesimarco** [comment]
👌 @dvesh3 
Thanks!

**Comment by dvesh3** [comment]
@milesimarco Hi, changing target base on Github is not enough, as now you have unrelated commits in the PR. Please rebase your commits on branch 10.2 and force push. thanks!

**Comment by dvesh3** [comment]
Closed in favor of #10945

**Pull request closed without merging**
