### PR TITLE
Bug fix - allow export to contain duplicate columns

### LINKED ISSUE #11493: [Bug]: colums missing in CSV Export from GRID with multiple operators of the same type
### Expected behavior

When exporting a CSV from the grid I would expect to get a file with all the columns that are shown in Pimcore.
This should also be the case, when I use the same operator/formatter multiple times.

No columns should be missing.

### Actual behavior

Currently when you use the same operator/formatter multiple times, the csv export removes all of them except the first one.
This is the case, when you use the grid options to define your columns and use the same type multiple times.

It seems to be the case with all operators, where you can not explicitly set a name for the column head.
The export removes duplicate column-names.

### Steps to reproduce

1. Open a grid view for data objects
2. Set Grid Options with operators of the same type
image

2a) Grid View is fine
image

3. Export the CSV File -> colum missing
image

### PR DESCRIPTION
**Pull request by torqdev**
## Changes in this pull request  
Resolves #11493

### CODE REVIEW

**Comment by dvesh3** [comment]
@torqdev please rebase it on 10.5 branch, since this is a fix. thanks!

**Comment by torqdev** [comment]
Hi @dvesh3 - we were going with `10.6` because of this line https://github.com/pimcore/pimcore/blob/bf8d956c5e7ab85ee85ea79a59348c58625d53d6/CONTRIBUTING.md?plain=1#L11 in `CONTRIBUTING.md` - please advise

**Comment by robertSt7** [comment]
> please advise

@torqdev  Thanks for pointing that out, we'll change that right away. The correct branch for bug fixes is 10.5 at the moment

**Comment by torqdev** [comment]
Hi @dvesh3 - we've updated to use base `10.5`.

**Comment by dvesh3** [comment]
@torqdev thanks! we'll review the changes soon 😉

**Comment by robertSt7** [comment]
@torqdev Thanks

**Comment by mcop1** [comment]
Unfortunately we decided to revert the changes of this pr, because it affects several other bundles, see  #14009

**Pull request merged**
