### PR TITLE
[DataObject] Edit form: Possibility of CSS Values for widths/heights

### PR DESCRIPTION
**Pull request by blankse**
Follow up to #6880

### CODE REVIEW

**Comment by blankse** [comment]
@weisswurstkanone I add the numeric check/cast to the setWidth/setLabelWidth methods.

**Comment by weisswurstkanone** [comment]
Assigned milestone 7 because then we get testing for free

**Comment by weisswurstkanone** [comment]
@blankse  Humble question: is there a specific reason why the "height" is not covered in the same way? Would be a nice addition I guess.

**Comment by blankse** [comment]
@weisswurstkanone I saw no need for percentage heights but I can also change it in the same way.

**Comment by weisswurstkanone** [comment]
great, thanks!

**Comment by blankse** [comment]
I rebased, because of #6880 merge

**Comment by weisswurstkanone** [comment]
@blankse could you please check the tests ?

**Comment by blankse** [comment]
@weisswurstkanone I merged the master again. Now the tests are green :)

**Comment by weisswurstkanone** [comment]
Merci!

**Comment by dvesh3** [comment]
thanks a lot @blankse!

**Pull request merged**
