### PR TITLE
Fix: Copying an object with mandatory and unique field is not possible.

### PR DESCRIPTION
**Pull request by blankse**
See #5243

Steps to reproduce:
- Create a Class in the pimcore demo with only 1 input field (mandatory, unique)
- Create a object
- Copy this object
- Error when paste:
image

### CODE REVIEW

**Comment by dvesh3** [comment]
I can reproduce the issue but the question is, why it is required to set **omitMandatory** check when publish status is **false**. It should not be checked by default when just saving the object. @blankse do you know the reason?

**Comment by dvesh3** [comment]
@blankse or this already fixes the issue https://github.com/pimcore/pimcore/pull/6769? can you please try on master

**Comment by blankse** [comment]
@dvesh3 Yes, in master branch it works. Can we backport #6769 to 6.6 branch?

**Comment by brusch** [comment]
@blankse unfortunately we can't backport #6769 because it changes the behavior, so we agreed to NOT do this change in a bug-fix release.

**Comment by dvesh3** [comment]
already fixed in #6769

**Pull request closed without merging**
