### PR TITLE
allow object passthrough inpost/pre object hooks

### PR DESCRIPTION
**Pull request by solverat**

### CODE REVIEW

**Comment by weisswurstkanone** [comment]
thanks!

**Comment by weisswurstkanone** [comment]
Oops, sorry, this was an accident. Reverted that change. 
However, this is a topic for assets and documents as well (eg. postSaveAsset). Wondering if we shouldn't refactor the whole stuff as "this" (the edit mask) isn't available in other contexts. Maybe we should go for a "options" object where at least the id is available.

**Comment by solverat** [comment]
the thing is, documents also passes the whole object:
```pimcore.plugin.broker.fireEvent("postSaveDocument", this, this.getType(), task, only);```

i think it's pretty useful to pass the object so other plugins may able to collaborate with it, don't you think?.

**Comment by weisswurstkanone** [comment]
I agree, I am just tending in the direction that only a single "params" object should be passed, with mandatory and optional attributes. Something like
fireEvent("postSave",    // instead of "postSaveDocument"
{
type: "document", //mandatory
id: 123, // mandatory
editor: this // optional, as not always available
...
}

**Pull request merged**
