### PR TITLE
[Asset] Support for all/custom media-queries in thumbnails

### LINKED ISSUE #5201: Image Thumbnails - Media Queries for min-width breakpoints
Image Thumbnails don't follow the mobile first concepts by providing only max-width media queries.
It should be possible to set up min-width media queries for thumbnails too (or in my opinion, technically it should be only the min-width - way to define media queries for thumbnails, but this will obviously break existing ones)

Currently you always have to set the largest variant of the image as default and then create media query variants for smaller devices. The mobile-first approach would be more to first define the smallest thumbnail as default and then create media querys for larger sizes.

Currently it is a bit weird concerning the mobile-first approach: You just start to code your mobile template but have to create a thumbnail definition with at least a large default and a media query size for mobile. You cannot start by setting the default to the small size and later add a larger media query when you develop the desktop template.
Even worse would be if you initially create the mobile size as default and later on add larger sizes. You develop the mobile template and are finished some time. Then you continue to the desktop version: You add a media query size and without knowing the previously defined default size will not be used anymore for small devices because of the max-width approach.

### PR DESCRIPTION
**Pull request by brusch**
Resolves #5201

In the past only `max-width` media queries were supported, now any media query can be defined. 

image

### CODE REVIEW

**Comment by julmot** [comment]
@brusch @weisswurstkanone Please note: In this PR in the DataHub repository we've integrated Pimcore's srcset functionality into DataHub: https://github.com/pimcore/data-hub/pull/177. Changes in the Pimcore API may have an direct impact to this API, as it was in this case.

I was debugging our application and found out that the `descriptor` in this PR was no longer `768px` but `(max-width: 768px)`.

Unfortunately the change in this PR was merged with a minor version, instead of a major version, even though it's a breaking change. Most probably you haven't noticed yet, but please see this as an example why we urgently need to follow [semantic versioning](https://github.com/pimcore/pimcore/issues/4647). Also a reason is that Pimcore doesn't have a [changelog](https://github.com/pimcore/pimcore/releases), there are no descriptions in the releases. If this would have been the case then we'd have noticed that.

In the meantime, until v7 is out and semantic versioning is being used, would it be possible to announce this somehow in the DataHub repository, when things change due to Pimcore updates?

**Comment by brusch** [comment]
I haven't seen this as a breaking change, because it was designed to be fully compatible, so I merged it. Imho this is really an edge case that could even happen when strictly using semver.

**Comment by julmot** [comment]
Not sure why this was classified as non breaking change. I know this PR includes a migration, but I don't think the question is "is a migration included?". It should rather be "Would it be possible that code of users depend on this certain thing directly and could it be that it breaks their code?". If the answer is yes, which it is in this case, it should be classified as breaking change. In this case this user is DataHub/Pimcore itself, but custom implementations on top of Pimcore are also valid use cases that should not be ignored in my opinion.

A quote from semantic versioning:

> If even the tiniest backwards incompatible changes to the public API require a major version bump, won’t I end up at version 42.0.0 very rapidly?

> This is a question of responsible development and foresight. Incompatible changes should not be introduced lightly to software that has a lot of dependent code. The cost that must be incurred to upgrade can be significant. Having to bump major versions to release incompatible changes means you’ll think through the impact of your changes, and evaluate the cost/benefit ratio involved.

I think if it can not be guaranteed that you follow semver it should at least be documented in the release description, otherwise there's no chance for us users to know what changed, without going to all of the git commits manually. If it's documented and we know you will not follow semver, we can stick to a hardcoded version and no longer use e.g. Caret Version Range for this repository.

**Comment by brankko** [comment]
The perfect opportunity to start with release notes :)

**Pull request merged**
