### PR TITLE
fix: config might be undefined

### PR DESCRIPTION
**Pull request by dkarlovi**
## Changes in this pull request  

If config is undefined, it will not raise a warning

```
      Warning: Undefined array key "error_pages" in vendor/pimcore/pimcore/bundles/CoreBundle/EventListener/ResponseExceptionListener.php line 190
```

### <samp>🤖 Generated by Copilot at a2f2f4a</samp>

Fix undefined index errors in `ResponseExceptionListener.php` when error document config is missing. This improves PHP 8 compatibility for the pimcore core bundle.

### <samp>🤖 Generated by Copilot at a2f2f4a</samp>

> _`??` operators_
> _avoid undefined indexes_
> _winter of errors_

### <samp>🤖 Generated by Copilot at a2f2f4a</samp>

*  Prevent undefined index errors when accessing error document paths from config by using null coalescing operators ([link](https://github.com/pimcore/pimcore/pull/15329/files?diff=unified&w=0#diff-1be9370a0c5dbeeedecc49569c3d3c29a3b7f973a364de15667fd94532b0411dL190-R191))

### CODE REVIEW

**Comment by dkarlovi** [comment]
I'm almost certain we've fixed this issue before? :thinking: 

Edit: we did in #13069, what happened in the meantime?

**Comment by dkarlovi** [comment]
CI failure unrelated.

**Comment by mattamon** [comment]
> I'm almost certain we've fixed this issue before? 🤔
> 
> Edit: we did in #13069, what happened in the meantime?

https://github.com/pimcore/pimcore/pull/14179 -> this PR changed it again but I am not sure why.

**Comment by dvesh3** [comment]
@dkarlovi thanks!

**Pull request merged**
