### PR TITLE
[Task] Optimized urlslug input

### PR DESCRIPTION
**Pull request by Corepex**

### CODE REVIEW

**Comment by NiklasBr** [comment]
This looks like an XSS fix on Pretty URL:s rather than an an optmization on URL Slugs?

**Comment by jdreesen** [comment]
"optimized" seems to be Pimcore's new "code" for security fixes, judging by the many PRs named "optimized" with similar code lately ;)

**Comment by Corepex** [comment]
@NiklasBr @jdreesen 

maybe your on to something 😋 🔍 

https://www.youtube.com/watch?v=eVTXPUF4Oz4

**Comment by NiklasBr** [comment]
@Corepex did you paste the wrong link?

**Comment by Corepex** [comment]
🎵 I tried so hard (to hide the security issue) and I got so far but in the end, it doesn't matter 😛

**Comment by NiklasBr** [comment]
I think it would be [better to be up-front](https://github.com/symfony/symfony/pull/49526), because that would mean we can send the [milestone link](https://github.com/pimcore/pimcore/milestone/190?closed=1) to account/product managers/customers and have them see that "there are not just bug fixes and some minor improvements, there are also security patches here". Even though many have some technical know-how they will never click och each change and inspect the code i detail to find the security patches.

**Comment by mattamon** [comment]
@NiklasBr please check our security policies. https://github.com/pimcore/pimcore/security/policy
We do create an advisory for every security fix when it is released: https://github.com/pimcore/pimcore/security/advisories

**Comment by NiklasBr** [comment]
I know.

But that's not my point.

My point is that it is obscure, and it is an anti-pattern which only makes it harder for regular customers for no apparent reason other than to be vague for the sake of being vague.

**Comment by NiklasBr** [comment]
>  We do create an advisory for every security fix when it is released: https://github.com/pimcore/pimcore/security/advisories

@mattamon why no security advisories published?

image

**Comment by mattamon** [comment]
@NiklasBr the new advisories are now published.

**Pull request merged**
