### PR TITLE
Typo in Pimcore word

### PR DESCRIPTION
**Pull request by vicefi**
## Changes in this pull request  
Resolves # Typo in Pimcore word

### CODE REVIEW

**Comment by brusch** [comment]
Thanks!

**Comment by jdreesen** [comment]
@CLAassistant is a bit late xD

**Comment by brusch** [comment]
Yep, but for one character not essential 😊
@vicefi however would be good if you can sign the CLA anyway. Thanks in advance

**Comment by vicefi** [comment]
It seems that I've did everything OK for now. It was not clear what I should sign. :)

**Pull request merged**
