### PR TITLE
fix: fixed checking variable if is array and array key exists

### PR DESCRIPTION
**Pull request by zoidbergx**
Resolves #

The convertBucketValues checks for subAggregationBuckets but it is not checking if we have at least an array and if the array key exists. This could lead to errors if the bucket data is only a single value

### CODE REVIEW

**Review by aryaantony92 — COMMENTED** [review]
@zoidbergx Thanks for the fix. The change looks good. But, we should also keep the is_array() check for $subAggregationBuckets['buckets']. Otherwise it could result in an error if $subAggregationBuckets['buckets'] is not an array since we are iterating over it.

**Comment by aryaantony92** [comment]
> @zoidbergx Thanks for the fix. The change looks good. But, we should also keep the is_array() check for $subAggregationBuckets['buckets']. Otherwise it could result in an error if $subAggregationBuckets['buckets'] is not an array since we are iterating over it.

@zoidbergx Just a gentle reminder

**Comment by zoidbergx** [comment]
@aryaantony92 should that not fail with the second check than:
```php
 array_key_exists('buckets', $subAggregationBuckets)
```
if the key does not exists it just returns the data or I'm wrong ?

**Comment by aryaantony92** [comment]
> @aryaantony92 should that not fail with the second check than:
> 
> ```
>  array_key_exists('buckets', $subAggregationBuckets)
> ```
> 
> if the key does not exists it just returns the data or I'm wrong ?

@zoidbergx Thanks for the reply. If the key doesn't exists, it just returns the data, that's true. But if key exists, shouldn't we check if $subAggregationBuckets['buckets'] is also an array ?

**Comment by zoidbergx** [comment]
@aryaantony92 yes you're right.
What dou you think about the latest change ? makes it a littel bit slimmer

**Comment by aryaantony92** [comment]
> @aryaantony92 yes you're right. What dou you think about the latest change ? makes it a littel bit slimmer

Thank you for the change. LGTM

**Comment by dvesh3** [comment]
@zoidbergx could you please provide a PR on https://github.com/pimcore/ecommerce-framework-bundle? so that we have the fix on latest version of the bundle. thanks!!

**Pull request merged**
