### PR TITLE
[Improvement]  Route AssetUpdateTasksMessage via pimcore_image_optimize transport

### LINKED ISSUE #11613: [Improvement] Route AssetUpdateTasksMessage via dedicated transport (pimcore_asset_update)
### Improvement description

so that more costly image/video processing can be prioritized accordingly

### PR DESCRIPTION
**Pull request by aryaantony92**
## Changes in this pull request  
Resolves #11613

### CODE REVIEW

**Comment by brusch** [comment]
@aryaantony92 can you please resolve the conflict? Thanks!

**Comment by aryaantony92** [comment]
@brusch Sure 👍

**Comment by brusch** [comment]
@aryaantony92 Imageoptimization is done by `\Pimcore\Messenger\Handler\OptimizeImageHandler` can you please fix that? Thanks 😊

**Comment by brusch** [comment]
Obsolete, we've decided to route this messages to a dedicated transport in Pimcore 11.

**Pull request closed without merging**
