### PR TITLE
Delete `Pimcore\Tool\Authentication::authenticateHttpBasic()`

### PR DESCRIPTION
**Pull request by jdreesen**
It seems like this method is not used in Pimcore itself (anymore?) so I propose to [deprecate it in Pimcore `10.6`](https://github.com/pimcore/pimcore/pull/14298) and remove it in Pimcore `11.0`.

### CODE REVIEW

**Comment by brusch** [comment]
Thanks! 👍

**Comment by jdreesen** [comment]
What about `Pimcore\Tool\Authentication::authenticatePlaintext()` https://github.com/pimcore/pimcore/blob/11.x/lib/Tool/Authentication.php#L32 ? 
It's also not used anymore. Should we remove it, too?

**Comment by brusch** [comment]
You're right, I'D kick that then too (first deprecate in `10.6`). Can you provide a PR? 😊

**Comment by jdreesen** [comment]
Will do.

**Comment by jdreesen** [comment]
See #14358 and #14359

**Pull request merged**
