### PR TITLE
Add AppBundle placeholder path

### PR DESCRIPTION
**Pull request by ckogler-elements**

### CODE REVIEW

**Comment by dpfaffenbauer** [comment]
you should refactor this and make this available through the container. adding a new path makes this now more complicated to refactor -> since it will be a BC break.

**Comment by dpfaffenbauer** [comment]
And, since you are touching this, also consider open tickets like:

https://github.com/pimcore/pimcore/issues/3242

**Comment by ckogler-elements** [comment]
@fashxp updated the docs.
@dpfaffenbauer : I think it makes  sence to add the AppBundle path as it would be the default location when you migrate from Pimocre 4 to 5.

**Comment by fashxp** [comment]
PRs are welcome ;-)
for now this is better than it was before, therefore we merge it. Thx.

**Pull request merged**
