### PR TITLE
#11144: adding cache invalidation for classification store KeyConfig

### PR DESCRIPTION
**Pull request by awroblewski**
Adding cache invalidation for Classification Store KeyConfiguration as per issue #11144.

### CODE REVIEW

**Comment by brusch** [comment]
@awroblewski Thank you very much for your PR! 
I think it would be good if we move the creation of the cache keys into a static method, so that we have the logic just in one place. Similar to what we do here: 
https://github.com/pimcore/pimcore/blob/beee7587a1757a73ca9565ac344423394288b95c/models/Asset/Image/Thumbnail/Config.php#L244

Additionally it would be necessary to rebase your PR onto `10.2` as this is a bug fix. 

Could you please update your PR accordingly? 
Thanks in advance!

**Comment by brusch** [comment]
@awroblewski ping 🏓😉

**Comment by awroblewski** [comment]
@brusch 

sorry for the delay

Sure, I'll rebase to 10.2 and implement the creation of the cache keys into a static method as you shown in the example.

**Comment by brusch** [comment]
@awroblewski cool, thanks! We'll release `10.2.9` today afternoon, if the PR is ready until then, it could be part of it 😉

**Comment by weisswurstkanone** [comment]
IMHO, this should be done for GroupConfig as well altough there is more or less no magic there. Thx!

**Comment by awroblewski** [comment]
HI,

unfortunately i messed up my forked repository of pimcore while doing the rebase. I had to remove it and fork again. Is it OK to create a new pull request on 10.2?

As I'm currently busy in a project, I'll be able to perfrom the changes monday next week. I guess it'll be 10.3 branch then?

Andreas

**Comment by weisswurstkanone** [comment]
Hi, yes, please take your time and we will be thankful to merge it!

**Comment by brusch** [comment]
@awroblewski it will be still branch `10.2` 😉

**Comment by brusch** [comment]
I'll close this PR then - looking forward for the new one 😊

**Comment by awroblewski** [comment]
@brusch Danke für die Info :)

**Pull request closed without merging**
