### PR TITLE
Let global actions in Workflows determine the subject saving

### PR DESCRIPTION
**Pull request by RickardAhlstedt**
## Changes in this pull request  
 - Made it possible to set saveSubject on global actions defined in workflows.
* Added getter for saveSubject-option in GlobalAction.php
* Updated WorkflowController.php to get the option 'saveSubject' from the current globalaction-event

### WHAT
The background for this PR is basically that we wanted a way to control if a global action should save the subject or not, since we're pulling updates from another dataobject into an unpublished version when a global action is triggered.  
This resulted in the published version receiving the same data as the unpublished new version, which we can't have since an e-com and other services rely on correct information in the published version.

### HOW
By allowing a new option in a global action (named `saveSubject`) that defaults to true, we can modify the behavior in WorkflowController.php:172 by fetching the option, and passing it to the Manager.php:289, thus being able to control the saving of the subject.

### FOOTNOTE
I tried to apply the same behavior for branch 11.x, but I was unable to find the WorkflowController, which usually resides in the AdminBundle in previous versions, and due to our reference-system being built on 10.6, I decided to make this code for 10.6
*Edit*: Found it here: https://github.com/pimcore/admin-ui-classic-bundle/blob/1.x/src/Controller/Admin/WorkflowController.php

### CODE REVIEW

**Comment by dvesh3** [comment]
Hi @RickardAhlstedt thank you for your contribution. 

We see this change as an improvement so would like to introduce it with next minor version `11.1` and there will be no next minor release for v10 since it is reaching it's EOL in August.

Could you please rebase your PR on 11.x branch and create a seperate PR for admin bundle changes [here](https://github.com/pimcore/admin-ui-classic-bundle/blob/1.x/src/Controller/Admin/WorkflowController.php)? thanks!

**Comment by RickardAhlstedt** [comment]
@dvesh3 please see issue #15447 for the 11.x and [#144](https://github.com/pimcore/admin-ui-classic-bundle/pull/144) for the admin-ui-classic-bundle

**Comment by dvesh3** [comment]
@RickardAhlstedt thanks for the quick action 👍

**Comment by dvesh3** [comment]
Closed in favor of #15447

**Pull request closed without merging**
