### PR TITLE
[Data objects] Open element when double-clicking relation item

### PR DESCRIPTION
**Pull request by BlackbitNeueMedien**
Originally I was annoyed of an advanced many-to-many relation with a lot of meta fields. When you want to open the related object you have to scroll to the complete right. This PR adds support for opening the related element via double-click.
To be consistent I also implemented this behaviour for all other relational types.

### CODE REVIEW

**Comment by weisswurstkanone** [comment]
what about reverseManyToManyObjectRelation ?

**Comment by BlackbitNeueMedien** [comment]
Have not tested but I thought it would work because `pimcore.object.tags.reverseManyToManyObjectRelation` extends `pimcore.object.tags.manyToManyObjectRelation`
Have you tested, @weisswurstkanone - does it really not work?

**Comment by brusch** [comment]
I'm just thinking ... since the handler function is always identical, should be move it to `pimcore.object.tags.abstractRelations` and just reference it on the implementations? 

e.g.
```js
listeners: {
    rowdblclick: this.gridRowDblClickHandler
}
```

Would save a lot of duplicate code.

**Comment by brusch** [comment]
Thanks!

**Pull request merged**
