### PR TITLE
[Session] Fix AdminSessionHandler write close in case of no main request

### LINKED ISSUE #11927: [Bug]: Authentication is closing session when its not supposed to
### Expected behavior

`Authentication::authenticateSession($request);` should find the current Admin User in the Session

### Actual behavior

`Authentication::authenticateSession($request);` finds the current user, but it uses `AdminSessionHandler::useSessionAttributeBag` which runs `writeClose` closing the current session and therefore hindering Symfony from sending the right newly, generated and migrated, session ID to the user since the session is actually closed.

### Steps to reproduce

Enabled Pimcore Targeting:

```
pimcore:
    targeting:
        enabled: false
```

And authenticate to a firewall. In my case it happens with CoreShop Tests: https://github.com/coreshop/CoreShop/pull/1970/files#diff-2f8cab0f04dcf2454dbe1699f7f35fd8d169952ad38ba6baee510b20bde8ef6cR5

### PR DESCRIPTION
**Pull request by dvesh3**
## Changes in this pull request  
Resolves #11927

### CODE REVIEW

**Comment by solverat** [comment]
@dvesh3 This won't work, because it would not close the session if no request is available.

This should work: 

```php

if (!$this->requestHelper->hasMainRequest()) {
    return true;
}

return $this->canWriteAndClose ??= $this->isAdminRequest($this->requestHelper->getMainRequest());

**Comment by dvesh3** [comment]
> @dvesh3 This won't work, because it would not close the session if no request is available.
> 
> This should work:
> 
> ```
> if (!$this->requestHelper->hasMainRequest()) {
>     return true;
> }
> 
> return $this->canWriteAndClose ??= $this->isAdminRequest($this->requestHelper->getMainRequest());
> ```

@solverat I'm wondering, how it loads session in first place, when request is not available 🤔 
image

**Comment by solverat** [comment]
That's why I suggested the "In a perfect World, the request should reach `AdminSessionHandler`  https://github.com/pimcore/pimcore/issues/11927#issuecomment-1320510099"

That's why I think that the method `shouldWriteAndClose` is quite dangerous. It should receive the original request (which also holds the initiated session, started in `Authentication::authenticateSession($request)`). Otherwise, we **can't be 100%** sure, that we're dealing with the right request object.

To answer your question: I'm not sure why this is happening, that's why I also attached the stack trace in the linked comment above. But it's also a fact, that functional tests (Symfony Module) are running into `Failed to start the session: already started by PHP.` because of this `There is no main request available` exception.

**Comment by dvesh3** [comment]
@solverat This is happening due to session service [fallback](https://github.com/pimcore/pimcore/blob/98f11e7f066e06ba8a5762e542475efa39b381a3/bundles/AdminBundle/Session/Handler/AdminSessionHandler.php#L97). I have now adapted the PR to return true if request is not available.

**Pull request merged**
