### PR TITLE
JS helper to format durations

### PR DESCRIPTION
**Pull request by NiklasBr**
## Changes in this pull request  
After and before:

image

### CODE REVIEW

**Comment by weisswurstkanone** [comment]
Hi @NiklasBr, I like the idea! 

But I fear that there will be localization issues. What do you think about this ISO standard?
https://en.wikipedia.org/wiki/ISO_8601

**Comment by NiklasBr** [comment]
@weisswurstkanone this is not a date format, but a [duration](https://en.wikipedia.org/wiki/ISO_8601#Durations), I mean yes we can show the format like `12H30M5S` but that seems too technical to me,

**Comment by brusch** [comment]
Why not just `01:45:51`? (`hh:mm:ss`) It's international and everyone knows what it means?

**Comment by NiklasBr** [comment]
Apparently both iTunes and WMP show durations on minutes without the leading "0" when it is a single digit, maybe I should copy that?
image

**Comment by brusch** [comment]
@NiklasBr yep, fine for me as well 😊 Thanks!

**Comment by NiklasBr** [comment]
image

**Comment by brusch** [comment]
Thanks a lot! 👍

**Pull request merged**
