### PR TITLE
Fix Asset\Service::copyContents()

### PR DESCRIPTION
**Pull request by blankse**
Fix the Asset\Service::copyContents() method. Element\Service::cloneMe() accept only objects with ElementInterface as parameter. The other copyContents() (Document/Object) also set the properties direct.
Splitting up from #11826

### CODE REVIEW

**Comment by dvesh3** [comment]
@blankse thanks!

**Comment by brusch** [comment]
Could be dangerous, as it keeps the references, right? 
Should we do at least a deep copy? Or maybe `array_map(... clone ...)`.

**Comment by blankse** [comment]
@brusch Yes this was also in my thoughts. But this must be fixed/changed in all 3 element types.

**Comment by dvesh3** [comment]
@brusch @blankse please see https://github.com/pimcore/pimcore/pull/11860

**Comment by dvesh3** [comment]
@brusch @blankse please see https://github.com/pimcore/pimcore/pull/11860

**Pull request merged**
