### PR TITLE
Fix max image size in image editor - No more limits

### PR DESCRIPTION
**Pull request by Yivan**
Hello,

This pull request resolve https://github.com/pimcore/pimcore/issues/3723

There is no more limits of 3000x3000.
Test on image resolution of less 3000x3000 and more than 3000, saving it on the image editor preserve original image size.
Resizing up the image work well too.

Thanks

### CODE REVIEW

**Comment by brusch** [comment]
Thanks @Yivan for your PR. 
Before we merge this PR I guess we should fist check which limitations miniPaint has.
If there are limitations on the amount of pixels in an image we should check them and display an info message in case an image is too big for miniPaint, we should then give the user the choice to cancel the editing or continue with a downsized image. 

I've tried to find our something about the limitations of miniPaint, but haven't found anything, maybe you can check it again or make your own experiences. 

Thanks a lot!

**Comment by Yivan** [comment]
@brush i didn't find any limitation mentionned.
I trid with a 10000x10000 png image. Open it on https://viliusle.github.io/miniPaint/ , add some pencil stroke ; ) and save it.
It was ok, no limitation. The resulting image make 10000x10000.
I wanted to try 20000x20000 but my computer was in pain for memory !!!
So i think the limitation would be computer memory before miniPaint limitation ; )

**Comment by brusch** [comment]
Ok, thanks for checking. 
I've just pushed ff2ee54f06c92ae6cf5781b33aeb88a78ed7c793 with some further optimizations.

**Comment by Yivan** [comment]
@brush Thanks, and nice addition the file format conversion !

**Pull request closed without merging**
