### PR TITLE
[Data objects] Disable inheritance for single fields

### LINKED ISSUE #5416: Field Level Controlled Inheritance
Sometimes, you don't want certain fields to inherit but you want some to inherit. In that case, I always work with "dummy" values to break inheritance. (Thinks like a Metadata ManyToMany with Warehouses and Stock Quantity, a product can not inherit stock-values, since it is SKU based)

I think it should be quite easy possible for Pimcore to check on a field-definition level if inheritance is enabled or not, if not, don't inherit.

WDYT?

### PR DESCRIPTION
**Pull request by BlackbitDevs**
Sometimes there is the wish to enable inheritance for most fields but to exclude some others from being inherited. The suggestion in https://github.com/pimcore/pimcore/pull/6584#issuecomment-660097524 sadly is not enough to accomplish this because in the backend data is not loaded with inheritance through the getter methods but with 
https://github.com/pimcore/pimcore/blob/9bb42bc29e54493573aee21e197fe6efecdab991/bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php#L596
and afterwards
https://github.com/pimcore/pimcore/blob/9bb42bc29e54493573aee21e197fe6efecdab991/bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php#L681
This way it is not possible to exclude single fields from inheritance by overriding `\Pimcore\Model\DataObject\Concrete::getValueFromParent()` (as this is not used for loading backend data).

This PR adds a new parameter to `$fieldName` to `Concrete::getNextParentForInheritance()`. This way you can override this method in a data object class and implement something like
```php
public function getNextParentForInheritance($fieldName = null)
{
    if($fieldName === 'imageGallery'){
       return null;
    }
    return parent::getNextParentForInheritance($fieldName);
}
```

Resolves #5416

### CODE REVIEW

**Comment by BlackbitDevs** [comment]
Failing test is not caused by this PR but something with Docker.

**Comment by passioneight** [comment]
I feel like this should be a checkbox in the class editor. What do you think?

**Comment by BlackbitDevs** [comment]
@passioneight Yes, me too but I first wanted the hear if this PR has a chance to get merged because in #6584 I already had it implemented with a checkbox (but with a different data model approach) and this was simply closed. To not waste that effort again, I would first like to hear some opinions of the Pimcore maintainers.

**Comment by brusch** [comment]
For me this sounds like a good solution: 
- it gives the control over inheritance to the dev
- it doesn't break anything
- it doesn't require any additional configuration

@dvesh3 what's your opinion on that? Any concerns? 😊

**Comment by brusch** [comment]
@BlackbitNeueMedien as this might be of general interest, could you please also add this possibility to the docs? Thanks in advance!

**Comment by brusch** [comment]
This would resolve #5416

**Comment by BlackbitDevs** [comment]
@brusch I will update the docs.
As this PR now seems to get accepted, shall I also add a checkbox to disable inheritance in the field definition as @passioneight suggested? Actually I can copy most of the JS code from #6584 for this.

**Comment by brusch** [comment]
@BlackbitNeueMedien I'd leave it a coding only feature for now. We can think of a UI later on 😊

**Comment by brusch** [comment]
Thank you very much! 🙏

**Comment by brusch** [comment]
Reverted due to #10931

**Pull request merged**
