### PR TITLE
[EcommerceFrameworkBundle] Refactored as per modern bundle structure

### PR DESCRIPTION
**Pull request by dvesh3**
## Changes in this pull request  
Resolves partially #12559

### CODE REVIEW

**Comment by aashan10** [comment]
@dvesh3 please fix the conflicts :)

**Review by kingjia90 — COMMENTED** [review]
Confirming the problem that Arya found about add/update pricing rule, but it's not caused by this PR.
The root of the problem is `condition` being a [reserved word](https://mariadb.com/kb/en/reserved-words/) but not being automatically quoted. The weird thing is that on Demo it works.

Opening a new issue for it https://github.com/pimcore/pimcore/issues/13336

**Comment by dvesh3** [comment]
> @dvesh3 please fix the conflicts :)

done.

**Comment by kingjia90** [comment]
Update: I've found the culprit for the pricing rule not working on 11.x, https://github.com/pimcore/pimcore/pull/13373 so we can now safely merge this one.

**Pull request merged**
