### PR TITLE
Remove unused translations

### PR DESCRIPTION
**Pull request by blankse**
Was removed also here https://github.com/pimcore/pimcore/pull/12881
But was added here again: https://github.com/pimcore/pimcore/commit/c1f1f832be30136bc920cedbfee1e687267d0650

### CODE REVIEW

**Comment by blankse** [comment]
Also remove deprecated translation. Follow up to https://github.com/pimcore/pimcore/pull/13393

**Comment by dvesh3** [comment]
> Also remove deprecated translation. Follow up to #13393

@blankse we intentionally kept the deprecation keys as it is generic and could be used going forward. could you please revert it? thanks!

**Comment by blankse** [comment]
@dvesh3 Done

**Comment by mcop1** [comment]
Thanks!

**Pull request merged**
