### PR TITLE
Fix: Objectbrick csv import

### PR DESCRIPTION
**Pull request by blankse**
If I drag and drop a object brick field in the column tab of the csv import, the attribute fields are empty/incorrect and readonly.

### CODE REVIEW

**Comment by weisswurstkanone** [comment]
Is this still WIP ?

**Comment by blankse** [comment]
@weisswurstkanone No, should work now.

**Comment by blankse** [comment]
@weisswurstkanone I have restored the compatibility in the DefaultValue.php

**Comment by weisswurstkanone** [comment]
thx!

**Pull request merged**
