### PR TITLE
Retrieve bundle manager from container each time isInstalled is called on a bundle (#16438)

### LINKED ISSUE #16438: [Bug]: PimcoreBundleManager gets into wrong state when running multiple Kernel tests in a suite
### Pimcore version

11.1.4

### Steps to reproduce

- Create a WebTestCase that boots a kernel
- Execute some code that will call the `isInstalled` method on a Pimcore Bundle (PimcoreSeoBundle for me)
- Notice that the test of class `TestA` passes while the one of class `TestB` does not (when they run in the same suite)

```php
<?php

declare(strict_types=1);

namespace App\Tests;

use Pimcore\Model\Document\Page;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

final class TestA extends WebTestCase
{
    public function testA(): void
    {
        self::bootKernel();

        Page::getById(1, ['force' => true])
            ?->setTitle('test')
            ->save()
        ;
    }
}
```

```php
<?php

declare(strict_types=1);

namespace App\Tests;

use Pimcore\Model\Document\Page;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

final class TestB extends WebTestCase
{
    public function testB(): void
    {
        self::bootKernel();

        Page::getById(1, ['force' => true])
            ?->setTitle('test')
            ->save()
        ;
    }
}
```

I tracked it down to [this](https://github.com/pimcore/pimcore/blob/11.x/lib/Extension/Bundle/AbstractPimcoreBundle.php#L47) line of code. When changing the `??=` operator to just `=` the second test passes as well.  
Is there something I am doing wrong and this is expected or have I found a bug?

The line of code that crashes the test is [this](https://github.com/pimcore/pimcore/blob/11.x/bundles/SeoBundle/src/PimcoreSeoBundle.php#L52) one. When the second test runs the value of `$this->container` is null. This makes sense since the kernel sets the container of all bundles to null on shutdown. It just seems like it does not get properly re-set when booting the kernel on the next test.

### Actual Behavior

The second test fails

### Expected Behavior

Both tests pass

### PR DESCRIPTION
**Pull request by GALPR**
## Changes in this pull request  
Resolves #16438

### CODE REVIEW

**Comment by fashxp** [comment]
could you please rebase to 11.1, thx.

**Comment by GALPR** [comment]
@fashxp done

**Comment by brusch** [comment]
@GALPR Thanks, just one more thing: your change makes `static::$bundleManager` obsolete, so I'd refactor it to use a local variable instead.

**Comment by GALPR** [comment]
@brusch This would be a BC break though, wouldn't it?

**Comment by brusch** [comment]
Ah yes, you're right, thought the var is `private` 😉 Thanks!

**Comment by jdreesen** [comment]
Should we deprecate it then?

**Comment by brusch** [comment]
@jdreesen yep, thanks - done here #16590

**Pull request merged**
