### PR TITLE
[WebsiteSettings] getData should lazy load like Property class

### PR DESCRIPTION
**Pull request by blankse**
The Property class loads the elements but the WebsiteSetting class doesn't:
https://github.com/pimcore/pimcore/blob/652a614a0c50d1b33212471e548e3cc96a517aad/models/Property.php#L140-L152

I know its a kind of bc break. Perhaps it is possible in 5.7.0 with a bc notice?

### CODE REVIEW

**Comment by brusch** [comment]
It only breaks BC if you're accessing the `data` property in your code, or I'm missing something? 
I think we should then take the chance to change all the properties of `WebsiteSetting` to `protected`, can you add that to your PR? 
Please also put a note here https://github.com/pimcore/pimcore/blob/master/doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/01_Within_V5/README.md#L2-L1
We'll merge it into 5.7 then.

**Comment by blankse** [comment]
@brusch Done :)

**Comment by dpfaffenbauer** [comment]
tests break cause they are accessing the `Property` properties directly

**Comment by blankse** [comment]
I will correct the tests on Monday

**Comment by blankse** [comment]
Tests are correct now

**Comment by brusch** [comment]
@blankse needed to revert this PR, due to #4095

**Pull request merged**
