### PR TITLE
[Task] Add librsvg2 to recommended packages

### PR DESCRIPTION
**Pull request by saitho**
librsvg2 is needed to calculate preview images for SVG files. Therefore it's added to the list of recommended packages, making it visible in the system check module and command.

  
  

## Changes in this pull request  

I had issues with my Pimcore installation not displaying preview images for SVG files in the backend.
After a couple of hours debugging I found out that the package "librsvg2-bin" is needed for it to work.

If I'm not wrong here, I think this should be added to the system requirements check tooling, so other people can get a better idea what may be missing in their setup, when they come across the same issue.

## Additional info

My local Pimcore environment runs with DDEV. After I configured the package to be installed, it worked fine.

### CODE REVIEW

**Comment by saitho** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mattamon** [comment]
recheck

**Comment by mattamon** [comment]
@saitho we also need to add it then in the installation guide.
https://pimcore.com/docs/platform/Pimcore/Installation_and_Upgrade/System_Requirements

https://github.com/pimcore/pimcore/blob/11.x/doc/23_Installation_and_Upgrade/01_System_Requirements.md

@brusch should not be a problem right?

**Comment by mattamon** [comment]
@saitho could you also please merge the latest 11.x into your branch. Seems like you still have some outdated workflows

**Comment by saitho** [comment]
Sure. :) I'll also update the docs soon.

I still haven't figured out my issue with SVGs completely yet. I still can't see them, but this change should be fine.:)
Need to do some more digging next time I'm firing up the Pimcore project.

**Comment by brusch** [comment]
Rsvg is not an actual requirement, as this depends on your individual  ImageMagick delegates.
There are multiple options available such as the build-in SVG renderer, Inkscape or rsvg. 
So rsvg is an optional dependency of another optional feature, as Imagick is no requirement. 
Therefore I don't see this as the right place for it, rather a note in the docs, but not in the requirements check.

Thanks anyway for your PR 😊

**Comment by saitho** [comment]
> So rsvg is an optional dependency of another optional feature, as Imagick is no requirement.
Therefore I don't see this as the right place for it, rather a note in the docs, but not in the requirements check.

Makes sense to me. I'd appreciate a note in the docs, because I spent some time trying to figure out, why I don't see SVG previews. :)

**Comment by fashxp** [comment]
@saitho would you like to create a PR to add the notes to the docs which would have helped you?

**Pull request closed without merging**
