### PR TITLE
WIP: Export to xlsx

### LINKED ISSUE #4455: Export to Excel
# Feature Request
Possibility to export to xls or ods format from a grid perspective.
## Feature description
Expand grid CSV export feature to include xls format. Converting between csv and excel (or ods) format is rather easy. It can solve issues with interoperability caused by different encoding used by Microsoft Office and Pimcore. Also, it would allow skipping configuration step when opening an exported file in Libre Office.
If feature proposal is accepted, I could implement it.

### PR DESCRIPTION
**Pull request by kubaplas**
This is still work in progress, but feel free to comment on the solution.
## Changes in this pull request  
Resolves #4455 

## Additional info  
I tried to rewrite the js code to allow adding new export types easily and without overwriting core code.
Xlsx part is right now the most trivial approach - I convert already generated CSV file to Xlsx.

### CODE REVIEW

**Comment by brusch** [comment]
@kubaplas is it still WIP or ready to be reviewed?

**Comment by kubaplas** [comment]
@brusch it's still WIP
Functionality works, but I still need to update configuration window in Ext.js and refactor code to use league/csv.
You can review the code to tell me if the direction I took in js part is correct.

**Comment by brusch** [comment]
@kubaplas looks good so far!

**Comment by brusch** [comment]
@kubaplas are you planning to continue the work on this PR in the near future, or can we close this PR for now? Thanks for a quick reply ☺

**Comment by kubaplas** [comment]
Sorry @brusch, I couldn't finish this feature right away, I'll reopen PR when I'll finish it. Thanks for the feedback!

**Pull request closed without merging**
