### PR TITLE
Add frontend_prefixes Twig Function

### PR DESCRIPTION
**Pull request by dpfaffenbauer**
This allows to get the prefix for usage of static paths in twig templates

### CODE REVIEW

**Comment by brusch** [comment]
@dpfaffenbauer what is the actual use case? We should also add this to the docs 😉

**Comment by dpfaffenbauer** [comment]
we upload eg. favicons to assets and statically refer to them in the templates.

```
<link rel="apple-touch-icon" sizes="180x180" href="/favicons/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicons/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicons/favicon-16x16.png">
```

they then actually get uploaded to gcp storage and need to be loaded like:

```
<link rel="apple-touch-icon" sizes="180x180" href="{{ pimcore_asset_prefix_source() }}/favicons/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="{{ pimcore_asset_prefix_source() }}/favicons/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="{{ pimcore_asset_prefix_source() }}/favicons/favicon-16x16.png">
```

**Comment by brusch** [comment]
@dpfaffenbauer thanks for sharing the use-case, but wouldn't it be better than to use `{{ pimcore_asset_by_path("/favicons/favicon-16x16.png") }}` instead?

**Comment by brusch** [comment]
Closed due to inactivity. Please feel free to continue the discussion or provide the missing information on this issue, we'll then reopen it if necessary. Thanks a lot!

**Pull request closed without merging**
