### PR TITLE
Fixed typo for return type and wrong usage of method_exist function.

### PR DESCRIPTION
**Pull request by ngeleedst**
## Changes in this pull request  
Resolves #
This bugfix addresses the fix for the save/publish event of encrypted fields. Because of the typos it was unable to save and results in an ContextException.

## Additional info  
Fixed two small bugfixes.

### CODE REVIEW

**Comment by ngeleedst** [comment]
Hi,
I would like to create a pull request, how to?

**Comment by brusch** [comment]
@ngeleedst you've created already a PR ;) or what is your question? 
Btw. please sign the CLA so that we can merge your PR.

**Comment by ngeleedst** [comment]
Hi @brusch!

Thanks, i already did “You have signed the CLA already but the status is still pending? Let us recheck it.” is it ok now?

**Comment by brusch** [comment]
@ngeleedst still not ok. 
Please check if your primary email address on GitHub is the same as you use for Git. 
You can check that with the following command: `git config --global user.email`

**Comment by weisswurstkanone** [comment]
thx!

**Comment by weisswurstkanone** [comment]
PHPStorm's code inspector would have caught it at well ;-)

**Comment by brusch** [comment]
@dpfaffenbauer it wasn't me ;)

**Comment by dpfaffenbauer** [comment]
I don't wanna blame anyone, just point at some tools that help to avoid that ;)

**Comment by brusch** [comment]
I know, just kidding ;)

**Pull request merged**
