### PR TITLE
Add notes to install documentation for custom PIMCORE_ENVIRONMENT

### PR DESCRIPTION
**Pull request by Yivan**
Hello,

Thias pull request add notes to documentation, so less problem could occurs in case of custom PIMCORE_ENVIRONMENT.
(see https://github.com/pimcore/pimcore/issues/3327)

Thanks.

### CODE REVIEW

**Comment by brusch** [comment]
I'm wondering if this is the right place for this information, since this page is mainly for Pimcore newbies that don't know what the additional note actually means and we don't want to confuse them :| 

Maybe it's better to put the note here https://pimcore.com/docs/5.x/Development_Documentation/Deployment/Multi_Environment.html ?

**Comment by Yivan** [comment]
@brusch I don't know. I would prefer to have it on the installation page. When installing a new Pimcore, i go to this page, and i think other people do like this (experienced or not) to refer if some things changed for installing Pimcore. I hope to find all information on this same page to be able to install Pimcore even if multienv is activated. I think to have related information in same place is better.

Another way, would be to put it in `https://pimcore.com/docs/5.x/Development_Documentation/Deployment/Multi_Environment.html` and refer to it in the installation page. But i thin as it is command for installing, it should really directly be in the installation page documentation.

Tell me what you prefer, and i can change my PR if needed.

**Comment by Yivan** [comment]
@brusch 
Thanks for your modification. But the real anoying problem is you need a custom skeleton...
**Composer cannot create project if directory is not empty**, so you cannot prepare the file before the create composer command.
Making `PIMCORE_ENVIRONMENT= COMPOSER_MEMORY_LIMIT=-1 composer create-project ...` resolves nicely this problem, as just after this you can add this `app/config/config_[env_name].yml` and go on the install process.

Maybe you could just change the sentence you added by:
```
If you're running the installation using a custom environment name, ensure you have already the right config files in place, e.g. app/config/config_[env_name].yml. You can create the composer project by using command `PIMCORE_ENVIRONMENT= COMPOSER_MEMORY_LIMIT=-1 composer create-project ...` which will unset PIMCORE_ENVIRONMENT just for the creation of the project.
```

At least people won't have to make a custom skeleton to create the composer project. And it is a nice tip for Continous Integration where installing fresh Pimcore.

**Comment by dpfaffenbauer** [comment]
I don't see any problem here, this is perfectly normal Symfony behaviour, if you need custom envs in your setup, just create a custom skeleton, there is nothing wrong with it.

**Comment by Yivan** [comment]
@dpfaffenbauer Thanks for your insights!
I would say it is more composer than synfony related (being able to bypass create-project to be able to add the config file).
I never done this, maybe it should be documented or at least point to the synfony doc explaining it ?
I just looked into what does exactly "create-project, and i found it here: `https://getcomposer.org/doc/03-cli.md#create-project`

So I imagine to install Pimcore on custom PIMCORE_ENVIRONMENT, it is something like this:
- `git clone https://github.com/pimcore/skeleton.git .`
- add app/config/config_[env_name].yml
- `COMPOSER_MEMORY_LIMIT=-1 composer install`

In all case having it documented could only help people to install Pimcore ; ) I doesn't hurt.
(this way by git clone + composer install, or this way `PIMCORE_ENVIRONMENT= COMPOSER_MEMORY_LIMIT=-1 composer create-project ...`)

@brush if you think it is valuable information i can make a new PR (just tell me what you wish for it), or we can leave this issue closed (people could always refer to this github issue to have some hints).

**Pull request closed without merging**
