### PR TITLE
Add BSI compliant password standards

### LINKED ISSUE #17053: [Improvement]: BSI compliant password standards
### Improvement description

The german administration for security in information technology (BSI) recommend a higher password policy than pimcore have at the moment. 

BSI recommendations:

Short and more complex Passwords:
- 8 to 12 chars long
- One or more upper case, lower case, number and special sign

Longer and less complex Passwords:
- minimum of 25 chars long
- containing minimum two types of signs

[BSI INFO PDF](https://www.bsi.bund.de/SharedDocs/Downloads/DE/BSI/Checklisten/sichere_passwoerter_faktenblatt.pdf?__blob=publicationFile&v=4#:~:text=Um%20das%20zu%20verhindern%2C%20sollte,f%C3%BCr%20einen%20Zugang%20genutzt%20werden.&text=Ist%20mindestens%2025%20Zeichen%20lang,ein%20Zeichen%20voneinander%20getrennt%20sind.)

Should we implement this in Pimcore?

### PR DESCRIPTION
**Pull request by kevinloeber-twocream**
## Changes in this pull request  
Resolves https://github.com/pimcore/pimcore/issues/17053

### CODE REVIEW

**Comment by brusch** [comment]
@kevinloeber-twocream Thanks for your PR - however, I don't see that the config values are actually used somewhere 🤔 Is there something missing?

**Comment by kevinloeber-twocream** [comment]
Hey, pimcore itself I would change a few lines of code. But the setting was mostly applied in the admin-ui-classic-bundle

**Comment by skoch-twocream** [comment]
Hi @brusch - I will discuss the PR internally first, can you please close it. In my view, some is not correct here - I would like to catch this in an internal Q/A first after the vacation of @kevinloeber-twocream.

Thanks!

**Comment by brusch** [comment]
@skoch-twocream sure, thanks for your feedback 👍😊

**Pull request closed without merging**
