### PR TITLE
ControllerReferenceMigrationCommand: Don't load all documents at once

### PR DESCRIPTION
**Pull request by blankse**
I have problems to execute this command. It progresses but is still being terminated...

### CODE REVIEW

**Comment by weisswurstkanone** [comment]
Hello @blankse , what are the steps to reproduce (except executing the command) ?

**Comment by blankse** [comment]
@weisswurstkanone I think many documents with many area bricks and little memory. I still haven't managed to migrate. i think i need more optimization. I must look deeper. But the command always will killed without message...

Maybe we can only load documents that still have the wrong controller schema?

**Comment by weisswurstkanone** [comment]
@blankse, did you try to execute Pimcore::collectGarbage() inside the loop

**Comment by blankse** [comment]
@weisswurstkanone No, thanks for the hint. I will try :)

**Comment by dpfaffenbauer** [comment]
does it actually has to load the documents? Wouldn't it be efficient enough to just check the documents_snippet and document_page tables directly? That would massively increase the performance. Especially when you deal with lots and big documents

**Comment by weisswurstkanone** [comment]
@dpfaffenbauer , yes maybe there is room for improvement. Perfomance always matters but you execute a migration script only once. Top priority is to get the migration done in a **correct way**. So let us focus on this point first ;-)

**Comment by dpfaffenbauer** [comment]
> @dpfaffenbauer , yes maybe there is room for improvement. Perfomance always matters but you execute a migration script only once. Top priority is to get the migration done in a **correct way**. So let us focus on this point first ;-)

Performance for a migration is also super important. you cannot let the migration run for an hour during a deployment process... that makes the website unusable during that time ;)

**Comment by dpfaffenbauer** [comment]
there you go https://github.com/pimcore/pimcore/pull/8949

**Comment by blankse** [comment]
Close in favor of #8949

**Pull request closed without merging**
