### PR TITLE
chore: Remove unnecessary casts

### PR DESCRIPTION
**Pull request by jdreesen**
Now that we have improved parameter/return types, we can get rid of many unnecessary casts.

### CODE REVIEW

**Comment by Corepex** [comment]
@jdreesen please resolve the conflicts :)

**Comment by jdreesen** [comment]
Done. This will probably happen a few more times, unless you merge it soon.

**Comment by jdreesen** [comment]
I fixed the conflicts.

**Comment by lukmzig** [comment]
@jdreesen thank you for the cleanup

**Pull request merged**
