### PR TITLE
Support endroid/qr-code 4

### PR DESCRIPTION
**Pull request by blankse**
I use endroid/qr-code-bundle and I get deprecation notices in V3. V4 has PHP 8 support and fixed this notices.

### CODE REVIEW

**Comment by brusch** [comment]
@blankse are there any BC breaks in v4?

**Comment by blankse** [comment]
@brusch Yes the API in v4 is completely different.
But is it a BC break for Pimcore? See https://github.com/semver/semver/issues/148
If someone has also used the qr-code dependency with v3 the composer would not be update until he also update to v4.
The qr-code-bundle is unusable with PHP 8. Every page has outprinted notices...

I can try to make a wrapper to support v3 and v4 so somebody can stay on v3.

**Comment by brusch** [comment]
@blankse I'm fine with that, thanks a lot! Can you just resolve the conflict?

**Comment by blankse** [comment]
@brusch I rebased the branch.

**Comment by brusch** [comment]
@blankse Thanks a lot! 👍

**Pull request merged**
