### PR TITLE
XLIFF: fixing import when working with html entities

### PR DESCRIPTION
**Pull request by brusch**
Fixes #11859

### CODE REVIEW

**Comment by brusch** [comment]
@valentin- can you plz confirm this fixes the issue reported in https://github.com/pimcore/pimcore/pull/11859 for you? Thanks!

**Comment by valentin-** [comment]
@brusch unfortunately I can't update the project to the latest commit id as there are too many dependencies. But it looks good to me.

**Comment by aryaantony92** [comment]
@valentin Xliff import is working with regular html entities with the existing implementation itself.  So, is there any particular test case? Or could you please share the Xliff file/content to test?

**Comment by valentin-** [comment]
@aryaantony92 I copied the code changes directly into the project (locally) and ran a fresh import.

Looks good to me, no more issues with special chars.

image

**Comment by aryaantony92** [comment]
@valentin- Thank you

**Pull request merged**
