### PR TITLE
Logout from custom firewall always deletes complete session

### PR DESCRIPTION
**Pull request by jheimbach**
## Steps to reproduce

1. create custom symfony firewall
2. login to custom firewall
3. login to admin
4. trigger logout for custom firewall
5. Check login status in pimcore admin (you are logged out)

## Additional info  
The LogoutEventListener is called on each LogoutEvent, not only pimcore_admin related events. Additionally the session is cleared entirely but it should only remove the admin attributes.

I also fixed the event handler, it should set the response to the given event object and not return it.

### CODE REVIEW

**Comment by fashxp** [comment]
Related to https://github.com/pimcore/pimcore/issues/6747 ... 
We don't wanna do that in 10.5, can you please rebase to 11.x?

**Comment by jheimbach** [comment]
Hey @dvesh3, 

sorry didn't searched the open issues enough.

I rebased onto 11.x branch

**Comment by dpfaffenbauer** [comment]
@fashxp what are the side-effects of this? Why not having it in 10.x?

**Comment by brusch** [comment]
@JHeimbach if we use tags now, we can remove the `EventSubscriberInterface` from `LogoutListener` and these lines, right: 
https://github.com/pimcore/pimcore/blob/83142b53cfd5a791e3c6167470a66336fd03da22/bundles/AdminBundle/src/Security/Event/LogoutListener.php#L49-L54

@dpfaffenbauer we are just worried about potential security related side-effects, and it has been always like this 😉 So let's merge this into `11.x` and keep the behavior for the `10` branch.

**Comment by jheimbach** [comment]
@brusch we use an event_subscriber tag, the tag changes only the dispatcher.  If you want we can use an event_listener tag with all settings combined (event, method, dispatcher)

**Comment by brusch** [comment]
@JHeimbach All good, thanks for clarifying! 👍

**Comment by dvesh3** [comment]
@JHeimbach please rebase on 11.x branch to have this change https://github.com/pimcore/pimcore/commit/03822b93c4aefdd08e218b7758353c58996dfee4 for fixing failing tests. thanks!

**Comment by jheimbach** [comment]
done

**Review by dvesh3 — APPROVED** [review]

**Comment by dvesh3** [comment]
@JHeimbach works like a charm 💯 thank you very much!

**Pull request merged**
