### PR TITLE
Add additional check for publish right

### LINKED ISSUE #11314: [Bug][DataObjects]: Autosave throws Error if only publish permission (and not save) given
### Expected behavior

When an User have explicit publish rights (and no explicit save rights) to an object, one of these should be correct behaviour:

1. Disabling all Fields, making just Publish and Unpublish working, but no other edits
2. Not showing an error popup.

### Actual behavior

An Error popup shows.

grafik

### Steps to reproduce

1. Create Folder, DataObject etc. as needed
2. Create Object in Folder. 
2. Create User
3. Give User list, view and publish rights on folder (via workspace)
4. Login with new User
5. Open Object in Folder from Step 1.
6. Change value of some field e.g. input field.

### PR DESCRIPTION
**Pull request by chrisjung-dev**
## Changes in this pull request  
Resolves #11314

### CODE REVIEW

**Comment by brusch** [comment]
@campino2k Thanks a lot for your PR, however since this is a bug fix, could you rebase this PR onto the `10.2`? Thanks in advance.

**Comment by chrisjung-dev** [comment]
I'll see what I can do later.

**Comment by brusch** [comment]
@campino2k no worries, just 🍒-picked the PR into `10.2`, see 877c7303b82348550eecd2f97a48eca2e43d8e5c - so nothing else to do for you - thanks a lot!

**Comment by chrisjung-dev** [comment]
Thanks!

**Pull request closed without merging**
