### PR TITLE
Update Datetime.php

### PR DESCRIPTION
**Pull request by j-jonas**
## Changes in this pull request  Resolves #

if getColumnType is "datetime" string will be returned

### CODE REVIEW

**Comment by mattamon** [comment]
@j-jonas this should be a bugfix right?

**Comment by j-jonas** [comment]
Yes, it is a bugfix

**Comment by mcop1** [comment]
@j-jonas Thank you for your contribution, since this is a bugfix, could you please rebase your pr to the 11.0 branch? Thank you!

**Comment by j-jonas** [comment]
please delete this and see: https://github.com/pimcore/pimcore/pull/15313

**Comment by mattamon** [comment]
Closed in favor of #15313

**Pull request closed without merging**
