### PR TITLE
Add filter for path column in the dependencies view

### PR DESCRIPTION
**Pull request by Geni2**
## Changes in this pull request  
I have add filter in the path column in the dependencies view

### CODE REVIEW

**Comment by BlackbitDevs** [comment]
Does this work with pagination? Or in other words: Does this use remote filtering or only on client-side (in this case it would only filter for first page)?

**Comment by Geni2** [comment]
> Does this work with pagination? Or in other words: Does this use remote filtering or only on client-side (in this case it would only filter for first page)?

Yes you are right for this it make the search only in the first page, I will add the remote filter and make another commit. Thank you.

**Comment by mattamon** [comment]
@Geni2 can you also please sign the CLA? :)

**Comment by Geni2** [comment]
> @Geni2 can you also please sign the CLA? :)

I have sign it but after I created the PR. I don't know why it not refresh here yet!

**Comment by mattamon** [comment]
> > @Geni2 can you also please sign the CLA? :)
> 
> I have sign it but after I created the PR. I don't know why it not refresh here yet!

Hmm this is odd, did you create this PR without a Github User?

Mariglen Meta seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by Geni2** [comment]
> > > @Geni2 can you also please sign the CLA? :)
> > 
> > 
> > I have sign it but after I created the PR. I don't know why it not refresh here yet!
> 
> Hmm this is odd, did you create this PR without a Github User?
> 
> Mariglen Meta seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

No I didn't but I created this PR from my organization Github page.

As you can see I have an active Github account since 2019.
I will create another PR because I will add the remote filter and I think everything will be okay, I notice that i haven't sign in with my Github account in my PC when I commit my changes this is the problem.

**Comment by jdreesen** [comment]
If the email address of the commit is not [attached to your GitHub account](https://github.com/settings/emails), the CLA assistant will not recognize it.

**Comment by Geni2** [comment]
> If the email address of the commit is not [attached to your GitHub account](https://github.com/settings/emails), the CLA assistant will not recognize it.

I have attached my email address [here](https://github.com/settings/emails) as a primary email.

**Comment by jdreesen** [comment]
GitHub somehow doesn't seem to recognize it.

**Comment by mattamon** [comment]
@Geni2 are you going to open another PR with the new changes? :)

**Comment by Geni2** [comment]
> @Geni2 are you going to open another PR with the new changes? :)

Yes but I'm currently working with remote filter so it can take a some time.

**Comment by mattamon** [comment]
Waiting for the new PR

**Pull request closed without merging**
