### PR TITLE
Add links to objects in WYSIWYG editor issue 485

### PR DESCRIPTION
**Pull request by timhonders**
We are also interested in adding an object link in a WYSIWYG editor

https://github.com/pimcore/pimcore/issues/485

Added the following functions:

- Possibility to drop an Object on an WYSIWYG editor

- Popup to select a Static route

popup

- The variables that are set in a static route are replaced in the link by variable from the object (only stings and numbers)

static_route

So /object/%key/%testinput will be /object/{the o_key of the object}/{testinput value from object}

### CODE REVIEW

**Comment by dpfaffenbauer** [comment]
Looks cool, but what if the user has no permissions for static routes? Your request "/admin/settings/staticroutes" would not work.

**Comment by timhonders** [comment]
mmm good point, some possible solutions:

1. Give every user premission to read the static routes by removing the premission check of the  staticroutes action

2. Add static route when configuring the class definitions

3. Don't use a static route, build the url by hand with an input.

What do u think

**Comment by dpfaffenbauer** [comment]
class-definition already allow to define a url, you could use that one?

**Comment by atietje** [comment]
Great that someone picked this up. As I suggested in #485 I'd prefer not to use a dialog to select a static route, because normal users could easily be overwhelmed, and we have that permission issue @dpfaffenbauer mentioned. 

> To create the URL I suggest to add a **selection field to the class definition dialog** to select an existing static route with named placeholders. Then, when the editable is rendered, the URL to the object could be created by using the specified static route. If no route is selected the link tag wouldn't be rendered or - as a fallback solution - the objects preview URL or full path would be used as the URL

One more thing: What about multiple languages, locales in URLs? /de/mein-produkt vs. /en/my-product?

**Comment by timhonders** [comment]
Multiple languages good point.

Is there any possibility in the preview url for multi language?

**Comment by atietje** [comment]
IMHO there's no out-of-the-box multi language support in routes. But: 

When the content gets rendered, there has to be some way to determine the current locale, `Zend_Registry::get("Zend_Locale")` and the like. 

Say you have a route like `/product/%locale/%key`, then you could write an appropriate method like \Website\Model\Object\Product::getLocale(), (add that class to classmap etc.) which returns the current locale. 

You could even have a route like `/%myprettyurl` and let a function build a complete path like `/produkt/key` for DE or `/product/key` for EN and add build a class, say `MyRouter`, that extends `Zend_Controller_Router_Route_Abstract`, register that class in `startup.php` like 

`
$router = Zend_Controller_Front::getInstance()->getRouter();
$router->addRoute(product', new MyRouter());
`
and let MyRouter::match() figure out what `/product/en/my-product-key` means.

As always, there's more than one way to do it :)

**Comment by atietje** [comment]
Oh, and I think previewUrl should not be used for this, because that's for preview, and that might be different from the "production" URL. We should simply add an additional field to select an appropriate route in the class configuration.

**Comment by timhonders** [comment]
You are right i will fix that after the language issue :)

I think we need to address the language issue when the object is droped on to the WYSIWYG.

What do u think about using the language property of the document where the WYSIWYG
or when something like when %locale or %language is in the "Production" URL.

Show a popup so you can select the language the link has to be

**Comment by atietje** [comment]
I don't know exactly when and where the URL is generated. When I insert a link to a document, I get 

`<a href="/path/to/document" pimcore_id="123" pimcore_type="document">Link-Text</a>`

Here the /path/to/document doesn't take into account neither that the page might be located in a sub-site or that it might have a prettyUrl. The final URL is assebled when the edited page gets rendered (Frontend).

Accordingly, we should have 

`<a href="/path/to/dropped/objects/previewUrl" pimcore_id="456" pimcore_type="object">Link-Text</a>`

to link to an object. No need to assemble the final URL in admin mode or guess or ask for the locale. That will be done later by any means the developer would like to use to build the url.

**Comment by brusch** [comment]
Hmm, the language issue is just another variable in the process of generating an url, but basically the url generation depends on the actual context, which can have many (non-standard) variables that need to be addressed. 

So I think the only way of providing a generic solution for this problem is a php callback-function that can be defined on class level. This callback function needs to implement the url generation and returns the url / path based on the given context.

**Pull request closed without merging**
