### PR TITLE
Update ClassificationstoreController.php

### PR DESCRIPTION
**Pull request by mc-supply**
Fix route name for /groups (POST/PUT)

  
  

## Changes in this pull request  
Resolves #

### CODE REVIEW

**Comment by weisswurstkanone** [comment]
Isn't this fixed already via https://github.com/pimcore/pimcore/pull/6580 ?

**Comment by mc-supply** [comment]
Looks like it is.  Didn't see that.

**Comment by blankse** [comment]
The 6.6 branch isn't merged to master yet.

**Comment by brusch** [comment]
Yes, we do that just from time to time or after a bug fix release (which is common practice). 
In general, bug fixes only go into the latest release branch, so e.g. `6.6`. 
See also: https://github.com/pimcore/pimcore/blob/master/CONTRIBUTING.md#contributing-pull-requests 😉

Thanks anyway!

**Pull request closed without merging**
