### PR TITLE
[Thumbnails] Scaling animated GIFs does not work

### PR DESCRIPTION
**Pull request by BlackbitDevs**
Steps to reproduce:
1. Upload this image to Pimcore assets
5d667803a7a67_gif1-Everyonelovesgifs_4ef1dbef8a604a3e1b26eebf2c000ef0

2. Create this thumbnail definition:
```yaml
pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    test:
                        items:
                            -
                                method: cover
                                arguments:
                                    width: 200
                                    height: 80
                                    positioning: center
                                    forceResize: false
                        medias: {  }
                        name: test
                        description: test
                        group: ''
                        format: ORIGINAL
                        quality: 85
                        highResolution: 0.0
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: true
                        modificationDate: 1697029839
                        creationDate: 1694377896
                        preserveAnimation: true
```

Open the asset and download it with thumbnail definition `test`.

Generated thumbnail will look like this:
5d667803a7a67_gif1-everyonelovesgifs_4ef1dbef8a604a3e1b26eebf2c000ef0(2)

See that only the first frame is scaled correctly, all others are unscaled (but do not fit into viewport anymore of course).

Output with this PR:
5d667803a7a67_gif1-everyonelovesgifs_4ef1dbef8a604a3e1b26eebf2c000ef0(3)

I have not checked for other transformations than `cover` but I guess those have the same problem...

### CODE REVIEW

**Comment by robertSt7** [comment]
@BlackbitDevs Sorry for me the PR doesn't fix the problem. Could you please take a second look? Thanks

**Comment by brusch** [comment]
@BlackbitDevs I can confirm the issue and that the fix works for `crop`. To be consistent we should fix the issue for all the other affected transformation methods as well, like `sepia`, `sharpen`, ... basically all transformations which do a call on `$this->resource`.  Can you update your PR accordingly? 

Thanks in advance!

**Comment by blankse** [comment]
Is fixed by https://github.com/pimcore/pimcore/pull/17084 now.

**Comment by BlackbitDevs** [comment]
Strange, #17084 contains exactly the same solution as this PR. Don't understand why this PR had not been taken into account for such a long time...
Thanks for notifying @blankse !

**Comment by kingjia90** [comment]
@BlackbitDevs i am sorry for that, this PR went off my radar and didn't realize that the other one was a duplicate.
However the `checkPreserveAnimation()` check was missing in this one. 

We may need to extend to the other transformations as per
https://github.com/pimcore/pimcore/pull/16083#issuecomment-1938780947 even though it gets in the domain of an improvement.

Could you still work on it?
Something like

```
    private function applyTransformation(array $functions = []): void
    {
        if ($this->checkPreserveAnimation()) {
            foreach ($this->resource as $i => $frame) {
                foreach ($functions as $function => $args){
                    $frame->$function(...$args);
                }
            }
        } else {
            foreach ($functions as $function => $args){
                $this->resource->$function(...$args);
            }
        }
    }
    public function crop(int $x, int $y, int $width, int $height): static
    {
        $this->preModify();

        $this->applyTransformation(
            ['cropImage' => [$width, $height, $x, $y]],
            ['setImagePage' => [$width, $height, 0, 0]]
        );

        $this->setWidth($width);
        $this->setHeight($height);

        $this->postModify();

        return $this;
    }
```
for each of existing transformation that access to `this->resource` and we could then get rid of this line
image

**Pull request closed without merging**
