### PR TITLE
[Translations] Fix shared translations

### LINKED ISSUE #7184: Shared translations broken in 6.7.2
# Bug Report
### Expected behavior
Translations work as they used to. This will be properly translated if placed in a twig view template:
`{{ "Role"|trans }}`
Works in 6.7.0.

### Actual behavior
Starting from 6.7.2, this will no longer use the proper translated value but the english value only.

### Reason
Must be in this commit:
https://github.com/pimcore/pimcore/pull/7071/commits/3f4e0e3b81f330ccb287716d3a5c46318e08d3b2#diff-35148f8556f54cb705805f95b0f19fed
Reverting it fixes the bug.

### PR DESCRIPTION
**Pull request by dvesh3**
## Changes in this pull request  
Resolves #7184

Might fix also #7584
## Additional info  
Fixes:
- parameters usage
- fallback translations
- translated text as keys

### CODE REVIEW

**Comment by dvesh3** [comment]
@Cruiser13 @jremmurd can you please give it a try? thanks!

**Comment by brusch** [comment]
@kathangeorg @solverat @ayoob-lfc @podarcis @Cruiser13 @jremmurd can you please verify that this fixes your issue reported in #7184

**Comment by kathangeorg** [comment]
@brusch Seems to fix the issue #7184 we had in our project. 
Returns the correct value (from fallback language) if there is no value provided in the current language.

**Comment by Cruiser13** [comment]
@dvesh3 @brusch I can confirm that this does fix our issue. Thank you very much!

**Comment by podarcis** [comment]
Unfortunately, with our particular project (migrated from Pimcore 4) it's still not working: Auto-added translations without an override for the current language are rendered lowercase.

e.g. `$this->t("Art-Nr.: %s")` auto-created a website translation entry with key `art-nr.: %s`. Pre 6.7.2 the frontend showed a value `Art-Nr.: foobar`, post 6.7.2 and on `fix_shared_translations|896af8f4fde1df0c5b88ccc09c0ffd3542cbb063` it's showing `art-nr.: foobar`.

What is your setting for `pimcore-translations.case_insensitive`? Ours is configured as `true`.

**Comment by dvesh3** [comment]
> Unfortunately, with our particular project (migrated from Pimcore 4) it's still not working: Auto-added translations without an override for the current language are rendered lowercase.
> 
> e.g. `$this->t("Art-Nr.: %s")` auto-created a website translation entry with key `art-nr.: %s`. Pre 6.7.2 the frontend showed a value `Art-Nr.: foobar`, post 6.7.2 and on `fix_shared_translations|896af8f4fde1df0c5b88ccc09c0ffd3542cbb063` it's showing `art-nr.: foobar`.
> 
> What is your setting for `pimcore.translations.case_insensitive`? Ours is configured as `true`.

@podarcis thanks for your findings....yes, i don't this setting configured, so it was disabled in my case. will look into it 😉

**Comment by ayoob-lfc** [comment]
@dvesh3 @brusch Fixed the issue with regards to parameter usage. Nice one &#128077;

**Comment by dvesh3** [comment]
@podarcis  can you please check this fixes your issue? https://github.com/pimcore/pimcore/pull/7588/commits/12e7581365606192dab9f6c9c2e30076c6a5558d thanks!

**Comment by podarcis** [comment]
@dvesh3 I can confirm it's now working for the frontend, thank you very much.

However I noticed quite a strange behavior within the backend with pre-existing backend-translations that were still affected. I purged those translations in questions and the strings are correct now. 

The main issue however is solved, thanks again!

**Pull request merged**
