### PR TITLE
[Bug]: Fix thumbnails when using temp storage with cloud object storages

### LINKED ISSUE #15454: [Bug]: Thumbnails broken when setting PIMCORE_SYSTEM_TEMP_DIRECTORY to work with cloud storage (s3)
### Pimcore version

10.5.25

### Steps to reproduce

We have a setup that uses Kubernetes so we have multiple Pimcore pods, therefore we use S3 as blob storage, and we have configured the **flysystem** accordingly. 
Because of multiple pods we needed to specify too **pimcore.temp.storage** to use S3 and also adjust the constant **PIMCORE_SYSTEM_TEMP_DIRECTORY** to point to the same place.
This way we can make sure that exports with the **Advanced Object Search** works correctly.
All this is fine but when setting the constant PIMCORE_SYSTEM_TEMP_DIRECTORY to use S3 instead, the images thumbnails break. I debugged it and they seem to work if the `[0]` is removed in here: https://github.com/pimcore/pimcore/blob/99a8d04f0790145cfb7f44472222b7d26e595944/lib/Image/Adapter/Imagick.php#L80
Not sure why is that there, perhaps is used for PDF or something like that, but I wanted to check before creating a PR.
With thumbnails breaking I mean that the subsequent call `$i->readImage($imagePathLoad) ` will end up in an exception with the message "fail to read the file", however it works without adding the `[0]`
Cheers.

### Expected / actual behavior

_No response_

### PR DESCRIPTION
**Pull request by flamadrid-jsmdg**
## Changes in this pull request  
Resolves #15454

### CODE REVIEW

**Comment by brusch** [comment]
See my comment here: https://github.com/pimcore/pimcore/issues/15454#issuecomment-1630973407 
I think this fix is not necessary at all ... 
If assets are located on a remote storage, they are getting copied to the local temp folder anyway, which is then the source for the Imagick adapter.

**Comment by flamadrid-jsmdg** [comment]
@brusch I answer the comment so to explain the reasons. About the specific changes in this PR, seems ImageMagick handles well layered images without the extra added **[0]** With the local file system works with or without.
If you call $i->readImage('s3://path-to-image' . '[0]'); will end up in an exception with the message "fail to read the file".
So seems adding **[0]**  does not provide any functionality. 
The only situation I see if someone would tray to upgrade to pimcore 10.6 with this change and is running a very old version of ImageMagick buy that is from 2019.
Like @solverat  mentions [here](https://github.com/pimcore/pimcore/issues/15454#issuecomment-1614339989)

**Comment by brusch** [comment]
@flamadrid-jsmdg is there a replacement for selecting layers/pages? Because then we should implement the replacement rather than just removing it 😬

**Comment by flamadrid-jsmdg** [comment]
@brusch not sure if we need a replacement, since if the image type is for example a PSD, the thumbnail will render the first page anyway. At least this is what I observed in a local test. Mind that I only checked it with PSD and jpg and both work well.
Not sure about all image types out there. I haven't found proper documentation on the `[0]`

**Comment by flamadrid-jsmdg** [comment]
@brusch Then if the fix needs to be in the advanced-object-search, The fix will be related to make somehow advanced-object-search aware of Pimcore's storage abstraction right?  I could close this PR.

**Comment by brusch** [comment]
I'd leave this PR open for now - if the `[0]` is really obsolete, we should of course remove it. 
I'm looking for a test PSD now, to check whether it makes a difference or not. 

Just for reference, this was re-introduced by https://github.com/pimcore/pimcore/issues/3607

**Comment by brusch** [comment]
Yep, still in ImageMagick 7 the behavior is different, depending on using `[0]` or not. 
Tested with a PSD using ` ImageMagick 7.1.1-11 Q16-HDRI x86_64 20230529`

**Pull request closed without merging**
