### PR TITLE
[Task]: Fix broken tests

### PR DESCRIPTION
**Pull request by kingjia90**
~Seems related to https://github.com/symfony/symfony/issues/57612~

### CODE REVIEW

**Comment by derrabus** [comment]
Can you please check if symfony/symfony#57615 fixes your tests?

**Comment by kingjia90** [comment]
@derrabus Thank you for coming by, but i can't test it because it's likely unrelated ([fails](https://github.com/pimcore/pimcore/actions/runs/9742454379/job/26883803520?pr=17255#step:9:328) with 7.1.1) to that. 
It still seems related to some "regression" in the latest release, because our lowest tests are working fine, but highest started failing in these 3 days which matches with the latest symfony bugfix release

**Comment by markus-moser** [comment]
No idea why but the latest bugfix release of symfony/http-client breaks our tests

**Comment by blankse** [comment]
@markus-moser You mean `symfony/http-kernel`
It must be this PR then: https://github.com/symfony/symfony/pull/57553

The PR https://github.com/symfony/symfony/pull/57372 is too old. Then the tests must have failed for 2 weeks (there is a 6.4.x test).

**Comment by markus-moser** [comment]
@blankse Yes I also thought that this PR can be the only reason.

**Comment by blankse** [comment]
@markus-moser I can confirm that it is this PR. When I locally revert these changes, the tests run correctly.

**Comment by blankse** [comment]
Maybe is the error here:
https://github.com/pimcore/pimcore/blob/11.x/lib/Translation/Translator.php#L390
The internal translator has a new second argument `$buildDir`

**Comment by markus-moser** [comment]
> https://github.com/pimcore/pimcore/blob/11.x/lib/Translation/Translator.php#L390

Thanks for the hint - yes this sounds like it could be the cause of the problem

**Comment by markus-moser** [comment]
It's a bit weird but works now.

The fallback language was not actually defined in the system settings of the tests. So it only worked by some kind of side effect. Maybe because of the order of the tests and this configuration change in the localized field test https://github.com/pimcore/pimcore/blob/cf8dee882824803cab7c5510584ca906486b8051/tests/Model/DataType/LocalizedFieldTest.php#L132

**Comment by xabbuh** [comment]
If the HttpKernel change causes issues, could you please check if https://github.com/symfony/symfony/pull/57593 is of any help?

**Comment by markus-moser** [comment]
@xabbuh Thanks for your hint but we found out that a problem in our test setup was the root cause of the problem.

**Pull request merged**
