### PR TITLE
[Assets] Fix "allowed memory size exhausted" error

### PR DESCRIPTION
**Pull request by aweichler**
Fix an error, which occurs when using "Download selected items as ZIP" function at a folder view in assets.
It occurs when selecting large files. In our case there where 3 Videos ~200M. PHP Memory Limit was at 256M or 512M.
The function "file_get_contents" reads the whole file into memory before inserting it into the ZIP archive. With "addFile" of the class "ZipArchive" this limitation is bypassed.

### CODE REVIEW

**Comment by brusch** [comment]
We used that already in the past, but this caused problems when using remote streams, see #5628
I'd suggest to check whether `$a->getFileSystemPath()` is a local or remote stream (`stream_is_local()`) and then use `addFromString()` or `addFile()` accordingly. 

Can you update your PR? 😊 Thanks a lot!

**Comment by aweichler** [comment]
Would it also be possible to apply the changes in Pimcore 6.x? Our customer uses this feature and would have to wait very long for Pimcore 10.

**Comment by brusch** [comment]
@aweichler yes, `6.9` would be possible, can you please rebase your PR onto this branch and change base accordingly? Thanks!

**Comment by aweichler** [comment]
I am not sure how to do this. Would it be ok if i provide a new pull request for branch 6.9?

**Comment by brusch** [comment]
@aweichler yes, of course, just create a new PR 😉

**Pull request closed without merging**
