### PR TITLE
[Application logger] Make text selectable / Link related object

### PR DESCRIPTION
**Pull request by BlackbitDevs**
With this PR you can select and copy the text in the log grid. 
Additionally you can directly jump to the related object by clicking the link in the  `Related object` column.
Bildschirmfoto 2021-06-21 um 13 29 22

### CODE REVIEW

**Comment by BlackbitDevs** [comment]
Failing tests are imho not caused by this PR.

**Comment by NiklasBr** [comment]
I think #9508 will resolve them

**Comment by weisswurstkanone** [comment]
maybe related https://github.com/pimcore/pimcore/pull/9498

**Comment by brusch** [comment]
@BlackbitNeueMedien can you please rebase your PR in order to fix the tests? Thanks!

**Comment by weisswurstkanone** [comment]
Hello  @BlackbitNeueMedien , would it make sense to beatify it with the open icon? 
image
What do you think ?

**Comment by BlackbitDevs** [comment]
Imho there is not much space anyway because the most important thing is the error message. And as the link already shows that something will happen when you click it, I do not know if it is necessary. But would also be not much work. If you want it, just tell, then I will include it in the renderer function.

**Comment by weisswurstkanone** [comment]
@BlackbitNeueMedien thanks a lot for your contribution!

**Pull request merged**
