### PR TITLE
[DataObject] Fix notice in Grid Operators

### PR DESCRIPTION
**Pull request by blankse**
```
ErrorException: Notice: Undefined property: stdClass::$textValue in vendor/pimcore/pimcore/lib/DataObject/GridColumnConfig/Operator/Text.php:28
Stack trace:
#0 vendor/pimcore/pimcore/lib/DataObject/GridColumnConfig/Operator/Factory/DefaultOperatorFactory.php(36): Pimcore\DataObject\GridColumnConfig\Operator\Text->__construct(Object(stdClass), Array)
#1 vendor/pimcore/pimcore/lib/DataObject/GridColumnConfig/Service.php(99): Pimcore\DataObject\GridColumnConfig\Operator\Factory\DefaultOperatorFactory->build(Object(stdClass), Array)
#2 vendor/pimcore/pimcore/lib/DataObject/GridColumnConfig/Service.php(83): Pimcore\DataObject\GridColumnConfig\Service->buildOperator('Text', Object(stdClass), Array)
#3 vendor/pimcore/pimcore/lib/DataObject/GridColumnConfig/Service.php(57): Pimcore\DataObject\GridColumnConfig\Service->doBuildConfig(Array, Array, Array)
#4 vendor/pimcore/pimcore/models/DataObject/Service.php(515): Pimcore\DataObject\GridColumnConfig\Service->buildOutputDataConfig(Array, Array)
#5 vendor/pimcore/pimcore/models/DataObject/Service.php(537): Pimcore\Model\DataObject\Service::getConfigForHelperDefinition(Array, '#5e7cd1d52a3ce', Array)
#6 vendor/pimcore/pimcore/models/DataObject/Service.php(330): Pimcore\Model\DataObject\Service::calculateCellValue(Object(Pimcore\Model\DataObject\DfInquiryContainer), Array, '#5e7cd1d52a3ce', Array)
#7 vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php(1748): Pimcore\Model\DataObject\Service::gridObjectData(Object(Pimcore\Model\DataObject\DfInquiryContainer), Array, 'de')
#8 vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(146): Pimcore\Bundle\AdminBundle\Controller\Admin\DataObject\DataObjectController->gridProxyAction(Object(Symfony\Component\HttpFoundation\Request), Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher), Object(Pimcore\Bundle\AdminBundle\Helper\GridHelperService))
#9 vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#10 vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(201): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#11 web/app.php(36): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#12 {main}
```

### CODE REVIEW

**Comment by blankse** [comment]
In the Concatenator operator is a property `forceValue `that cannot be set in the admin interface.

**Comment by blankse** [comment]
There is also a PropertyGetter which I can't select in the admin interface.

So I tested all operators :) Can you review it @weisswurstkanone ?

**Comment by weisswurstkanone** [comment]
Hi @blankse is the comment about PropertyGetter still valid ?

**Comment by blankse** [comment]
@weisswurstkanone No I correct both issues:

- In the Concatenator operator is a property forceValue that cannot be set in the admin interface. https://github.com/pimcore/pimcore/pull/6104/commits/e3db3a34a8e6e7b59b05b95e70c09d79b01ad63
- There is also a PropertyGetter which I can't select in the admin interface. https://github.com/pimcore/pimcore/pull/6104/commits/47e0cfa531e2b2003af25ad38323bfc49977084c

**Comment by weisswurstkanone** [comment]
@blankse great, thanks! also for cleaning up 👍

**Pull request merged**
