### PR TITLE
Fix insertOrUpdate on tables without primary keys

### PR DESCRIPTION
**Pull request by blankse**
Since https://github.com/pimcore/pimcore/pull/11159 the insertOrUpdate method throws an exception if the table has no primary key. See tests in customer-data-framework:

```
1) ActivityTest: Track activity
 Test  tests/Model/Activity/ActivityTest.php:testTrackActivity

  [Doctrine\DBAL\Exception] Table plugin_cmf_deletions has no primary key.  

/home/runner/work/customer-data-framework/customer-data-framework/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Table.php:743
/home/runner/work/customer-data-framework/customer-data-framework/vendor/pimcore/pimcore/lib/Db/PimcoreExtensionsTrait.php:348
/home/runner/work/customer-data-framework/customer-data-framework/src/CustomerSaveManager/DefaultCustomerSaveManager.php:282
/home/runner/work/customer-data-framework/customer-data-framework/src/CustomerSaveManager/DefaultCustomerSaveManager.php:236
/home/runner/work/customer-data-framework/customer-data-framework/src/Event/PimcoreObjectEventListener.php:135
/home/runner/work/customer-data-framework/customer-data-framework/vendor/symfony/event-dispatcher/Debug/WrappedListener.php:117
/home/runner/work/customer-data-framework/customer-data-framework/vendor/symfony/event-dispatcher/EventDispatcher.php:230
/home/runner/work/customer-data-framework/customer-data-framework/vendor/symfony/event-dispatcher/EventDispatcher.php:59
/home/runner/work/customer-data-framework/customer-data-framework/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:154
/home/runner/work/customer-data-framework/customer-data-framework/vendor/pimcore/pimcore/models/DataObject/AbstractObject.php:660
/home/runner/work/customer-data-framework/customer-data-framework/vendor/pimcore/pimcore/tests/_support/Util/TestHelper.php:834
/home/runner/work/customer-data-framework/customer-data-framework/vendor/pimcore/pimcore/tests/_support/Util/TestHelper.php:796
/home/runner/work/customer-data-framework/customer-data-framework/tests/Model/Activity/ActivityTest.php:21
/home/runner/work/customer-data-framework/customer-data-framework/vendor/phpunit/phpunit/src/Framework/TestCase.php:1197
/home/runner/work/customer-data-framework/customer-data-framework/vendor/phpunit/phpunit/src/Framework/TestResult.php:726
/home/runner/work/customer-data-framework/customer-data-framework/vendor/phpunit/phpunit/src/Framework/TestCase.php:903
/home/runner/work/customer-data-framework/customer-data-framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php:678
/home/runner/work/customer-data-framework/customer-data-framework/vendor/codeception/phpunit-wrapper/src/Runner.php:117
/home/runner/work/customer-data-framework/customer-data-framework/vendor/codeception/codeception/src/Codeception/SuiteManager.php:161
/home/runner/work/customer-data-framework/customer-data-framework/vendor/codeception/codeception/src/Codeception/Codecept.php:208
/home/runner/work/customer-data-framework/customer-data-framework/vendor/codeception/codeception/src/Codeception/Codecept.php:162
/home/runner/work/customer-data-framework/customer-data-framework/vendor/codeception/codeception/src/Codeception/Command/Run.php:544
/home/runner/work/customer-data-framework/customer-data-framework/vendor/codeception/codeception/src/Codeception/Command/Run.php:408
/home/runner/work/customer-data-framework/customer-data-framework/vendor/symfony/console/Command/Command.php:298
/home/runner/work/customer-data-framework/customer-data-framework/vendor/symfony/console/Application.php:1005
/home/runner/work/customer-data-framework/customer-data-framework/vendor/symfony/console/Application.php:299
/home/runner/work/customer-data-framework/customer-data-framework/vendor/symfony/console/Application.php:171
/home/runner/work/customer-data-framework/customer-data-framework/vendor/codeception/codeception/src/Codeception/Application.php:117
/home/runner/work/customer-data-framework/customer-data-framework/vendor/codeception/codeception/app.php:46
/home/runner/work/customer-data-framework/customer-data-framework/vendor/codeception/codeception/app.php:47
/home/runner/work/customer-data-framework/customer-data-framework/vendor/codeception/codeception/codecept:7
/home/runner/work/customer-data-framework/customer-data-framework/vendor/bin/codecept:107
```

### CODE REVIEW

**Comment by blankse** [comment]
Additional I think there should be primary key columns. I create there an issue https://github.com/pimcore/customer-data-framework/issues/251

**Comment by blankse** [comment]
Can be tested also in the demo. Simply try to delete a Customer object.

**Comment by yamenalahlas** [comment]
it still does not work 


Bildschirmfoto 2022-01-29 um 15 31 38
Bildschirmfoto 2022-01-29 um 20 43 00
Bildschirmfoto 2022-01-29 um 20 43 15

**Comment by blankse** [comment]
@yamenalahlas This change is not released yet. Do you really checkout the pimcore 10.2 branch?

**Comment by yamenalahlas** [comment]
I think so,
Bildschirmfoto 2022-01-29 um 21 08 30

**Comment by blankse** [comment]
@yamenalahlas You are at tag v10.2.9 This change will be part of v10.2.10

**Comment by yamenalahlas** [comment]
sorry am still new with Pimcore, I didn't quite understand it 
should i upgrade my Version ? or this Problem will be Fixed at the next Version !
thank you very much.

**Comment by blankse** [comment]
@yamenalahlas The problem is fixed with the next version. This should be released on Wednesday.

**Comment by yamenalahlas** [comment]
Ok ver good, thanks again

**Pull request merged**
