### PR TITLE
Cast request params to right type

### LINKED ISSUE #13979: [Bug]: Advanced Relation Many-Many Error
### Expected behavior

Allow adding advanced many-many with no errors.

### Actual behavior

When adding a new advanced many-many relation we get type errors.

`Message: Pimcore\Bundle\AdminBundle\Controller\Admin\DataObject\DataObjectHelperController::getDefaultGridFields(): Argument #4 ($noBrickColumns) must be of type bool, string given, called in /var/www/html/vendor/pimcore/pimcore/bundles/AdminBundle/src/Controller/Admin/DataObject/DataObjectHelperController.php on line 371`

image

### Steps to reproduce

1. Checkout `11.x` branch or go to `11.x` demo site (https://11.x-dev.pimcore.fun/admin/)
2. Add `Advanced Many-To-Many Object Relation`
3. Error above will appear

### PR DESCRIPTION
**Pull request by blankse**
Fix https://github.com/pimcore/pimcore/issues/13979

### CODE REVIEW

**Comment by torqdev** [comment]
Hi @blankse, thank you for the very quick fix. We also noted that even when casting this parameter to a boolean, there's another issue with this function on the `fields` parameter (it complains about not accepting null values). Our suggested fix is to make it nullable, i.e. changing
`public function getDefaultGridFields(bool $noSystemColumns, ?DataObject\ClassDefinition $class, string $gridType, bool $noBrickColumns, array $fields, array $context, int $objectId, array $types = []): array`
to
`public function getDefaultGridFields(bool $noSystemColumns, ?DataObject\ClassDefinition $class, string $gridType, bool $noBrickColumns, ?array $fields, array $context, int $objectId, array $types = []): array`

**Comment by blankse** [comment]
@torqdev I changed the fields param to nullable

**Comment by lukmzig** [comment]
Thank you for the fix, looks good.

**Comment by fashxp** [comment]
that PR destroys Asset upload and potentially other things ... every request needs to be double checked

**Pull request merged**
