### PR TITLE
Update VideoProcessor

### PR DESCRIPTION
**Pull request by dpfaffenbauer**
Stop further processing of the thumbnail if ffmpeg fails to generate it

### CODE REVIEW

**Comment by fashxp** [comment]
@dpfaffenbauer could you please have a look at the phpstan ... thx.

**Comment by brusch** [comment]
@dpfaffenbauer 🏓

**Comment by dpfaffenbauer** [comment]
@fashxp fixed, but now it complains about changes outside my pr.

**Comment by dvesh3** [comment]
@dpfaffenbauer please rebase to the fix the failing Phpstan tests.

**Comment by brusch** [comment]
🍒-picked and squashed this PR into #12402

**Comment by dpfaffenbauer** [comment]
thanks @brusch

**Pull request closed without merging**
