### PR TITLE
[Recycle Bin] Fix restoring relations in Localized Fields, Object Bricks and Field Collections

### LINKED ISSUE #5255: [Recycle Bin] Localized Fields, Object Bricks and Field Collections are not getting restored
If single item restore, works for nested restores

### PR DESCRIPTION
**Pull request by dvesh3**
## Changes in this pull request  
Resolves #5255

### CODE REVIEW

**Comment by brusch** [comment]
Well, so your suggestion is to just keep the bug? Alright, I understand 😉

**Comment by brusch** [comment]
Let me clarify one thing here: we are not responsible to check any of our changes against compatibility with Doctrine entities, so this is actually not a BC break, it's just a bug fix nothing else.

**Comment by dpfaffenbauer** [comment]
Changing behavior in a patch release is the point here. That change was not a bug, so it does not have to be in a patch release. Doing that with Pimcore 6.5 wouldn’t be an issue. 

It is just too hard to maintain Plugins for Pimcore with the way you keep changing and breaking stuff.

**Comment by dpfaffenbauer** [comment]
BTW: you also recommend doctrine for custom entities in your docs: https://pimcore.com/docs/6.x/Development_Documentation/Extending_Pimcore/Custom_Persistent_Models.html

So it should also work in combination with Pimcore Elements.

**Pull request merged**
