### PR TITLE
New option in classs definition: Disallow deletion of objects if dependencies exist 

### PR DESCRIPTION
**Pull request by Lexipowder**
image

Helps to keep data consistent. System critial data, like masterdata, can't be deleted as long dependencies exist.

### CODE REVIEW

**Comment by BlackbitNeueMedien** [comment]
This currently only protects objects in the Pimcore GUI, doesn't it?
To be consistent we would also need to protect objects which are tried to be deleted via code, e.g.
```php
$object = new \Pimcore\Model\DataObject\Product();
$category = new \Pimcore\Model\DataObject\Category(); // must not be deleted when it has dependencies
$object->setCategories([$category]);
$object->save();
$category->delete();
```

**Comment by Lexipowder** [comment]
Our idea was to avoid any inconsistencies caused by any kind of GUI-User / System-Admin. Deletion by code would be system designer hemisphere and we hope that they know what to code. 

But I can see the point, on the other hand due to the given database structure it is always possible to delete/destroy any object by a simple SQL-command:
DELETE FROM `database`.`objects` WHERE (`o_id` = '390');
which btw leads to dead fragments in the database. 

As pimcore is an open system and the database engine, as well the structure of the database allows any system designer to delete via code on several levels, I see no chance to avoid inconsistencies caused by system designer level with the given database structure

If $object->delete() has to be extended with the check if dependencies exist in order that the PR will be accepted we will look into it. 

Please let me know your thoughts.

BTW have you seen my comment here: https://github.com/pimcore/pimcore/issues/3951
Can you double check, if you have the same issue with the current version.

**Comment by brusch** [comment]
First of all thanks a lot for your contribution! 
I'm not sure if this is topic is really of general interest or if this is just a special project specific requirement. I'd rather say it's not. 

This functionality can also be easily implemented using events - even a generic configurable bundle would be possible - so there's no need to have that directly in the core. 

Any other opinions on that? 
Thanks!

**Comment by brusch** [comment]
Also this PR only does checks in the UI but not on the server-side, so `$object->delete()` wouldn't be covered. But let's wait for other opinions first 😉

**Comment by brusch** [comment]
Since there were no other opinions on that, I'll close that for now.
Feel free to continue the discussion, in the meantime you can use event approach described above.

**Pull request closed without merging**
