### PR TITLE
Fix incorrect Custom Reports dialog label

### PR DESCRIPTION
**Pull request by NiklasBr**
## Changes in this pull request  

Label in UI dialog should be clearer about it's technical requirements and the regex shown should match the actual rule on line 168.

### CODE REVIEW

**Review by mattamon — CHANGES_REQUESTED** [review]
Can we maybe rebase this to 10.6?
This is not really a bug for 10.5 and since 10.5 should mostly consist only of bugfixes (with some exceptions) I feel like this should go into 10.6.

**Comment by NiklasBr** [comment]
Are not user interface bugs bugs?

**Comment by mattamon** [comment]
> Are not user interface bugs bugs?

Well this info does not change any functionality does it? :) It only clarifies the underlying intention. I would not consider this as a bug, because it works as intended even though parts of the info is missing. I agree that we should change it though.

**Comment by NiklasBr** [comment]
The bug was **incorrect** _and_ missing information in the UI. Why are you so reluctant to allow bugfixes today? By your logic a missing `if` statement or a missing `function` argument would not be considered bugs either because the code worked as intended even though parts were missing.

**Comment by mattamon** [comment]
@NiklasBr this is not what I wrote/meant. We are still talking about this specific PR, not a general approach.
We decided in the team, that we will ask you nicely to rebase it to 10.6 but since you insist we'll keep it for 10.5.

**Comment by NiklasBr** [comment]
Now it's no longer a UI change. Maybe this bug fix is a correct bug fix. Thanks for your feedback.

**Comment by mattamon** [comment]
As I wrote in my last comment, we agreed to keep it for 10.5, so I directly pushed your previous commit to 10.5

**Pull request closed without merging**
