### PR TITLE
[Doc] Fix config/pimcore/classes path

### PR DESCRIPTION
**Pull request by blankse**
Path must relative and not absolute

### CODE REVIEW

**Comment by blankse** [comment]
@brusch I set `PIMCORE_CLASS_DEFINITION_WRITABLE=true` in the .env file but `getenv('PIMCORE_CLASS_DEFINITION_WRITABLE')` in the isWritable methods is false. Seems there is a bug.

**Comment by blankse** [comment]
I create another PR for this: https://github.com/pimcore/pimcore/pull/10804

**Comment by blankse** [comment]
@brusch Next problem: The `pimcore:deployment:classes-rebuild` command doesn't work if `PIMCORE_CLASS_DEFINITION_WRITABLE=true` is not set. So the live system can't generate the database changes and the DataObject folder.

The DataObject folder is also in config/pimcore/classes. So the autoload doesen't work anymore.
Has anyone used this feature before? :D

**Comment by brusch** [comment]
Thanks!

**Pull request merged**
