### PR TITLE
Fixed all KernelEvent::isMasterRequest() deprecation messages

### PR DESCRIPTION
**Pull request by h4rdc0m**
## Changes in this pull request  
Fixes the deprecation messages in the log about isMasterRequest deprecation, changed all of them into isMainRequest as per Symfony standard.

### CODE REVIEW

**Comment by jdreesen** [comment]
This would require updating to Symfony 5.3 as minimum version, as the method `isMainRequest()` has [been introduced](https://github.com/symfony/symfony/blob/5.3/UPGRADE-5.3.md#httpkernel) in that version.

**Comment by h4rdc0m** [comment]
Seems that the test suite installs symfony 5.2 instead of 5.3 when you install per instruction

**Comment by h4rdc0m** [comment]
> This would require updating to Symfony 5.3 as minimum version, as the method `isMainRequest()` has [been introduced](https://github.com/symfony/symfony/blob/5.3/UPGRADE-5.3.md#httpkernel) in that version.

Problem is that when you install per instruction Symfony 5.3 is installed, makes reading logs very hard.
"symfony/symfony": "^5.2.0", means that anything up to 6.0.0 will be installed on new installs.

**Comment by brusch** [comment]
I think you should just exclude the deprecation messages in Monolog.

**Pull request closed without merging**
