### PR TITLE
Color picker

### PR DESCRIPTION
**Pull request by Yivan**
This is a pull request for https://github.com/pimcore/pimcore/issues/733.

It is very light implementation, based on html5 color input type. No external dependency, just a checkbox for input field "Is color" has been added. If checked, it change the type of input to "color" instead of "text" in the edit layout only.
So it doesn't introduce new datetype, just some small code changes, and provide just a great helper tool for color selection (for HTML5 compatible browser: http://caniuse.com/#feat=input-color , cover nearly 70%, and last chrome/firefox version, the more used by Pimcore administrator).

Sample:
colorpicker

### CODE REVIEW

**Comment by Yivan** [comment]
Translation for "is_color" need to be added, i don't know the procedure. Is it on you side ?

**Comment by Yivan** [comment]
By the way, i fixed the maxLength problem: it was only cutted in the save (server side), so enduser was not aware that some part of the text he fill could be lost (until he reopened the object).
Now it prevent typing more caracters than allowed.

**Comment by brusch** [comment]
Thanks for the max-length fix -> merged.

**Comment by brusch** [comment]
*Color* should be a dedicated data-type which can extend the input data-type. Adding an `isColor` flag to the input is a very bad idea and a pretty hacky solution. 

Please have a look at `email`, `time` or `firstname`, they all extend input but represent a dedicated data-type. The *color* data-type should have a proper validation (hex, rgb) and database column (6 digits).

**Comment by Yivan** [comment]
Thanks brush to had a look on my PR.
The purpose of this PR was to not introduce new datatype and be a very lightweight solution, wich is it is true "hacky" ; ) A new data type will be better for data integrity sure.

Is such a new datatype planned ? I think it is better that the core team develop such feature, but if you want i can try a PR for this, you just need to give me expected specifications so i go in the good direction (native HTML5 or JS plugin, database type: 6 digits, no "#" - would have to be text field in this case, ...) ?

**Comment by brusch** [comment]
Currently we don't have this feature on our roadmap. 
The native HTML5 color picker widget sounds like the easiest option, but I'm missing some features like direct hex input, predefined colors, ... so I don't think we should use it at the moment. 
ExtJS offers also a color picker, but again, very limited :( 
So I'm not sure what the best option would be. But you can develop the data-type as a plugin and share it on packagist so you're completely independent and you decide how it should work :)

**Comment by brusch** [comment]
Here is an example plugin that provides a data-type: 
https://github.com/weblizards-gmbh/dynamicdropdown-plugin

**Comment by Yivan** [comment]
Ok thanks brush! Yes native HTML5 depend of browser/OS. On Windows 7/Firefox as you can see there is predefined color, but not hex input. On JS color picker will be more generic/same on different plateform. I will think about a plugin.

**Pull request closed without merging**
