### PR TITLE
Use readonly attribute for readonly input fields - not disabled

### PR DESCRIPTION
**Pull request by BlackbitNeueMedien**
When you set an input field to be not editable, Pimcore uses ExtJS's disable() method in the input field. This leads to being not able to highlight or copy contents of such readonly fields in Firefox. Anyway readonly is the more approprate attribute for setting something to be not editable.
With this PR readonly attribute is used.

### CODE REVIEW

**Comment by brusch** [comment]
If we change that, we should change it for all affected data-types, right? 

That would be additionally: 
- Textarea
- Quantity Value
- Input Quantity Value
- Date
- Date Time
- Time
- Select (incl. all descendants) 
- External Image
- Calculated Field

**Comment by BlackbitNeueMedien** [comment]
Tested with normal text input field and tooltip works as expected also with readonly.

Will update the other data types tomorrow...

**Comment by brusch** [comment]
@BlackbitNeueMedien Thanks!

**Comment by BlackbitNeueMedien** [comment]
Ok, I added the data types mentioned by @brusch - only Ext.ux.form.MultiSelect does not support setReadOnly(). Thus I kept disable for multiselect.

**Comment by brusch** [comment]
@BlackbitNeueMedien looks good, thanks a lot!

**Comment by fashxp** [comment]
date time does not support setReadonly ... see #3718

**Pull request merged**
