### PR TITLE
Added min/max value to time class definition.

### PR DESCRIPTION
**Pull request by cleggypdc**
One of our clients needed a minimum value on time fields, so rather than add this restriction into an event I modified the core class definition file so that you can define both a min and maximum value from within the class builder:

image

Hope that this is useful!

There are a couple of translations required in the admin / POE Editor:
min_max_times : "Min / Max Times"
reset: "Reset"

### CODE REVIEW

**Comment by weisswurstkanone** [comment]
Since Oct. 29th the master translations are not managed in the POE Editor anymore. Just add them to en.json and commit them ...
Could you provide another pull request?

**Comment by cleggypdc** [comment]
Thanks Josef, I have updated the pull request.

**Comment by weisswurstkanone** [comment]
Hi Paul, cool feature. What I noticed is that you can still enter "invalid" values via the keyboard. I guess the Ext.form.TimeField validation logic works different that for the number field?

**Comment by cleggypdc** [comment]
Thanks! I have updated to prevent keyboard entry on min/max values

**Comment by weisswurstkanone** [comment]
timetag

Hi, I guess I was not clear enough :-)  I was talking about the tag. See the screenshot. I am not sure if there is an easy way to prevent this ... 
Maybe by adding a check on the server side (similar to the numeric field) ?

**Comment by brusch** [comment]
Hi Paul, 

Are there any updates on the issue mentioned above?
I think if we introduce min/max limitations we should also validate them appropriately, which isn't the case at the moment. I think the easiest way would be to validate this just on the server side, to also ensure that modifications on the API are covered. This is simply done by implementing the checkValidity() method in the data type. 

See also: 
https://github.com/pimcore/pimcore/blob/master/pimcore/models/Object/ClassDefinition/Data/Input.php#L188

Thanks!

**Comment by cleggypdc** [comment]
Hi Bernhard,

i've added a server side check which I think should cover all bases. The checkValidility converts the sent times to a relative timestamp to compare the range.

**Pull request closed without merging**
