### PR TITLE
[Docs] How to remove a cache item created be the templating helper

### PR DESCRIPTION
**Pull request by ultramegatom**
add doc on how to remove a cache item created by the templating helper

### CODE REVIEW

**Comment by brusch** [comment]
I think it would be better to provide a method on the helper to clear an item, because the prefix may change in the future or additional suffixes such as `webp` will be added.

**Comment by ultramegatom** [comment]
@brusch 
was thinking about that but not sure where to but that. Seems pretty useless inside the helper since i would never clear the cache inside a view. And getting a templating helper and calling a method on it in application code seems like super ugly to me.

Doesn't really seem to fit inside the \Pimcore\Cache class either.

So not sure whats our best option here.

**Comment by dpfaffenbauer** [comment]
@ultramegatom Create a new Service that will also be used by the helper that takes care about Template Caches.

**Comment by brusch** [comment]
@ultramegatom @dpfaffenbauer yes, a dedicated service that handles the caching in templates would be the best solution (should be also used by the helper). 
I'll close this PR for now, please create a new PR for the new service.

**Pull request closed without merging**
