### PR TITLE
Revert to latest phpstan release

### PR DESCRIPTION
**Pull request by weisswurstkanone**

### CODE REVIEW

**Comment by NiklasBr** [comment]
Why?

**Comment by weisswurstkanone** [comment]
Because I downgraded to an older version a couple of days ago

**Comment by NiklasBr** [comment]
That was my question. Why revert PHPStan to an outdated version?

**Comment by weisswurstkanone** [comment]
It isn't.
As you see in the build log it uses 0.12.28 now (instead of 0.12.25)

**Pull request merged**
