### PR TITLE
Re-add AdminSessionAuthenticator for session authentication from external systems

### PR DESCRIPTION
**Pull request by dvesh3**
## Changes in this pull request  
follow up to #13909

## Additional info  
Resolves https://github.com/pimcore/openid-connect/issues/54

### CODE REVIEW

**Comment by dpfaffenbauer** [comment]
can't the open-id provider add that?

**Comment by dvesh3** [comment]
@dpfaffenbauer I was just thinking of other custom implementations which relies on user being set on session and that should authenticate successfully. Anyway `Authentication::authenticateSession()` should respect the user being set already on session before checking token. wdyt?

**Comment by kingjia90** [comment]
Needs to add the service, like 
https://github.com/pimcore/pimcore/blob/8041cb5d6d593d1a5afaa42cc54656e08c660ad6/bundles/AdminBundle/config/security_services.yaml#L25

I am facing a problem where the js files are "redirecting" to login page.
image
image
after reloading 2 times, it logs out

**Comment by dpfaffenbauer** [comment]
@dvesh3 I don't really see the use-case, but I guess it is fine to have it in the core.

**Comment by dvesh3** [comment]
> Needs to add the service, like
@kingjia90 Done.

**Comment by kingjia90** [comment]
> I am facing a problem where the js files are "redirecting" to login page. image image after reloading 2 times, it logs out

Thank you @dvesh3, but this problem is still there, only if i revert `stateless: true` it would work, could you please double-check this 

https://github.com/pimcore/pimcore/pull/13909/files?w=1#diff-ee8ff688fded8943af83197fb3b0953bf27ea9ff986d6754f5c4d1a5b5767a3eL22-L24

**Comment by dvesh3** [comment]
@kingjia90 `stateless` was already [kicked](https://github.com/pimcore/demo/pull/407/files#diff-19446c4b69407952b20ae26dbd032cdad8dcc487db081a5cb17261831e80a4cc) in the last refactoring. Please check you must be using old config.

**Comment by dvesh3** [comment]
@kingjia90 it works for me without `stateless: true`. please update your security.yaml as per https://github.com/pimcore/demo/pull/429

**Comment by dvesh3** [comment]
this needs discussion, if we should re-add this authenticator.

**Comment by dvesh3** [comment]
We are facing some side effects with this PR, loading user from the session so closing it and the OpenIdConnect will then implement it's own authenticator.

**Pull request closed without merging**
