### PR TITLE
Removed session configurators

### LINKED ISSUE #12472: Remove session configurators
### Improvement description

Follow up to #12294

### PR DESCRIPTION
**Pull request by dvesh3**
## Changes in this pull request  
Resolves #12472

### CODE REVIEW

**Comment by dvesh3** [comment]
This PR needs https://github.com/pimcore/pimcore/pull/12873 to be merged for passing tests.

**Review by aashan10 — APPROVED** [review]

**Review by aashan10 — COMMENTED** [review]
Please resolve the conflicts @dvesh3

**Comment by dvesh3** [comment]
> Please resolve the conflicts @dvesh3

done!

**Comment by aashan10** [comment]
@dvesh3 there still is a conflict in upgrade notes

**Comment by dvesh3** [comment]
> @dvesh3 there still is a conflict in upgrade notes

@aashan10 done

**Review by aashan10 — APPROVED** [review]

**Comment by kingjia90** [comment]
What about these occurrences?

https://github.com/pimcore/pimcore/blob/b7d67edaaebeb366b5ddfcfc5983a1e20e139c53/bundles/CoreBundle/Resources/config/pimcore/default.yaml#L258-L265

**Comment by brusch** [comment]
Probably also related: 
https://github.com/pimcore/pimcore/blob/38419b06c61565e62122e32684e37c102cbe25d2/bundles/AdminBundle/src/EventListener/AdminSessionBagListener.php#L70
https://github.com/pimcore/pimcore/blob/70b1db360a2a4fa498c69f71a33aa1db5a3a42d1/bundles/CoreBundle/DependencyInjection/Configuration.php#L1126

**Comment by dvesh3** [comment]
@kingjia90 yes, @brusch is right that these are still being used in `AdminSessionBagListener` to register session bags.

**Pull request merged**
