### PR TITLE
Ecom Framework JS and CSS updates

### PR DESCRIPTION
**Pull request by NiklasBr**
Some libraries have waited a long time to be updated. Native JavaScript for Bootstrap upgrade [includes some minor breaking changes](https://github.com/thednp/bootstrap.native/releases/tag/3.0.0), but they appear to be for non-supported browsers and Bootstrap versions so that should not affect Pimcore.

And the `head_ie_stylesheets` should no longer be relevant, right?

### CODE REVIEW

**Comment by NiklasBr** [comment]
@brusch For version 11, what if these were installed using NPM or some such tool?

**Comment by brusch** [comment]
@NiklasBr yeah, would definitely make sense

**Comment by NiklasBr** [comment]
There is a slight difference in x-height on some lower-case words in an updated version of Open Sans (the drop-downs on the right), that's ok?

image
image

**Comment by brusch** [comment]
@NiklasBr what's causing the difference? Updating Bootstrap shouldn't have any effects on ExtJS right?

**Comment by NiklasBr** [comment]
I tested an updated version of Open Sans as well as part of this PR because I was hoping that it should fix these errors (which it appears to do)

image

**Comment by dvesh3** [comment]
@NiklasBr Please don't forget to update current version for libraries in the [PIMCORE_MODIFICATIONS.md](https://github.com/pimcore/pimcore/blob/10.x/bundles/AdminBundle/Resources/public/js/lib/PIMCORE_MODIFICATIONS.md#ace-editor). Thanks!

**Comment by NiklasBr** [comment]
@dvesh3 I not sure I understand the docs fully. Does "clean up" mean something different than "remove" or "delete"?

**Comment by dvesh3** [comment]
> @dvesh3 I not sure I understand the docs fully. Does "clean up" mean something different than "remove" or "delete"?

Nope. It just means removing extra files, which are not used anywhere.

**Comment by mcop1** [comment]
After applying the changes I noticed that the edit/cancel/complain item buttons, in the back office order list, aren´t working anymore:
image

Console output:
image

https://github.com/pimcore/pimcore/blob/10.x/bundles/EcommerceFrameworkBundle/Resources/views/back-office.html.twig#L91

Could you please have a look?

**Comment by mcop1** [comment]
@NiklasBr Any chance you had some time to take a look at this topic?

**Comment by dvesh3** [comment]
@NiklasBr please see https://github.com/pimcore/pimcore/pull/10606#issuecomment-994905354

**Comment by NiklasBr** [comment]
@dvesh3 Will do

**Comment by brusch** [comment]
@NiklasBr Any updates on this 😊 Thanks in advance!

**Comment by NiklasBr** [comment]
I'll probably have some time next week

**Comment by mcop1** [comment]
Hello @NiklasBr ,
just wanted to ask if you are still going to update this pr?

**Comment by NiklasBr** [comment]
@mcop1 Awaiting the new admin UI since I suspect lost of things here will be of no use once that is revealed.

**Comment by fashxp** [comment]
New admin ui won't arrive with Pimcore 11.0 ... So we should get this done.

**Comment by NiklasBr** [comment]
Closing due to lack of time and #14399

**Pull request closed without merging**
