### PR TITLE
Use DeepClone 1.9

### LINKED ISSUE #4203: DeepCopy 1.9.0 not working with Pimcore
Withing a `composer update` process, deep-copy gets updated to "`1.9.0`":

https://github.com/pimcore/pimcore/blob/9bdb03c8c8cdbf002661be2df54c60112e8d808a/composer.json#L68

After this update, no document / object can be copied anymore:

```json
Fatal error:  Declaration of class@anonymous::matches($object, $property) must be compatible with DeepCopy\Matcher\Matcher::matches(object $object, ReflectionProperty $reflectionProperty): bool in /var/www/public/vendor/pimcore/pimcore/models/Element/Service.php on line 1054
{"success":false,"message":"Compile Error: Declaration of class@anonymous::matches($object, $property) must be compatible with DeepCopy\\Matcher\\Matcher::matches(object $object, ReflectionProperty $reflectionProperty): bool","trace":[],"traceString":"#0 {main}"}
```

### PR DESCRIPTION
**Pull request by solverat**
Resolves #4203.

### CODE REVIEW

**Comment by brusch** [comment]
Grazie Mille!

**Comment by fashxp** [comment]
@solverat did you test that?

**Comment by solverat** [comment]
@fashxp, yes we duplicated a full language tree. why?

**Comment by fashxp** [comment]
damn, they changed it again... see release 1.9.1 ...

**Comment by fashxp** [comment]
so, we should be able to just revert this PR.

**Comment by solverat** [comment]
i see...

**Pull request merged**
