### PR TITLE
[GridHelperService] Fix Notice: Undefined index: value

### PR DESCRIPTION
**Pull request by blankse**
1. Open Asset Folder
2. Filter file name with no input
3. Get error:
image

### CODE REVIEW

**Comment by weisswurstkanone** [comment]
Just curious how exactly this can be reproduced. Was not able to reproduce this by enabling the filter checkbox. But doesn't hurt anyway :-)

thx!

**Comment by blankse** [comment]
@weisswurstkanone You must also set PIMCORE_PHP_ERROR_REPORTING to E_ALL

**Comment by weisswurstkanone** [comment]
I know, it is turned on :-)

**Comment by blankse** [comment]
Strange... :thinking:

**Pull request merged**
