### PR TITLE
[DOC] Official documentation corrections for Routing and URLs

### PR DESCRIPTION
**Pull request by dvelguru**
Improved the documentation for how routing is processed by priority.

### CODE REVIEW

**Comment by dvesh3** [comment]
@dvelguru 0 File changes?

**Comment by dvelguru** [comment]
> @dvelguru 0 File changes?

What do you mean?

**Comment by dvelguru** [comment]
> @dvelguru 0 File changes?

Hi dvesh3, I see what you mean. I have to fix this.

**Review by dvelguru — COMMENTED** [review]
Undo revert

**Comment by dvelguru** [comment]
Testing the Reopening and Committing to a Pull Request for a valid issue.

**Comment by dvelguru** [comment]
Testing the Reopening and Committing to a Pull Request for a valid issue.

**Comment by dvelguru** [comment]
> @dvelguru 0 File changes?

Hi dvesh3, ok I fixed it and now everything should be fine.

**Comment by dvesh3** [comment]
thanks @dvelguru!

**Pull request merged**
