### PR TITLE
Version: Don't throw exception to generate StackTrace

### PR DESCRIPTION
**Pull request by blankse**
See https://github.com/orgs/pimcore/discussions/16684

### CODE REVIEW

**Comment by quayle** [comment]
Thank you for answer. Yet, why that stacktrace is generated. What's the purpose of storing it on every save, even if it is not thrown?

**Comment by blankse** [comment]
@quayle I think it was added to be able to understand why the version was created. So rather for debugging purposes. Maybe @brusch knows more.

But you can deactivate it via configuration:
```
pimcore:
    assets:
        versions:
            disable_stack_trace: true
    documents:
        versions:
            disable_stack_trace: true
    objects:
        versions:
            disable_stack_trace: true
```

I see this configuration is not documented. I will add a doc.

**Comment by quayle** [comment]
Ok. It clarified a little.. Still, this is weird for me. 

I would suggest, to add comment about that before yours:
`$this->stackTrace = (new \Exception())->getTraceAsString();`

IMHO, any debugging informations should be passed to logger. Not into DB.

**Comment by mcop1** [comment]
Hello @blankse , thank you for the PR. Think we could even base it on the 11.2 branch and include it in the bugfix release? Would be good to have the documentation part there. What do you think?

**Comment by blankse** [comment]
@mcop1 I changed the target branch

**Comment by mcop1** [comment]
@blankse thank you!
@quayle If you would like to see that behavior changed, please create a new ticket

**Pull request merged**
