### PR TITLE
[Events] Symfony version agnostic EventDispatcher

### PR DESCRIPTION
**Pull request by BlackbitNeueMedien**
As I was annoyed by all the deprecation notices like `Calling the "EventDispatcher::dispatch()" method with the event name as the first argument is deprecated since Symfony 4.3, pass it as the second argument and provide the event object as the first argument instead.` which come from the Pimcore core, I created this decorator. The reason for the dispatch calls to have wrong order (in the sense of Symfony 4) is that in Pimcore 6.* we want to support Symfony 3 where the order of arguments of `EventDispatcher::dispatch()` was switched compared to now.
With this decorator we can switch to the new `dispatch()` syntax step by step without BC breaks.

A disadvantage is that developers would not get deprecation notices about application-specific events. But perhaps we find a way to also solve that until we can throw away this decorator when Pimcore will not support Symfony 3 anymore.

### CODE REVIEW

**Comment by dpfaffenbauer** [comment]
IMO: the disadvantage is disadvantage enough for me to not implement that. How am I supposed to know what to change in my application when you disable this notices?

**Comment by BlackbitNeueMedien** [comment]
@dpfaffenbauer That is what I said: Perhaps we find a way to distinguish between events dispatched by the core and events dispatched by the application.

**Comment by dpfaffenbauer** [comment]
Not sure if that even is possible properly. Only way to know is by checking for the path the event comes from, and that is still not a nice solution then, cause if requires dirty things like debug_backtrace.

I'd rather opt to make that an Application specific implementation than to merge that into the core...

**Comment by BlackbitNeueMedien** [comment]
Only works with Symfony 4 ;-(
In Symfony 3 there is
`Declaration of Pimcore\Event\EventDispatcher::dispatch($event) must be compatible with Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch($eventName, ?Symfony\Component\EventDispatcher\Event $event = NULL)`
But I cannot change the method signature because then it would be incpmpatible with the Symfony 4 variant...

**Pull request closed without merging**
