### PR TITLE
[BUG] - Use the correct CLI parameter for command

### PR DESCRIPTION
**Pull request by roland4432**
Updated the call for the console command to use the return value from the getFfmpegCli call

### CODE REVIEW

**Comment by dvesh3** [comment]
@roland4432 please rebase on 10.1, since this is a fix. thanks!

**Comment by roland4432** [comment]
@dvesh3 branch is now rebased on 10.1

**Comment by dvesh3** [comment]
@roland4432 Something went wrong, as you have unrelated commits in this PR. could you please create a fresh PR? thanks!

**Comment by dvesh3** [comment]
@roland4432 nevermind! I squashed and merged it. thanks!

**Pull request merged**
