### PR TITLE
fix seo panel tree route

### PR DESCRIPTION
**Pull request by solverat**
SEO Document editor does not work because of wrong route definition. Regression of https://github.com/pimcore/pimcore/pull/6146.

### CODE REVIEW

**Comment by blankse** [comment]
@solverat I think this should be done for 6.6 branch

**Comment by solverat** [comment]
Damn you‘re right. Going to rebase it tomorrow!

**Comment by solverat** [comment]
done

**Comment by weisswurstkanone** [comment]
thanks a lot!

**Pull request merged**
