### PR TITLE
Add self validating Value Objects

### LINKED ISSUE #91: Move value objects validation to the core
* Create a PR for pimcore/pimcore to provide value objects for basic types (positive integer, positive integer-array, path string,...) with validation directly in the constructor
* Use those value objects in our search models instead of our custom approach

### PR DESCRIPTION
**Pull request by martineiber**
## Changes in this pull request  
Resolves https://github.com/pimcore/generic-data-index-bundle/issues/91

## Additional info

 - BooleanArray
 - IntegerArray
 - PositiveInteger
 - PositiveIntegerArray
 - StringArray
 - Path

### CODE REVIEW

**Review by lukmzig — APPROVED** [review]
LGTM :)

**Comment by dpfaffenbauer** [comment]
What about symfony validator?!

**Review by markus-moser — APPROVED** [review]

**Comment by markus-moser** [comment]
> What about symfony validator?!

Symfony validator is not self-validating directly in the constructor. We wanted that our objects are validated directly on instantiation.

**Comment by dpfaffenbauer** [comment]
I probably don't see the bigger picture here since I don't have access to the linked repo, but why?

**Comment by markus-moser** [comment]
> I probably don't see the bigger picture here since I don't have access to the linked repo, but why?

Because then when you want to use a object it's guaranteed that it's in a valid state without the need of calling any validation functions.

**Comment by mattamon** [comment]
@dpfaffenbauer  
Here is a link about value objects. There stem from Domain Driven Design.
https://medium.com/@miladev95/value-objects-in-php-5459e74268fa#:~:text=Value%20objects%20are%20a%20programming%20concept%20that%20can%20be%20used,the%20domain%20of%20the%20application.

We had a lot of trainings in the last year and we want to improve the overall concept and consistency of data in the application.

**Review by lukmzig — APPROVED** [review]

**Pull request merged**
