### PR TITLE
WYSIWYG Menu Floating Fix

### LINKED ISSUE #14828: [Bug]: Floating WYSIWYG menu
### Expected behavior

WYSWIG menu is docked to the chosen attribute

### Actual behavior

WYSWIG menu for a chosen attribute is floating

### Steps to reproduce

**1.** Go to the Pimcore demo
**2.** Open any car object
**3.** Go to "Basedata" tab
**4.** Clink on the value of the "Description" attribute
**5.** WYSIWYG menu opens up

image

**6.** Scroll screen down
**7.** WYSWIG menu goes down and covers other attributes.

imagecovers

### PR DESCRIPTION
**Pull request by torqdev**
## Changes in this pull request  
Resolves #14828

### CODE REVIEW

**Comment by lukmzig** [comment]
@torqdev thank you for the contribution! Unfortunately I am still able to reproduce the reported issue, can you please double check?
Screenshot 2023-05-15 091702

**Comment by torqdev** [comment]
> @torqdev thank you for the contribution! Unfortunately I am still able to reproduce the reported issue, can you please double check? Screenshot 2023-05-15 091702

These are the results we are currently getting. We tried on multiple browsers, multiple resolutions. What browser are you currently using? 

https://github.com/pimcore/pimcore/assets/67965755/bb8ece0b-fbf1-4887-8eca-a5a8a04d0097

**Comment by lukmzig** [comment]
Hi @torqdev, 
I tried it again (I am using Chrome browser). The fix is working fine if there is a lot of content so the height of the screen is large (like in your video).
However, as in the original issue if I take the **car** Data Object from the demo as an example (so on the large screen there is actually no issue) and have a look at it on the small screen (e.g 1280x720) then the fix is not working anymore. 
Can you please have a look at this? Thank you very much!

**Comment by torqdev** [comment]
Hi @lukmzig, we were able to replicate the issue, and we adjusted the logic to attach the scroll event to parent panels.

**Comment by lukmzig** [comment]
Hi @torqdev! 
Thank you very much, looks better to be from the functionality perspective. We had a look on the code itself and it seems like this could potentially fire a really large amount of events as it is per scroll. We fear that this could lead to some issues, what is your opinion on that?

**Comment by lukmzig** [comment]
@torqdev could you please have a look at my previous comment? :) 
Also I would kindly ask you to rebase your PR to 10.6 as we are currently stopping bugfix releases for 10.5

**Comment by torqdev** [comment]
> @torqdev could you please have a look at my previous comment? :) Also I would kindly ask you to rebase your PR to 10.6 as we are currently stopping bugfix releases for 10.5

Hi @lukmzig,

Thanks for pointing that out, we added a `setTimeout` to prevent `CKEDITOR.document.getWindow().fire('scroll');` from being triggered multiple times.

We did notice that on version 11, the WYSIWYG is now tinymce and has the same issue. If this gets merged, we will have to investigate a fix for that as well.

**Comment by robertSt7** [comment]
Hi @torqdev, 

thanks for adding the timeout. The code of the two files look very similar, could you please extract it into a function in the [helper](https://github.com/pimcore/pimcore/blob/642096e0e1888077e61e38f3e1914ff02f196fc9/bundles/AdminBundle/Resources/public/js/pimcore/helpers.js) to avoid code duplication. 

Could you also please call this function then in the translations, because if we have a translation with many lines in it, we have the same problem.

Thanks a lot

**Comment by robertSt7** [comment]
> Hi @torqdev,
> 
> thanks for adding the timeout. The code of the two files look very similar, could you please extract it into a function in the [helper](https://github.com/pimcore/pimcore/blob/642096e0e1888077e61e38f3e1914ff02f196fc9/bundles/AdminBundle/Resources/public/js/pimcore/helpers.js) to avoid code duplication.
> 
> Could you also please call this function then in the translations, because if we have a translation with many lines in it, we have the same problem.
> 
> Thanks a lot

@torqdev Thanks for the PR, I have create an Issue for this comment https://github.com/pimcore/pimcore/issues/15539

**Pull request merged**
