### PR TITLE
Add icon to not editable fields #11562

### PR DESCRIPTION
**Pull request by ctippler**
@see https://github.com/pimcore/pimcore/issues/11562

### CODE REVIEW

**Comment by dvesh3** [comment]
please rebase to fix the tests. Fixed here https://github.com/pimcore/pimcore/pull/11576

**Comment by brusch** [comment]
This is how it looks like: 

image

**Comment by brusch** [comment]
Tests are failing because of #11576 
So I guess we can just ignore them 😉

**Comment by aryaantony92** [comment]
@ckogler-elements Thank you.

**Pull request merged**
