### PR TITLE
Remove ChildsCompatibilityTrait

### LINKED ISSUE #10535: Remove ChildsCompatibilityTrait
### Improvement description

Related to https://github.com/pimcore/pimcore/pull/10527

### PR DESCRIPTION
**Pull request by robertSt7**
resolve #10535

### CODE REVIEW

**Review by mcop1 — COMMENTED** [review]
@robertSt7 
Following code returns the expected children in 11.x, but isn´t working anymore with the changes from this pr. Could you please have a look?
```
$cd = ClassDefinition::getById("CAR");
$ld = $cd->getLayoutDefinitions();
$childs = $ld->getChildren();
```

Additionally we should add an entry in the upgrade notes.

**Comment by brusch** [comment]
We should consider JS BC layers here as well, such as: 
https://github.com/pimcore/pimcore/blob/d34b60574994ea91db51758603c056b3033a3e52/bundles/AdminBundle/Resources/public/js/pimcore/object/classes/layout/layout.js#L29
https://github.com/pimcore/pimcore/blob/2f18a0f26380c56b609d937b40d2050c8d1a3e1a/bundles/AdminBundle/Resources/public/js/pimcore/object/fieldlookup/helper.js#L27

**Comment by mcop1** [comment]
> @robertSt7 Following code returns the expected children in 11.x, but isn´t working anymore with the changes from this pr. Could you please have a look?
> 
> ```
> $cd = ClassDefinition::getById("CAR");
> $ld = $cd->getLayoutDefinitions();
> $childs = $ld->getChildren();
> ```
> 
> Additionally we should add an entry in the upgrade notes.

@robertSt7 still not working

**Comment by mcop1** [comment]
> > @robertSt7 Following code returns the expected children in 11.x, but isn´t working anymore with the changes from this pr. Could you please have a look?
> > ```
> > $cd = ClassDefinition::getById("CAR");
> > $ld = $cd->getLayoutDefinitions();
> > $childs = $ld->getChildren();
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Additionally we should add an entry in the upgrade notes.
> 
> @robertSt7 still not working

Wasn´t a problem with the changes from this pr, it was related to the custom layouts in the demo, see https://github.com/pimcore/demo/pull/365

**Pull request merged**
