### PR TITLE
[Images] Allow disabling assets.image.max_pixels config

### PR DESCRIPTION
**Pull request by BlackbitDevs**
It is best practice to always upload images in best quality in a lossless format and then for later use in output channels use thumbnail definitions. Having this in mind it is a bit counter-intuitive that by default the maximum dimension for images is limited to 40 MP in
https://github.com/pimcore/pimcore/blob/e22a8209fde57c953a5caba13292d60ae3b06979/bundles/CoreBundle/src/DependencyInjection/Configuration.php#L375-L377

Of course you can set a higher number in the config.yaml but you can currently not disable this check at all. With this PR if you set
```yaml
pimcore:
  assets:
    image:
      max_pixels: ~ or 0
```
this check can be disabled.

(A little side effect is that the image dimension does not have to be read in this case resulting in better performance.)

Actually I wonder why the maximum dimension is limited hard-coded by default at all, so we can also discuss if this actually makes sense at all...

### CODE REVIEW

**Comment by BlackbitDevs** [comment]
Any news on this? @dvesh3 maybe?

**Comment by brusch** [comment]
@BlackbitDevs 

> Actually I wonder why the maximum dimension is limited hard-coded by default at all, so we can also discuss if this actually makes sense at all...

That's for security reasons, otherwise Pimcore would be vulnerable to the pixel flood attack - so bad practice ...

**Comment by BlackbitDevs** [comment]
Where does this cause a problem? I would suspect that it only is a problem if ImageMagick cannot handle such corrupt pixel flood images, right? So the problem should be handled there, I guess.

And even if it may cause a problem: This PR is not about removing the `max_pixels` but it is about the ability to disable it in a specific project. Maybe the PIM is not even accessible from the internet - imho enforcing a max pixel size nursemaids clients in an unnecessary way. I mean we can keep the current default value for `max_pixels` - but why not allow to disable it when the project admins want to?

**Comment by brusch** [comment]
@BlackbitDevs Unfortunately it isn't handled by the underlying libraries, but anyway 😊
You're right, disabling on your own risk doesn't hurt, as long as we keep the default value.

**Pull request merged**
