### PR TITLE
New hooks for maintenance and cache

### PR DESCRIPTION
**Pull request by luklewluk**
I had to add a few hooks to my project but I think they can be useful in other cases as well.

If you accept the Pull Request I will update this page of documentation: https://www.pimcore.org/wiki/pages/viewpage.action?pageId=16854309

**System / General**

| Name | Target | Parameters | Description |
| --- | --- | --- | --- |
| system.maintenance.activate |  |  | This event is fired on maintenance mode activation |
| system.maintenance.deactivate |  |  | This event is fired on maintenance mode deactivation |
| system.cache.clearOutputCache |  |  |  |
| system.cache.clear |  |  |  |
| system.cache.clearTemporaryFiles |  |  |  |

### CODE REVIEW

**Comment by weisswurstkanone** [comment]
Hi, two questions:
- wouldn't be inside Admin::(de)activateMaintenanceMode the better (because more central) place for this?
- just curious: what is your use case for this? ;-)

**Comment by luklewluk** [comment]
Hi.

1. You are right, I've changed it to admin.(de)activateMaintenanceMode
2. I've been working on Supercache/Full Page Cache plugin for Pimcore ( https://github.com/luklewluk/SupercachePlugin ). I want to clean cache when I active maintenance mode and when I clean output cache. But it can be used for better integration with Varnish too :)

**Comment by weisswurstkanone** [comment]
Sorry, my idea was to move the trigger into the Tool\Admin::activateMaintenanceMode() method

**Comment by luklewluk** [comment]
Can I place the trigger into a static method? If yes, what do I suppose to use as a second parameter (instead of "$this")?

**Comment by weisswurstkanone** [comment]
Hi,
yes, that was my idea. Regarding the second paramter: it is optional (defaults to null). Not sure anyway if it makes sense to add any additional data for those events. What do you think?

**Comment by luklewluk** [comment]
Ok, great. I've moved it.

**Comment by weisswurstkanone** [comment]
Thanks a lot!

**Comment by maff** [comment]
Wouldn't it make sense to rename the event names back to `system.maintenance.activate`/`system.maintenance.deactivate`?

**Comment by luklewluk** [comment]
What do you think @weisswurstkanone ?

**Comment by weisswurstkanone** [comment]
yep, makes sense

**Pull request merged**
