### PR TITLE
[Improvement] Adding functionality to create preview images on InDesign Files

### PR DESCRIPTION
**Pull request by Alanin**
## Changes in this pull request  
Adding functionality to render preview images from InDesign (indd) Files.

### CODE REVIEW

**Comment by brusch** [comment]
I'm not entirely happy with the current approach, for the following reasons: 
1. since we're just extracting the embedded thumbnail of the `indd` file, we should only use it for preview purposes in the admin UI
2. in the admin UI we should make clear that this is just a preview and that this file-type cannot be used for thumbnails (e.g. image editables, image data-types, ...) 
3. `indd` shouldn't be generally considered as an image imho

So I'm thinking of having this as an admin UI - only functionality, that can be handled in an action, wdyt?

**Comment by brusch** [comment]
@Alanin ping 🏓😊
Please also see the failing PHPStan check: 

```
Error: Caught class Pimcore\Helper\Exception not found.
 ------ --------------------------------------------------------------------- 
  Line   lib/Helper/InddPreviewGenerationHelper.php                           
 ------ --------------------------------------------------------------------- 
  57     Caught class Pimcore\Helper\Exception not found.                     
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols  
 ------ --------------------------------------------------------------------- 
```

**Comment by brusch** [comment]
@Alanin 🏓 any updates on this? Thanks 😊

**Comment by brusch** [comment]
@Alanin one more try - any chance to incorporate my feedback?

**Comment by Alanin** [comment]
Hey @brusch,

sorry I am very busy at the moment. not able to address all issues here.

1. true
2. true :)  
3. indd files contain a lot of meta data. using just 'document' as type would prevent showing those data.

tbh. I don't really like this solution. I would like to see a way to have some kind of file handlers which helps community to add functions for yet unsupported filetypes. so we could add methods to generate thumbnails or define functions for exporting derivates when needed.

do you think something like that would be possible in future? I think a more generic way of handling assets would be great ;)

**Comment by brusch** [comment]
@Alanin that's planned for `v11` , see https://github.com/pimcore/pimcore/issues/10245
You could help is in providing a PR for that 😉

**Comment by brusch** [comment]
With the current state I'm still not happy, as it's an backend functionality it should probably covered in the `AdminBundle` and also the file headers need to be correct. 
If you don't have time for that, I'd close it for now and create a follow up issue for us.

**Comment by SandraRGitHub** [comment]
Hi, we tried this code for getting previews on indesign files, but we only get it to work with multiple page indd files (it displays only the preview for first page) but it does not give a preview on single page indd files. 
Any suggestions or help? We are running pimcore portals on v2.3.1.

**Comment by Alanin** [comment]
@SandraRGitHub is the preview integrated in the single page files as well? the code is only extracting the low-res preview images provided by InDesign.

those are saved in the EXIF Metadata in Field PageImage

**Comment by SandraRGitHub** [comment]
@Alanin we actually did a test, we created a new indd file with just one single page. And the checked the box for "Always save preview images with documents". 
We checked the raw data for the file in page info and there is a tagg <xmpGImg:image> in the <xmp:PageInfo> of the file.

But when we upload the file to the pimcore DAM portal then we get no preview, and instead it just displays a blue icon a question mark. So something seems not right...

**Comment by brusch** [comment]
@SandraRGitHub this feature is not yet implemented, so it can't work 😉

**Comment by Alanin** [comment]
Tbh it's not a good idea to use that code here. Pimcore implemented an official way to add adapters to create previews for unsupported filetypes. 

It would be way better to make a bundle to extract the images using the official way

**Comment by Alanin** [comment]
I'll have a look into it tomorrow, maybe I can refactor that code here to a standalone bundle using the new apis.

But that would be Pimcore 11 and not compatible to 10.x

**Comment by Alanin** [comment]
@SandraRGitHub i have refactored the code to a Pimcore 11 compatible bundle. When you have a running Pimcore 11 instance, can you please get in touch with me. I would like you to test the bundle before I release that bundle to the public.

**Comment by Alanin** [comment]
@brusch i have tried to implement the bundle, but seems the is still some more work in core to make it easy and convenient to implement own asset types... https://github.com/pimcore/pimcore/discussions/15707

**Comment by brusch** [comment]
Closing this for now due to inactivity. 
Might  be a nice addition for Studio UI in future 😊

**Pull request closed without merging**
