### PR TITLE
Always use PIMCORE_PHP_ERROR_REPORTING and fix PHP notices

### LINKED ISSUE #4708: [Improvement] No notice errors in back-office and Pimcore code + activate E_ALL in debug mode
Hello,

I have seen phpstan is on his way for Pimcore test suite, kool !
On our side, we are trying to enforce code quality, by setting `error_reporting(E_ALL);` for bundles in the `src` directory.

We cannot enforce this setting globally including Pimcore because Pimcore send some notice errors in back-end.
It would be nice a global pass could be done to eliminate all those notice errors.
For instance `$limit` here could not be defined (empty skeleton, just open the BO and check for error 500 in browser dev console): https://github.com/pimcore/pimcore/blob/master/bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php#L196

image

There is more (i didn't check everywhere... the recycle bin for instance, etc.)

Idea behind this, is to be able to develop on the Pimcore GUI with notice errors being reported.
It will make Pimcore code more robust too.

The final objective is to be able to change this line: https://github.com/pimcore/pimcore/blob/31fd11bcf370ab92b6539b68fc88da53cfec0e12/lib/Pimcore.php#L73 by `error_reporting(E_ALL);`
This way people developping Pimcore extension would produce better code too.

### PR DESCRIPTION
**Pull request by blankse**
## Changes in this pull request  
Partly resolves #4708

With this PR it is possible to set an PIMCORE_PHP_ERROR_REPORTING env to show all error inclusive notices in dev mode.

**.env.local.php**
```
<?php

return [
    'PIMCORE_PHP_ERROR_REPORTING' => E_ALL,
];

```

### CODE REVIEW

**Comment by brusch** [comment]
Nice!
But imho the error reporting level shouldn't be a system setting, I'd prefer configuring it via an environment variable.

**Comment by dpfaffenbauer** [comment]
I'd prefer configuring it via php settings, where they usually are...

**Comment by brusch** [comment]
For v7 yes -> proper BC break! 
But in the meantime I'd say it's better to do that via constant/env variable (like the other stuff).

**Comment by dpfaffenbauer** [comment]
BC break cause Pimcore statically defines the levels?

**Comment by brusch** [comment]
Yes, if your code relies on that ... booom.

**Comment by dpfaffenbauer** [comment]
Just a minor BC then :P

Alright then, we should keep it on the list for Pimcore 7 then.

BTW: Also, when we're gonna change it to an setting, we have to use the current situation as default fallback then as well.

**Comment by blankse** [comment]
There is already a PIMCORE_PHP_ERROR_REPORTING const. This is used only with disabled debug mode. But has a lower level (E_ALL & ~E_NOTICE & ~E_STRICT instead of E_ALL & ~E_NOTICE)

Should we use this for both modi? Or should I create a new one?

**Comment by brusch** [comment]
@blankse in my opinion `PIMCORE_PHP_ERROR_REPORTING` should be used either way.

**Comment by brusch** [comment]
Default should stay on `E_ALL & ~E_NOTICE & ~E_STRICT`. 
Let me know when this PR is ready for review.

**Comment by brusch** [comment]
As far as I can see only one `error_reporting()` in `Boostrap.php` should be sufficient, we should get rid of all the other calls 😊
Thanks!

**Comment by brusch** [comment]
@blankse ready for review? 😊

**Comment by brusch** [comment]
Uh, tests are failing, can you fix them? Thanks!

**Comment by blankse** [comment]
@brusch I am working on it. I'll contact you if the tests are successful :)

**Comment by blankse** [comment]
@brusch I was able to correct all errors in the tests. Also the error in the current master branch (https://github.com/pimcore/pimcore/pull/5310/commits/41e7a38fa6d8b14a288638a5ca2f71cdb5df7d94).

**Comment by blankse** [comment]
Rebase because of https://github.com/pimcore/pimcore/commit/6958beb148070696e3f30f5c615b934e782434b9

**Comment by weisswurstkanone** [comment]
I am getting a undefined index notice in pimcore/lib/Config.php:784 when I try to load the backend UI.
Everything is find if I stay on the master branch.

Seems that this forces me to E_ALL although PIMCORE_PHP_ERROR_REPORTING is not defined.

image

**Comment by blankse** [comment]
@weisswurstkanone Thank you for reviewing. You are right, Symfony Debug set the error reporting level to E_ALL in dev mode. I set the error reporting level argument now.

I get no error in the backend. In pimcore/lib/Config.php:784 should be a closing bracket?

**Comment by brusch** [comment]
Very, very nice, thank you so much!

**Comment by Yivan** [comment]
Howwww so great ! @blankse thanks a lot for having taken this problem.
(it was a big task and i didn't had time to handle it: https://github.com/pimcore/pimcore/issues/4708)
It is one of the best improvements to be able to improve code quality.
Mille merci : )

@brush for subsequent development to come, will the core code be developped in E_ALL on your side (+phpstan level 2 for instance) ? Would be great so we keep this abilities to develop in front and back end with maximum level error reporting.

**Comment by brusch** [comment]
@Yivan wrong username again 😉 (u know `brush` vs `brusch`), it's not about me but about the poor real `brush` who get's the messages instead 😅

But to answer your question: Yes, that would be the plan.

**Comment by Yivan** [comment]
@brusch You are right, sorry !!
Very great if this is the plan so ! Thanks. Have a nice evening.

**Pull request merged**
